In [1]:
from parse import load_dataframes
import pandas as pd

# parse
data = load_dataframes()

# user_rating = data['reviews']
# user_rating = user_rating.pivot_table('score', index = "user", columns="store")

# 전체 음식점 데이터
stores = data['stores']
stores.rename(columns={'id':'store'}, inplace = True)

# 모든 음식점들의 리뷰 데이터를
ratings_stores = pd.merge(data['reviews'], stores, on='store')

# 각각의 유저에 대하여 평점을 계산
group = ratings_stores.groupby(["store", "store_name", "user"])
mean = group.mean().reset_index()

# 유저 X 음식점으로 피봇테이블 생성 ( 각 유저가 음식점들에 남긴 평점을 확인 가능 )
user_rating_store = mean.pivot_table('score', index='user', columns="store_name").fillna(0)

user_rating_store

store_name,010수산,100회,101번지남산돈까스,10G,10막창,117파크,11자리,17도씨,17테이블,18번완당집,...,중화가정,중화복춘,중화요리궁,중화원,쥬뗑뷔뜨,쥬마뺄,쥬씨,즉떡왕,즉석우동짜장,지구당
user,,,,,,,,,,,,,,,,,,,,,
23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
147,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
166,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
182,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
189,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
947671,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
947927,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
949019,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
949944,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
950331,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [2]:
from sklearn.metrics.pairwise import cosine_similarity

# 유저 유사도 계산
user_sim = cosine_similarity(user_rating_store, user_rating_store)
user_sim_df = pd.DataFrame(data = user_sim, index = user_rating_store.index, columns = user_rating_store.index)

user_sim_df

user,23,147,166,182,189,313,345,535,541,640,...,946575,946652,946771,947622,947653,947671,947927,949019,949944,950331
user,,,,,,,,,,,,,,,,,,,,,
23,1.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
147,0.0,1.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
166,0.0,0.0,1.000000,0.0,0.328266,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
182,0.0,0.0,0.000000,1.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
189,0.0,0.0,0.328266,0.0,1.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
947671,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
947927,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
949019,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
949944,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
950331,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [3]:
# 모든 유저들간의 유사도를 뽑아내보면?
for i in user_sim_df.index:
    print(i)
    print(user_sim_df[i].sort_values(ascending=False)[1:10])
    print()

23
user
1599      0.624695
4629      0.232810
392082    0.162657
516840    0.130574
504746    0.100751
485567    0.090581
103304    0.074022
171918    0.000000
171678    0.000000
Name: 23, dtype: float64

147
user
927595    0.462250
854097    0.326860
193213    0.244906
129012    0.216468
211039    0.173175
372398    0.145609
33179     0.125809
156952    0.092105
364545    0.082178
Name: 147, dtype: float64

166
user
138679    0.335035
327446    0.328266
426952    0.328266
157564    0.328266
199172    0.328266
317713    0.328266
28722     0.328266
261822    0.328266
51752     0.328266
Name: 166, dtype: float64

182
user
37980     0.529813
321692    0.529813
246545    0.529813
22636     0.529813
194122    0.529813
153678    0.529813
222975    0.529813
780237    0.529813
261654    0.529813
Name: 182, dtype: float64

189
user
51752     1.0
219458    1.0
199172    1.0
295792    1.0
261822    1.0
193795    1.0
260171    1.0
329184    1.0
365315    1.0
Name: 189, dtype: float64

313
user
313       1.000000
173421    1.000000
323845    0.441726
155466    0.348155
173300    0.000000
173293    0.000000
173236    0.000000
173325    0.000000
173218    0.000000
Name: 313, dtype: float64

345
user
67245     0.348155
791637    0.346688
158711    0.291606
70333     0.253546
43726     0.234261
321572    0.228665
24325     0.212132
96360     0.197546
155100    0.189737
Name: 345, dtype: float64

535
user
328754    0.391630
132262    0.313304
365419    0.313304
117869    0.313304
244614    0.313304
774737    0.313304
213659    0.313304
626627    0.313304
202032    0.313304
Name: 535, dtype: float64

541
user
392977    0.424264
259415    0.402015
850922    0.278543
249051    0.234662
91720     0.207514
145101    0.109930
69019     0.088475
138574    0.082479
173126    0.000000
Name: 541, dtype: float64

640
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 640, dtype: float64

744
user
95763     0.386695
96613     0.386695
562349    0.386695
71046     0.366851
428481    0.309356
471642    0.290021
158718    0.275138
702397    0.273434
836215    0.232017
Name: 744, dtype: float64

746
user
190348    0.327327
192676    0.311400
264572    0.305888
179727    0.088216
173236    0.000000
173218    0.000000
173293    0.000000
173187    0.000000
172589    0.000000
Name: 746, dtype: float64

820
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 820, dtype: float64

1028
user
550014    0.416025
833379    0.322078
950331    0.000000
173038    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173126    0.000000
172504    0.000000
Name: 1028, dtype: float64

1190
user
88648     1.000000
699433    1.000000
1190      1.000000
148748    0.529813
211039    0.468293
357798    0.312348
781898    0.295487
194979    0.254000
386997    0.216574
Name: 1190, dtype: float64

1409
user
390006    1.000000
321594    1.000000
326545    1.000000
87516     1.000000
170923    1.000000
71245     0.554700
88418     0.554700
153040    0.468521
665848    0.457496
Name: 1409, dtype: float64

1451
user
305856    0.152008
950331    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 1451, dtype: float64

1521
user
382215    1.000000
1521      1.000000
608997    0.980581
279785    0.232104
593182    0.219900
197504    0.208514
469245    0.171701
182213    0.152499
173141    0.000000
Name: 1521, dtype: float64

1557
user
386287    1.000000
171329    1.000000
351769    1.000000
1557      1.000000
21052     1.000000
557732    1.000000
219148    0.780869
392992    0.615457
684910    0.404061
Name: 1557, dtype: float64

1582
user
249441    0.492366
815492    0.492366
582183    0.369274
195632    0.369274
302442    0.369274
260179    0.369274
29491     0.362608
621199    0.326077
389973    0.307579
Name: 1582, dtype: float64

1596
user
570294    0.267927
85331     0.207888
251474    0.144561
385219    0.130917
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
Name: 1596, dtype: float64

1599
user
23        0.624695
4629      0.372678
392082    0.260378
516840    0.209020
504746    0.161281
485567    0.145000
103304    0.118493
171918    0.000000
171678    0.000000
Name: 1599, dtype: float64

1656
user
155894    0.857493
74618     0.685994
172079    0.352427
190080    0.238849
213301    0.159750
724982    0.118135
950331    0.000000
173038    0.000000
173126    0.000000
Name: 1656, dtype: float64

1705
user
15289     0.565685
371282    0.254558
49954     0.238197
127617    0.234082
725789    0.224045
924558    0.207020
580520    0.147292
173038    0.000000
173126    0.000000
Name: 1705, dtype: float64

1727
user
387438    1.0
354968    1.0
24895     1.0
392580    1.0
1727      1.0
25573     1.0
245724    1.0
28763     1.0
318930    1.0
Name: 1727, dtype: float64

2109
user
31984     0.388075
927427    0.388075
915067    0.388075
191363    0.388075
224377    0.310460
336473    0.310460
74904     0.274411
397183    0.242429
885428    0.232845
Name: 2109, dtype: float64

2112
user
154870    0.928477
256609    0.262613
860255    0.214423
135672    0.103324
530433    0.098062
6838      0.084103
173218    0.000000
173236    0.000000
173187    0.000000
Name: 2112, dtype: float64

2131
user
2131      1.000000
95985     0.552158
30196     0.380143
180729    0.261116
175405    0.242091
283160    0.201008
728009    0.161558
386997    0.129944
171918    0.000000
Name: 2131, dtype: float64

2175
user
882402    1.0
465152    1.0
43207     1.0
239439    1.0
648094    1.0
169215    1.0
2175      1.0
642214    1.0
230190    1.0
Name: 2175, dtype: float64

2295
user
2295      1.0
173421    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 2295, dtype: float64

2301
user
394042    1.000000
5311      0.228748
172946    0.000000
173415    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
Name: 2301, dtype: float64

2368
user
256395    0.894427
630195    0.894427
924719    0.894427
282534    0.698430
302395    0.632456
881353    0.516398
284839    0.516398
763655    0.279372
4629      0.266667
Name: 2368, dtype: float64

2379
user
746330    0.615457
460437    0.615457
140931    0.615457
71170     0.527750
7598      0.492366
51466     0.435194
402190    0.422200
389013    0.393648
2847      0.378788
Name: 2379, dtype: float64

2419
user
938757    0.585206
126931    0.468165
200652    0.468165
418510    0.468165
839712    0.468165
150968    0.434680
441889    0.331042
148206    0.331042
48977     0.323126
Name: 2419, dtype: float64

2572
user
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 2572, dtype: float64

2709
user
372209    0.320092
82952     0.311286
820908    0.246932
172770    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 2709, dtype: float64

2842
user
49642     0.194717
74999     0.181568
950331    0.000000
172955    0.000000
173415    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
Name: 2842, dtype: float64

2847
user
460437    0.615457
140931    0.615457
71170     0.527750
191363    0.492366
31984     0.492366
51466     0.435194
389013    0.393648
2379      0.378788
25840     0.375917
Name: 2847, dtype: float64

2849
user
2849      1.000000
161783    1.000000
400268    0.800000
393981    0.529813
131358    0.518476
367228    0.514496
293382    0.431331
369062    0.404061
390671    0.370625
Name: 2849, dtype: float64

2920
user
662556    1.000000
138663    0.577350
21542     0.219382
256163    0.133897
173146    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
Name: 2920, dtype: float64

3006
user
30223     1.000000
572720    0.242983
950331    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
173146    0.000000
173187    0.000000
Name: 3006, dtype: float64

3019
user
504649    0.762493
107432    0.762493
158481    0.762493
47297     0.762493
112616    0.762493
85705     0.762493
874578    0.747686
192236    0.595407
855363    0.595407
Name: 3019, dtype: float64

3044
user
323463    1.000000
3044      1.000000
94030     1.000000
819045    0.600000
308086    0.333333
534410    0.279751
816423    0.236250
710291    0.175412
90754     0.171219
Name: 3044, dtype: float64

3123
user
3123      1.000000
274810    1.000000
314010    1.000000
164819    0.894427
448451    0.468165
632495    0.404061
175356    0.000000
172339    0.000000
173146    0.000000
Name: 3123, dtype: float64

3153
user
279978    0.707107
45308     0.707107
74666     0.707107
107751    0.707107
113136    0.707107
24006     0.552158
358118    0.500000
29563     0.441726
28330     0.424264
Name: 3153, dtype: float64

3357
user
203647    0.707107
318073    0.707107
475865    0.707107
92831     0.707107
420587    0.707107
106676    0.707107
398867    0.552158
13006     0.441726
518696    0.441726
Name: 3357, dtype: float64

3629
user
178745    0.600000
148115    0.600000
280081    0.424264
138572    0.308697
177951    0.303046
158711    0.247436
211972    0.224781
364509    0.210674
391631    0.134916
Name: 3629, dtype: float64

3739
user
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 3739, dtype: float64

3798
user
510431    0.188144
950331    0.000000
172589    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 3798, dtype: float64

3816
user
44729     0.370625
354735    0.370625
196651    0.344116
85785     0.296500
321082    0.296500
325034    0.289409
529160    0.262071
763655    0.231527
113193    0.204643
Name: 3816, dtype: float64

3882
user
31926     0.499756
5010      0.499756
252207    0.374532
157653    0.303731
249421    0.295420
42484     0.222375
96360     0.209529
321572    0.194029
641859    0.154598
Name: 3882, dtype: float64

3906
user
87583     0.408248
469607    0.408248
110846    0.318788
286165    0.288675
329057    0.265747
48688     0.201008
179727    0.054021
950331    0.000000
173038    0.000000
Name: 3906, dtype: float64

4345
user
950331    0.0
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 4345, dtype: float64

4347
user
774737    0.662266
448633    0.529813
944394    0.529813
45836     0.529813
853410    0.529813
201564    0.529813
622340    0.529813
39314     0.529813
761773    0.529813
Name: 4347, dtype: float64

4385
user
4385      1.0
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 4385, dtype: float64

4548
user
510614    1.000000
419237    1.000000
155793    1.000000
60263     1.000000
775370    1.000000
821860    0.707107
366858    0.624695
257535    0.483368
54197     0.424264
Name: 4548, dtype: float64

4629
user
1599      0.372678
177065    0.298142
25951     0.298142
192226    0.298142
924719    0.298142
256395    0.298142
180453    0.298142
10287     0.298142
356789    0.298142
Name: 4629, dtype: float64

4668
user
264944    1.000000
4668      1.000000
946652    1.000000
75468     1.000000
260632    1.000000
937146    0.447214
173126    0.000000
172946    0.000000
172955    0.000000
Name: 4668, dtype: float64

4891
user
838134    1.000000
4891      1.000000
6791      1.000000
793871    1.000000
945633    1.000000
288137    1.000000
686161    1.000000
75794     0.648886
906467    0.624695
Name: 4891, dtype: float64

4974
user
439187    0.666667
211148    0.666667
851090    0.666667
61770     0.666667
188061    0.666667
732125    0.666667
340105    0.666667
401305    0.596285
263524    0.533333
Name: 4974, dtype: float64

5010
user
776878    0.780869
371282    0.624695
3882      0.499756
112746    0.480592
5847      0.413714
31926     0.390244
353401    0.384473
824879    0.318788
252207    0.292460
Name: 5010, dtype: float64

5015
user
696718    0.487950
129168    0.487950
85853     0.487950
343630    0.390360
249802    0.312288
24614     0.258522
315596    0.225374
707972    0.220821
186982    0.212959
Name: 5015, dtype: float64

5036
user
219765    0.331042
172504    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
Name: 5036, dtype: float64

5111
user
327538    1.000000
334694    0.357771
172770    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 5111, dtype: float64

5121
user
618570    1.000000
491529    0.780869
725655    0.680414
424678    0.565685
79647     0.554700
795084    0.447214
694627    0.275010
173187    0.000000
173146    0.000000
Name: 5121, dtype: float64

5142
user
256181    0.436436
512463    0.436436
526951    0.327327
151661    0.327327
356252    0.278651
31926     0.255599
360381    0.251976
255287    0.231455
192095    0.231311
Name: 5142, dtype: float64

5239
user
504746    0.268802
950331    0.000000
172589    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 5239, dtype: float64

5244
user
247859    0.302614
950331    0.000000
172589    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 5244, dtype: float64

5282
user
380394    0.707107
864133    0.500000
535452    0.441726
180718    0.424264
368907    0.345547
579530    0.222375
754864    0.188982
180541    0.186052
328775    0.125078
Name: 5282, dtype: float64

5311
user
99088     0.304997
686640    0.304997
198386    0.304997
612464    0.266223
546411    0.242387
405980    0.228748
170852    0.228748
129190    0.228748
644110    0.228748
Name: 5311, dtype: float64

5600
user
5600      1.000000
151201    0.707107
227462    0.600000
373775    0.421076
156230    0.337869
646881    0.310460
446951    0.192450
70650     0.075593
593182    0.043980
Name: 5600, dtype: float64

5666
user
131428    0.2719
40447     0.2566
159381    0.2566
177140    0.2566
254149    0.2566
398361    0.2566
924557    0.2566
70861     0.2566
197359    0.2566
Name: 5666, dtype: float64

5710
user
53578     0.577350
292194    0.461880
356252    0.319235
127124    0.255822
485567    0.145000
580520    0.130189
173236    0.000000
173293    0.000000
173218    0.000000
Name: 5710, dtype: float64

5732
user
326966    0.707107
950331    0.000000
172770    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 5732, dtype: float64

5847
user
776878    0.529813
332107    0.517143
371282    0.423850
5010      0.413714
112746    0.326077
353401    0.260862
824879    0.216295
632095    0.170774
686300    0.167542
Name: 5847, dtype: float64

5884
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 5884, dtype: float64

5995
user
630504    1.000000
5995      1.000000
319753    1.000000
869698    1.000000
849404    1.000000
389704    1.000000
412468    0.980581
7265      0.780869
134131    0.780869
Name: 5995, dtype: float64

6093
user
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 6093, dtype: float64

6169
user
319818    0.825192
175043    0.552158
70299     0.552158
161965    0.441726
286800    0.206801
781898    0.203944
151946    0.191273
372398    0.104358
279615    0.101565
Name: 6169, dtype: float64

6574
user
6574      1.000000
611186    1.000000
181027    1.000000
279303    0.707107
319153    0.358569
950331    0.000000
172589    0.000000
172770    0.000000
172946    0.000000
Name: 6574, dtype: float64

6757
user
672483    0.400000
674768    0.353553
31285     0.268802
186286    0.151186
215042    0.108112
175861    0.000000
172589    0.000000
173236    0.000000
173218    0.000000
Name: 6757, dtype: float64

6780
user
149174    0.456435
950331    0.000000
172770    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 6780, dtype: float64

6791
user
838134    1.000000
4891      1.000000
6791      1.000000
793871    1.000000
945633    1.000000
288137    1.000000
686161    1.000000
75794     0.648886
906467    0.624695
Name: 6791, dtype: float64

6838
user
8055      0.452911
756238    0.452911
227485    0.452911
424498    0.452911
928303    0.452911
863840    0.452911
710581    0.405096
839814    0.354459
783901    0.353664
Name: 6838, dtype: float64

6899
user
353104    1.000000
224662    1.000000
136730    1.000000
85149     1.000000
6899      1.000000
335411    1.000000
531388    0.928477
536176    0.780869
169956    0.707107
Name: 6899, dtype: float64

7155
user
667169    0.441726
85688     0.114043
950331    0.000000
172770    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 7155, dtype: float64

7226
user
211542    0.970143
350949    0.970143
180780    0.970143
179191    0.730107
108936    0.257585
135044    0.140028
201482    0.140028
724982    0.133654
697977    0.051972
Name: 7226, dtype: float64

7265
user
134131    1.000000
365420    0.780869
630504    0.780869
5995      0.780869
319753    0.780869
869698    0.780869
849404    0.780869
389704    0.780869
412468    0.765705
Name: 7265, dtype: float64

7320
user
63998     0.312348
385143    0.312348
563103    0.312348
36587     0.312348
361892    0.312348
172490    0.276079
170172    0.220863
53433     0.195122
364520    0.195122
Name: 7320, dtype: float64

7467
user
293102    0.316228
950331    0.000000
173421    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 7467, dtype: float64

7488
user
82581     1.0
487327    1.0
652607    1.0
42615     1.0
7488      1.0
721140    1.0
645667    1.0
664747    1.0
192450    1.0
Name: 7488, dtype: float64

7505
user
322844    0.529813
950331    0.000000
172770    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 7505, dtype: float64

7598
user
402190    0.857493
631109    0.500000
2379      0.492366
646881    0.310460
391794    0.141762
173126    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
Name: 7598, dtype: float64

7640
user
172770    0.0
173415    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 7640, dtype: float64

8036
user
8036      1.000000
351808    0.400000
180519    0.323498
385272    0.316228
108338    0.276172
108936    0.265513
710291    0.263117
71632     0.248452
129333    0.199007
Name: 8036, dtype: float64

8055
user
863840    1.000000
8055      1.000000
928303    1.000000
756238    1.000000
424498    1.000000
710581    0.894427
334520    0.707107
420344    0.707107
926948    0.707107
Name: 8055, dtype: float64

8272
user
350778    0.492366
395445    0.492366
557866    0.492366
376096    0.492366
114908    0.492366
332711    0.492366
113970    0.492366
816326    0.492366
651501    0.482805
Name: 8272, dtype: float64

8273
user
950331    0.0
172770    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 8273, dtype: float64

8323
user
899377    1.000000
42721     1.000000
709700    1.000000
757228    1.000000
87724     1.000000
8323      1.000000
501746    1.000000
470673    0.800000
131375    0.707107
Name: 8323, dtype: float64

8338
user
22636     1.0

Name: 11389, dtype: float64

11392
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 11392, dtype: float64

11891
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 11891, dtype: float64

11935
user
811320    1.000000
60473     0.707107
65081     0.529813
180729    0.435194
322627    0.396526
108338    0.368230
192676    0.311400
173038    0.000000
173126    0.000000
Name: 11935, dtype: float64

11951
user
358687    0.349215
425198    0.279372
212239    0.279372
746330    0.279372
275746    0.279372
542897    0.279372
409694    0.279372
35307     0.279372
177837    0.228886
Name: 11951, dtype: float64

12109
user
363254    0.270765
252216    0.227429
190766    0.190910
173141    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173146    0.000000
Name: 12109, dtype: float64

12225
user
138402    1.000000
50592     1.000000
397331    1.000000
18611     1.000000
354415    0.624695
197904    0.514496
69546     0.514496
539244    0.390360
90296     0.252478
Name: 12225, dtype: float64

12285
user
59764     0.707107
388041    0.500000
522869    0.500000
247348    0.468293
252419    0.428746
171582    0.408248
699447    0.408248
195147    0.357143
155094    0.341793
Name: 12285, dtype: float64

12567
user
671905    1.000000
69546     0.685994
156952    0.199254
173187    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
173146    0.000000
Name: 12567, dtype: float64

12903
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 12903, dtype: float64

13006
user
442748    0.780869
824879    0.637577
475865    0.624695
420587    0.624695
318073    0.624695
203647    0.624695
92831     0.624695
398891    0.552158
382523    0.517143
Name: 13006, dtype: float64

14914
user
150074    1.000000
753989    1.000000
885308    1.000000
86766     1.000000
702397    0.707107
39188     0.685994
279785    0.232104
836186    0.191273
249051    0.187729
Name: 14914, dtype: float64

14944
user
514724    1.0
14944     1.0
173146    0.0
172946    0.0
172955    0.0
173038    0.0
173126    0.0
173141    0.0
950331    0.0
Name: 14944, dtype: float64

14959
user
14959     1.000000
396107    1.000000
179719    0.231455
256163    0.178529
171853    0.000000
172946    0.000000
173325    0.000000
173300    0.000000
171636    0.000000
Name: 14959, dtype: float64

15289
user
1705      0.565685
49954     0.421076
127617    0.413803
725789    0.396059
580520    0.260378
173293    0.000000
173300    0.000000
173236    0.000000
173218    0.000000
Name: 15289, dtype: float64

16096
user
413895    1.000000
16096     1.000000
940619    0.577350
89781     0.464238
220825    0.384111
421743    0.384111
171967    0.245770
53368     0.206901
103304    0.157991
Name: 16096, dtype: float64

16383
user
16383     1.000000
103304    0.197488
173146    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
173187    0.000000
Name: 16383, dtype: float64

16704
user
101449    0.8
574786    0.8
172946    0.8
359293    0.8
122394    0.8
149217    0.8
397299    0.8
156256    0.8
827709    0.6
Name: 16704, dtype: float64

16928
user
86590     1.000000
136660    1.000000
441050    1.000000
16928     1.000000
62113     0.514496
328775    0.176887
173187    0.000000
173126    0.000000
173141    0.000000
Name: 16928, dtype: float64

17211
user
861818    0.745356
91092     0.745356
285710    0.745356
359203    0.745356
212056    0.745356
922962    0.745356
321283    0.596285
419505    0.596285
152413    0.596285
Name: 17211, dtype: float64

17698
user
43805     1.000000
17698     1.000000
32652     1.000000
96575     0.217250
350771    0.165145
173141    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
Name: 17698, dtype: float64

17987
user
163884    0.237356
173421    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 17987, dtype: float64

18297
user
776788    1.000000
18297     1.000000
182213    0.609994
163884    0.296695
173236    0.000000
173218    0.000000
173187    0.000000
172770    0.000000
173146    0.000000
Name: 18297, dtype: float64

18386
user
950331    0.0
172770    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 18386, dtype: float64

18611
user
138402    1.000000
50592     1.000000
397331    1.000000
18611     1.000000
354415    0.624695
197904    0.514496
69546     0.514496
539244    0.390360
90296     0.252478
Name: 18611, dtype: float64

18783
user
721140    0.319235
664747    0.319235
487327    0.319235
57135     0.319235
7488      0.319235
82581     0.319235
200742    0.319235
294354    0.319235
886362    0.319235
Name: 18783, dtype: float64

18966
user
229007    1.000000
18966     1.000000
707972    0.707107
197504    0.417029
79647     0.416025
395948    0.296500
172946    0.000000
172955    0.000000
173038    0.000000
Name: 18966, dtype: float64

19252
user
19252     1.000000
157739    1.000000
315462    0.214423
950331    0.000000
172946    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
Name: 19252, dtype: float64

19325
user
19325     1.000000
290708    1.000000
129333    0.099504
950331    0.000000
172946    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
Name: 19325, dtype: float64

19437
user
33061     0.284083
213564    0.105511
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
173146    0.000000
950331    0.000000
172770    0.000000
Name: 19437, dtype: float64

20363
user
446105    0.256495
419748    0.205196
614812    0.205196
814610    0.205196
179871    0.205196
398361    0.205196
923681    0.205196
44077     0.205196
636320    0.205196
Name: 20363, dtype: float64

20754
user
249880    0.338062
85688     0.215041
391794    0.085057
173146    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
950331    0.000000
Name: 20754, dtype: float64

21052
user
386287    1.000000
171329    1.000000
351769    1.000000
1557      1.000000
21052     1.000000
557732    1.000000
219148    0.780869
392992    0.615457
684910    0.404061
Name: 21052, dtype: float64

21105
user
607450    1.000000
21105     1.000000
357798    0.312348
243883    0.288675
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
Name: 21105, dtype: float64

21351
user
252964    1.000000
642291    1.000000
21351     1.000000
10762     1.000000
387303    0.529813
817844    0.514496
230662    0.404061
215995    0.339276
85688     0.268802
Name: 21351, dtype: float64

21542
user
105931    0.365636
132480    0.365636
72566     0.365636
323037    0.365636
670377    0.292509
804396    0.292509
366858    0.228411
706437    0.228411
396276    0.225034
Name: 21542, dtype: float64

21918
user
245915    0.8
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 21918, dtype: float64

22030
user
950331    0.0
172770    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 22030, dtype: float64

22062
user
49771     0.514496
261654    0.514496
222975    0.514496
153678    0.514496
321692    0.514496
37980     0.514496
780237    0.514496
22636     0.514496
55705     0.514496
Name: 22062, dtype: float64

22071
user
175350    0.668153
950331    0.000000
172589    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 22071, dtype: float64

22074
user
22074     1.000000
114146    1.000000
905082    0.707107
950331    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 22074, dtype: float64

22141
user
209755    0.323498
950331    0.000000
172770    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 22141, dtype: float64

22268
user
354771    0.624695
253153    0.552158
253154    0.552158
550014    0.541435
274267    0.270501
623554    0.223105
305856    0.152008
213301    0.145475
106056    0.131860
Name: 22268, dtype: float64

22566
user
745537    0.117309
950331    0.000000
173421    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 22566, dtype: float64

22608
user
115600    0.972229
492757    0.662266
32771     0.662266
172049    0.529813
325116    0.468293
507738    0.326077
74344     0.317888
116780    0.234032
52663     0.222158
Name: 22608, dtype: float64

22636
user
22636     1.0
261654    1.0
222975    1.0
153678    1.0
321692    1.0
37980     1.0
780237    1.0
55705     1.0
194122    1.0
Name: 22636, dtype: float64

22782
user
183668    0.404651
790296    0.374634
7488      0.374634
42615     0.374634
334992    0.374634
664747    0.374634
195551    0.374634
352512    0.374634
886362    0.374634
Name: 22782, dtype: float64

22784
user
259513    1.0
48575     1.0
200843    1.0
678481    1.0
950331    0.0
173038    0.0
173126    0.0
173141    0.0
173146    0.0
Name: 22784, dtype: float64

23255
user
219760    1.000000
794785    1.000000
23255     1.000000
358700    1.000000
792019    1.000000
506648    0.780869
598467    0.707107
848512    0.707107
149784    0.707107
Name: 23255, dtype: float64

23370
user
631109    0.390434
224934    0.252415
401684    0.175709
43793     0.158163
856133    0.115124
950331    0.000000
172946    0.000000
172504    0.000000
172589    0.000000
Name: 23370, dtype: float64

23375
user
950331    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 23375, dtype: float64

23390
user
23390     1.000000
95389     0.600000
385219    0.339276
190348    0.327327
315118    0.194054
32143     0.069171
173218    0.000000
173187    0.000000
173146    0.000000
Name: 23390, dtype: float64

23433
user
148586    0.552158
10287     0.441726
192226    0.441726
177065    0.441726
10258     0.441726
930037    0.441726
50007     0.431163
550554    0.367538
29563     0.344930
Name: 23433, dtype: float64

23533
user
23533     1.0
317949    1.0
158717    1.0
524501    1.0
820044    1.0
739296    1.0
946187    1.0
465115    1.0
835141    1.0
Name: 23533, dtype: float64

23682
user
23682     1.000000
401684    0.225018
950331    0.000000
173126    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173141    0.000000
Name: 23682, dtype: float64

23999
user
50758     1.000000
23999     1.000000
224421    0.624695
116524    0.492366
127843    0.400892
74527     0.348155
315409    0.312348
174016    0.307794
397119    0.292603
Name: 23999, dtype: float64

24006
user
113136    0.780869
107751    0.780869
45308     0.780869
74666     0.780869
279978    0.780869
247060    0.624695
358118    0.552158
3153      0.552158
29563     0.487805
Name: 24006, dtype: float64

24276
user
51496     0.577350
96722     0.577350
43065     0.577350
776175    0.461880
195582    0.450835
805528    0.408248
743374    0.320256
190145    0.305888
251311    0.284268
Name: 24276, dtype: float64

24283
user
572599    0.707107
46373     0.441726
389728    0.369274
251581    0.305424
705731    0.238909
178016    0.133038
173187    0.000000
173146    0.000000
173141    0.000000
Name: 24283, dtype: float64

24308
user
789611    1.000000
377242    1.000000
24308     1.000000
612464    0.218218
173187    0.000000
173146    0.000000
173141    0.000000
173218    0.000000
173126    0.000000
Name: 24308, dtype: float64

24319
user
326607    0.337284
676901    0.122169
589791    0.018851
76488     0.016549
173126    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173146    0.000000
Name: 24319, dtype: float64

24325
user
294245    0.500000
26888     0.500000
368338    0.400000
106056    0.253295
355767    0.246183
448451    0.234082
345       0.212132
215995    0.212047
67245     0.147710
Name: 24325, dtype: float64

24330
user
390564    0.135457
950331    0.000000
173146    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
173187    0.000000
Name: 24330, dtype: float64

24614
user
350778    0.529813
129168    0.529813
557866    0.529813
696718    0.529813
85853     0.529813
459047    0.529813
332711    0.529813
715137    0.529813
114908    0.529813
Name: 24614, dtype: float64

24883
user
633046    1.000000
24883     1.000000
364545    0.177778
950331    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
Name: 24883, dtype: float64

24895
user
387438    1.0
354968    1.0
24895     1.0
392580    1.0
1727      1.0
25573     1.0
245724    1.0
28763     1.0
318930    1.0
Name: 24895, dtype: float64

24902
user
8036      1.000000
351808    0.400000
180519    0.323498
385272    0.316228
108338    0.276172
108936    0.265513
710291    0.263117
71632     0.248452
129333    0.199007
Name: 24902, dtype: float64

24943
user
24943     1.000000
95664     1.000000
360079    1.000000
880552    1.000000
426302    1.000000
286800    0.585206
158429    0.419314
79647     0.416025
217426    0.346410
Name: 24943, dtype: float64

24953
user
250560    0.780869
674768    0.390434
133993    0.208398
90296     0.197152
114074    0.183101
53368     0.051700
172770    0.000000
173293    0.000000
176709    0.000000
Name: 24953, dtype: float64

24964
user
137575    0.443678
175320    0.443678
551587    0.443678
192778    0.354943
479278    0.346455
50137     0.346455
622858    0.346455
51466     0.313728
190564    0.266207
Name: 24964, dtype: float64

25002
user
137126    1.000000
25002     1.000000
473329    0.685994
452187    0.577350
276312    0.226455
390564    0.203186
884890    0.174574
173236    0.000000
173293    0.000000
Name: 25002, dtype: float64

25134
user
159773    0.57735
899670    0.57735
446105    0.57735
106216    0.57735
267306    0.57735
203033    0.57735
487400    0.57735
151203    0.57735
342978    0.57735
Name: 25134, dtype: float64

25486
user
732055    1.0
950331    0.0
173141    0.0
172770    0.0
172946    0.0
172955    0.0
173038    0.0
173126    0.0
173187    0.0
Name: 25486, dtype: float64

25563
user
511279    0.600000
95703     0.328798
172589    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 25563, dtype: float64

25573
user
387438    1.0
354968    1.0
24895     1.0
392580    1.0
1727      1.0
25573     1.0
245724    1.0
28763     1.0
318930    1.0
Name: 25573, dtype: float64

25840
user
2847      0.375917
334520    0.299005
234398    0.264157
863840    0.234920
576558    0.234920
928303    0.234920
460437    0.234920
133586    0.234920
140931    0.234920
Name: 25840, dtype: float64

25951
user
4629      0.298142
580520    0.260378
213301    0.186299
179727    0.132324
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
Name: 25951, dtype: float64

26162
user
281732    0.707107
700993    0.707107
776502    0.707107
320261    0.707107
247028    0.707107
894693    0.552158
196412    0.353553
211039    0.264906
745537    0.221201
Name: 26162, dtype: float64

26187
user
356471    0.148704
950331    0.000000
172589    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 26187, dtype: float64

26205
user
30101     0.205847
388218    0.167542
283542    0.154533
249880    0.106904
172946    0.000000
172955    0.000000
173038    0.000000
950331    0.000000
172589    0.000000
Name: 26205, dtype: float64

26298
user
131381    0.320750
659757    0.320750
246134    0.320750
322044    0.256600
315596    0.185185
135678    0.139589
861280    0.105339
68203     0.100219
90709     0.070014
Name: 26298, dtype: float64

26352
user
28722     1.000000
26352     1.000000
885528    1.000000
666409    0.707107
193499    0.577350
193549    0.435194
166       0.328266
173141    0.000000
173126    0.000000
Name: 26352, dtype: float64

26394
user
950331    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
173126    0.0
Name: 26394, dtype: float64

26415
user
136764    0.524142
714695    0.524142
452487    0.260771
318686    0.251588
641859    0.168815
169618    0.132599
171636    0.000000
172504    0.000000
173218    0.000000
Name: 26415, dtype: float64

26450
user
26450     1.000000
401104    1.000000
392903    1.000000
253154    0.707107
905460    0.707107
253153    0.707107
130006    0.529813
392887    0.396059
255258    0.328798
Name: 26450, dtype: float64

26506
user
26506     1.0
950331    0.0
173415    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 26506, dtype: float64

26510
user
412528    0.707107
212395    0.707107
111635    0.707107
150433    0.707107
212461    0.707107
173943    0.707107
173796    0.707107
292280    0.707107
154154    0.707107
Name: 26510, dtype: float64

26531
user
74592     0.818317
114257    0.577350
387478    0.500000
500916    0.500000
360002    0.500000
196448    0.372678
73676     0.312348
471483    0.288675
131497    0.288675
Name: 26531, dtype: float64

26705
user
562349    0.577350
96613     0.577350
45013     0.577350
487983    0.577350
95763     0.577350
428481    0.461880
702397    0.408248
836215    0.346410
423018    0.297044
Name: 26705, dtype: float64

26760
user
157564    0.296174
782157    0.296174
317713    0.296174
23533     0.296174
30184     0.296174
136661    0.296174
319105    0.296174
739296    0.296174
835141    0.296174
Name: 26760, dtype: float64

26843
user
336473    0.464238
224377    0.464238
804396    0.371391
885428    0.371391
397183    0.362509
193723    0.328266
366858    0.290007
216704    0.290007
130789    0.278543
Name: 26843, dtype: float64

26888
user
26888     1.000000
24325     0.500000
215995    0.424094
950331    0.000000
172946    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
Name: 26888, dtype: float64

26996
user
132799    1.0
105855    1.0
196696    1.0
216052    1.0
26996     1.0
28644     1.0
197937    1.0
87286     1.0
359458    1.0
Name: 26996, dtype: float64

27176
user
684910    0.404061
788114    0.369800
90754     0.228292
173146    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
Name: 27176, dtype: float64

27333
user
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 27333, dtype: float64

27339
user
703342    1.000000
627098    1.000000
253041    1.000000
729240    1.000000
27339     1.000000
360829    0.707107
269477    0.545545
65219     0.421076
172770    0.416025
Name: 27339, dtype: float64

27460
user
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 27460, dtype: float64

27465
user
815492    0.544331
710618    0.496243
930847    0.481125
262368    0.429669
1582      0.268010
171967    0.222967
150353    0.219943
251266    0.196323
5142      0.178174

Name: 27465, dtype: float64

27703
user
390006    0.404061
1409      0.404061
326545    0.404061
321594    0.404061
170923    0.404061
87516     0.404061
526951    0.404061
751014    0.303046
197359    0.303046
Name: 27703, dtype: float64

27836
user
359553    0.624695
911169    0.441726
586606    0.348009
41555     0.241566
128271    0.198166
101994    0.177084
288157    0.143551
186286    0.100174
171918    0.000000
Name: 27836, dtype: float64

27939
user
316768    1.0
695760    1.0
27939     1.0
50690     1.0
134761    1.0
50739     1.0
147932    1.0
29070     1.0
256789    1.0
Name: 27939, dtype: float64

27962
user
783730    1.000000
27962     1.000000
109581    1.000000
423018    0.514496
220825    0.512148
421743    0.512148
160914    0.500000
130768    0.428571
641859    0.193247
Name: 27962, dtype: float64

28032
user
439187    0.800000
851090    0.800000
188061    0.800000
732125    0.800000
61770     0.800000
340105    0.800000
401305    0.715542
744990    0.640000
263524    0.640000
Name: 28032, dtype: float64

28304
user
791844    0.780869
551576    0.624695
129098    0.624695
295763    0.624695
840877    0.624695
115682    0.460063
444370    0.441726
50137     0.390244
314389    0.344930
Name: 28304, dtype: float64

28330
user
317740    0.800000
198873    0.800000
74666     0.600000
107751    0.600000
113136    0.600000
45308     0.600000
279978    0.600000
50007     0.499756
789207    0.482418
Name: 28330, dtype: float64

28339
user
43065     0.419314
51496     0.419314
96722     0.419314
776175    0.335451
195582    0.327429
371474    0.314485
281748    0.296500
805528    0.296500
24276     0.242091
Name: 28339, dtype: float64

28524
user
71242     0.527750
158711    0.212174
469245    0.147232
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
950331    0.000000
Name: 28524, dtype: float64

28600
user
314002    0.513964
745127    0.327429
68750     0.327429
30202     0.296500
531322    0.262071
913037    0.242091
475084    0.231527
728391    0.174714
288240    0.161754
Name: 28600, dtype: float64

28644
user
132799    1.0
105855    1.0
196696    1.0
216052    1.0
26996     1.0
28644     1.0
197937    1.0
87286     1.0
359458    1.0
Name: 28644, dtype: float64

28722
user
28722     1.000000
26352     1.000000
885528    1.000000
666409    0.707107
193499    0.577350
193549    0.435194
166       0.328266
173141    0.000000
173126    0.000000
Name: 28722, dtype: float64

28724
user
399809    0.514496
317295    0.272587
172504    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
Name: 28724, dtype: float64

28739
user
950331    0.0
173421    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 28739, dtype: float64

28763
user
387438    1.0
354968    1.0
24895     1.0
392580    1.0
1727      1.0
25573     1.0
245724    1.0
28763     1.0
318930    1.0
Name: 28763, dtype: float64

28991
user
173421    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 28991, dtype: float64

29070
user
316768    1.0
695760    1.0
27939     1.0
50690     1.0
134761    1.0
50739     1.0
147932    1.0
29070     1.0
256789    1.0
Name: 29070, dtype: float64

29112
user
29112     1.0
950331    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 29112, dtype: float64

29192
user
319979    1.000000
212395    1.000000
284794    1.000000
280639    1.000000
173796    1.000000
412528    1.000000
111635    1.000000
29192     1.000000
70203     0.780869
Name: 29192, dtype: float64

29445
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 29445, dtype: float64

29491
user
355775    0.490973
249441    0.460287
285457    0.460287
582183    0.368230
450355    0.368230
195632    0.368230
260179    0.368230
389100    0.368230
11194     0.368230
Name: 29491, dtype: float64

29563
user
192226    0.780869
10287     0.780869
177065    0.780869
930037    0.780869
279978    0.624695
74666     0.624695
107751    0.624695
45308     0.624695
113136    0.624695
Name: 29563, dtype: float64

29669
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 29669, dtype: float64

29939
user
30758     0.800000
357672    0.758947
703432    0.600000
192450    0.600000
487327    0.600000
652607    0.600000
7488      0.600000
334992    0.600000
664747    0.600000
Name: 29939, dtype: float64

30097
user
391247    1.0
172946    0.0
172955    0.0
173038    0.0
173126    0.0
173141    0.0
173146    0.0
950331    0.0
172589    0.0
Name: 30097, dtype: float64

30101
user
315530    0.390567
388218    0.344879
283542    0.318102
501275    0.240377
249880    0.220059
26205     0.205847
401684    0.087884
251567    0.085229
69019     0.051833
Name: 30101, dtype: float64

30156
user
150132    0.373968
137899    0.305812
172770    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 30156, dtype: float64

30184
user
23533     1.0
317949    1.0
158717    1.0
524501    1.0
820044    1.0
739296    1.0
946187    1.0
465115    1.0
835141    1.0
Name: 30184, dtype: float64

30196
user
360476    0.380143
2131      0.380143
935034    0.304114
76564     0.304114
471642    0.304114
148169    0.304114
525593    0.304114
113896    0.304114
194777    0.304114
Name: 30196, dtype: float64

30202
user
195551    0.565685
913037    0.408248
22782     0.370869
170611    0.361961
135920    0.326599
28600     0.296500
728391    0.294628
101141    0.278524
386553    0.224781
Name: 30202, dtype: float64

30223
user
30223     1.000000
572720    0.242983
950331    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
173146    0.000000
173187    0.000000
Name: 30223, dtype: float64

30427
user
2295      1.0
173421    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 30427, dtype: float64

30438
user
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 30438, dtype: float64

30454
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 30454, dtype: float64

30758
user
357672    0.948683
29939     0.800000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
173146    0.000000
173187    0.000000
172770    0.000000
Name: 30758, dtype: float64

30970
user
570055    1.0
950331    0.0
172770    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
Name: 30970, dtype: float64

31000
user
109566    1.0
697629    1.0
256643    1.0
354616    1.0
49598     1.0
48740     1.0
352086    1.0
176896    1.0
357454    1.0
Name: 31000, dtype: float64

31010
user
95895     1.000000
113728    0.707107
665456    0.624695
867891    0.554700
861280    0.109472
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
Name: 31010, dtype: float64

31058
user
546902    0.615457
446157    0.615457
459734    0.615457
367815    0.615457
665848    0.469282
95336     0.418766
725655    0.418766
171582    0.355335
217426    0.355335
Name: 31058, dtype: float64

31176
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 31176, dtype: float64

31269
user
112746    0.348155
31285     0.268802
74999     0.128388
724982    0.097416
173038    0.000000
173126    0.000000
173141    0.000000
173146    0.000000
173187    0.000000
Name: 31269, dtype: float64

31285
user
149905    0.380143
482273    0.380143
42721     0.304114
8323      0.304114
757228    0.304114
87724     0.304114
899377    0.304114
200875    0.304114
709700    0.304114
Name: 31285, dtype: float64

31431
user
31431     1.000000
757292    1.000000
727829    0.780869
421319    0.707107
173187    0.000000
173146    0.000000
173141    0.000000
173126    0.000000
172490    0.000000
Name: 31431, dtype: float64

31624
user
256176    0.447214
95560     0.447214
700080    0.447214
846528    0.447214
608132    0.276026
589791    0.276026
223400    0.230089
840243    0.220193
730158    0.204598
Name: 31624, dtype: float64

31926
user
151661    0.780869
157653    0.607758
255287    0.552158
3882      0.499756
32306     0.450835
5010      0.390244
252207    0.292460
923459    0.258572
5142      0.255599
Name: 31926, dtype: float64

31984
user
31984     1.000000
74904     0.707107
298395    0.505076
2847      0.492366
180519    0.431331
177951    0.404061
2109      0.388075
46560     0.334825
923459    0.264906
Name: 31984, dtype: float64

31997
user
159024    0.600000
386072    0.600000
568571    0.565685
9510      0.499756
51766     0.317888
247634    0.237915
82952     0.199223
485567    0.087000
950331    0.000000
Name: 31997, dtype: float64

32143
user
49805     0.199851
158492    0.194450
157928    0.189805
23533     0.172929
465115    0.172929
815556    0.172929
39314     0.172929
906243    0.172929
782157    0.172929
Name: 32143, dtype: float64

32151
user
51957     0.800000
180541    0.350823
213971    0.336861
900562    0.263752
132504    0.162459
32143     0.138343
179727    0.132324
173218    0.000000
173187    0.000000
Name: 32151, dtype: float64

32198
user
950331    0.0
173421    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 32198, dtype: float64

32306
user
151661    0.577350
31926     0.450835
255287    0.408248
157653    0.273998
176665    0.243975
923459    0.191180
5142      0.188982
356252    0.184310
212969    0.170716
Name: 32306, dtype: float64

32338
user
950331    0.0
173421    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 32338, dtype: float64

32652
user
43805     1.000000
17698     1.000000
32652     1.000000
96575     0.217250
350771    0.165145
173141    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
Name: 32652, dtype: float64

32771
user
492757    1.000000
325116    0.707107
22608     0.662266
507738    0.492366
115600    0.468521
224347    0.279372
284357    0.214115
237668    0.180746
728009    0.161558
Name: 32771, dtype: float64

32779
user
950331    0.0
173421    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 32779, dtype: float64

32793
user
32793     1.000000
322627    0.396526
41555     0.386695
950331    0.000000
172589    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
Name: 32793, dtype: float64

32863
user
950331    0.0
173421    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 32863, dtype: float64

33053
user
500373    0.707107
392680    0.500000
225910    0.499756
557847    0.441726
179544    0.424264
807425    0.293294
73273     0.263523
110348    0.261116
361309    0.254558
Name: 33053, dtype: float64

33061
user
200652    0.441726
418510    0.441726
839712    0.441726
126931    0.441726
148206    0.312348
441889    0.312348
19437     0.284083
2419      0.206801
93647     0.187409
Name: 33061, dtype: float64

33094
user
127037    0.457496
781898    0.281633
109058    0.249584
315409    0.142898
674425    0.137249
710291    0.120375
30196     0.104348
752650    0.102872
222718    0.092957
Name: 33094, dtype: float64

33147
user
950331    0.0
173421    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 33147, dtype: float64

33179
user
364818    0.680414
325654    0.680414
269788    0.583450
268107    0.544331
286962    0.544331
578969    0.544331
190564    0.408248
664138    0.392837
899799    0.384900
Name: 33179, dtype: float64

33567
user
648839    1.0
783345    1.0
111561    1.0
786717    1.0
753506    1.0
314345    1.0
596425    1.0
257101    1.0
44077     1.0
Name: 33567, dtype: float64

33650
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 33650, dtype: float64

33831
user
750325    0.707107
66431     0.707107
926401    0.707107
393293    0.500000
855363    0.441726
314604    0.331042
251266    0.318788
101994    0.267261
90296     0.178529
Name: 33831, dtype: float64

34751
user
151456    0.707107
196412    0.353553
179488    0.248069
697977    0.202031
516840    0.197066
392082    0.184115
46936     0.173097
257609    0.155126
312492    0.149256
Name: 34751, dtype: float64

35172
user
108666    0.500000
195653    0.460287
917504    0.441726
129831    0.408248
250820    0.400000
71232     0.374766
41555     0.341793
652898    0.335578
136981    0.264906
Name: 35172, dtype: float64

35307
user
35307     1.000000
52663     0.524142
321677    0.441726
110306    0.431934
11951     0.279372
173325    0.000000
173300    0.000000
173415    0.000000
173293    0.000000
Name: 35307, dtype: float64

35538
user
588237    0.742781
870138    0.689655
899670    0.557086
203033    0.557086
159773    0.557086
151203    0.557086
267306    0.557086
106216    0.557086
487400    0.557086
Name: 35538, dtype: float64

36587
user
563103    1.000000
385143    1.000000
361892    1.000000
63998     1.000000
170172    0.707107
364520    0.624695
778423    0.554700
840243    0.492366
179488    0.350823
Name: 36587, dtype: float64

36636
user
356277    0.928477
498185    0.742781
470036    0.725018
441024    0.725018
863771    0.491919
887956    0.423239
252295    0.395904
359001    0.375161
4891      0.371391
Name: 36636, dtype: float64

37980
user
22636     1.0
261654    1.0
222975    1.0
153678    1.0
321692    1.0
37980     1.0
780237    1.0
55705     1.0
194122    1.0
Name: 37980, dtype: float64

38110
user
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 38110, dtype: float64

38120
user
882402    1.0
465152    1.0
43207     1.0
239439    1.0
648094    1.0
169215    1.0
2175      1.0
642214    1.0
230190    1.0
Name: 38120, dtype: float64

38738
user
352507    0.707107
172770    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 38738, dtype: float64

39188
user
14914     0.685994
86766     0.685994
753989    0.685994
885308    0.685994
150074    0.685994
702397    0.485071
279785    0.159222
150132    0.147839
836186    0.131212
Name: 39188, dtype: float64

39314
user
853410    1.000000
39314     1.000000
622340    1.000000
944394    1.000000
828625    0.894427
49805     0.780869
83257     0.577350
4347      0.529813
310557    0.514496
Name: 39314, dtype: float64

40447
user
40447     1.000000
220853    0.565685
531322    0.500000
134807    0.348155
138679    0.340207
196166    0.278543
363254    0.270765
705731    0.270295
5666      0.256600
Name: 40447, dtype: float64

41555
user
254239    0.483368
400694    0.483368
63030     0.483368
162500    0.483368
328802    0.483368
73653     0.483368
65017     0.448796
147610    0.414485
32793     0.386695
Name: 41555, dtype: float64

42317
user
392159    1.000000
42317     1.000000
836480    1.000000
363944    1.000000
859147    0.390567
284695    0.225647
173141    0.000000
172946    0.000000
172955    0.000000
Name: 42317, dtype: float64

42319
user
399753    0.6
387438    0.6
354968    0.6
24895     0.6
392580    0.6
1727      0.6
25573     0.6
245724    0.6
28763     0.6
Name: 42319, dtype: float64

42351
user
950331    0.0
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 42351, dtype: float64

42373
user
950331    0.0
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 42373, dtype: float64

42417
user
950331    0.0
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 42417, dtype: float64

42450
user
72699     1.000000
113066    1.000000
169197    0.624695
263894    0.529813
243313    0.371391
163884    0.237356
173141    0.000000
172955    0.000000
173038    0.000000
Name: 42450, dtype: float64

42484
user
551060    0.370625
634851    0.370625
252211    0.317808
74871     0.296500
488321    0.296500
611711    0.296500
290704    0.296500
553056    0.296500
394954    0.296500
Name: 42484, dtype: float64

42540
user
31000     0.928477
48740     0.928477
138698    0.928477
697629    0.928477
256643    0.928477
171046    0.928477
109566    0.928477
328852    0.928477
354616    0.928477
Name: 42540, dtype: float64

42615
user
82581     1.0
487327    1.0
652607    1.0
42615     1.0
7488      1.0
721140    1.0
645667    1.0
664747    1.0
192450    1.0
Name: 42615, dtype: float64

42721
user
899377    1.000000
42721     1.000000
709700    1.000000
757228    1.000000
87724     1.000000
8323      1.000000
501746    1.000000
470673    0.800000
131375    0.707107
Name: 42721, dtype: float64

42789
user
950331    0.0
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 42789, dtype: float64

43065
user
43065     1.000000
51496     1.000000
776175    0.800000
195582    0.780869
805528    0.707107
24276     0.577350
743374    0.554700
251311    0.492366
885332    0.492366
Name: 43065, dtype: float64

43128
user
43128     1.000000
386149    1.000000
322689    1.000000
327506    1.000000
138663    0.577350
269477    0.545545
539244    0.390360
467850    0.361787
96575     0.217250
Name: 43128, dtype: float64

43197
user
950331    0.0
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 43197, dtype: float64

43207
user
882402    1.0
465152    1.0
43207     1.0
239439    1.0
648094    1.0
169215    1.0
2175      1.0
642214    1.0
230190    1.0
Name: 43207, dtype: float64

43235
user
630347    1.000000
199077    0.428746
173141    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173146    0.000000
Name: 43235, dtype: float64

43292
user
49500     0.554700
75597     0.554700
359898    0.554700
332865    0.554700
171549    0.346518
138541    0.320256
150887    0.306282
674425    0.221880
597369    0.221880
Name: 43292, dtype: float64

43325
user
213231    0.577350
110773    0.577350
94663     0.577350
360829    0.408248
9852      0.201008
222193    0.186628
5015      0.180300
117820    0.150849
229831    0.115470
Name: 43325, dtype: float64

43510
user
935034    1.000000
136933    0.577350
350644    0.500000
113193    0.441726
174016    0.307794
30196     0.304114
173141    0.000000
173038    0.000000
173126    0.000000
Name: 43510, dtype: float64

43726
user
115485    0.552158
328852    0.441726
354616    0.441726
49598     0.441726
352086    0.441726
176896    0.441726
48740     0.441726
357454    0.441726
109566    0.441726
Name: 43726, dtype: float64

43742
user
431662    0.615457
652088    0.586939
90709     0.373176
69329     0.348155
861280    0.184159
132144    0.165977
69019     0.108905
950331    0.000000
172946    0.000000
Name: 43742, dtype: float64

43793
user
87328     0.253061
347289    0.227866
71789     0.224387
114663    0.202548
147193    0.202548
648839    0.202548
66608     0.202548
284794    0.202548
319979    0.202548
Name: 43793, dtype: float64

43801
user
83257     0.57735
172770    0.00000
173415    0.00000
173325    0.00000
173300    0.00000
173293    0.00000
173236    0.00000
173218    0.00000
173187    0.00000
Name: 43801, dtype: float64

43805
user
43805     1.000000

Name: 45410, dtype: float64

45431
user
950331    0.0
172770    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 45431, dtype: float64

45482
user
290423    0.424094
249051    0.140797
950331    0.000000
172589    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 45482, dtype: float64

45519
user
172770    0.0
173415    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 45519, dtype: float64

45609
user
928292    1.000000
46592     0.270914
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
172770    0.000000
173146    0.000000
Name: 45609, dtype: float64

45617
user
583035    0.707107
686300    0.223607
807425    0.219971
217350    0.137725
173126    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173141    0.000000
Name: 45617, dtype: float64

45627
user
256396    0.800000
143034    0.328798
48793     0.271420
322597    0.192773
351825    0.181827
728009    0.129247
724982    0.110214
173293    0.000000
173236    0.000000
Name: 45627, dtype: float64

45836
user
132641    1.000000
448633    1.000000
45836     1.000000
92068     0.894427
199410    0.780869
212057    0.707107
4347      0.529813
686300    0.316228
276312    0.226455
Name: 45836, dtype: float64

45885
user
135672    0.278207
950331    0.000000
172770    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 45885, dtype: float64

45970
user
45970     1.000000
385514    1.000000
353436    1.000000
679280    1.000000
505806    0.386912
109622    0.323423
623554    0.285714
173187    0.000000
173218    0.000000
Name: 45970, dtype: float64

45978
user
128615    0.886969
574781    0.426401
787677    0.369274
550014    0.266091
317295    0.254152
385219    0.217001
674425    0.191881
392887    0.189990
155100    0.114416
Name: 45978, dtype: float64

46003
user
107237    0.780869
783096    0.285714
350771    0.220193
114160    0.187135
213301    0.186299
173038    0.000000
173126    0.000000
173141    0.000000
173146    0.000000
Name: 46003, dtype: float64

46154
user
223211    0.399043
172946    0.399043
122394    0.399043
149217    0.399043
574786    0.399043
156256    0.399043
359293    0.399043
101449    0.399043
804396    0.399043
Name: 46154, dtype: float64

46159
user
196734    0.707107
818006    0.458349
176665    0.338062
243883    0.288675
71632     0.248452
385612    0.164153
950331    0.000000
173038    0.000000
172770    0.000000
Name: 46159, dtype: float64

46255
user
46255     1.000000
327434    1.000000
399266    0.624695
293300    0.624695
851312    0.554700
882082    0.492366
361582    0.266667
8647      0.249029
728009    0.161558
Name: 46255, dtype: float64

46312
user
648676    1.000000
169608    1.000000
46312     1.000000
582482    1.000000
87328     0.780869
219577    0.547723
347289    0.500000
856133    0.245718
249051    0.234662
Name: 46312, dtype: float64

46322
user
816326    0.639602
376096    0.639602
94448     0.639602
248522    0.639602
395445    0.639602
620236    0.511682
465110    0.452267
256497    0.452267
397159    0.452267
Name: 46322, dtype: float64

46373
user
390639    0.773021
172078    0.624695
566689    0.624695
193723    0.441726
24283     0.441726
389728    0.326236
705731    0.211065
155100    0.167623
350771    0.137553
Name: 46373, dtype: float64

46551
user
67901     0.765705
132614    0.307579
173146    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
950331    0.000000
Name: 46551, dtype: float64

46560
user
145101    0.357030
192226    0.334825
362085    0.334825
177065    0.334825
31984     0.334825
809373    0.334825
10287     0.334825
930037    0.334825
191363    0.334825
Name: 46560, dtype: float64

46592
user
783901    0.475984
67429     0.338643
85315     0.338643
726820    0.338643
194342    0.338643
256861    0.338643
558567    0.338643
428771    0.338643
106580    0.338643
Name: 46592, dtype: float64

46607
user
813771    1.000000
199410    0.624695
650646    0.340503
950331    0.000000
173126    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173146    0.000000
Name: 46607, dtype: float64

46715
user
46715     1.000000
309102    0.780869
148702    0.304114
315118    0.258738
820908    0.197546
171967    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
Name: 46715, dtype: float64

46758
user
422401    1.000000
321865    1.000000
677778    1.000000
254215    1.000000
46758     1.000000
539803    1.000000
418830    0.707107
179653    0.600000
305522    0.524142
Name: 46758, dtype: float64

46833
user
68246     0.441726
356471    0.154825
153457    0.131881
950331    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
173146    0.000000
173218    0.000000
Name: 46833, dtype: float64

46936
user
86173     0.244796
776878    0.244796
151456    0.244796
695627    0.244796
377841    0.218952
371282    0.195837
435544    0.191154
5010      0.191154
112565    0.183597
Name: 46936, dtype: float64

46980
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 46980, dtype: float64

46987
user
320723    0.331295
196448    0.329243
73676     0.275944
471483    0.255031
74592     0.240981
854097    0.234261
172339    0.227266
26531     0.220863
764772    0.191273
Name: 46987, dtype: float64

47085
user
169585    0.339199
172079    0.263038
950331    0.000000
173146    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
173218    0.000000
Name: 47085, dtype: float64

47297
user
107432    1.000000
504649    1.000000
112616    1.000000
47297     1.000000
85705     1.000000
874578    0.980581
855363    0.780869
192236    0.780869
3019      0.762493
Name: 47297, dtype: float64

47462
user
47462     1.0
172770    0.0
173415    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
Name: 47462, dtype: float64

47478
user
47478     1.000000
147927    0.707107
92767     0.565685
279652    0.421076
262002    0.363803
155100    0.357771
106056    0.281439
127124    0.255822
247859    0.242091
Name: 47478, dtype: float64

47484
user
66639     0.707107
65841     0.707107
844482    0.707107
340512    0.707107
447445    0.707107
192944    0.707107
417735    0.707107
643010    0.685994
667169    0.552158
Name: 47484, dtype: float64

47493
user
47493     1.000000
326587    1.000000
147610    0.514496
219765    0.331042
184471    0.280745
247859    0.242091
133400    0.197305
53368     0.165521
856133    0.122859
Name: 47493, dtype: float64

47528
user
386010    0.707107
91034     0.464238
211972    0.374634
68977     0.370625
156230    0.337869
256163    0.178529
171871    0.000000
172955    0.000000
173325    0.000000
Name: 47528, dtype: float64

47751
user
163884    0.237356
194387    0.229416
217350    0.155818
173146    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
Name: 47751, dtype: float64

48104
user
522869    0.707107
859147    0.650945
129012    0.374634
409870    0.346410
154501    0.290191
172589    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
Name: 48104, dtype: float64

48295
user
261456    0.408248
49642     0.194717
172955    0.000000
173421    0.000000
173415    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
Name: 48295, dtype: float64

48369
user
177951    0.505076
133470    0.424264
388218    0.397360
130558    0.390360
91034     0.371391
176665    0.253546
173293    0.000000
173236    0.000000
173218    0.000000
Name: 48369, dtype: float64

48442
user
357985    1.000000
118351    0.742781
294618    0.707107
221510    0.707107
65621     0.624695
791637    0.490290
180539    0.447214
293161    0.439057
391017    0.274721
Name: 48442, dtype: float64

48575
user
259513    1.0
48575     1.0
200843    1.0
678481    1.0
950331    0.0
173038    0.0
173126    0.0
173141    0.0
173146    0.0
Name: 48575, dtype: float64

48688
user
469607    0.492366
132144    0.207471
3906      0.201008
173187    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
173146    0.000000
Name: 48688, dtype: float64

48699
user
48699     1.0
170196    1.0
950331    0.0
173146    0.0
172955    0.0
173038    0.0
173126    0.0
173141    0.0
173218    0.0
Name: 48699, dtype: float64

48725
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 48725, dtype: float64

48732
user
351740    1.0
173187    0.0
172955    0.0
173038    0.0
173126    0.0
173141    0.0
173146    0.0
950331    0.0
172770    0.0
Name: 48732, dtype: float64

48740
user
109566    1.0
697629    1.0
256643    1.0
354616    1.0
49598     1.0
48740     1.0
352086    1.0
176896    1.0
357454    1.0
Name: 48740, dtype: float64

48786
user
148013    1.000000
85601     1.000000
434980    1.000000
48786     1.000000
500728    1.000000
386300    1.000000
112521    1.000000
328899    0.707107
469069    0.624695
Name: 48786, dtype: float64

48793
user
158492    0.529859
174892    0.424094
551366    0.424094
553056    0.424094
488321    0.424094
611711    0.424094
71798     0.424094
74871     0.424094
394954    0.424094
Name: 48793, dtype: float64

48799
user
48799     1.000000
159599    0.390360
246061    0.361787
390564    0.270914
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 48799, dtype: float64

48814
user
204033    1.000000
48814     1.000000
931768    1.000000
719811    1.000000
75174     1.000000
707460    1.000000
98330     0.780869
62904     0.585206
211914    0.492366
Name: 48814, dtype: float64

48822
user
194889    0.624695
661090    0.519778
109622    0.202041
179719    0.192785
623554    0.178484
580520    0.162657
694627    0.057266
173187    0.000000
173218    0.000000
Name: 48822, dtype: float64

48924
user
402115    1.000000
728009    0.121169
172770    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 48924, dtype: float64

48977
user
42615     0.552158
192450    0.552158
886362    0.552158
790296    0.552158
578647    0.552158
487327    0.552158
652607    0.552158
721140    0.552158
334992    0.552158
Name: 48977, dtype: float64

49201
user
950331    0.0
172770    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 49201, dtype: float64

49451
user
194387    0.305888
217350    0.116863
173146    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
950331    0.000000
172770    0.000000
Name: 49451, dtype: float64

49486
user
329217    0.577350
387463    0.577350
214528    0.577350
447025    0.577350
334089    0.577350
118351    0.321634
399680    0.195881
652898    0.164399
360130    0.144620
Name: 49486, dtype: float64

49500
user
49500     1.000000
332865    1.000000
43292     0.554700
150887    0.552158
674425    0.400000
173146    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
Name: 49500, dtype: float64

49529
user
49529     1.000000
868283    1.000000
694627    0.366679
420805    0.297044
163884    0.237356
900562    0.197814
179727    0.088216
173218    0.000000
173187    0.000000
Name: 49529, dtype: float64

49534
user
950331    0.0
172770    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 49534, dtype: float64

49598
user
109566    1.0
697629    1.0
256643    1.0
354616    1.0
49598     1.0
48740     1.0
352086    1.0
176896    1.0
357454    1.0
Name: 49598, dtype: float64

49642
user
885332    0.245672
793692    0.243396
818821    0.243396
697795    0.243396
696729    0.243396
351552    0.243396
316443    0.243396
499267    0.243396
475084    0.215029
Name: 49642, dtype: float64

49680
user
806808    0.348155
828090    0.348155
491888    0.261116
94677     0.169819
744       0.168287
327058    0.155700
109622    0.118232
386997    0.045241
173146    0.000000
Name: 49680, dtype: float64

49738
user
130534    1.0
950331    0.0
172770    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
Name: 49738, dtype: float64

49742
user
328956    0.707107
70333     0.478091
256325    0.229794
173415    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
Name: 49742, dtype: float64

49771
user
22636     1.0
261654    1.0
222975    1.0
153678    1.0
321692    1.0
37980     1.0
780237    1.0
55705     1.0
194122    1.0
Name: 49771, dtype: float64

49805
user
201564    0.780869
944394    0.780869
39314     0.780869
622340    0.780869
853410    0.780869
828625    0.698430
249441    0.624695
83257     0.450835
4347      0.413714
Name: 49805, dtype: float64

49936
user
93168     1.000000
85694     0.268328
356471    0.247841
173428    0.000000
173415    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
Name: 49936, dtype: float64

49954
user
44204     0.421076
148777    0.421076
532651    0.421076
15289     0.421076
191551    0.421076
940225    0.421076
194777    0.421076
113896    0.421076
63763     0.421076
Name: 49954, dtype: float64

49956
user
237186    1.000000
284374    0.707107
386968    0.298511
94677     0.243884
73577     0.232845
43793     0.151911
391794    0.113410
172049    0.000000
172066    0.000000
Name: 49956, dtype: float64

49999
user
323570    0.610762
351825    0.530612
247085    0.315519
358201    0.311740
177628    0.242437
215649    0.178484
386968    0.120617
71205     0.104986
391153    0.104328
Name: 49999, dtype: float64

50007
user
148586    0.780869
198873    0.624695
317740    0.624695
28330     0.499756
23433     0.431163
789207    0.376705
178898    0.340799
173428    0.275944
652365    0.217491
Name: 50007, dtype: float64

50137
user
551587    0.780869
175320    0.780869
295763    0.624695
840877    0.624695
551576    0.624695
129098    0.624695
479278    0.609756
51466     0.552158
115161    0.450835
Name: 50137, dtype: float64

50204
user
180453    1.000000
85626     0.615457
4629      0.298142
172770    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 50204, dtype: float64

50553
user
321082    0.423999
85785     0.423999
194152    0.423999
804396    0.423999
197268    0.411340
689905    0.393673
579530    0.355578
366858    0.331088
68246     0.299813
Name: 50553, dtype: float64

50592
user
138402    1.000000
50592     1.000000
397331    1.000000
18611     1.000000
354415    0.624695
197904    0.514496
69546     0.514496
539244    0.390360
90296     0.252478
Name: 50592, dtype: float64

50690
user
316768    1.0
695760    1.0
27939     1.0
50690     1.0
134761    1.0
50739     1.0
147932    1.0
29070     1.0
256789    1.0
Name: 50690, dtype: float64

50713
user
50713     1.000000
290566    0.800000
789207    0.452267
130558    0.390360
459433    0.336861
243883    0.115470
950331    0.000000
172955    0.000000
173038    0.000000
Name: 50713, dtype: float64

50739
user
316768    1.0
695760    1.0
27939     1.0
50690     1.0
134761    1.0
50739     1.0
147932    1.0
29070     1.0
256789    1.0
Name: 50739, dtype: float64

50758
user
50758     1.000000
23999     1.000000
224421    0.624695
116524    0.492366
127843    0.400892
74527     0.348155
315409    0.312348
174016    0.307794
397119    0.292603
Name: 50758, dtype: float64

50808
user
50808     1.000000
161601    0.707107
131485    0.464238
688218    0.424264
305522    0.419314
159313    0.390567
323570    0.318223
397635    0.307692
127124    0.255822
Name: 50808, dtype: float64

51021
user
699829    1.000000
51021     1.000000
382866    0.707107
88042     0.492366
401684    0.281272
425396    0.242536
391631    0.224860
217350    0.194772
53368     0.165521
Name: 51021, dtype: float64

51374
user
950331    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 51374, dtype: float64

51405
user
551366    0.268028
214780    0.268028
786333    0.268028
71798     0.268028
837685    0.268028
223400    0.229832
335411    0.214423
173187    0.214423
6899      0.214423
Name: 51405, dtype: float64

51448
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 51448, dtype: float64

51466
user
175320    0.707107
551587    0.707107
140931    0.707107
460437    0.707107
71170     0.606339
479278    0.552158
50137     0.552158
389013    0.452267
2379      0.435194
Name: 51466, dtype: float64

51496
user
43065     1.000000
51496     1.000000
776175    0.800000
195582    0.780869
805528    0.707107
24276     0.577350
743374    0.554700
251311    0.492366
885332    0.492366
Name: 51496, dtype: float64

51752
user
51752     1.0
219458    1.0
199172    1.0
295792    1.0
261822    1.0
193795    1.0
260171    1.0
329184    1.0
365315    1.0
Name: 51752, dtype: float64

51766
user
732125    0.529813
851090    0.529813
61770     0.529813
188061    0.529813
386072    0.529813
340105    0.529813
159024    0.529813
439187    0.529813
783901    0.517143
Name: 51766, dtype: float64

51866
user
684910    0.505076
950331    0.000000
172770    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 51866, dtype: float64

51957
user
32151     0.800000
180541    0.280659
213971    0.269489
534410    0.223801
900562    0.211002
90754     0.136975
132504    0.129967
32143     0.110674
179727    0.105859
Name: 51957, dtype: float64

52284
user
435544    0.401754
264572    0.157378
46936     0.125947
485567    0.074602
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
950331    0.000000
Name: 52284, dtype: float64

52424
user
250580    0.390360
170611    0.114184
150196    0.111658
173146    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
950331    0.000000
Name: 52424, dtype: float64

52558
user
148013    1.000000
85601     1.000000
434980    1.000000
48786     1.000000
500728    1.000000
386300    1.000000
112521    1.000000
328899    0.707107
469069    0.624695
Name: 52558, dtype: float64

52663
user
212239    0.524142
437764    0.524142
35307     0.524142
172049    0.419314
864848    0.327429
115600    0.261943
74344     0.251588
321677    0.231527
190348    0.228755
Name: 52663, dtype: float64

52776
user
209783    0.707107
459047    0.707107
715137    0.707107
175861    0.707107
568330    0.552158
560395    0.500000
170419    0.408248
24614     0.374634
211972    0.331133
Name: 52776, dtype: float64

53026
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 53026, dtype: float64

53199
user
481150    1.000000
502763    0.468521
923459    0.264906
173146    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
Name: 53199, dtype: float64

53202
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 53202, dtype: float64

53311
user
169618    0.316228
172589    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
Name: 53311, dtype: float64

53332
user
53332     1.000000
622936    1.000000
402103    0.707107
568571    0.707107
220825    0.512148
421743    0.512148
932113    0.492366
190348    0.436436
114074    0.293105
Name: 53332, dtype: float64

53368
user

Name: 63030, dtype: float64

63246
user
300358    0.140028
462894    0.130013
143948    0.068945
70779     0.030238
173187    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
173146    0.000000
Name: 63246, dtype: float64

63399
user
664747    0.780869
645667    0.780869
703432    0.780869
487327    0.780869
652607    0.780869
721140    0.780869
42615     0.780869
334992    0.780869
7488      0.780869
Name: 63399, dtype: float64

63512
user
197359    0.447214
751014    0.447214
179745    0.447214
94677     0.218137
46322     0.190693
27703     0.135526
5666      0.114755
138574    0.110657
109622    0.086784
Name: 63512, dtype: float64

63622
user
309828    1.000000
250513    1.000000
461917    1.000000
105989    1.000000
197893    1.000000
63622     1.000000
252432    1.000000
721134    0.970143
721787    0.707107
Name: 63622, dtype: float64

63653
user
950331    0.0
173421    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 63653, dtype: float64

63697
user
913374    0.441726
132480    0.331295
72566     0.331295
706437    0.206958
396276    0.203898
239796    0.200877
208228    0.170450
129686    0.146592
21542     0.121133
Name: 63697, dtype: float64

63751
user
950331    0.0
173421    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 63751, dtype: float64

63763
user
194777    1.000000
44204     1.000000
76564     1.000000
113896    1.000000
63763     1.000000
940225    1.000000
148777    1.000000
89712     0.928477
87704     0.745356
Name: 63763, dtype: float64

63870
user
950331    0.0
173421    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 63870, dtype: float64

63998
user
563103    1.000000
385143    1.000000
361892    1.000000
63998     1.000000
170172    0.707107
364520    0.624695
778423    0.554700
840243    0.492366
179488    0.350823
Name: 63998, dtype: float64

64255
user
388390    0.624695
950331    0.000000
173428    0.000000
173415    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
Name: 64255, dtype: float64

64269
user
321594    0.327327
326545    0.327327
87516     0.327327
170923    0.327327
390006    0.327327
1409      0.327327
932113    0.201456
71245     0.181568
88418     0.181568
Name: 64269, dtype: float64

64301
user
44878     0.226180
63030     0.205499
400694    0.205499
162500    0.205499
656088    0.205499
73653     0.205499
67890     0.205499
149955    0.205499
922709    0.205499
Name: 64301, dtype: float64

64375
user
71232     0.423999
198050    0.237915
950331    0.000000
173141    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173146    0.000000
Name: 64375, dtype: float64

64412
user
249421    0.378788
220831    0.322587
190725    0.186097
256163    0.082408
172490    0.000000
172589    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
Name: 64412, dtype: float64

64551
user
64551     1.000000
828166    0.346410
133400    0.147979
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
173146    0.000000
173187    0.000000
Name: 64551, dtype: float64

64632
user
258080    1.000000
64632     1.000000
65433     0.424264
390564    0.270914
356252    0.239426
173187    0.000000
173126    0.000000
173141    0.000000
173146    0.000000
Name: 64632, dtype: float64

64652
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 64652, dtype: float64

64762
user
279615    0.306570
105881    0.290957
130044    0.288487
172589    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
950331    0.000000
Name: 64762, dtype: float64

64931
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 64931, dtype: float64

65014
user
65014     1.0
950331    0.0
173146    0.0
172946    0.0
172955    0.0
173038    0.0
173126    0.0
173141    0.0
173187    0.0
Name: 65014, dtype: float64

65017
user
73653     0.928477
63030     0.928477
254239    0.928477
328802    0.928477
400694    0.928477
162500    0.928477
147610    0.796162
947671    0.510662
891451    0.491919
Name: 65017, dtype: float64

65081
user
774737    0.662266
197081    0.651584
54441     0.529813
11935     0.529813
811320    0.529813
202112    0.468293
4347      0.438596
108457    0.438596
71789     0.407597
Name: 65081, dtype: float64

65219
user
319891    0.421076
944394    0.421076
606620    0.421076
622340    0.421076
39314     0.421076
253041    0.421076
27339     0.421076
853410    0.421076
729240    0.421076
Name: 65219, dtype: float64

65345
user
195083    1.000000
823508    1.000000
353976    1.000000
149737    1.000000
222092    1.000000
65345     1.000000
129294    0.707107
570294    0.650945
550554    0.554700
Name: 65345, dtype: float64

65433
user
65841     0.707107
417735    0.707107
66639     0.707107
447445    0.707107
340512    0.707107
643010    0.685994
434598    0.565685
493676    0.565685
130120    0.565685
Name: 65433, dtype: float64

65483
user
129160    0.565685
226057    0.441726
229831    0.212132
74751     0.204302
149300    0.154678
224927    0.143942
921028    0.128665
350771    0.062280
173218    0.000000
Name: 65483, dtype: float64

65621
user
48442     0.624695
357985    0.624695
118351    0.464012
294618    0.441726
221510    0.441726
791637    0.306282
180539    0.279372
293161    0.274277
530433    0.206180
Name: 65621, dtype: float64

65624
user
180710    1.0
950331    0.0
172770    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
Name: 65624, dtype: float64

65788
user
123958    0.707107
241453    0.707107
43793     0.107417
171636    0.000000
172770    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
Name: 65788, dtype: float64

65841
user
417735    1.000000
65841     1.000000
340512    1.000000
66639     1.000000
643010    0.970143
667169    0.780869
65433     0.707107
47484     0.707107
870790    0.685994
Name: 65841, dtype: float64

65902
user
637070    0.780869
950331    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
173146    0.000000
Name: 65902, dtype: float64

66002
user
46592     0.203186
172589    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 66002, dtype: float64

66347
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 66347, dtype: float64

66367
user
116780    0.441726
950331    0.000000
173146    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
173187    0.000000
Name: 66367, dtype: float64

66411
user
192285    0.424094
26760     0.236940
276312    0.169842
173141    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173187    0.000000
Name: 66411, dtype: float64

66431
user
66431     1.000000
926401    1.000000
33831     0.707107
393293    0.707107
855363    0.624695
314604    0.468165
251266    0.450835
101994    0.377964
90296     0.252478
Name: 66431, dtype: float64

66608
user
66608     1.000000
677551    1.000000
288873    0.707107
698792    0.624695
192437    0.507093
198312    0.424264
851312    0.277350
82952     0.249029
43793     0.202548
Name: 66608, dtype: float64

66634
user
109057    0.857493
950331    0.000000
172589    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 66634, dtype: float64

66639
user
417735    1.000000
65841     1.000000
340512    1.000000
66639     1.000000
643010    0.970143
667169    0.780869
65433     0.707107
47484     0.707107
870790    0.685994
Name: 66639, dtype: float64

66654
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 66654, dtype: float64

67088
user
199202    0.457496
197460    0.457496
151373    0.285795
149174    0.278423
136933    0.264135
452187    0.264135
211972    0.171394
334694    0.163679
290423    0.155217
Name: 67088, dtype: float64

67211
user
95887     0.707107
149905    0.707107
482273    0.707107
252734    0.441726
397051    0.428746
201482    0.408248
621199    0.374634
918706    0.363803
95985     0.312348
Name: 67211, dtype: float64

67245
user
417312    0.615457
168899    0.615457
332593    0.615457
721055    0.435194
424678    0.435194
218450    0.355335
153279    0.355335
385138    0.348155
345       0.348155
Name: 67245, dtype: float64

67288
user
950331    0.0
173421    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 67288, dtype: float64

67351
user
950331    0.0
173421    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 67351, dtype: float64

67395
user
156698    1.000000
806497    1.000000
59146     0.707107
363072    0.577350
286366    0.577350
85669     0.500000
159353    0.266667
356252    0.239426
593182    0.175920
Name: 67395, dtype: float64

67429
user
389047    1.0
558567    1.0
277858    1.0
256861    1.0
159824    1.0
67429     1.0
106580    1.0
72150     1.0
726820    1.0
Name: 67429, dtype: float64

67485
user
394415    1.000000
67485     1.000000
219615    1.000000
196448    0.596285
811088    0.369274
194387    0.305888
109622    0.258738
163884    0.237356
179727    0.132324
Name: 67485, dtype: float64

67607
user
707094    1.00000
67607     1.00000
148839    0.57735
153457    0.26389
173146    0.00000
173038    0.00000
173126    0.00000
173141    0.00000
173218    0.00000
Name: 67607, dtype: float64

67868
user
72849     0.360159
824879    0.300463
776878    0.283069
199202    0.283069
179544    0.283069
197460    0.283069
795396    0.283069
190521    0.283069
371282    0.226455
Name: 67868, dtype: float64

67888
user
129012    0.165486
5311      0.101044
950331    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
173146    0.000000
173187    0.000000
173236    0.000000
Name: 67888, dtype: float64

67890
user
262112    1.000000
173038    1.000000
913037    0.577350
85626     0.492366
218901    0.213785
64301     0.205499
728009    0.121169
172770    0.000000
172946    0.000000
Name: 67890, dtype: float64

67901
user
46551     0.765705
350771    0.043183
385272    0.031009
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173325    0.000000
Name: 67901, dtype: float64

67902
user
389789    0.980581
519716    0.577350
788114    0.462250
173146    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
Name: 67902, dtype: float64

68072
user
366741    0.270501
950331    0.000000
173146    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
173218    0.000000
Name: 68072, dtype: float64

68122
user
538853    0.374634
169881    0.331133
864848    0.292540
753900    0.280976
191568    0.280976
500654    0.280976
282575    0.264906
133470    0.264906
355767    0.230571
Name: 68122, dtype: float64

68203
user
481628    0.505207
138572    0.446544
591369    0.416605
936541    0.416605
470215    0.390567
261998    0.390567
322044    0.390567
798855    0.390567
282875    0.362632
Name: 68203, dtype: float64

68246
user
804396    0.707107
366858    0.552158
328956    0.500000
127770    0.468293
87328     0.441726
326195    0.441726
46833     0.441726
172066    0.435194
136933    0.408248
Name: 68246, dtype: float64

68563
user
392159    1.000000
42317     1.000000
836480    1.000000
363944    1.000000
859147    0.390567
284695    0.225647
173141    0.000000
172946    0.000000
172955    0.000000
Name: 68563, dtype: float64

68632
user
51496     0.201456
1409      0.201456
252432    0.201456
43065     0.201456
96722     0.201456
63622     0.201456
755162    0.201456
250513    0.201456
87516     0.201456
Name: 68632, dtype: float64

68716
user
556848    1.000000
882571    0.325396
950331    0.000000
172589    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 68716, dtype: float64

68750
user
155148    0.624695
495957    0.558744
28600     0.327429
724982    0.107578
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173146    0.000000
Name: 68750, dtype: float64

68939
user
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 68939, dtype: float64

68977
user
47528     0.370625
211068    0.370625
386131    0.370625
605904    0.370625
380154    0.370625
471642    0.296500
11328     0.289409
481628    0.287647
158718    0.281284
Name: 68977, dtype: float64

69019
user
571810    0.221187
479148    0.221187
753494    0.221187
179008    0.176950
257776    0.176950
250513    0.132712
105989    0.132712
63622     0.132712
804396    0.132712
Name: 69019, dtype: float64

69329
user
652088    0.374634
329189    0.374634
43742     0.348155
467850    0.255822
861280    0.103211
752650    0.053000
173146    0.000000
173187    0.000000
173141    0.000000
Name: 69329, dtype: float64

69546
user
12567     0.685994
671905    0.685994
777853    0.514496
12225     0.514496
50592     0.514496
397331    0.514496
138402    0.514496
18611     0.514496
354415    0.321403
Name: 69546, dtype: float64

69562
user
898548    0.894427
950331    0.000000
172770    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 69562, dtype: float64

69676
user
113135    0.423999
838116    0.423999
109687    0.423999
809373    0.317999
362085    0.317999
348677    0.299813
503594    0.264870
194941    0.224860
308086    0.212000
Name: 69676, dtype: float64

70099
user
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 70099, dtype: float64

70159
user
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 70159, dtype: float64

70195
user
740367    0.707107
678384    0.516398
950331    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
172589    0.000000
Name: 70195, dtype: float64

70203
user
224545    0.780869
319979    0.780869
212395    0.780869
284794    0.780869
280639    0.780869
173796    0.780869
29192     0.780869
111635    0.780869
412528    0.780869
Name: 70203, dtype: float64

70299
user
175043    1.000000
319818    0.762493
6169      0.552158
781898    0.369358
172946    0.000000
172955    0.000000
173038    0.000000
950331    0.000000
172770    0.000000
Name: 70299, dtype: float64

70326
user
859384    1.00000
132144    0.26968
950331    0.00000
173141    0.00000
172946    0.00000
172955    0.00000
173038    0.00000
173126    0.00000
173146    0.00000
Name: 70326, dtype: float64

70333
user
49742     0.478091
434550    0.478091
342506    0.478091
350965    0.478091
469069    0.373327
388896    0.338062
328956    0.338062
276610    0.332923
152915    0.310759
Name: 70333, dtype: float64

70650
user
749783    0.195973
230190    0.188982
194482    0.188982
709411    0.188982
38120     0.188982
648094    0.188982
126234    0.188982
642214    0.188982
43207     0.188982
Name: 70650, dtype: float64

70651
user
216874    0.615457
72348     0.615457
107751    0.492366
74666     0.492366
113136    0.492366
45308     0.492366
279978    0.492366
24006     0.384473
831703    0.362977
Name: 70651, dtype: float64

70778
user
70778     1.0
809423    1.0
950331    0.0
172946    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
Name: 70778, dtype: float64

70779
user
736492    0.359908
288030    0.359908
171136    0.359908
459702    0.359908
397753    0.359908
176888    0.254493
801415    0.238355
300358    0.215945
427974    0.203595
Name: 70779, dtype: float64

70799
user
70799     1.000000
255093    0.609994
71232     0.423999
46592     0.270914
156230    0.270295
32143     0.103757
173141    0.000000
172955    0.000000
173038    0.000000
Name: 70799, dtype: float64

70813
user
633046    1.000000
24883     1.000000
364545    0.177778
950331    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
Name: 70813, dtype: float64

70861
user
398361    1.000000
924557    1.000000
70861     1.000000
85645     0.707107
5666      0.256600
133400    0.246632
20363     0.205196
256325    0.172345
745537    0.156412
Name: 70861, dtype: float64

71046
user
744       0.366851
367648    0.316228
134866    0.316228
72686     0.243332
441414    0.098374
950331    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
Name: 71046, dtype: float64

71170
user
460437    0.857493
140931    0.857493
51466     0.606339
389013    0.548454
2847      0.527750
2379      0.527750
804396    0.514496
366858    0.401754
73676     0.401754
Name: 71170, dtype: float64

71205
user
284357    0.368569
392903    0.324785
401104    0.324785
26450     0.324785
400110    0.324785
526951    0.259828
345311    0.259828
380154    0.259828
386131    0.259828
Name: 71205, dtype: float64

71232
user
70799     0.423999
461242    0.423999
282529    0.423999
128414    0.423999
356593    0.423999
64375     0.423999
35172     0.374766
108666    0.374766
195653    0.345000
Name: 71232, dtype: float64

71242
user
28524     0.527750
247685    0.492366
248657    0.492366
128349    0.369274
201575    0.348155
334694    0.176154
169940    0.170136
158711    0.152286
8272      0.136364
Name: 71242, dtype: float64

71245
user
812784    0.588348
326545    0.554700
390006    0.554700
1409      0.554700
170923    0.554700
87516     0.554700
321594    0.554700
88418     0.307692
153040    0.259889
Name: 71245, dtype: float64

71595
user
726820    0.57735
428771    0.57735
256861    0.57735
558567    0.57735
143267    0.57735
133152    0.57735
112180    0.57735
877370    0.57735
277858    0.57735
Name: 71595, dtype: float64

71632
user
157793    0.248452
465115    0.248452
8036      0.248452
906243    0.248452
782157    0.248452
907523    0.248452
317949    0.248452
31984     0.248452
319105    0.248452
Name: 71632, dtype: float64

71758
user
155466    0.348155
935084    0.296500
593182    0.175920
728009    0.161558
173126    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
950331    0.000000
Name: 71758, dtype: float64

71789
user
606877    0.615457
143267    0.615457
491073    0.615457
774737    0.615457
112180    0.615457
133152    0.615457
632235    0.615457
877370    0.615457
937146    0.550482
Name: 71789, dtype: float64

71798
user
551366    1.000000
283360    0.577350
157653    0.474579
85130     0.472456
219293    0.431934
48793     0.424094
365596    0.368230
391631    0.299813
51405     0.268028
Name: 71798, dtype: float64

71905
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 71905, dtype: float64

71929
user
314531    0.244339
224755    0.222375
224347    0.197546
169940    0.183254
250495    0.097953
884890    0.092582
173293    0.000000
173236    0.000000
173218    0.000000
Name: 71929, dtype: float64

72150
user
389047    1.0
558567    1.0
277858    1.0
256861    1.0
159824    1.0
67429     1.0
106580    1.0
72150     1.0
726820    1.0
Name: 72150, dtype: float64

72188
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0

user
49500     1.000000
332865    1.000000
43292     0.554700
150887    0.552158
674425    0.400000
173146    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
Name: 75597, dtype: float64

75773
user
324767    1.000000
75773     1.000000
114860    0.436436
707972    0.424264
101994    0.377964
950331    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
Name: 75773, dtype: float64

75782
user
120261    0.492366
649025    0.492366
386997    0.106634
138574    0.081219
173146    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
Name: 75782, dtype: float64

75794
user
288137    0.648886
4891      0.648886
838134    0.648886
280902    0.648886
945633    0.648886
793871    0.648886
686161    0.648886
6791      0.648886
420587    0.486664
Name: 75794, dtype: float64

76488
user
389767    0.270914
423140    0.270914
445612    0.270914
656927    0.270914
292049    0.270914
348417    0.270914
452036    0.270914
92150     0.242313
879423    0.203186
Name: 76488, dtype: float64

76564
user
194777    1.000000
44204     1.000000
76564     1.000000
113896    1.000000
63763     1.000000
940225    1.000000
148777    1.000000
89712     0.928477
87704     0.745356
Name: 76564, dtype: float64

78370
user
328775    0.106132
950331    0.000000
172770    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 78370, dtype: float64

79213
user
277258    1.000000
740367    0.707107
678384    0.387298
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
173146    0.000000
950331    0.000000
Name: 79213, dtype: float64

79511
user
270595    1.000000
116734    1.000000
79511     1.000000
361531    1.000000
882571    0.542326
924558    0.390360
87153     0.350823
173187    0.000000
172770    0.000000
Name: 79511, dtype: float64

79543
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 79543, dtype: float64

79647
user
5121      0.554700
618570    0.554700
491529    0.433148
160404    0.416025
880552    0.416025
128662    0.416025
229007    0.416025
287964    0.416025
24943     0.416025
Name: 79647, dtype: float64

80323
user
840243    0.261116
370681    0.204658
70650     0.106904
173141    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173146    0.000000
Name: 80323, dtype: float64

80469
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 80469, dtype: float64

80911
user
851090    0.780869
61770     0.780869
188061    0.780869
439187    0.780869
340105    0.780869
732125    0.780869
401305    0.698430
263524    0.624695
744990    0.624695
Name: 80911, dtype: float64

82581
user
82581     1.0
487327    1.0
652607    1.0
42615     1.0
7488      1.0
721140    1.0
645667    1.0
664747    1.0
192450    1.0
Name: 82581, dtype: float64

82914
user
47478     1.000000
147927    0.707107
92767     0.565685
279652    0.421076
262002    0.363803
155100    0.357771
106056    0.281439
127124    0.255822
247859    0.242091
Name: 82914, dtype: float64

82952
user
9510      0.350026
315610    0.311286
317740    0.311286
777776    0.311286
107434    0.311286
2709      0.311286
725984    0.311286
198873    0.311286
28330     0.249029
Name: 82952, dtype: float64

83257
user
39314     0.577350
43801     0.577350
201564    0.577350
622340    0.577350
944394    0.577350
853410    0.577350
828625    0.516398
49805     0.450835
4347      0.305888
Name: 83257, dtype: float64

83810
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 83810, dtype: float64

84736
user
84736     1.0
172770    0.0
173415    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
Name: 84736, dtype: float64

84840
user
321082    0.392232
85785     0.392232
501275    0.362103
290566    0.353009
71595     0.339683
397183    0.245026
399680    0.199612
531322    0.196116
255258    0.193448
Name: 84840, dtype: float64

84930
user
359996    0.457496
856133    0.122859
950331    0.000000
172589    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 84930, dtype: float64

84986
user
84986     1.0
950331    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 84986, dtype: float64

85047
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 85047, dtype: float64

85130
user
551366    0.472456
71798     0.472456
551587    0.377964
175320    0.377964
479278    0.295141
50137     0.295141
283360    0.272772
51466     0.267261
157653    0.224218
Name: 85130, dtype: float64

85134
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 85134, dtype: float64

85149
user
353104    1.000000
224662    1.000000
136730    1.000000
85149     1.000000
6899      1.000000
335411    1.000000
531388    0.928477
536176    0.780869
169956    0.707107
Name: 85149, dtype: float64

85211
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 85211, dtype: float64

85315
user
389047    1.0
558567    1.0
277858    1.0
256861    1.0
159824    1.0
67429     1.0
106580    1.0
72150     1.0
726820    1.0
Name: 85315, dtype: float64

85331
user
108884    0.505076
774737    0.404061
197081    0.301169
202112    0.285714
108457    0.267596
4347      0.267596
65081     0.267596
71789     0.248682
355767    0.248682
Name: 85331, dtype: float64

85495
user
65014     1.0
950331    0.0
173146    0.0
172946    0.0
172955    0.0
173038    0.0
173126    0.0
173141    0.0
173187    0.0
Name: 85495, dtype: float64

85552
user
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 85552, dtype: float64

85601
user
148013    1.000000
85601     1.000000
434980    1.000000
48786     1.000000
500728    1.000000
386300    1.000000
112521    1.000000
328899    0.707107
469069    0.624695
Name: 85601, dtype: float64

85615
user
385886    0.341882
676064    0.341882
321062    0.341882
924153    0.341882
354415    0.266965
43926     0.241747
650429    0.241747
329189    0.226417
227120    0.224441
Name: 85615, dtype: float64

85626
user
50204     0.615457
180453    0.615457
899799    0.609272
268107    0.492366
67890     0.492366
578969    0.492366
173038    0.492366
286962    0.492366
262112    0.492366
Name: 85626, dtype: float64

85645
user
179871    0.707107
398361    0.707107
924557    0.707107
70861     0.707107
5666      0.181444
133400    0.174395
20363     0.145095
256325    0.121867
745537    0.110600
Name: 85645, dtype: float64

85660
user
4548      0.371391
510614    0.371391
419237    0.371391
60263     0.371391
155793    0.371391
775370    0.371391
821860    0.262613
366858    0.232006
257535    0.179518
Name: 85660, dtype: float64

85663
user
110279    0.780869
227388    0.780869
106676    0.624695
3357      0.441726
361727    0.256748
175469    0.234261
169940    0.202370
386997    0.108234
172955    0.000000
Name: 85663, dtype: float64

85669
user
806497    0.500000
67395     0.500000
156698    0.500000
133586    0.500000
59146     0.353553
363072    0.288675
286366    0.288675
485831    0.264906
861992    0.246183
Name: 85669, dtype: float64

85688
user
89963     0.274007
642291    0.268802
252964    0.268802
21351     0.268802
10762     0.268802
901025    0.268802
505936    0.268802
328852    0.215041
109566    0.215041
Name: 85688, dtype: float64

85694
user
280011    0.447214
534551    0.383482
232697    0.357771
261984    0.357771
665344    0.316228
189901    0.282739
314217    0.279372
890235    0.275241
49936     0.268328
Name: 85694, dtype: float64

85705
user
107432    1.000000
504649    1.000000
112616    1.000000
47297     1.000000
85705     1.000000
874578    0.980581
855363    0.780869
192236    0.780869
3019      0.762493
Name: 85705, dtype: float64

85785
user
321082    1.000000
397183    0.624695
531322    0.500000
197268    0.485071
50553     0.423999
579530    0.419314
798609    0.404061
84840     0.392232
397051    0.363803
Name: 85785, dtype: float64

85786
user
313       1.000000
173421    1.000000
323845    0.441726
155466    0.348155
173300    0.000000
173293    0.000000
173236    0.000000
173325    0.000000
173218    0.000000
Name: 85786, dtype: float64

85808
user
706227    0.680414
92295     0.680414
922940    0.544331
288121    0.544331
181135    0.544331
308373    0.544331
167525    0.544331
279375    0.544331
449148    0.481125
Name: 85808, dtype: float64

85853
user
85853     1.000000
129168    1.000000
24614     0.529813
5015      0.487950
114860    0.436436
250495    0.230879
32143     0.138343
173126    0.000000
173141    0.000000
Name: 85853, dtype: float64

86173
user
377841    0.894427
46936     0.244796
950331    0.000000
172946    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
Name: 86173, dtype: float64

86501
user
86501     1.000000
130330    1.000000
305522    0.524142
230662    0.404061
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
Name: 86501, dtype: float64

86590
user
86590     1.000000
136660    1.000000
441050    1.000000
16928     1.000000
62113     0.514496
328775    0.176887
173187    0.000000
173126    0.000000
173141    0.000000
Name: 86590, dtype: float64

86766
user
150074    1.000000
753989    1.000000
885308    1.000000
86766     1.000000
702397    0.707107
39188     0.685994
279785    0.232104
836186    0.191273
249051    0.187729
Name: 86766, dtype: float64

86857
user
747926    0.223607
950331    0.000000
173421    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 86857, dtype: float64

86868
user
109566    1.0
697629    1.0
256643    1.0
354616    1.0
49598     1.0
48740     1.0
352086    1.0
176896    1.0
357454    1.0
Name: 86868, dtype: float64

86948
user
92296     0.529813
150647    0.529813
234765    0.397360
53458     0.234032
180729    0.184457
323845    0.175524
155466    0.138343
90296     0.100324
172770    0.000000
Name: 86948, dtype: float64

87050
user
86590     1.000000
136660    1.000000
441050    1.000000
16928     1.000000
62113     0.514496
328775    0.176887
173187    0.000000
173126    0.000000
173141    0.000000
Name: 87050, dtype: float64

87153
user
156256    0.350823
397299    0.350823
361531    0.350823
270595    0.350823
79511     0.350823
574786    0.350823
122394    0.350823
101449    0.350823
750203    0.350823
Name: 87153, dtype: float64

87206
user
950331    0.0
172770    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 87206, dtype: float64

87286
user
132799    1.0
105855    1.0
196696    1.0
216052    1.0
26996     1.0
28644     1.0
197937    1.0
87286     1.0
359458    1.0
Name: 87286, dtype: float64

87328
user
582482    0.780869
599838    0.780869
169608    0.780869
46312     0.780869
648676    0.780869
804396    0.624695
366858    0.487805
68246     0.441726
328956    0.441726
Name: 87328, dtype: float64

87338
user
292003    0.544331
790247    0.481125
315174    0.481125
191023    0.481125
862633    0.471782
182213    0.293484
731285    0.291725
97666     0.288675
554398    0.272166
Name: 87338, dtype: float64

87516
user
390006    1.000000
321594    1.000000
326545    1.000000
87516     1.000000
170923    1.000000
71245     0.554700
88418     0.554700
153040    0.468521
665848    0.457496
Name: 87516, dtype: float64

87583
user
110846    0.780869
329057    0.650945
3906      0.408248
179727    0.132324
173126    0.000000
172955    0.000000
173038    0.000000
950331    0.000000
172946    0.000000
Name: 87583, dtype: float64

87627
user
950331    0.0
172770    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 87627, dtype: float64

87704
user
148169    0.745356
113896    0.745356
44204     0.745356
63763     0.745356
76564     0.745356
940225    0.745356
194777    0.745356
148777    0.745356
89712     0.692046
Name: 87704, dtype: float64

87724
user
899377    1.000000
42721     1.000000
709700    1.000000
757228    1.000000
87724     1.000000
8323      1.000000
501746    1.000000
470673    0.800000
131375    0.707107
Name: 87724, dtype: float64

87892
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 87892, dtype: float64

88042
user
513840    0.615457
283659    0.615457
699829    0.492366
51021     0.492366
110208    0.492366
252583    0.435194
382866    0.348155
401684    0.138489
132504    0.133316
Name: 88042, dtype: float64

88172
user
88172     1.0
692426    1.0
529676    1.0
593945    1.0
944033    1.0
473854    1.0
363134    1.0
569529    1.0
182301    1.0
Name: 88172, dtype: float64

88316
user
805310    0.435565
170852    0.426401
289156    0.426401
445293    0.426401
213694    0.416204
129333    0.387160
149832    0.319801
148013    0.319801
113970    0.319801
Name: 88316, dtype: float64

88338
user
74527     0.435194
256163    0.178529
173141    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173146    0.000000
172589    0.000000
Name: 88338, dtype: float64

88380
user
88380     1.000000
369524    0.270501
950331    0.000000
172589    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 88380, dtype: float64

88418
user
87516     0.554700
170923    0.554700
321594    0.554700
390006    0.554700
1409      0.554700
326545    0.554700
386300    0.416025
319612    0.416025
500728    0.416025
Name: 88418, dtype: float64

88424
user
137065    0.780869
650429    0.707107
261456    0.408248
173293    0.000000
173236    0.000000
173300    0.000000
173218    0.000000
172589    0.000000
173187    0.000000
Name: 88424, dtype: float64

88482
user
88482     1.000000
318030    0.290957
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173300    0.000000
172504    0.000000
173146    0.000000
Name: 88482, dtype: float64

88648
user
88648     1.000000
699433    1.000000
1190      1.000000
148748    0.529813
211039    0.468293
357798    0.312348
781898    0.295487
194979    0.254000
386997    0.216574
Name: 88648, dtype: float64

88663
user
9852      0.435194
950331    0.000000
172770    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 88663, dtype: float64

88703
user
402103    0.707107
318665    0.615457
212036    0.529813
505806    0.309529
73273     0.298142
173218    0.000000
173187    0.000000
173146    0.000000
173236    0.000000
Name: 88703, dtype: float64

88881
user
350778    0.615457
557866    0.615457
332711    0.615457
114908    0.615457
393834    0.615457
586606    0.457150
325142    0.435194
506648    0.384473
274267    0.355335
Name: 88881, dtype: float64

88901
user
5600      1.000000
151201    0.707107
227462    0.600000
373775    0.421076
156230    0.337869
646881    0.310460
446951    0.192450
70650     0.075593
593182    0.043980
Name: 88901, dtype: float64

89133
user
632364    1.000000
321116    1.000000
592038    1.000000
114663    1.000000
153839    1.000000
518696    0.780869
467642    0.742781
611078    0.529813
658421    0.500000
Name: 89133, dtype: float64

89287
user
465110    0.741249
9339      0.605228
816326    0.524142
149217    0.524142
172946    0.524142
359293    0.524142
376096    0.524142
574786    0.524142
101449    0.524142
Name: 89287, dtype: float64

89332
user
150999    0.707107
179160    0.707107
192285    0.239904
117820    0.230940
133993    0.150970
391794    0.060145
173187    0.000000
173126    0.000000
173141    0.000000
Name: 89332, dtype: float64

89610
user
950331    0.0
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 89610, dtype: float64

89712
user
194777    0.928477
76564     0.928477
113896    0.928477
63763     0.928477
44204     0.928477
148777    0.928477
148169    0.928477
940225    0.928477
87704     0.692046
Name: 89712, dtype: float64

89719
user
857507    0.441726
401012    0.441726
113970    0.441726
651501    0.433148
918706    0.378777
190236    0.353381
202044    0.353381
354415    0.344930
43926     0.312348
Name: 89719, dtype: float64

89781
user
62880     0.464238
819615    0.464238
658169    0.464238
919776    0.464238
413895    0.464238
865559    0.464238
16096     0.464238
387113    0.464238
140023    0.464238
Name: 89781, dtype: float64

89963
user
197109    0.431934
179008    0.345547
196651    0.320833
364504    0.305424
85688     0.274007
325034    0.269827
63763     0.259161
170923    0.259161
148777    0.259161
Name: 89963, dtype: float64

89999
user
191191    0.539164
686640    0.539164
198386    0.539164
254431    0.539164
612464    0.470621
906552    0.326916
390671    0.199827
134807    0.187713
357677    0.173227
Name: 89999, dtype: float64

90292
user
319105    0.40161
23533     0.40161
194854    0.40161
524501    0.40161
820044    0.40161
465115    0.40161
739296    0.40161
906243    0.40161
30184     0.40161
Name: 90292, dtype: float64

90296
user
914914    0.315597
327468    0.315597
337835    0.315597
723330    0.315597
319979    0.252478
926401    0.252478
113136    0.252478
29192     0.252478
250560    0.252478
Name: 90296, dtype: float64

90437
user
90437     1.0
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 90437, dtype: float64

90681
user
950331    0.0
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 90681, dtype: float64

90687
user
798609    0.404061
950331    0.000000
172770    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 90687, dtype: float64

90709
user
431662    0.606339
327363    0.606339
177783    0.606339
43742     0.373176
51496     0.363803
43065     0.363803
96722     0.363803
776175    0.291043
195582    0.284083
Name: 90709, dtype: float64

90754
user
104713    0.285365
943164    0.285365
910316    0.285365
906136    0.285365
279641    0.228292
27176     0.228292
261432    0.228292
340113    0.228292
501408    0.228292
Name: 90754, dtype: float64

90848
user
43793     0.151911
950331    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
Name: 90848, dtype: float64

90997
user
835141    0.428746
319105    0.428746
194854    0.428746
739296    0.428746
136661    0.428746
906243    0.428746
465115    0.428746
524501    0.428746
23533     0.428746
Name: 90997, dtype: float64

91027
user
470252    0.707107
159353    0.188562
90754     0.161427
177278    0.155126
284357    0.151402
64301     0.116248
43793     0.107417
173126    0.000000
172946    0.000000
Name: 91027, dtype: float64

91034
user
557866    0.464238
47528     0.464238
332711    0.464238
350778    0.464238
114908    0.464238
388218    0.393535
59764     0.371391
48369     0.371391
586606    0.344828
Name: 91034, dtype: float64

91092
user
922962    1.000000
861818    1.000000
359203    1.000000
285710    1.000000
91092     1.000000
234398    0.780869
17211     0.745356
361303    0.696311
151946    0.577350
Name: 91092, dtype: float64

91136
user
221495    0.577350
127689    0.408248
276312    0.130744

user
93916     1.000000
562119    1.000000
352205    0.707107
328775    0.141510
53368     0.124141
175875    0.000000
172490    0.000000
176544    0.000000
173187    0.000000
Name: 93916, dtype: float64

93955
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 93955, dtype: float64

93992
user
289156    0.685994
445293    0.685994
170852    0.685994
557866    0.514496
114908    0.514496
332711    0.514496
350778    0.514496
74904     0.485071
215860    0.485071
Name: 93992, dtype: float64

94030
user
323463    1.000000
3044      1.000000
94030     1.000000
819045    0.600000
308086    0.333333
534410    0.279751
816423    0.236250
710291    0.175412
90754     0.171219
Name: 94030, dtype: float64

94448
user
248522    1.000000
620236    0.800000
46322     0.639602
257876    0.514496
641859    0.322078
686300    0.316228
256163    0.178529
950331    0.000000
173038    0.000000
Name: 94448, dtype: float64

94663
user
43325     0.57735
172589    0.00000
173325    0.00000
173300    0.00000
173293    0.00000
173236    0.00000
173218    0.00000
173187    0.00000
173146    0.00000
Name: 94663, dtype: float64

94677
user
256348    0.511718
460437    0.304855
140931    0.304855
287457    0.304855
71170     0.261411
109916    0.243884
49956     0.243884
237186    0.243884
198226    0.243884
Name: 94677, dtype: float64

95336
user
459734    0.680414
446157    0.680414
546902    0.680414
57135     0.680414
367815    0.680414
665848    0.518811
694627    0.498987
725655    0.462963
31058     0.418766
Name: 95336, dtype: float64

95389
user
135001    0.600000
23390     0.600000
385219    0.203565
190348    0.196396
315118    0.116432
32143     0.041503
173218    0.000000
173187    0.000000
173146    0.000000
Name: 95389, dtype: float64

95551
user
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 95551, dtype: float64

95560
user
256176    1.000000
589791    0.617213
31624     0.447214
173126    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173141    0.000000
172589    0.000000
Name: 95560, dtype: float64

95664
user
24943     1.000000
95664     1.000000
360079    1.000000
880552    1.000000
426302    1.000000
286800    0.585206
158429    0.419314
79647     0.416025
217426    0.346410
Name: 95664, dtype: float64

95703
user
354616    0.410997
317949    0.410997
357454    0.410997
319105    0.410997
328852    0.410997
877370    0.410997
31000     0.410997
739296    0.410997
112180    0.410997
Name: 95703, dtype: float64

95763
user
96613     1.000000
562349    1.000000
428481    0.800000
702397    0.707107
836215    0.600000
26705     0.577350
423018    0.514496
292085    0.441726
88418     0.416025
Name: 95763, dtype: float64

95887
user
67211     0.707107
621199    0.529813
918706    0.514496
159599    0.390360
650202    0.319235
89963     0.259161
360130    0.250490
129333    0.199007
114160    0.187135
Name: 95887, dtype: float64

95895
user
95895     1.000000
113728    0.707107
665456    0.624695
867891    0.554700
861280    0.109472
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
Name: 95895, dtype: float64

95916
user
815556    0.408248
820044    0.408248
910316    0.408248
319105    0.408248
906243    0.408248
136661    0.408248
30184     0.408248
739296    0.408248
317949    0.408248
Name: 95916, dtype: float64

95985
user
2131      0.552158
384721    0.552158
360476    0.552158
149905    0.441726
482273    0.441726
67211     0.312348
252734    0.275944
397051    0.267836
201482    0.255031
Name: 95985, dtype: float64

96278
user
31058     0.295420
354228    0.268328
173300    0.000000
173293    0.000000
173236    0.000000
173325    0.000000
173218    0.000000
172770    0.000000
173187    0.000000
Name: 96278, dtype: float64

96320
user
158378    0.399043
755162    0.399043
817844    0.342177
851090    0.319235
439187    0.319235
61770     0.319235
732125    0.319235
340105    0.319235
188061    0.319235
Name: 96320, dtype: float64

96360
user
37980     0.349215
780237    0.349215
49771     0.349215
246545    0.349215
153678    0.349215
8338      0.349215
55705     0.349215
261654    0.349215
321692    0.349215
Name: 96360, dtype: float64

96373
user
864883    1.000000
893228    1.000000
290662    1.000000
759526    1.000000
918040    0.455842
173428    0.441726
219293    0.431934
73273     0.372678
395948    0.370625
Name: 96373, dtype: float64

96471
user
96471     1.000000
796502    1.000000
629675    0.529813
48977     0.441726
173187    0.000000
173146    0.000000
173141    0.000000
173126    0.000000
172504    0.000000
Name: 96471, dtype: float64

96524
user
95916     0.288675
322019    0.182956
217350    0.137725
237668    0.127807
172955    0.000000
172589    0.000000
172770    0.000000
172946    0.000000
173038    0.000000
Name: 96524, dtype: float64

96575
user
385219    0.281011
393032    0.271563
782157    0.271563
465115    0.271563
136661    0.271563
815556    0.271563
158717    0.271563
820044    0.271563
319105    0.271563
Name: 96575, dtype: float64

96613
user
96613     1.000000
562349    1.000000
428481    0.800000
702397    0.707107
836215    0.600000
26705     0.577350
423018    0.514496
292085    0.441726
88418     0.416025
Name: 96613, dtype: float64

96722
user
43065     1.000000
51496     1.000000
776175    0.800000
195582    0.780869
805528    0.707107
24276     0.577350
743374    0.554700
251311    0.492366
885332    0.492366
Name: 96722, dtype: float64

96856
user
96856     1.000000
724982    0.137767
728009    0.121169
172589    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 96856, dtype: float64

97130
user
97130     1.00000
385612    0.21887
950331    0.00000
173126    0.00000
172770    0.00000
172946    0.00000
172955    0.00000
173038    0.00000
173141    0.00000
Name: 97130, dtype: float64

97224
user
950331    0.0
173421    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 97224, dtype: float64

97283
user
907523    0.707107
642339    0.707107
156173    0.707107
157793    0.707107
505806    0.273588
783096    0.252538
321572    0.228665
154501    0.205196
71632     0.175682
Name: 97283, dtype: float64

97666
user
249391    0.365148
630210    0.358569
87338     0.288675
485567    0.145000
950331    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
Name: 97666, dtype: float64

97995
user
218901    0.171028
724982    0.103325
950331    0.000000
173141    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173187    0.000000
Name: 97995, dtype: float64

98330
user
48814     0.780869
707460    0.780869
75174     0.780869
748583    0.780869
931768    0.780869
719811    0.780869
204033    0.780869
939233    0.624695
62904     0.456969
Name: 98330, dtype: float64

98586
user
576558    1.000000
339564    1.000000
132873    0.373002
174016    0.307794
25840     0.234920
397635    0.230769
156230    0.202721
724982    0.103325
172770    0.000000
Name: 98586, dtype: float64

99088
user
773716    0.577350
5311      0.304997
46560     0.267860
391794    0.113410
173236    0.000000
173293    0.000000
173218    0.000000
173300    0.000000
173325    0.000000
Name: 99088, dtype: float64

100397
user
100397    1.000000
133400    0.197305
950331    0.000000
173187    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
173146    0.000000
Name: 100397, dtype: float64

100771
user
752281    1.000000
475240    1.000000
111719    1.000000
227401    1.000000
641062    1.000000
213776    1.000000
100771    1.000000
805528    0.707107
110095    0.707107
Name: 100771, dtype: float64

101141
user
192437    0.520156
195551    0.492366
7488      0.369274
721140    0.369274
42615     0.369274
703432    0.369274
487327    0.369274
652607    0.369274
334992    0.369274
Name: 101141, dtype: float64

101449
user
359293    1.000000
397299    1.000000
122394    1.000000
101449    1.000000
149217    1.000000
156256    1.000000
172946    1.000000
16704     0.800000
465110    0.707107
Name: 101449, dtype: float64

101994
user
652607    0.377964
66431     0.377964
645667    0.377964
194342    0.377964
726820    0.377964
703432    0.377964
558567    0.377964
852721    0.377964
334992    0.377964
Name: 101994, dtype: float64

102825
user
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 102825, dtype: float64

103304
user
516840    0.244922
665569    0.242473
392082    0.215970
673813    0.209987
831703    0.209650
200875    0.197488
501746    0.197488
709700    0.197488
8323      0.197488
Name: 103304, dtype: float64

103529
user
158378    0.419314
647834    0.419314
730158    0.191834
156952    0.182766
96320     0.167324
539244    0.163683
441682    0.116797
636781    0.032787
172589    0.000000
Name: 103529, dtype: float64

103928
user
200786    0.577350
139218    0.577350
186286    0.092582
172589    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 103928, dtype: float64

103952
user
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 103952, dtype: float64

104713
user
104713    1.000000
943164    1.000000
883362    0.357143
90754     0.285365
115682    0.276172
728009    0.161558
173141    0.000000
173146    0.000000
173187    0.000000
Name: 104713, dtype: float64

105338
user
318884    0.662266
199034    0.662266
476529    0.662266
753519    0.662266
901297    0.662266
284559    0.592349
30184     0.529813
815556    0.529813
739296    0.529813
Name: 105338, dtype: float64

105794
user
214780    0.565685
837685    0.565685
44853     0.384900
568404    0.331042
155094    0.273434
314389    0.249878
282032    0.230940
361582    0.188562
251567    0.154303
Name: 105794, dtype: float64

105855
user
132799    1.0
105855    1.0
196696    1.0
216052    1.0
26996     1.0
28644     1.0
197937    1.0
87286     1.0
359458    1.0
Name: 105855, dtype: float64

105881
user
179544    0.363696
316443    0.290957
64762     0.290957
499267    0.290957
804396    0.290957
183668    0.280598
366858    0.227199
110348    0.223840
361309    0.218218
Name: 105881, dtype: float64

105921
user
195546    0.507093
369062    0.404061
192285    0.254457
641859    0.193247
950331    0.000000
173038    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
Name: 105921, dtype: float64

105931
user
105931    1.000000
546411    0.529813
539244    0.390360
21542     0.365636
315118    0.258738
5311      0.228748
173126    0.000000
172770    0.000000
172946    0.000000
Name: 105931, dtype: float64

105981
user
43793     0.151911
950331    0.000000
172504    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
Name: 105981, dtype: float64

105989
user
309828    1.000000
250513    1.000000
461917    1.000000
105989    1.000000
197893    1.000000
63622     1.000000
252432    1.000000
721134    0.970143
721787    0.707107
Name: 105989, dtype: float64

106056
user
448451    0.362339
179653    0.309583
418830    0.298511
430904    0.281439
55705     0.281439
82914     0.281439
222975    0.281439
368338    0.281439
246545    0.281439
Name: 106056, dtype: float64

106059
user
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 106059, dtype: float64

106083
user
822237    0.336861
556845    0.336861
440081    0.336861
148723    0.336861
943069    0.336861
552621    0.252646
135920    0.194487
201349    0.190557
351808    0.168430
Name: 106083, dtype: float64

106094
user
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
173126    0.0
Name: 106094, dtype: float64

106107
user
109622    0.323423
623554    0.285714
950331    0.000000
172504    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
Name: 106107, dtype: float64

106216
user
487400    1.000000
159773    1.000000
342978    1.000000
106216    1.000000
899670    1.000000
267306    1.000000
203033    1.000000
177362    0.970143
135354    0.707107
Name: 106216, dtype: float64

106526
user
213564    0.273434
530433    0.198030
173126    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173141    0.000000
172504    0.000000
Name: 106526, dtype: float64

106580
user
389047    1.0
558567    1.0
277858    1.0
256861    1.0
159824    1.0
67429     1.0
106580    1.0
72150     1.0
726820    1.0
Name: 106580, dtype: float64

106676
user
3357      0.707107
85663     0.624695
386997    0.173259
173126    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
950331    0.000000
Name: 106676, dtype: float64

106725
user
251729    0.662266
133400    0.197305
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
950331    0.000000
172589    0.000000
Name: 106725, dtype: float64

106874
user
950331    0.0
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 106874, dtype: float64

106884
user
950331    0.0
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 106884, dtype: float64

107027
user
950331    0.0
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 107027, dtype: float64

107059
user
783730    1.000000
27962     1.000000
109581    1.000000
423018    0.514496
220825    0.512148
421743    0.512148
160914    0.500000
130768    0.428571
641859    0.193247
Name: 107059, dtype: float64

107237
user
46003     0.780869
171918    0.535672
783096    0.223105
350771    0.171942
114160    0.146128
213301    0.145475
145101    0.137345
745537    0.097710
43793     0.094898
Name: 107237, dtype: float64

107246
user
950331    0.0
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 107246, dtype: float64

107324
user
107324    1.000000
561911    1.000000
148730    0.780869
636781    0.208514
173126    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
Name: 107324, dtype: float64

107386
user
631936    1.000000
130013    0.518476
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
173126    0.000000
Name: 107386, dtype: float64

107432
user
107432    1.000000
504649    1.000000
112616    1.000000
47297     1.000000
85705     1.000000
874578    0.980581
855363    0.780869
192236    0.780869
3019      0.762493
Name: 107432, dtype: float64

107434
user
777776    1.000000
315610    1.000000
725984    1.000000
82952     0.311286
315118    0.258738
173141    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
Name: 107434, dtype: float64

107472
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 107472, dtype: float64

107490
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 107490, dtype: float64

107593
user
537282    0.542326
804396    0.433861
366858    0.338788
249802    0.325396
821511    0.325396
816423    0.324582
328956    0.306786
68246     0.306786
127770    0.287331
Name: 107593, dtype: float64

107704
user
107704    1.0
950331    0.0
172490    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
173126    0.0
Name: 107704, dtype: float64

107751
user
45308     1.000000
74666     1.000000
107751    1.000000
279978    1.000000
24006     0.780869
358118    0.707107
3153      0.707107
29563     0.624695
28330     0.600000
Name: 107751, dtype: float64

107769
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 107769, dtype: float64

108034
user
469245    0.171701
950331    0.000000
172504    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
Name: 108034, dtype: float64

108338
user
354735    0.368230
488536    0.368230
136070    0.368230
811320    0.368230
133181    0.368230
11935     0.368230
8036      0.276172
24902     0.276172
804396    0.276172
Name: 108338, dtype: float64

108443
user
194152    0.656532
127971    0.328266
50553     0.278369
67868     0.148675
156952    0.130817
237668    0.118665
279785    0.114288
485567    0.047599
328775    0.027872
Name: 108443, dtype: float64

108457
user
774737    0.662266
197081    0.493624
202112    0.468293
4347      0.438596
65081     0.438596
355767    0.407597
71789     0.407597
251266    0.298573
190348    0.289037
Name: 108457, dtype: float64

108483
user
158718    0.316228
173141    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
950331    0.000000
172504    0.000000
Name: 108483, dtype: float64

108666
user
35172     0.500000
195653    0.460287
917504    0.441726
129831    0.408248
250820    0.400000
71232     0.374766
41555     0.341793
652898    0.335578
136981    0.264906
Name: 108666, dtype: float64

108692
user
250393    0.680414
419560    0.212526
634648    0.192450
53368     0.084467
215995    0.069254
247859    0.049417
364545    0.048385
728009    0.032978
173141    0.000000
Name: 108692, dtype: float64

108742
user
423159    0.529813
319153    0.358569
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
173126    0.000000
173038    0.000000
Name: 108742, dtype: float64

108796
user
613864    1.000000
827709    1.000000
108796    1.000000
129947    1.000000
190366    1.000000
389377    1.000000
678906    1.000000
194541    1.000000
721055    0.707107
Name: 108796, dtype: float64

108828
user
11198     0.431934
229208    0.345547
44848     0.345547
398658    0.345547
358417    0.345547
43926     0.244339
389198    0.212670
173146    0.183075
350644    0.172774
Name: 108828, dtype: float64

108848
user
173325    0.707107
950331    0.000000
172770    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 108848, dtype: float64

108884
user
85331     0.505076
249570    0.410997
705731    0.270295
129333    0.248759
284695    0.225647
173038    0.000000
172946    0.000000
172955    0.000000
173126    0.000000
Name: 108884, dtype: float64

108936
user
385143    0.331891
805262    0.331891
361892    0.331891
663999    0.331891
563103    0.331891
219166    0.331891
36587     0.331891
63998     0.331891
350949    0.265513
Name: 108936, dtype: float64

108959
user
55852     1.000000
613686    0.707107
217350    0.155818
173038    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
950331    0.000000
172504    0.000000
Name: 108959, dtype: float64

109057
user
66634     0.857493
950331    0.000000
172589    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 109057, dtype: float64

109058
user
397299    0.545545
149217    0.545545
101449    0.545545
150345    0.545545
359293    0.545545
172946    0.545545
156256    0.545545
574786    0.545545
122394    0.545545
Name: 109058, dtype: float64

109566
user
109566    1.0
697629    1.0
256643    1.0
354616    1.0
49598     1.0
48740     1.0
352086    1.0
176896    1.0
357454    1.0
Name: 109566, dtype: float64

109581
user
783730    1.000000

user
112180    1.000000
143267    1.000000
632235    1.000000
133152    1.000000
491073    1.000000
606877    1.000000
937146    0.894427
322423    0.800000
71789     0.615457
Name: 112180, dtype: float64

112193
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 112193, dtype: float64

112229
user
101449    0.662266
574786    0.662266
172946    0.662266
156256    0.662266
359293    0.662266
397299    0.662266
149217    0.662266
122394    0.662266
201162    0.529813
Name: 112229, dtype: float64

112268
user
501799    0.57735
172504    0.00000
173300    0.00000
173293    0.00000
173236    0.00000
173218    0.00000
173187    0.00000
173146    0.00000
173141    0.00000
Name: 112268, dtype: float64

112304
user
686939    1.0
112304    1.0
194777    0.0
173415    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
Name: 112304, dtype: float64

112416
user
305395    0.857493
559469    0.669589
435544    0.535672
273043    0.363803
399680    0.218195
2109      0.159730
159353    0.114332
160914    0.000000
171582    0.000000
Name: 112416, dtype: float64

112521
user
148013    1.000000
85601     1.000000
434980    1.000000
48786     1.000000
500728    1.000000
386300    1.000000
112521    1.000000
328899    0.707107
469069    0.624695
Name: 112521, dtype: float64

112523
user
947927    0.707107
950331    0.000000
173146    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
173218    0.000000
Name: 112523, dtype: float64

112534
user
163201    1.000000
834840    1.000000
11328     0.624695
632495    0.505076
196166    0.464238
606826    0.447214
155100    0.447214
824879    0.408248
166       0.262613
Name: 112534, dtype: float64

112565
user
46936     0.183597
950331    0.000000
173146    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
173187    0.000000
Name: 112565, dtype: float64

112616
user
107432    1.000000
504649    1.000000
112616    1.000000
47297     1.000000
85705     1.000000
874578    0.980581
855363    0.780869
192236    0.780869
3019      0.762493
Name: 112616, dtype: float64

112746
user
65841     0.615457
66639     0.615457
447445    0.615457
340512    0.615457
417735    0.615457
776878    0.615457
643010    0.597081
371282    0.492366
5010      0.480592
Name: 112746, dtype: float64

113000
user
618544    0.800000
794560    0.800000
467164    0.600000
279615    0.245256
257609    0.131629
173187    0.000000
173218    0.000000
173146    0.000000
173141    0.000000
Name: 113000, dtype: float64

113023
user
259023    0.428746
213694    0.312348
138541    0.288675
589868    0.257248
364509    0.234082
514754    0.153393
651198    0.130558
308702    0.129369
728009    0.080779
Name: 113023, dtype: float64

113066
user
72699     1.000000
113066    1.000000
169197    0.624695
263894    0.529813
243313    0.371391
163884    0.237356
173141    0.000000
172955    0.000000
173038    0.000000
Name: 113066, dtype: float64

113135
user
69676     0.423999
247421    0.188044
950331    0.000000
173126    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173141    0.000000
Name: 113135, dtype: float64

113136
user
45308     1.000000
74666     1.000000
107751    1.000000
279978    1.000000
24006     0.780869
358118    0.707107
3153      0.707107
29563     0.624695
28330     0.600000
Name: 113136, dtype: float64

113143
user
126427    0.346410
179262    0.178227
96320     0.147448
213564    0.126294
315462    0.099038
728009    0.055965
950331    0.000000
173126    0.000000
172946    0.000000
Name: 113143, dtype: float64

113193
user
44729     0.552158
853410    0.441726
622340    0.441726
935034    0.441726
944394    0.441726
39314     0.441726
201564    0.441726
43510     0.441726
828625    0.395092
Name: 113193, dtype: float64

113728
user
31010     0.707107
95895     0.707107
665456    0.441726
867891    0.392232
861280    0.077408
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
Name: 113728, dtype: float64

113732
user
668508    1.000000
224755    0.524142
936595    0.457496
213971    0.421076
135672    0.278207
391153    0.258199
172946    0.000000
172955    0.000000
173038    0.000000
Name: 113732, dtype: float64

113896
user
194777    1.000000
44204     1.000000
76564     1.000000
113896    1.000000
63763     1.000000
940225    1.000000
148777    1.000000
89712     0.928477
87704     0.745356
Name: 113896, dtype: float64

113968
user
950331    0.0
172770    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 113968, dtype: float64

113970
user
651501    0.980581
54197     0.565685
8272      0.492366
213694    0.468521
469418    0.450835
89719     0.441726
251474    0.374634
180541    0.350823
385219    0.339276
Name: 113970, dtype: float64

114074
user
622936    0.293105
53332     0.293105
305160    0.293105
123336    0.293105
61776     0.293105
60263     0.234484
419237    0.234484
4548      0.234484
775370    0.234484
Name: 114074, dtype: float64

114081
user
470215    0.800000
261998    0.800000
798855    0.800000
282875    0.742781
770493    0.624695
219586    0.600000
131154    0.600000
389608    0.565685
887586    0.443760
Name: 114081, dtype: float64

114141
user
195148    1.0
114141    1.0
950331    0.0
173187    0.0
172955    0.0
173038    0.0
173126    0.0
173141    0.0
173146    0.0
Name: 114141, dtype: float64

114146
user
22074     1.000000
114146    1.000000
905082    0.707107
950331    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 114146, dtype: float64

114160
user
175320    0.311891
173879    0.311891
551587    0.311891
67211     0.264649
719811    0.249513
748583    0.249513
707460    0.249513
931768    0.249513
287274    0.249513
Name: 114160, dtype: float64

114162
user
892043    0.707107
745622    0.272166
82952     0.124515
173187    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
173146    0.000000
Name: 114162, dtype: float64

114234
user
950331    0.0
172770    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 114234, dtype: float64

114257
user
26531     0.577350
360002    0.577350
387478    0.577350
284269    0.577350
500916    0.577350
131497    0.333333
74592     0.314970
725789    0.285831
702417    0.223384
Name: 114257, dtype: float64

114596
user
150092    0.624695
173421    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 114596, dtype: float64

114602
user
179488    0.350823
950331    0.000000
173421    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 114602, dtype: float64

114625
user
489209    1.000000
789449    1.000000
114625    1.000000
127610    1.000000
867166    0.780869
662901    0.707107
116016    0.707107
876665    0.624695
263524    0.600000
Name: 114625, dtype: float64

114663
user
632364    1.000000
321116    1.000000
592038    1.000000
114663    1.000000
153839    1.000000
518696    0.780869
467642    0.742781
611078    0.529813
658421    0.500000
Name: 114663, dtype: float64

114691
user
327058    0.447214
173421    0.000000
173415    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 114691, dtype: float64

114777
user
47462     1.0
172770    0.0
173415    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
Name: 114777, dtype: float64

114797
user
153457    0.26389
950331    0.00000
172589    0.00000
173300    0.00000
173293    0.00000
173236    0.00000
173218    0.00000
173187    0.00000
173146    0.00000
Name: 114797, dtype: float64

114860
user
288222    0.617213
10287     0.436436
75773     0.436436
852721    0.436436
906243    0.436436
319105    0.436436
696718    0.436436
194854    0.436436
815556    0.436436
Name: 114860, dtype: float64

114908
user
350778    1.000000
557866    1.000000
332711    1.000000
586606    0.742781
506648    0.624695
88881     0.615457
274267    0.577350
24614     0.529813
93992     0.514496
Name: 114908, dtype: float64

114961
user
667504    1.000000
114961    1.000000
684910    0.505076
173126    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
950331    0.000000
Name: 114961, dtype: float64

115004
user
393943    1.0
717906    1.0
950331    0.0
173415    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
Name: 115004, dtype: float64

115012
user
950331    0.0
172770    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 115012, dtype: float64

115161
user
109566    0.57735
357454    0.57735
354616    0.57735
31000     0.57735
256643    0.57735
697629    0.57735
86868     0.57735
49598     0.57735
138698    0.57735
Name: 115161, dtype: float64

115485
user
43726     0.552158
195870    0.500000
150887    0.441726
176665    0.338062
131358    0.311086
534410    0.186501
173141    0.000000
173038    0.000000
173126    0.000000
Name: 115485, dtype: float64

115600
user
22608     0.972229
172049    0.624695
32771     0.468521
492757    0.468521
74344     0.374817
325116    0.331295
116780    0.275944
52663     0.261943
507738    0.230684
Name: 115600, dtype: float64

115682
user
28304     0.460063
791844    0.368230
290744    0.368230
840877    0.276172
129098    0.276172
906136    0.276172
295763    0.276172
943164    0.276172
104713    0.276172
Name: 115682, dtype: float64

115973
user
950331    0.0
172770    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 115973, dtype: float64

116016
user
789449    0.707107
114625    0.707107
127610    0.707107
743850    0.707107
489209    0.707107
730200    0.552158
867166    0.552158
662901    0.500000
876665    0.441726
Name: 116016, dtype: float64

116307
user
116307    1.000000
725466    1.000000
887586    0.832050
441024    0.624695
191100    0.514496
469418    0.450835
251474    0.374634
884890    0.174574
328775    0.141510
Name: 116307, dtype: float64

116445
user
323463    1.000000
3044      1.000000
94030     1.000000
819045    0.600000
308086    0.333333
534410    0.279751
816423    0.236250
710291    0.175412
90754     0.171219
Name: 116445, dtype: float64

116524
user
23999     0.492366
50758     0.492366
560061    0.492366
216476    0.435194
148222    0.369274
423018    0.337760
224421    0.307579
506377    0.254257
127843    0.197386
Name: 116524, dtype: float64

116734
user
270595    1.000000
116734    1.000000
79511     1.000000
361531    1.000000
882571    0.542326
924558    0.390360
87153     0.350823
173187    0.000000
172770    0.000000
Name: 116734, dtype: float64

116780
user
461242    0.441726
66367     0.441726
172049    0.441726
282529    0.441726
356593    0.441726
606053    0.331295
115600    0.275944
273350    0.271864
74344     0.265036
Name: 116780, dtype: float64

116816
user
419353    0.360668
950331    0.000000
173126    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173141    0.000000
172504    0.000000
Name: 116816, dtype: float64

116859
user
116859    1.000000
51405     0.160817
950331    0.000000
172770    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 116859, dtype: float64

117370
user
175320    0.464238
551587    0.464238
133181    0.371391
136070    0.371391
50137     0.362509
479278    0.362509
51466     0.328266
197448    0.328266
776878    0.278543
Name: 117370, dtype: float64

117432
user
74871     0.707107
553056    0.707107
394954    0.707107
500654    0.707107
753900    0.707107
611711    0.707107
191568    0.707107
488321    0.707107
158492    0.441726
Name: 117432, dtype: float64

117820
user
484527    0.408248
157928    0.350070
63030     0.326599
400694    0.326599
179160    0.326599
150999    0.326599
162500    0.326599
328802    0.326599
200742    0.326599
Name: 117820, dtype: float64

117869
user
365419    1.000000
117869    1.000000
202032    1.000000
244614    1.000000
132262    1.000000
626627    1.000000
702417    0.386912
110348    0.369274
91720     0.345857
Name: 117869, dtype: float64

118244
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 118244, dtype: float64

118351
user
48442     0.742781
357985    0.742781
329217    0.557086
387463    0.557086
214528    0.557086
221510    0.525226
294618    0.525226
65621     0.464012
791637    0.364179
Name: 118351, dtype: float64

120102
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 120102, dtype: float64

120261
user
649025    1.000000
75782     0.492366
138574    0.164957
173187    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
173146    0.000000
950331    0.000000
Name: 120261, dtype: float64

121486
user
193704    1.000000
155207    0.512989
179727    0.176432
485567    0.145000
328775    0.141510
173218    0.000000
173187    0.000000
173146    0.000000
172589    0.000000
Name: 121486, dtype: float64

122394
user
359293    1.000000
397299    1.000000
122394    1.000000
101449    1.000000
149217    1.000000
156256    1.000000
172946    1.000000
16704     0.800000
465110    0.707107
Name: 122394, dtype: float64

123336
user
279652    0.421076
114074    0.293105
172589    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 123336, dtype: float64

123958
user
65788     0.707107
43793     0.151911
173146    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
950331    0.000000
Name: 123958, dtype: float64

124281
user
124281    1.000000
714243    1.000000
132954    0.577350
213564    0.341793
226106    0.294174
218901    0.128271
173038    0.000000
172589    0.000000
172770    0.000000
Name: 124281, dtype: float64

126234
user
70650     0.188982
485567    0.181250
179727    0.132324
171678    0.000000
171853    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
Name: 126234, dtype: float64

126427
user
179262    0.514496
113143    0.346410
950331    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
173146    0.000000
Name: 126427, dtype: float64

126791
user
950331    0.0
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 126791, dtype: float64

126931
user
200652    1.000000
126931    1.000000
839712    1.000000
148206    0.707107
441889    0.707107
2419      0.468165
33061     0.441726
93647     0.424264
531388    0.371391
Name: 126931, dtype: float64

126946
user
395445    0.707107
376096    0.707107
816326    0.707107
465110    0.500000
256497    0.500000
397159    0.500000
611078    0.468293
46322     0.452267
502763    0.441726
Name: 126946, dtype: float64

127037
user
33094     0.457496
950331    0.000000
172589    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 127037, dtype: float64

127106
user
127106    1.000000
56796     0.577350
288312    0.554700
391957    0.305995
395948    0.296500
26843     0.278543
249051    0.234662
593182    0.219900
154501    0.217643
Name: 127106, dtype: float64

127124
user
397716    0.255822
82914     0.255822
128541    0.255822
47478     0.255822
50808     0.255822
5710      0.255822
360301    0.255822
401769    0.204658
358201    0.197371
Name: 127124, dtype: float64

127131
user
950331    0.0
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 127131, dtype: float64

127144
user
950331    0.0
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 127144, dtype: float64

127163
user
179325    1.000000
127163    1.000000
823651    0.928477
692299    0.707107
307072    0.707107
534410    0.373002
935084    0.370625
138679    0.340207
288157    0.287242
Name: 127163, dtype: float64

127215
user
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
173126    0.0
Name: 127215, dtype: float64

127610
user
489209    1.000000
789449    1.000000
114625    1.000000
127610    1.000000
867166    0.780869
662901    0.707107
116016    0.707107
876665    0.624695
263524    0.600000
Name: 127610, dtype: float64

127617
user
15289     0.413803
356593    0.331042
282529    0.331042
54805     0.331042
461242    0.331042
275243    0.331042
1705      0.234082
284374    0.234082
315409    0.232651
Name: 127617, dtype: float64

127689
user
221495    0.707107
91136     0.408248
276312    0.160128
884890    0.092582
172770    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 127689, dtype: float64

127770
user
804396    0.662266
194122    0.529813
153678    0.529813
37980     0.529813
55705     0.529813
222975    0.529813
8338      0.529813
321692    0.529813
261654    0.529813
Name: 127770, dtype: float64

127821
user
356446    1.000000
491634    0.685994
322019    0.194054
950331    0.000000
173126    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173141    0.000000
Name: 127821, dtype: float64

127843
user
596425    0.668153
111561    0.668153
147193    0.668153
186572    0.668153
614812    0.668153
636320    0.668153
786717    0.668153
753506    0.668153
44077     0.668153
Name: 127843, dtype: float64

127971
user
66639     0.400000
65841     0.400000
417735    0.400000
340512    0.400000
447445    0.400000
643010    0.388057
108443    0.328266
667169    0.312348
199202    0.300000
Name: 127971, dtype: float64

128216
user
305856    0.243332
950331    0.000000
172770    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 128216, dtype: float64

128254
user
403425    1.000000
820908    0.197546
950331    0.000000
172589    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 128254, dtype: float64

128271
user
122394    0.396526
574786    0.396526
101449    0.396526
359293    0.396526
156256    0.396526
397299    0.396526
280855    0.396526
149217    0.396526
172946    0.396526
Name: 128271, dtype: float64

128349
user
71242     0.369274
8272      0.369274
950331    0.000000
172946    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
Name: 128349, dtype: float64

128414
user
70799     1.000000
255093    0.609994
71232     0.423999
46592     0.270914
156230    0.270295
32143     0.103757
173141    0.000000
172955    0.000000
173038    0.000000
Name: 128414, dtype: float64

128498
user
574786    0.650945
156256    0.650945
172946    0.650945
359293    0.650945
101449    0.650945
149217    0.650945
122394    0.650945
397299    0.650945
16704     0.520756
Name: 128498, dtype: float64

128541
user
50808     1.000000
161601    0.707107
131485    0.464238
688218    0.424264
305522    0.419314
159313    0.390567
323570    0.318223
397635    0.307692
127124    0.255822
Name: 128541, dtype: float64

128613
user
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 128613, dtype: float64

128615
user
45978     0.886969
787677    0.320256
550014    0.230769
317295    0.220416

user
501746    0.707107
42721     0.707107
87724     0.707107
899377    0.707107
200875    0.707107
8323      0.707107
757228    0.707107
709700    0.707107
470673    0.565685
Name: 131375, dtype: float64

131381
user
131381    1.00000
26298     0.32075
173141    0.00000
172770    0.00000
172946    0.00000
172955    0.00000
173038    0.00000
173126    0.00000
950331    0.00000
Name: 131381, dtype: float64

131428
user
177140    0.529813
308086    0.353209
288451    0.289037
5666      0.271900
249880    0.223887
192285    0.179753
459433    0.178473
169618    0.167542
73273     0.157960
Name: 131428, dtype: float64

131485
user
50808     0.464238
793074    0.464238
128541    0.464238
197277    0.437688
946575    0.362509
158492    0.362509
161601    0.328266
399142    0.307449
263894    0.307449
Name: 131485, dtype: float64

131497
user
500916    0.577350
360002    0.577350
387478    0.577350
114257    0.333333
74592     0.314970
26531     0.288675
725789    0.285831
702417    0.223384
674425    0.173205
Name: 131497, dtype: float64

131505
user
195083    1.000000
823508    1.000000
353976    1.000000
149737    1.000000
222092    1.000000
65345     1.000000
129294    0.707107
570294    0.650945
550554    0.554700
Name: 131505, dtype: float64

131540
user
173141    1.000000
131540    1.000000
701499    1.000000
243313    0.371391
710618    0.291730
923208    0.284747
173146    0.000000
173187    0.000000
173218    0.000000
Name: 131540, dtype: float64

131790
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 131790, dtype: float64

131822
user
302395    0.707107
705731    0.270295
950331    0.000000
173146    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
Name: 131822, dtype: float64

132008
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 132008, dtype: float64

132144
user
804396    0.269680
91987     0.269680
70326     0.269680
431662    0.269680
859384    0.269680
366858    0.210585
48688     0.207471
696729    0.202260
793692    0.202260
Name: 132144, dtype: float64

132262
user
365419    1.000000
117869    1.000000
202032    1.000000
244614    1.000000
132262    1.000000
626627    1.000000
702417    0.386912
110348    0.369274
91720     0.345857
Name: 132262, dtype: float64

132446
user
171153    0.529813
950331    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
173146    0.000000
173187    0.000000
Name: 132446, dtype: float64

132478
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 132478, dtype: float64

132480
user
132480    1.000000
706437    0.624695
396276    0.615457
239796    0.606339
208228    0.514496
21542     0.365636
63697     0.331295
705731    0.270295
350771    0.220193
Name: 132480, dtype: float64

132504
user
326545    0.270765
390006    0.270765
87516     0.270765
170923    0.270765
321594    0.270765
227541    0.270765
1409      0.270765
921784    0.262681
105338    0.258219
Name: 132504, dtype: float64

132614
user
152413    0.615457
321283    0.615457
419505    0.615457
576148    0.492366
17211     0.477084
220887    0.369274
173187    0.369274
814144    0.355335
227331    0.339830
Name: 132614, dtype: float64

132641
user
132641    1.000000
448633    1.000000
45836     1.000000
92068     0.894427
199410    0.780869
212057    0.707107
4347      0.529813
686300    0.316228
276312    0.226455
Name: 132641, dtype: float64

132643
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 132643, dtype: float64

132734
user
922709    0.780869
149955    0.780869
785864    0.780869
219299    0.624695
599892    0.624695
879835    0.624695
424722    0.624695
780657    0.624695
148254    0.602453
Name: 132734, dtype: float64

132799
user
132799    1.0
105855    1.0
196696    1.0
216052    1.0
26996     1.0
28644     1.0
197937    1.0
87286     1.0
359458    1.0
Name: 132799, dtype: float64

132873
user
423140    0.466252
389767    0.466252
218745    0.466252
445612    0.466252
452036    0.466252
92150     0.417029
98586     0.373002
339564    0.373002
846528    0.373002
Name: 132873, dtype: float64

132931
user
950331    0.0
173421    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 132931, dtype: float64

132954
user
124281    0.577350
500209    0.577350
714243    0.577350
179544    0.346410
233623    0.236551
110348    0.213201
361309    0.207846
213564    0.197334
226106    0.169842
Name: 132954, dtype: float64

133152
user
112180    1.000000
143267    1.000000
632235    1.000000
133152    1.000000
491073    1.000000
606877    1.000000
937146    0.894427
322423    0.800000
71789     0.615457
Name: 133152, dtype: float64

133170
user
820971    1.0
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 133170, dtype: float64

133181
user
136070    1.000000
179191    0.658505
172339    0.514496
117370    0.371391
108338    0.368230
745537    0.156412
724982    0.137767
950331    0.000000
173141    0.000000
Name: 133181, dtype: float64

133270
user
151201    0.707107
129831    0.577350
292085    0.441726
616058    0.386695
227120    0.369274
365596    0.368230
70650     0.113389
171967    0.000000
173038    0.000000
Name: 133270, dtype: float64

133284
user
950331    0.0
173421    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 133284, dtype: float64

133400
user
6791      0.246632
838134    0.246632
398361    0.246632
4891      0.246632
70861     0.246632
686161    0.246632
945633    0.246632
179871    0.246632
924557    0.246632
Name: 133400, dtype: float64

133470
user
218336    0.565685
48369     0.424264
169881    0.400000
360185    0.300000
216642    0.299707
88881     0.278524
195653    0.276172
68122     0.264906
399142    0.224781
Name: 133470, dtype: float64

133493
user
227331    0.390434
882571    0.306786
467850    0.255822
179488    0.248069
568971    0.218218
264572    0.216295
5311      0.161749
364545    0.157135
250495    0.097953
Name: 133493, dtype: float64

133586
user
485831    0.529813
85669     0.500000
861992    0.492366
385272    0.316228
243883    0.288675
153457    0.263890
82952     0.249029
138574    0.247436
25840     0.234920
Name: 133586, dtype: float64

133591
user
195148    1.0
114141    1.0
950331    0.0
173187    0.0
172955    0.0
173038    0.0
173126    0.0
173141    0.0
173146    0.0
Name: 133591, dtype: float64

133983
user
393149    0.700140
170852    0.700140
658421    0.700140
445293    0.700140
289156    0.700140
74904     0.495074
215860    0.495074
93992     0.480292
213694    0.437374
Name: 133983, dtype: float64

133993
user
74579     0.266880
321082    0.266880
85785     0.266880
250560    0.266880
31000     0.213504
170268    0.213504
61770     0.213504
732125    0.213504
463997    0.213504
Name: 133993, dtype: float64

133997
user
14959     1.000000
396107    1.000000
179719    0.231455
256163    0.178529
171853    0.000000
172946    0.000000
173325    0.000000
173300    0.000000
171636    0.000000
Name: 133997, dtype: float64

134131
user
134131    1.000000
365420    0.780869
630504    0.780869
5995      0.780869
319753    0.780869
869698    0.780869
849404    0.780869
389704    0.780869
412468    0.765705
Name: 134131, dtype: float64

134173
user
678384    0.387298
950331    0.000000
173415    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 134173, dtype: float64

134323
user
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 134323, dtype: float64

134383
user
38120     0.615457
882402    0.615457
465152    0.615457
43207     0.615457
239439    0.615457
648094    0.615457
169215    0.615457
2175      0.615457
642214    0.615457
Name: 134383, dtype: float64

134530
user
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 134530, dtype: float64

134761
user
316768    1.0
695760    1.0
27939     1.0
50690     1.0
134761    1.0
50739     1.0
147932    1.0
29070     1.0
256789    1.0
Name: 134761, dtype: float64

134773
user
53368     0.12925
950331    0.00000
172770    0.00000
173325    0.00000
173300    0.00000
173293    0.00000
173236    0.00000
173218    0.00000
173187    0.00000
Name: 134773, dtype: float64

134807
user
686640    0.348155
357259    0.348155
40447     0.348155
152151    0.348155
343008    0.348155
198386    0.348155
159381    0.348155
612464    0.303895
354874    0.298541
Name: 134807, dtype: float64

134866
user
367648    1.000000
71046     0.316228
441414    0.311086
173126    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
950331    0.000000
Name: 134866, dtype: float64

134877
user
134877    1.000000
318030    0.218218
172504    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
Name: 134877, dtype: float64

135001
user
23390     1.000000
95389     0.600000
385219    0.339276
190348    0.327327
315118    0.194054
32143     0.069171
173218    0.000000
173187    0.000000
173146    0.000000
Name: 135001, dtype: float64

135044
user
226606    0.346410
201482    0.333333
72686     0.148087
392977    0.146969
7226      0.140028
697977    0.123718
153457    0.121886
194979    0.109985
593954    0.100939
Name: 135044, dtype: float64

135062
user
465115    0.650945
393032    0.650945
23533     0.650945
30184     0.650945
835141    0.650945
820044    0.650945
815556    0.650945
782157    0.650945
739296    0.650945
Name: 135062, dtype: float64

135113
user
443815    0.800000
362768    0.800000
364520    0.468521
115161    0.346410
386997    0.129944
96360     0.125717
173126    0.000000
172955    0.000000
173038    0.000000
Name: 135113, dtype: float64

135152
user
84986     1.0
950331    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 135152, dtype: float64

135201
user
135201    1.000000
136981    0.468293
950331    0.000000
172589    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173187    0.000000
173146    0.000000
Name: 135201, dtype: float64

135283
user
606979    0.617213
670976    0.617213
606826    0.552052
251581    0.266596
213971    0.259894
279652    0.207915
400150    0.154303
885234    0.154303
358746    0.154303
Name: 135283, dtype: float64

135314
user
844792    1.000000
329189    0.529813
516840    0.278693
900562    0.263752
153457    0.158334
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
Name: 135314, dtype: float64

135354
user
899670    0.707107
151203    0.707107
220389    0.707107
342978    0.707107
203033    0.707107
106216    0.707107
267306    0.707107
159773    0.707107
487400    0.707107
Name: 135354, dtype: float64

135672
user
879926    0.278207
833785    0.278207
250828    0.278207
463007    0.278207
668508    0.278207
113732    0.278207
45885     0.278207
480616    0.278207
839006    0.278207
Name: 135672, dtype: float64

135678
user
159313    0.169972
26298     0.139589
96320     0.138929
153457    0.114843
950331    0.000000
173126    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
Name: 135678, dtype: float64

135715
user
946771    1.000000
906229    1.000000
135715    1.000000
286800    0.468165
840293    0.435194
171853    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
Name: 135715, dtype: float64

135920
user
556845    0.577350
822237    0.577350
72697     0.577350
440081    0.577350
943069    0.577350
195551    0.577350
148723    0.577350
170611    0.379980
30202     0.326599
Name: 135920, dtype: float64

135937
user
594913    0.090075
25840     0.045581
534410    0.045233
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173293    0.000000
172504    0.000000
Name: 135937, dtype: float64

135938
user
371474    0.624695
110846    0.390244
28339     0.196458
390564    0.169239
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
950331    0.000000
Name: 135938, dtype: float64

136070
user
136070    1.000000
179191    0.658505
172339    0.514496
117370    0.371391
108338    0.368230
745537    0.156412
724982    0.137767
950331    0.000000
173141    0.000000
Name: 136070, dtype: float64

136076
user
950331    0.0
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 136076, dtype: float64

136660
user
86590     1.000000
136660    1.000000
441050    1.000000
16928     1.000000
62113     0.514496
328775    0.176887
173187    0.000000
173126    0.000000
173141    0.000000
Name: 136660, dtype: float64

136661
user
23533     1.0
317949    1.0
158717    1.0
524501    1.0
820044    1.0
739296    1.0
946187    1.0
465115    1.0
835141    1.0
Name: 136661, dtype: float64

136730
user
353104    1.000000
224662    1.000000
136730    1.000000
85149     1.000000
6899      1.000000
335411    1.000000
531388    0.928477
536176    0.780869
169956    0.707107
Name: 136730, dtype: float64

136764
user
714695    1.000000
26415     0.524142
641859    0.322078
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
173126    0.000000
Name: 136764, dtype: float64

136780
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 136780, dtype: float64

136933
user
804396    0.577350
935034    0.577350
43510     0.577350
197460    0.577350
199202    0.577350
366858    0.450835
328956    0.408248
68246     0.408248
127770    0.382360
Name: 136933, dtype: float64

136981
user
173218    0.468293
135201    0.468293
167525    0.374634
181135    0.374634
922940    0.374634
279375    0.374634
288121    0.374634
308373    0.374634
35172     0.264906
Name: 136981, dtype: float64

137021
user
475084    0.441726
950331    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
173146    0.000000
173187    0.000000
Name: 137021, dtype: float64

137035
user
137035    1.000000
762747    0.780869
53368     0.165521
173141    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
Name: 137035, dtype: float64

137065
user
88424     0.780869
364156    0.624695
650429    0.552158
261456    0.318788
74592     0.204479
154501    0.135960
250495    0.086537
173141    0.000000
172955    0.000000
Name: 137065, dtype: float64

137104
user
107751    0.423999
257974    0.423999
113136    0.423999
74666     0.423999
279978    0.423999
45308     0.423999
24006     0.331088
318831    0.299813
3153      0.299813
Name: 137104, dtype: float64

137126
user
137126    1.000000
25002     1.000000
473329    0.685994
452187    0.577350
276312    0.226455
390564    0.203186
884890    0.174574
173236    0.000000
173293    0.000000
Name: 137126, dtype: float64

137221
user
137221    1.0
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 137221, dtype: float64

137423
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 137423, dtype: float64

137575
user
622858    0.780869
178016    0.470360
24964     0.443678
149300    0.273434
950331    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
Name: 137575, dtype: float64

137615
user
137615    1.000000
902743    1.000000
902931    0.780869
380098    0.600000
652365    0.348155
516840    0.278693
392082    0.260378
308702    0.258738
665569    0.236113
Name: 137615, dtype: float64

137630
user
218451    0.707107
723330    0.707107
190541    0.707107
914914    0.707107
193020    0.707107
337835    0.707107
817367    0.707107
320837    0.565685
507738    0.435194
Name: 137630, dtype: float64

137761
user
150196    0.297812
190080    0.290007
173141    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
950331    0.000000
Name: 137761, dtype: float64

137802
user
950331    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 137802, dtype: float64

137899
user
150132    0.337602
30156     0.305812
665456    0.183487
27703     0.158243
130044    0.067788
189901    0.053535
135672    0.039224
74999     0.037924
173038    0.000000
Name: 137899, dtype: float64

137984
user
154279    0.780869
192676    0.233550
129333    0.199007
950331    0.000000
173141    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
Name: 137984, dtype: float64

138402
user
138402    1.000000
50592     1.000000
397331    1.000000
18611     1.000000
354415    0.624695
197904    0.514496
69546     0.514496
539244    0.390360
90296     0.252478
Name: 138402, dtype: float64

138436
user
24964     0.266207
350771    0.220193
950331    0.000000
172946    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
Name: 138436, dtype: float64

138450
user
43805     1.000000
17698     1.000000
32652     1.000000
96575     0.217250
350771    0.165145
173141    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
Name: 138450, dtype: float64

138465
user
950331    0.0
172770    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 138465, dtype: float64

138498
user
950331    0.0
172770    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 138498, dtype: float64

138541
user
259023    0.495074
43292     0.320256
589868    0.297044
113023    0.288675
319153    0.207020
514754    0.177123
279615    0.176998
651198    0.150756
308702    0.149383
Name: 138541, dtype: float64

138572
user
481628    0.831890
591369    0.685994
936541    0.685994
148115    0.514496
178745    0.514496
292085    0.473471
68203     0.446544
280081    0.363803
3629      0.308697
Name: 138572, dtype: float64

138574
user
39314     0.329914
622340    0.329914
201564    0.329914
853410    0.329914
944394    0.329914
828625    0.295084
49805     0.257620
751014    0.247436
197359    0.247436
Name: 138574, dtype: float64

138663
user
353069    0.57735
322689    0.57735
662556    0.57735
2920      0.57735
43128     0.57735
327506    0.57735
150336    0.57735
471179    0.57735
386149    0.57735
Name: 138663, dtype: float64

138679
user
365419    0.340207
195216    0.340207
261822    0.340207
260171    0.340207
127163    0.340207
192226    0.340207
117869    0.340207
10287     0.340207
199172    0.340207
Name: 138679, dtype: float64

138698
user
109566    1.0
697629    1.0
256643    1.0
354616    1.0
49598     1.0
48740     1.0
352086    1.0
176896    1.0
357454    1.0
Name: 138698, dtype: float64

139218
user
139218    1.00000
103928    0.57735
950331    0.00000
173293    0.00000
173236    0.00000
173218    0.00000
173187    0.00000
173146    0.00000
173141    0.00000
Name: 139218, dtype: float64

139802
user
139802    1.000000
883362    0.357143
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 139802, dtype: float64

140023
user
62880     1.000000
140023    1.000000
658169    1.000000
819615    1.000000
535452    0.468521
89781     0.464238
361582    0.266667

Name: 148839, dtype: float64

148939
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 148939, dtype: float64

149174
user
6780      0.456435
150345    0.365148
149905    0.365148
482273    0.365148
67088     0.278423
467489    0.258199
67211     0.258199
296014    0.234834
252734    0.228106
Name: 149174, dtype: float64

149217
user
359293    1.000000
397299    1.000000
122394    1.000000
101449    1.000000
149217    1.000000
156256    1.000000
172946    1.000000
16704     0.800000
465110    0.707107
Name: 149217, dtype: float64

149300
user
899828    0.341793
537282    0.341793
288190    0.341793
129160    0.273434
359723    0.273434
137575    0.273434
830007    0.249610
930847    0.241684
622858    0.213516
Name: 149300, dtype: float64

149490
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 149490, dtype: float64

149576
user
149576    1.000000
775813    1.000000
333372    0.666667
247348    0.529813
260469    0.386695
705731    0.270295
173218    0.000000
173187    0.000000
173146    0.000000
Name: 149576, dtype: float64

149655
user
320562    0.390567
950331    0.000000
172589    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 149655, dtype: float64

149684
user
212461    1.000000
129223    1.000000
173943    1.000000
57125     1.000000
150433    1.000000
195667    1.000000
292280    1.000000
149684    1.000000
283386    0.780869
Name: 149684, dtype: float64

149737
user
195083    1.000000
823508    1.000000
353976    1.000000
149737    1.000000
222092    1.000000
65345     1.000000
129294    0.707107
570294    0.650945
550554    0.554700
Name: 149737, dtype: float64

149784
user
794785    0.707107
358700    0.707107
201157    0.707107
219760    0.707107
792019    0.707107
23255     0.707107
506648    0.552158
598467    0.500000
360185    0.500000
Name: 149784, dtype: float64

149832
user
866967    1.000000
88316     0.319801
87153     0.263117
636781    0.208514
950331    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
Name: 149832, dtype: float64

149905
user
149905    1.000000
67211     0.707107
252734    0.624695
397051    0.606339
201482    0.577350
95985     0.441726
514754    0.383482
31285     0.380143
149174    0.365148
Name: 149905, dtype: float64

149955
user
149955    1.000000
785864    1.000000
132734    0.780869
148254    0.771517
158018    0.529999
837135    0.500000
326607    0.441726
534410    0.373002
322019    0.323423
Name: 149955, dtype: float64

150069
user
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 150069, dtype: float64

150074
user
150074    1.000000
753989    1.000000
885308    1.000000
86766     1.000000
702397    0.707107
39188     0.685994
279785    0.232104
836186    0.191273
249051    0.187729
Name: 150074, dtype: float64

150092
user
114596    0.624695
173421    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 150092, dtype: float64

150093
user
950331    0.0
172770    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 150093, dtype: float64

150132
user
804396    0.478913
30156     0.373968
366858    0.373968
68246     0.338643
328956    0.338643
137899    0.337602
127770    0.317168
326195    0.299175
87328     0.299175
Name: 150132, dtype: float64

150196
user
137761    0.297812
321116    0.286039
592038    0.286039
114663    0.286039
153839    0.286039
89133     0.286039
156909    0.286039
632364    0.286039
518696    0.223359
Name: 150196, dtype: float64

150279
user
320473    1.000000
150279    1.000000
198103    1.000000
215042    0.254824
197277    0.235702
950331    0.000000
173126    0.000000
172946    0.000000
172955    0.000000
Name: 150279, dtype: float64

150336
user
150336    1.000000
138663    0.577350
4629      0.298142
255258    0.246598
243883    0.230940
256325    0.229794
249051    0.187729
256163    0.178529
173218    0.000000
Name: 150336, dtype: float64

150345
user
467489    0.707107
109058    0.545545
399680    0.424094
149174    0.365148
323845    0.331295
535       0.234978
173141    0.000000
172955    0.000000
173038    0.000000
Name: 150345, dtype: float64

150353
user
352086    0.404061
256643    0.404061
357454    0.404061
354616    0.404061
109566    0.404061
31000     0.404061
697629    0.404061
49598     0.404061
86868     0.404061
Name: 150353, dtype: float64

150433
user
212461    1.000000
129223    1.000000
173943    1.000000
57125     1.000000
150433    1.000000
195667    1.000000
292280    1.000000
149684    1.000000
283386    0.780869
Name: 150433, dtype: float64

150647
user
86948     0.529813
53458     0.441726
180729    0.348155
323845    0.331295
155466    0.261116
90296     0.189358
171871    0.000000
172946    0.000000
173300    0.000000
Name: 150647, dtype: float64

150785
user
194777    0.524142
148777    0.524142
113896    0.524142
940225    0.524142
76564     0.524142
148169    0.524142
44204     0.524142
63763     0.524142
89712     0.486654
Name: 150785, dtype: float64

150839
user
215649    0.441726
950331    0.000000
172770    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 150839, dtype: float64

150887
user
332865    0.552158
49500     0.552158
75597     0.552158
115485    0.441726
43292     0.306282
936595    0.252610
43726     0.243902
674425    0.220863
195870    0.220863
Name: 150887, dtype: float64

150935
user
884890    0.130931
950331    0.000000
173421    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 150935, dtype: float64

150968
user
2419      0.434680
154897    0.371391
199077    0.127386
745537    0.108919
173187    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
173146    0.000000
Name: 150968, dtype: float64

150999
user
179160    1.000000
89332     0.707107
192285    0.339276
117820    0.326599
133993    0.213504
391794    0.085057
173187    0.000000
173126    0.000000
173141    0.000000
Name: 150999, dtype: float64

151058
user
669366    1.0
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 151058, dtype: float64

151133
user
194941    0.734847
360301    0.577350
809373    0.461880
362085    0.461880
157564    0.346410
153126    0.346410
317713    0.346410
308086    0.307920
664138    0.266667
Name: 151133, dtype: float64

151201
user
88901     0.707107
5600      0.707107
133270    0.707107
227462    0.424264
129831    0.408248
292085    0.312348
373775    0.297746
616058    0.273434
227120    0.261116
Name: 151201, dtype: float64

151203
user
487400    1.000000
159773    1.000000
342978    1.000000
106216    1.000000
899670    1.000000
267306    1.000000
203033    1.000000
177362    0.970143
135354    0.707107
Name: 151203, dtype: float64

151373
user
452187    0.811503
199202    0.624695
197460    0.624695
706437    0.609756
136933    0.360668
67088     0.285795
334694    0.223498
243313    0.217506
290423    0.211944
Name: 151373, dtype: float64

151456
user
34751     0.707107
516840    0.278693
392082    0.260378
46936     0.244796
312492    0.211079
469245    0.171701
103304    0.157991
172955    0.000000
173038    0.000000
Name: 151456, dtype: float64

151661
user
31926     0.780869
255287    0.707107
32306     0.577350
157653    0.474579
923459    0.331133
5142      0.327327
356252    0.319235
173126    0.000000
173141    0.000000
Name: 151661, dtype: float64

151743
user
154169    0.780869
212969    0.184715
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
950331    0.000000
Name: 151743, dtype: float64

151825
user
116859    1.000000
51405     0.160817
950331    0.000000
172770    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 151825, dtype: float64

151927
user
151927    1.0
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 151927, dtype: float64

151946
user
861818    0.57735
323358    0.57735
678906    0.57735
194541    0.57735
129947    0.57735
212056    0.57735
389377    0.57735
827709    0.57735
190366    0.57735
Name: 151946, dtype: float64

152151
user
343008    1.000000
357259    1.000000
354874    0.857493
444370    0.707107
467642    0.557086
134807    0.348155
705731    0.337869
342669    0.316228
224347    0.209529
Name: 152151, dtype: float64

152399
user
283750    0.680414
579521    0.145065
256163    0.091105
260469    0.078934
217350    0.053010
172589    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
Name: 152399, dtype: float64

152406
user
838164    0.424264
661090    0.235339
650646    0.192617
593182    0.124394
171636    0.000000
172504    0.000000
173218    0.000000
171549    0.000000
173187    0.000000
Name: 152406, dtype: float64

152413
user
152413    1.000000
321283    1.000000
132614    0.615457
17211     0.596285
227331    0.552158
173141    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
Name: 152413, dtype: float64

152437
user
392082    0.260378
665569    0.236113
172589    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 152437, dtype: float64

152466
user
170611    0.206835
950331    0.000000
172589    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 152466, dtype: float64

152480
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 152480, dtype: float64

152494
user
918441    0.500000
72686     0.181369
328775    0.100063
950331    0.000000
172770    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 152494, dtype: float64

152603
user
908860    1.000000
209415    1.000000
201162    1.000000
644110    1.000000
152603    1.000000
351982    1.000000
554398    0.707107
848512    0.707107
427422    0.624695
Name: 152603, dtype: float64

152915
user
254255    0.500000
616906    0.500000
221747    0.500000
474647    0.500000
177666    0.500000
350965    0.500000
797488    0.353553
70333     0.310759
316376    0.226134
Name: 152915, dtype: float64

153040
user
281939    0.624695
177746    0.624695
665848    0.500142
390006    0.468521
87516     0.468521
1409      0.468521
321594    0.468521
326545    0.468521
170923    0.468521
Name: 153040, dtype: float64

153068
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 153068, dtype: float64

153097
user
351878    0.742781
950331    0.000000
172770    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 153097, dtype: float64

153126
user
317713    1.000000
157564    1.000000
507859    0.615457
151133    0.346410
138679    0.340207
166       0.328266
26760     0.296174
391794    0.113410
173236    0.000000
Name: 153126, dtype: float64

153279
user
170852    0.577350
289156    0.577350
445293    0.577350
215860    0.408248
74904     0.408248
133983    0.404226
93992     0.396059
213694    0.360668
67245     0.355335
Name: 153279, dtype: float64

153457
user
920743    0.263890
340702    0.263890
263360    0.263890
133586    0.263890
707094    0.263890
195935    0.263890
114797    0.263890
67607     0.263890
160587    0.186598
Name: 153457, dtype: float64

153553
user
765136    1.000000
924558    0.390360
321572    0.323381
950331    0.000000
173141    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
Name: 153553, dtype: float64

153678
user
22636     1.0
261654    1.0
222975    1.0
153678    1.0
321692    1.0
37980     1.0
780237    1.0
55705     1.0
194122    1.0
Name: 153678, dtype: float64

153750
user
780363    1.0
173421    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 153750, dtype: float64

153839
user
632364    1.000000
321116    1.000000
592038    1.000000
114663    1.000000
153839    1.000000
518696    0.780869
467642    0.742781
611078    0.529813
658421    0.500000
Name: 153839, dtype: float64

153856
user
361663    1.000000
752963    1.000000
155666    0.707107
745537    0.195515
950331    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
Name: 153856, dtype: float64

154119
user
391585    1.000000
676118    1.000000
256539    1.000000
319153    0.478091
196166    0.464238
171853    0.000000
172955    0.000000
173300    0.000000
171636    0.000000
Name: 154119, dtype: float64

154154
user
212461    1.000000
129223    1.000000
173943    1.000000
57125     1.000000
150433    1.000000
195667    1.000000
292280    1.000000
149684    1.000000
283386    0.780869
Name: 154154, dtype: float64

154169
user
151743    0.780869
950331    0.000000
172504    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
Name: 154169, dtype: float64

154201
user
154201    1.000000
694627    0.458349
173141    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
950331    0.000000
Name: 154201, dtype: float64

154279
user
137984    0.780869
713500    0.624695
130558    0.243856
44923     0.185562
192676    0.182372
46560     0.167331
129333    0.155399
145101    0.103009
173038    0.000000
Name: 154279, dtype: float64

154501
user
188061    0.362738
61770     0.362738
732125    0.362738
340105    0.362738
364818    0.362738
442748    0.362738
851090    0.362738
325654    0.362738
439187    0.362738
Name: 154501, dtype: float64

154552
user
950331    0.0
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 154552, dtype: float64

154870
user
2112      0.928477
950331    0.000000
172589    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 154870, dtype: float64

154897
user
150968    0.371391
199077    0.342997
950331    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
173187    0.000000
Name: 154897, dtype: float64

155049
user
664880    0.577350
391650    0.552158
361497    0.492366
322019    0.323423
169618    0.316228
360130    0.313112
315118    0.258738
51405     0.214423
32143     0.172929
Name: 155049, dtype: float64

155094
user
837685    0.483368
214780    0.483368
59764     0.483368
394954    0.386695
74871     0.386695
611711    0.386695
553056    0.386695
488321    0.386695
12285     0.341793
Name: 155094, dtype: float64

155100
user
112534    0.447214
834840    0.447214
163201    0.447214
47478     0.357771
82914     0.357771
248496    0.357771
179832    0.357771
920668    0.347089
11328     0.279372
Name: 155100, dtype: float64

155148
user
495957    0.894427
68750     0.624695
724982    0.172209
950331    0.000000
173141    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
Name: 155148, dtype: float64

155173
user
950331    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
173126    0.0
Name: 155173, dtype: float64

155176
user
45970     1.000000
385514    1.000000
353436    1.000000
679280    1.000000
505806    0.386912
109622    0.323423
623554    0.285714
173187    0.000000
173218    0.000000
Name: 155176, dtype: float64

155207
user
121486    0.512989
193704    0.512989
241227    0.205196
283160    0.103115
179727    0.090508
485567    0.074383
328775    0.072593
103304    0.048628
175320    0.000000
Name: 155207, dtype: float64

155233
user
48799     1.000000
159599    0.390360
246061    0.361787
390564    0.270914
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 155233, dtype: float64

155466
user
323845    0.663216
557834    0.435194
397502    0.435194
173421    0.348155
71758     0.348155
85786     0.348155
179685    0.348155
313       0.348155
256985    0.278524
Name: 155466, dtype: float64

155636
user
451148    1.000000
881353    0.577350
180729    0.348155
171678    0.000000
172770    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 155636, dtype: float64

155666
user
752963    0.707107
153856    0.707107
361663    0.707107
137104    0.299813
764772    0.244949
391153    0.182574
293161    0.155230
177278    0.155126
745537    0.138250
Name: 155666, dtype: float64

155793
user
510614    1.000000
419237    1.000000
155793    1.000000
60263     1.000000
775370    1.000000
821860    0.707107
366858    0.624695
257535    0.483368
54197     0.424264
Name: 155793, dtype: float64

155894
user
1656      0.857493
74618     0.800000
172079    0.410997
213301    0.186299
724982    0.137767
950331    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
Name: 155894, dtype: float64

156156
user
249441    0.500000
10258     0.500000
195497    0.500000
550554    0.416025
621199    0.331133
470036    0.312348
389973    0.312348
49805     0.312348
609485    0.264906
Name: 156156, dtype: float64

156173
user
642339    1.000000
156173    1.000000
157793    1.000000
97283     0.707107
505806    0.386912
783096    0.357143
321572    0.323381
154501    0.290191
71632     0.248452
Name: 156173, dtype: float64

156230
user
47528     0.337869
5600      0.337869
88901     0.337869
71789     0.332710
112180    0.270295
491073    0.270295
632235    0.270295
774737    0.270295
877370    0.270295
Name: 156230, dtype: float64

156256
user
359293    1.000000
397299    1.000000
122394    1.000000
101449    1.000000
149217    1.000000
156256    1.000000
172946    1.000000
16704     0.800000
465110    0.707107
Name: 156256, dtype: float64

156507
user
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 156507, dtype: float64

156698
user
156698    1.000000
806497    1.000000
59146     0.707107
363072    0.577350
286366    0.577350
85669     0.500000
159353    0.266667
356252    0.239426
593182    0.175920
Name: 156698, dtype: float64

156822
user
3019      0.457496
171421    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 156822, dtype: float64

156887
user
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 156887, dtype: float64

156909
user
150196    0.286039
173421    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 156909, dtype: float64

156952
user
50553     0.274572
69546     0.264832
243233    0.249068
804396    0.249068
777853    0.249068
232697    0.249068
197268    0.217468
193213    0.204537
85785     0.199254
Name: 156952, dtype: float64

156985
user
156985    1.0
873812    1.0
173126    1.0
950331    0.0
173141    0.0
172946    0.0
172955    0.0
173038    0.0
173146    0.0
Name: 156985, dtype: float64

157097
user
447059    1.0
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 157097, dtype: float64

157552
user
950331    0.0

Name: 160914, dtype: float64

161129
user
838753    1.0
950331    0.0
172946    0.0
172955    0.0
173038    0.0
173126    0.0
173141    0.0
173146    0.0
173187    0.0
Name: 161129, dtype: float64

161601
user
128541    0.707107
50808     0.707107
131485    0.328266
688218    0.300000
305522    0.296500
159313    0.276172
323570    0.225018
397635    0.217571
127124    0.180894
Name: 161601, dtype: float64

161783
user
2849      1.000000
161783    1.000000
400268    0.800000
393981    0.529813
131358    0.518476
367228    0.514496
293382    0.431331
369062    0.404061
390671    0.370625
Name: 161783, dtype: float64

161965
user
6169      0.441726
950331    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 161965, dtype: float64

162425
user
413446    1.000000
385612    0.164153
950331    0.000000
173141    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173146    0.000000
Name: 162425, dtype: float64

162500
user
328802    1.000000
73653     1.000000
400694    1.000000
162500    1.000000
254239    1.000000
65017     0.928477
147610    0.857493
891451    0.529813
319754    0.514496
Name: 162500, dtype: float64

163201
user
163201    1.000000
834840    1.000000
11328     0.624695
632495    0.505076
196166    0.464238
606826    0.447214
155100    0.447214
824879    0.408248
166       0.262613
Name: 163201, dtype: float64

163709
user
777853    0.514496
689905    0.477697
360246    0.363803
528915    0.321403
69546     0.264706
50553     0.218146
390564    0.139384
156952    0.128144
173293    0.000000
Name: 163709, dtype: float64

163884
user
553056    0.296695
611711    0.296695
488321    0.296695
18297     0.296695
129271    0.296695
74871     0.296695
394954    0.296695
776788    0.296695
42450     0.237356
Name: 163884, dtype: float64

164108
user
950331    0.0
173421    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 164108, dtype: float64

164819
user
274810    0.894427
431688    0.894427
3123      0.894427
314010    0.894427
224377    0.447214
336473    0.447214
448451    0.418739
632495    0.361403
397183    0.349215
Name: 164819, dtype: float64

167525
user
279375    1.000000
308373    1.000000
288121    1.000000
167525    1.000000
181135    1.000000
261748    0.615457
256985    0.600000
129316    0.597614
85808     0.544331
Name: 167525, dtype: float64

168442
user
397635    0.230769
950331    0.000000
172770    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 168442, dtype: float64

168468
user
261659    0.514496
197936    0.468521
251765    0.328798
728009    0.121169
950331    0.000000
173038    0.000000
172946    0.000000
172955    0.000000
173126    0.000000
Name: 168468, dtype: float64

168647
user
950331    0.0
173421    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 168647, dtype: float64

168720
user
170419    0.360668
358474    0.330972
209755    0.269450
90296     0.157722
283160    0.156961
391794    0.070846
173141    0.000000
173038    0.000000
173126    0.000000
Name: 168720, dtype: float64

168866
user
860255    0.57735
950331    0.00000
173415    0.00000
173300    0.00000
173293    0.00000
173236    0.00000
173218    0.00000
173187    0.00000
173146    0.00000
Name: 168866, dtype: float64

168899
user
168899    1.000000
417312    1.000000
424678    0.707107
721055    0.707107
67245     0.615457
218450    0.577350
385138    0.565685
572720    0.242983
53368     0.165521
Name: 168899, dtype: float64

168906
user
520926    1.000000
326607    0.552158
259415    0.502519
744060    0.447214
173141    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
Name: 168906, dtype: float64

168917
user
91720     0.276686
950331    0.000000
173421    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 168917, dtype: float64

168976
user
318671    1.000000
708493    0.529813
73577     0.310460
256325    0.229794
391153    0.206559
641859    0.193247
173187    0.000000
173218    0.000000
173146    0.000000
Name: 168976, dtype: float64

169063
user
74871     0.600000
611711    0.600000
553056    0.600000
488321    0.600000
394954    0.600000
716619    0.565685
287074    0.499756
271060    0.499756
117432    0.424264
Name: 169063, dtype: float64

169197
user
42450     0.624695
113066    0.624695
72699     0.624695
328852    0.468521
86868     0.468521
138698    0.468521
697629    0.468521
256643    0.468521
109566    0.468521
Name: 169197, dtype: float64

169215
user
882402    1.0
465152    1.0
43207     1.0
239439    1.0
648094    1.0
169215    1.0
2175      1.0
642214    1.0
230190    1.0
Name: 169215, dtype: float64

169447
user
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 169447, dtype: float64

169490
user
84736     1.0
172770    0.0
173415    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
Name: 169490, dtype: float64

169532
user
31000     0.707107
357454    0.707107
697629    0.707107
256643    0.707107
354616    0.707107
49598     0.707107
48740     0.707107
352086    0.707107
176896    0.707107
Name: 169532, dtype: float64

169550
user
921028    0.181959
950331    0.000000
172589    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 169550, dtype: float64

169585
user
194231    0.411340
441889    0.374766
47085     0.339199
468444    0.299813
818006    0.233208
369062    0.171322
172079    0.139410
257609    0.124024
82952     0.079191
Name: 169585, dtype: float64

169608
user
648676    1.000000
169608    1.000000
46312     1.000000
582482    1.000000
87328     0.780869
219577    0.547723
347289    0.500000
856133    0.245718
249051    0.234662
Name: 169608, dtype: float64

169618
user
318686    0.442719
391650    0.349215
906243    0.316228
136661    0.316228
465115    0.316228
23533     0.316228
815556    0.316228
820044    0.316228
240369    0.316228
Name: 169618, dtype: float64

169636
user
169636    1.000000
495195    1.000000
314348    0.360668
264572    0.305888
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
Name: 169636, dtype: float64

169657
user
532525    0.685994
348677    0.485071
197936    0.428537
360185    0.363803
195653    0.334908
172770    0.285391
399142    0.272587
133470    0.218282
22782     0.192748
Name: 169657, dtype: float64

169812
user
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 169812, dtype: float64

169878
user
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 169878, dtype: float64

169881
user
133470    0.400000
88881     0.348155
68122     0.331133
420805    0.210042
173428    0.187409
114860    0.185164
172589    0.000000
173293    0.000000
173236    0.000000
Name: 169881, dtype: float64

169940
user
248657    0.345547
314022    0.345547
129947    0.259161
613864    0.259161
389047    0.259161
389377    0.259161
827709    0.259161
159824    0.259161
323358    0.259161
Name: 169940, dtype: float64

169956
user
352716    0.707107
85149     0.707107
224662    0.707107
136730    0.707107
353104    0.707107
6899      0.707107
335411    0.707107
531388    0.656532
536176    0.552158
Name: 169956, dtype: float64

170161
user
357798    0.349215
950331    0.000000
172589    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 170161, dtype: float64

170172
user
645667    0.707107
664747    0.707107
361892    0.707107
790296    0.707107
886362    0.707107
563103    0.707107
385143    0.707107
703432    0.707107
652607    0.707107
Name: 170172, dtype: float64

170196
user
48699     1.0
170196    1.0
950331    0.0
173146    0.0
172955    0.0
173038    0.0
173126    0.0
173141    0.0
173218    0.0
Name: 170196, dtype: float64

170268
user
209839    1.000000
439699    1.000000
170268    1.000000
745938    1.000000
463997    1.000000
419353    0.780869
59146     0.707107
609485    0.529813
423674    0.514496
Name: 170268, dtype: float64

170364
user
170364    1.000000
781718    1.000000
91788     0.707107
615574    0.624695
334694    0.357771
173141    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
Name: 170364, dtype: float64

170385
user
950331    0.0
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 170385, dtype: float64

170419
user
459047    0.577350
715137    0.577350
568330    0.450835
52776     0.408248
560395    0.408248
168720    0.360668
24614     0.305888
358474    0.305888
186286    0.277746
Name: 170419, dtype: float64

170611
user
135920    0.379980
195551    0.365636
30202     0.361961
22782     0.356148
440081    0.292509
256981    0.292509
316443    0.292509
556430    0.292509
388521    0.292509
Name: 170611, dtype: float64

170852
user
170852    1.000000
289156    1.000000
74904     0.707107
215860    0.707107
133983    0.700140
93992     0.685994
213694    0.624695
886698    0.600000
153279    0.577350
Name: 170852, dtype: float64

170923
user
390006    1.000000
321594    1.000000
326545    1.000000
87516     1.000000
170923    1.000000
71245     0.554700
88418     0.554700
153040    0.468521
665848    0.457496
Name: 170923, dtype: float64

171046
user
109566    1.0
697629    1.0
256643    1.0
354616    1.0
49598     1.0
48740     1.0
352086    1.0
176896    1.0
357454    1.0
Name: 171046, dtype: float64

171136
user
397753    1.000000
288030    1.000000
171136    1.000000
736492    1.000000
176888    0.707107
801415    0.662266
269509    0.447214
70779     0.359908
175875    0.000000
Name: 171136, dtype: float64

171153
user
198167    0.662266
132446    0.529813
249570    0.272190
190080    0.245959
293161    0.218079
366772    0.216295
44878     0.191820
64301     0.136095
103304    0.104632
Name: 171153, dtype: float64

171178
user
950331    0.0
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 171178, dtype: float64

171214
user
950331    0.0
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 171214, dtype: float64

171329
user
386287    1.000000
171329    1.000000
351769    1.000000
1557      1.000000
21052     1.000000
557732    1.000000
219148    0.780869
392992    0.615457
684910    0.404061
Name: 171329, dtype: float64

171421
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 171421, dtype: float64

171549
user
359898    0.624695
491073    0.468521
112180    0.468521
606877    0.468521
632235    0.468521
143267    0.468521
877370    0.468521
133152    0.468521
937146    0.419058
Name: 171549, dtype: float64

171582
user
218745    0.577350
459734    0.577350
446157    0.577350
367815    0.577350
59764     0.577350
546902    0.577350
665848    0.440225
12285     0.408248
388041    0.408248
Name: 171582, dtype: float64

171636
user
308732    1.000000
216288    1.000000
333372    0.666667
682485    0.457496
391794    0.113410
173141    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
Name: 171636, dtype: float64

171678
user
132799    1.0
105855    1.0
196696    1.0
216052    1.0
26996     1.0
28644     1.0
197937    1.0
87286     1.0
359458    1.0
Name: 171678, dtype: float64

171853
user
171853    1.0
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 171853, dtype: float64

171871
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 171871, dtype: float64

171918
user
107237    0.535672
361309    0.411597
420344    0.363803
409870    0.297044
180519    0.221918
145101    0.188528
600241    0.163209
108338    0.142090
745537    0.134123
Name: 171918, dtype: float64

171967
user
815492    0.409616
359723    0.327693
200875    0.327693
501746    0.327693
286962    0.327693
8323      0.327693
268107    0.327693
899377    0.327693
757228    0.327693
Name: 171967, dtype: float64

172049
user
115600    0.624695
74344     0.600000
22608     0.529813
116780    0.441726
52663     0.419314
686300    0.316228
114860    0.218218
256163    0.178529
70650     0.151186
Name: 172049, dtype: float64

172066
user
804396    0.615457
366858    0.480592
328956    0.435194
68246     0.435194
127770    0.407597
87328     0.384473
326195    0.384473
136933    0.355335
71170     0.316650
Name: 172066, dtype: float64

172078
user
172078    1.000000
390639    0.707107
193723    0.707107
46373     0.624695
155100    0.268328
350771    0.220193
129333    0.149256
145101    0.109930
173038    0.000000
Name: 172078, dtype: float64

172079
user
835141    0.410997
946187    0.410997
782157    0.410997
393032    0.410997
524501    0.410997
136661    0.410997
23533     0.410997
815556    0.410997
465115    0.410997
Name: 172079, dtype: float64

172339
user
145820    0.685994
136070    0.514496
133181    0.514496
196448    0.383482
179191    0.338798
73676     0.321403
471483    0.297044
74592     0.280680
26531     0.257248
Name: 172339, dtype: float64

172490
user
179262    0.606339
629675    0.468293
321576    0.374634
7320      0.276079
247421    0.132967
70650     0.080178
173141    0.000000
173146    0.000000
172504    0.000000
Name: 172490, dtype: float64

172504
user
385366    0.500000
319969    0.492366
950331    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
Name: 172504, dtype: float64

172589
user
950331    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 172589, dtype: float64

172770
user
54805     0.693375
275243    0.693375
284374    0.490290
729240    0.416025
627098    0.416025
27339     0.416025
793074    0.416025
532525    0.416025
703342    0.416025
Name: 172770, dtype: float64

172946
user
359293    1.000000
397299    1.000000
122394    1.000000
101449    1.000000
149217    1.000000
156256    1.000000
172946    1.000000
16704     0.800000
465110    0.707107
Name: 172946, dtype: float64

172955
user
172955    1.000000
380098    0.800000
190973    0.800000
314366    0.577350
322597    0.401610
224347    0.279372
363254    0.270765
554633    0.242536
315169    0.192450
Name: 172955, dtype: float64

173038
user
262112    1.000000
173038    1.000000
913037    0.577350
85626     0.492366
218901    0.213785
64301     0.205499
728009    0.121169
172770    0.000000
172946    0.000000
Name: 173038, dtype: float64

173126
user
156985    1.0
873812    1.0
173126    1.0
950331    0.0
173141    0.0
172946    0.0
172955    0.0
173038    0.0
173146    0.0
Name: 173126, dtype: float64

173141
user
173141    1.000000
131540    1.000000
701499    1.000000
243313    0.371391
710618    0.291730
923208    0.284747
173146    0.000000
173187    0.000000
173218    0.000000
Name: 173141, dtype: float64

173146
user
380154    0.662266
386131    0.662266
44848     0.529813
229208    0.529813
398658    0.529813
358417    0.529813
354580    0.468293
498923    0.407597
43926     0.374634
Name: 173146, dtype: float64

173187
user
220887    1.000000
814144    0.962250
101994    0.377964
132614    0.369274
17211     0.298142
51405     0.214423
43793     0.101274
215917    0.067574
172955    0.000000
Name: 173187, dtype: float64

173218
user
135201    1.000000
136981    0.468293
950331    0.000000
172589    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173187    0.000000
173146    0.000000
Name: 173218, dtype: float64

173236
user
288873    0.707107
867166    0.624695
172490    0.000000
173293    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
173126    0.000000
Name: 173236, dtype: float64

173293
user
636781    0.208514
950331    0.000000
172504    0.000000
173300    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
Name: 173293, dtype: float64

173300
user
227237    0.468165
950331    0.000000
172504    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
Name: 173300, dtype: float64

173325
user
108848    0.707107
874331    0.500000
158018    0.299813
255258    0.232495
173218    0.000000
173187    0.000000
173146    0.000000
172589    0.000000
173126    0.000000
Name: 173325, dtype: float64

173415
user
194983    1.000000
450803    0.707107
192236    0.441726
363254    0.191460
190766    0.168742
171853    0.000000
172770    0.000000
173293    0.000000
173236    0.000000
Name: 173415, dtype: float64

173421
user
313       1.000000
173421    1.000000
323845    0.441726
155466    0.348155
173300    0.000000
173293    0.000000
173236    0.000000
173325    0.000000
173218    0.000000
Name: 173421, dtype: float64

173428
user
759526    0.441726
290662    0.441726
317740    0.441726
893228    0.441726
864883    0.441726
198873    0.441726
96373     0.441726
28330     0.353381
634615    0.331295
Name: 173428, dtype: float64

173796
user
319979    1.000000
212395    1.000000
284794    1.000000
280639    1.000000
173796    1.000000
412528    1.000000
111635    1.000000
29192     1.000000
70203     0.780869
Name: 173796, dtype: float64

173838
user
173838    1.000000
923208    0.284747
636781    0.208514
173236    0.000000
173218    0.000000
173293    0.000000
173187    0.000000
173146    0.000000
172504    0.000000
Name: 173838, dtype: float64

173875
user
245621    1.0
314118    1.0
196360    1.0
248626    1.0
290161    1.0
738464    1.0
316074    1.0
442004    1.0
950331    0.0
Name: 173875, dtype: float64

173879
user
114160    0.311891
950331    0.000000
173421    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 173879, dtype: float64

173892
user
737809    1.000000
173892    1.000000
856133    0.307148
173146    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
Name: 173892, dtype: float64

173943
user
212461    1.000000
129223    1.000000
173943    1.000000
57125     1.000000
150433    1.000000
195667    1.000000
292280    1.000000
149684    1.000000
283386    0.780869
Name: 173943, dtype: float64

173973
user
224545    0.468165
212395    0.468165
111635    0.468165
173796    0.468165
280639    0.468165
319979    0.468165
284794    0.468165
412528    0.468165
29192     0.468165
Name: 173973, dtype: float64

174002
user
179685    0.600000
256985    0.480000
398557    0.346410
129316    0.286855
323845    0.265036
305856    0.259554
155466    0.208893
385272    0.126491
386997    0.077967
Name: 174002, dtype: float64

174016
user
43510     0.307794
560061    0.307794
935034    0.307794
401910    0.307794
50758     0.307794
23999     0.307794
98586     0.307794
576558    0.307794
339564    0.307794
Name: 174016, dtype: float64

174105
user
764772    0.461880
133993    0.213504
173146    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
950331    0.000000
Name: 174105, dtype: float64

174466
user
793074    0.624695
158492    0.487805
263894    0.413714
399142    0.413714
220695    0.406642
393981    0.330972
419534    0.315519
791637    0.306282
131485    0.290007
Name: 174466, dtype: float64


user
45308     0.436436
113136    0.436436
107751    0.436436
74666     0.436436
279978    0.436436
148586    0.436436
24006     0.340799
50007     0.340799
706290    0.327327
Name: 178898, dtype: float64

179008
user
89963     0.345547
90296     0.252478
213301    0.186299
69019     0.176950
243883    0.173205
391794    0.113410
173141    0.000000
172955    0.000000
173038    0.000000
Name: 179008, dtype: float64

179015
user
681788    1.0
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 179015, dtype: float64

179160
user
179160    1.000000
89332     0.707107
192285    0.339276
117820    0.326599
133993    0.213504
391794    0.085057
173187    0.000000
173126    0.000000
173141    0.000000
Name: 179160, dtype: float64

179191
user
211542    0.752577
350949    0.752577
180780    0.752577
7226      0.730107
133181    0.658505
136070    0.658505
172339    0.338798
117370    0.244562
108338    0.242481
Name: 179191, dtype: float64

179262
user
172490    0.606339
629675    0.567889
126427    0.514496
321576    0.454311
113143    0.178227
70650     0.097231
173038    0.000000
172770    0.000000
172946    0.000000
Name: 179262, dtype: float64

179325
user
179325    1.000000
127163    1.000000
823651    0.928477
692299    0.707107
307072    0.707107
534410    0.373002
935084    0.370625
138679    0.340207
288157    0.287242
Name: 179325, dtype: float64

179417
user
783096    0.285714
132504    0.216612
90997     0.171499
950331    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
173146    0.000000
173187    0.000000
Name: 179417, dtype: float64

179448
user
445791    1.00000
328775    0.14151
950331    0.00000
172589    0.00000
173293    0.00000
173236    0.00000
173218    0.00000
173187    0.00000
173146    0.00000
Name: 179448, dtype: float64

179488
user
112229    0.418209
149217    0.350823
361892    0.350823
152603    0.350823
101449    0.350823
644110    0.350823
201162    0.350823
359293    0.350823
385143    0.350823
Name: 179488, dtype: float64

179544
user
110348    0.615457
361309    0.600000
316376    0.452267
227331    0.441726
225910    0.441726
33053     0.424264
198050    0.396526
105881    0.363696
132954    0.346410
Name: 179544, dtype: float64

179653
user
418830    0.989949
556749    0.800000
305522    0.733799
230662    0.626295
790931    0.600000
46758     0.600000
422401    0.600000
677778    0.600000
254215    0.600000
Name: 179653, dtype: float64

179685
user
256985    0.800000
174002    0.600000
398557    0.577350
129316    0.478091
323845    0.441726
155466    0.348155
386997    0.129944
745537    0.117309
950331    0.000000
Name: 179685, dtype: float64

179719
user
191023    0.308607
268107    0.308607
315174    0.308607
578969    0.308607
790247    0.308607
194889    0.308607
286962    0.308607
862633    0.302614
661090    0.256776
Name: 179719, dtype: float64

179727
user
239796    0.213956
836071    0.185990
135062    0.183756
132480    0.176432
156256    0.176432
315174    0.176432
815556    0.176432
397299    0.176432
194854    0.176432
Name: 179727, dtype: float64

179745
user
197359    1.000000
751014    1.000000
63512     0.447214
46322     0.426401
27703     0.303046
5666      0.256600
138574    0.247436
109622    0.194054
173415    0.000000
Name: 179745, dtype: float64

179832
user
920668    0.970143
178600    0.600000
150785    0.419314
155100    0.357771
370681    0.289430
950331    0.000000
173126    0.000000
172955    0.000000
173038    0.000000
Name: 179832, dtype: float64

179846
user
396163    1.0
950331    0.0
172770    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 179846, dtype: float64

179859
user
179859    1.0
950331    0.0
172504    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 179859, dtype: float64

179871
user
398361    1.000000
924557    1.000000
70861     1.000000
85645     0.707107
5666      0.256600
133400    0.246632
20363     0.205196
256325    0.172345
745537    0.156412
Name: 179871, dtype: float64

180453
user
180453    1.000000
85626     0.615457
4629      0.298142
172770    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 180453, dtype: float64

180519
user
31984     0.431331
191363    0.431331
361309    0.345065
212395    0.323498
284794    0.323498
24902     0.323498
8036      0.323498
224545    0.323498
111635    0.323498
Name: 180519, dtype: float64

180539
user
48442     0.447214
357985    0.447214
118351    0.332182
294618    0.316228
221510    0.316228
65621     0.279372
791637    0.219265
293161    0.196352
391017    0.122859
Name: 180539, dtype: float64

180541
user
256332    0.350823
719811    0.350823
32151     0.350823
707460    0.350823
113970    0.350823
204033    0.350823
48814     0.350823
657251    0.350823
214747    0.350823
Name: 180541, dtype: float64

180670
user
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 180670, dtype: float64

180710
user
180710    1.0
950331    0.0
172770    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
Name: 180710, dtype: float64

180718
user
885234    0.800000
256001    0.800000
358746    0.800000
400150    0.800000
380394    0.600000
688990    0.461880
864133    0.424264
5282      0.424264
159313    0.416605
Name: 180718, dtype: float64

180729
user
553056    0.435194
74871     0.435194
611711    0.435194
811320    0.435194
11935     0.435194
394954    0.435194
488321    0.435194
823508    0.348155
150647    0.348155
Name: 180729, dtype: float64

180780
user
350949    1.000000
211542    1.000000
7226      0.970143
179191    0.752577
108936    0.265513
724982    0.137767
950331    0.000000
173038    0.000000
173126    0.000000
Name: 180780, dtype: float64

180812
user
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
173126    0.0
Name: 180812, dtype: float64

181027
user
6574      1.000000
611186    1.000000
181027    1.000000
279303    0.707107
319153    0.358569
950331    0.000000
172589    0.000000
172770    0.000000
172946    0.000000
Name: 181027, dtype: float64

181135
user
279375    1.000000
308373    1.000000
288121    1.000000
167525    1.000000
181135    1.000000
261748    0.615457
256985    0.600000
129316    0.597614
85808     0.544331
Name: 181135, dtype: float64

181159
user
745537    0.117309
950331    0.000000
172770    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 181159, dtype: float64

182213
user
790247    0.609994
18297     0.609994
315174    0.609994
191023    0.609994
776788    0.609994
129271    0.609994
245897    0.600510
862633    0.598149
652607    0.457496
Name: 182213, dtype: float64

182301
user
88172     1.0
692426    1.0
529676    1.0
593945    1.0
944033    1.0
473854    1.0
363134    1.0
569529    1.0
182301    1.0
Name: 182301, dtype: float64

183443
user
584895    1.000000
391957    0.305995
724982    0.172209
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
172504    0.000000
173141    0.000000
Name: 183443, dtype: float64

183668
user
556430    0.617213
755817    0.617213
256981    0.617213
388521    0.617213
664747    0.462910
886362    0.462910
645667    0.462910
82581     0.462910
790296    0.462910
Name: 183668, dtype: float64

184471
user
147610    0.445363
328802    0.350931
254239    0.350931
63030     0.350931
73653     0.350931
162500    0.350931
400694    0.350931
65017     0.325831
219760    0.280745
Name: 184471, dtype: float64

185483
user
323031    1.000000
62113     0.685994
754864    0.445435
93563     0.336336
171853    0.000000
171678    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
Name: 185483, dtype: float64

185514
user
109058    0.327327
950331    0.000000
172589    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 185514, dtype: float64

186286
user
170419    0.277746
783901    0.267131
51766     0.254877
152603    0.213809
715137    0.213809
439187    0.213809
54805     0.213809
644110    0.213809
340105    0.213809
Name: 186286, dtype: float64

186342
user
186342    1.0
950331    0.0
173141    0.0
172770    0.0
172946    0.0
172955    0.0
173038    0.0
173126    0.0
173187    0.0
Name: 186342, dtype: float64

186572
user
648839    1.0
783345    1.0
111561    1.0
786717    1.0
753506    1.0
314345    1.0
596425    1.0
257101    1.0
44077     1.0
Name: 186572, dtype: float64

186982
user
857507    0.545545
343630    0.545545
401012    0.545545
219148    0.528239
190236    0.436436
249802    0.436436
29192     0.436436
284794    0.436436
319979    0.436436
Name: 186982, dtype: float64

188061
user
851090    1.000000
188061    1.000000
732125    1.000000
439187    1.000000
61770     1.000000
401305    0.894427
263524    0.800000
744990    0.800000
28032     0.800000
Name: 188061, dtype: float64

189901
user
665344    0.543710
805528    0.483298
280011    0.427179
885332    0.378591
534551    0.366303
51496     0.341743
227401    0.341743
111719    0.341743
100771    0.341743
Name: 189901, dtype: float64

190080
user
198167    0.371391
327334    0.362509
137761    0.290007
171153    0.245959
1656      0.238849
150196    0.221317
249570    0.152641
91720     0.128448
293161    0.122296
Name: 190080, dtype: float64

190145
user
92949     0.529813
24276     0.305888
96360     0.185019
357677    0.170222
261456    0.144197
153457    0.111850
516840    0.110741
950331    0.000000
172955    0.000000
Name: 190145, dtype: float64

190213
user
71232     0.331088
215917    0.211065
789207    0.094176
179727    0.082662
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
173146    0.000000
Name: 190213, dtype: float64

190236
user
857507    0.800000
401012    0.800000
227541    0.600000
921784    0.582086
186982    0.436436
89719     0.353381
725789    0.316847
132504    0.162459
283160    0.090453
Name: 190236, dtype: float64

190348
user
53332     0.436436
622936    0.436436
61776     0.436436
437764    0.436436
774737    0.436436
135001    0.327327
746       0.327327
23390     0.327327
197081    0.325300
Name: 190348, dtype: float64

190366
user
613864    1.000000
827709    1.000000
108796    1.000000
129947    1.000000
190366    1.000000
389377    1.000000
678906    1.000000
194541    1.000000
721055    0.707107
Name: 190366, dtype: float64

190521
user
190521    1.000000
72849     0.334825
67868     0.283069
237668    0.180746
172589    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
Name: 190521, dtype: float64

190541
user
218451    1.000000
190541    1.000000
193020    1.000000
320837    0.800000
137630    0.707107
932113    0.369274
247421    0.188044
724982    0.137767
173146    0.000000
Name: 190541, dtype: float64

190564
user
498185    0.600000
33179     0.408248
169618    0.316228
24964     0.266207
173141    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
Name: 190564, dtype: float64

190640
user
950331    0.0
172490    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
173126    0.0
Name: 190640, dtype: float64

190725
user
393834    0.302372
93171     0.226779
804396    0.226779
325142    0.213809
88881     0.186097
249421    0.186097
64412     0.186097
366858    0.177084
170419    0.174574
Name: 190725, dtype: float64

190766
user
363254    0.413533
172066    0.264368
400110    0.238637
50592     0.238637
397331    0.238637
18611     0.238637
26450     0.238637
401104    0.238637
138402    0.238637
Name: 190766, dtype: float64

190972
user
273043    0.707107
702417    0.309529
950331    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
Name: 190972, dtype: float64

190973
user
172955    0.80
752559    0.80
380098    0.64
222975    0.60
261654    0.60
194122    0.60
49771     0.60
780237    0.60
246545    0.60
Name: 190973, dtype: float64

191023
user
790247    1.000000
315174    1.000000
862633    0.980581
182213    0.609994
731285    0.606339
245897    0.562544
87338     0.481125
586606    0.371391
314604    0.351123
Name: 191023, dtype: float64

191100
user
116307    0.514496
75433     0.514496
725466    0.514496
887586    0.428086
441024    0.321403
664880    0.297044
314604    0.240869
469418    0.231953
251474    0.192748
Name: 191100, dtype: float64

191191
user
254431    1.000000
89999     0.539164
357677    0.321288
646881    0.310460
288157    0.287242
85688     0.215041
950331    0.000000
172955    0.000000
173038    0.000000
Name: 191191, dtype: float64

191229
user
950331    0.0
172504    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
173126    0.0
Name: 191229, dtype: float64

191321
user
411020    0.857493
256163    0.191359
530433    0.135847
173126    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
950331    0.000000
Name: 191321, dtype: float64

191363
user
31984     1.000000
74904     0.707107
298395    0.505076
2847      0.492366
180519    0.431331
177951    0.404061
2109      0.388075
46560     0.334825
923459    0.264906
Name: 191363, dtype: float64

191379
user
209839    1.000000
439699    1.000000
170268    1.000000
745938    1.000000
463997    1.000000
419353    0.780869
59146     0.707107
609485    0.529813
423674    0.514496
Name: 191379, dtype: float64

191501
user
580520    0.260378
950331    0.000000
172504    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
Name: 191501, dtype: float64

191551
user
439060    1.000000
191551    1.000000
405980    1.000000
159583    0.780869
821860    0.565685
546411    0.529813
880907    0.492366
49954     0.421076
175405    0.302614
Name: 191551, dtype: float64

191568
user
753900    1.000000
191568    1.000000
117432    0.707107
572720    0.303728
68122     0.280976
186286    0.213809
173187    0.000000
173146    0.000000
172589    0.000000
Name: 191568, dtype: float64

191613
user
550105    1.000000
195147    0.404061
192676    0.389249
319153    0.358569
321572    0.323381
224347    0.279372
173187    0.000000
173146    0.000000
173141    0.000000
Name: 191613, dtype: float64

191782
user
686313    1.0
938515    1.0
950331    0.0
173141    0.0
172770    0.0
172946    0.0
172955    0.0
173038    0.0
173126    0.0
Name: 191782, dtype: float64

192095
user
113896    0.529999
940225    0.529999
148777    0.529999
44204     0.529999
76564     0.529999
194777    0.529999
63763     0.529999
148169    0.529999
89712     0.492092
Name: 192095, dtype: float64

192226
user
10287     1.000000
930037    1.000000
192226    1.000000
29563     0.780869
288222    0.707107
23433     0.441726
114860    0.436436
138679    0.340207
46560     0.334825
Name: 192226, dtype: float64

192236
user
504649    0.780869
47297     0.780869
158481    0.780869
112616    0.780869
85705     0.780869
107432    0.780869
874578    0.765705
855363    0.609756
3019      0.595407
Name: 192236, dtype: float64

192257
user
6574      1.000000
611186    1.000000
181027    1.000000
279303    0.707107
319153    0.358569
950331    0.000000
172589    0.000000
172770    0.000000
172946    0.000000
Name: 192257, dtype: float64

192285
user
66411     0.424094
127770    0.404443
321692    0.339276
37980     0.339276
261654    0.339276
49771     0.339276
924153    0.339276
222975    0.339276
804396    0.339276
Name: 192285, dtype: float64

192437
user
101141    0.520156
66608     0.507093
677551    0.507093
213740    0.507093
288873    0.358569
698792    0.316778
198312    0.215141
356471    0.167571
851312    0.140642
Name: 192437, dtype: float64

192450
user
82581     1.0
487327    1.0
652607    1.0
42615     1.0
7488      1.0
721140    1.0
645667    1.0
664747    1.0
192450    1.0
Name: 192450, dtype: float64

192676
user
191613    0.389249
550105    0.389249
128662    0.311400
426302    0.311400
360079    0.311400
811320    0.311400
746       0.311400
250391    0.311400
880552    0.311400
Name: 192676, dtype: float64

192754
user
950331    0.0
173415    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 192754, dtype: float64

192778
user
24964     0.354943
950331    0.000000
172589    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 192778, dtype: float64

192836
user
648839    1.0
783345    1.0
111561    1.0
786717    1.0
753506    1.0
314345    1.0
596425    1.0
257101    1.0
44077     1.0
Name: 192836, dtype: float64

192944
user
844482    1.000000
47484     0.707107
883362    0.285714
921028    0.227449
237668    0.144597
53368     0.124141
395537    0.122169
173187    0.000000
173146    0.000000
Name: 192944, dtype: float64

193009
user
950331    0.0
173415    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 193009, dtype: float64

193020
user
218451    1.000000
190541    1.000000
193020    1.000000
320837    0.800000
137630    0.707107
932113    0.369274
247421    0.188044
724982    0.137767
173146    0.000000
Name: 193020, dtype: float64

193185
user
355775    0.571662
61892     0.514496
875286    0.514496
614124    0.514496
222193    0.502395
224561    0.495074
609485    0.340733
514754    0.328834
29491     0.315754
Name: 193185, dtype: float64

193211
user
132799    1.0
105855    1.0
196696    1.0
216052    1.0
26996     1.0
28644     1.0
197937    1.0
87286     1.0
359458    1.0
Name: 193211, dtype: float64

193213
user
927595    0.529813
804396    0.397360
854097    0.374634
169197    0.330972
366858    0.310286
68246     0.280976
328956    0.280976
127770    0.263158
87328     0.248229
Name: 193213, dtype: float64

193499
user
426952    0.577350
28722     0.577350
26352     0.577350
885528    0.577350
666409    0.408248
388096    0.346410
193549    0.251259
85669     0.230940
166       0.189525
Name: 193499, dtype: float64

193549
user
148777    0.435194
940225    0.435194
63763     0.435194
28722     0.435194
426952    0.435194
76564     0.435194
885528    0.435194
194777    0.435194
54805     0.435194
Name: 193549, dtype: float64

193704
user
193704    1.000000
155207    0.512989
179727    0.176432
485567    0.145000
328775    0.141510
173218    0.000000
173187    0.000000
173146    0.000000
172589    0.000000
Name: 193704, dtype: float64

193723
user
172078    0.707107
336473    0.707107
224377    0.707107
566689    0.707107
397183    0.552158
390639    0.500000
46373     0.441726
26843     0.328266
164819    0.316228
Name: 193723, dtype: float64

193795
user
51752     1.0
219458    1.0
199172    1.0
295792    1.0
261822    1.0
193795    1.0
260171    1.0
329184    1.0
365315    1.0
Name: 193795, dtype: float64

194122
user
22636     1.0
261654    1.0
222975    1.0
153678    1.0
321692    1.0
37980     1.0
780237    1.0
55705     1.0
194122    1.0
Name: 194122, dtype: float64

194152
user
108443    0.656532
50553     0.423999
67868     0.226455
156952    0.199254
237668    0.180746
279785    0.174078
173146    0.000000
173187    0.000000
172946    0.000000
Name: 194152, dtype: float64

194159
user
194159    1.000000
196734    0.707107
949019    0.577350
950331    0.000000
173141    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
Name: 194159, dtype: float64

194231
user
468444    0.685994
169585    0.411340
369062    0.391997
257609    0.283775
818006    0.266798
205093    0.242536
82952     0.181195
884890    0.169362
256325    0.167200
Name: 194231, dtype: float64

194342
user
389047    1.0

Name: 196651, dtype: float64

196686
user
109744    0.83205
173415    0.00000
173325    0.00000
173300    0.00000
173293    0.00000
173236    0.00000
173218    0.00000
173187    0.00000
173146    0.00000
Name: 196686, dtype: float64

196696
user
132799    1.0
105855    1.0
196696    1.0
216052    1.0
26996     1.0
28644     1.0
197937    1.0
87286     1.0
359458    1.0
Name: 196696, dtype: float64

196734
user
194159    0.707107
46159     0.707107
195791    0.707107
949019    0.408248
818006    0.324102
176665    0.239046
243883    0.204124
71632     0.175682
385612    0.116073
Name: 196734, dtype: float64

196874
user
564331    1.0
217007    1.0
171636    0.0
171678    0.0
171582    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
Name: 196874, dtype: float64

197006
user
32143     0.138343
391794    0.113410
176709    0.000000
176665    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
Name: 197006, dtype: float64

197021
user
950331    0.0
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 197021, dtype: float64

197081
user
774737    0.745356
65081     0.651584
202112    0.527046
108457    0.493624
4347      0.493624
783901    0.465620
355767    0.458735
71789     0.458735
212057    0.421637
Name: 197081, dtype: float64

197109
user
89963     0.431934
950331    0.000000
172504    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
Name: 197109, dtype: float64

197247
user
813653    1.000000
388399    0.386695
950331    0.000000
172589    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 197247, dtype: float64

197268
user
819045    0.582086
85785     0.485071
804396    0.485071
321082    0.485071
50553     0.411340
579530    0.406794
366858    0.378777
328956    0.342997
68246     0.342997
Name: 197268, dtype: float64

197277
user
131485    0.437688
391153    0.304290
198103    0.235702
320473    0.235702
332713    0.235702
804396    0.235702
150279    0.235702
366858    0.184053
328956    0.166667
Name: 197277, dtype: float64

197308
user
607450    1.000000
21105     1.000000
357798    0.312348
243883    0.288675
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
Name: 197308, dtype: float64

197336
user
950331    0.0
172504    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
173126    0.0
Name: 197336, dtype: float64

197344
user
950331    0.0
172504    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
173126    0.0
Name: 197344, dtype: float64

197359
user
197359    1.000000
751014    1.000000
63512     0.447214
46322     0.426401
27703     0.303046
5666      0.256600
138574    0.247436
109622    0.194054
173415    0.000000
Name: 197359, dtype: float64

197448
user
614812    0.707107
626385    0.707107
814610    0.707107
186572    0.707107
648839    0.707107
147193    0.707107
753506    0.707107
111561    0.707107
314345    0.707107
Name: 197448, dtype: float64

197460
user
199202    1.000000
151373    0.624695
452187    0.577350
136933    0.577350
67088     0.457496
334694    0.357771
290423    0.339276
72849     0.334825
127971    0.300000
Name: 197460, dtype: float64

197504
user
160404    0.417029
229007    0.417029
18966     0.417029
755162    0.417029
817844    0.357599
944394    0.312772
622340    0.312772
39314     0.312772
853410    0.312772
Name: 197504, dtype: float64

197585
user
339218    1.000000
288042    1.000000
270590    1.000000
535452    0.624695
319153    0.239046
862633    0.196116
250495    0.184703
173038    0.000000
173126    0.000000
Name: 197585, dtype: float64

197893
user
309828    1.000000
250513    1.000000
461917    1.000000
105989    1.000000
197893    1.000000
63622     1.000000
252432    1.000000
721134    0.970143
721787    0.707107
Name: 197893, dtype: float64

197904
user
12225     0.514496
50592     0.514496
18611     0.514496
397331    0.514496
138402    0.514496
354415    0.321403
69546     0.264706
222718    0.232307
636781    0.223500
Name: 197904, dtype: float64

197936
user
532525    0.624695
794128    0.624695
168468    0.468521
348677    0.441726
169657    0.428537
172770    0.259889
261659    0.241052
363254    0.169146
251765    0.154049
Name: 197936, dtype: float64

197937
user
132799    1.0
105855    1.0
196696    1.0
216052    1.0
26996     1.0
28644     1.0
197937    1.0
87286     1.0
359458    1.0
Name: 197937, dtype: float64

197958
user
373775    0.336861
697977    0.285714
172589    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 197958, dtype: float64

198045
user
46715     1.000000
309102    0.780869
148702    0.304114
315118    0.258738
820908    0.197546
171967    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
Name: 198045, dtype: float64

198050
user
179544    0.396526
743691    0.317221
386131    0.317221
656927    0.317221
354735    0.317221
323611    0.317221
380154    0.317221
110348    0.244045
361309    0.237915
Name: 198050, dtype: float64

198067
user
251567    0.363696
401684    0.168763
133993    0.160128
950331    0.000000
173146    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
Name: 198067, dtype: float64

198103
user
320473    1.000000
150279    1.000000
198103    1.000000
215042    0.254824
197277    0.235702
950331    0.000000
173126    0.000000
172946    0.000000
172955    0.000000
Name: 198103, dtype: float64

198110
user
696746    0.894427
350912    0.624695
507859    0.615457
845485    0.320092
686300    0.316228
752650    0.149906
391794    0.113410
179727    0.044108
171918    0.000000
Name: 198110, dtype: float64

198167
user
171153    0.662266
249570    0.410997
190080    0.371391
293161    0.329293
366772    0.326599
44878     0.289642
64301     0.205499
103304    0.157991
724982    0.137767
Name: 198167, dtype: float64

198177
user
132799    1.0
105855    1.0
196696    1.0
216052    1.0
26996     1.0
28644     1.0
197937    1.0
87286     1.0
359458    1.0
Name: 198177, dtype: float64

198226
user
109752    0.800000
328899    0.707107
256348    0.331295
94677     0.243884
173141    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
Name: 198226, dtype: float64

198312
user
213740    0.424264
66608     0.424264
677551    0.424264
392840    0.374634
288873    0.300000
698792    0.265036
211972    0.264906
192437    0.215141
90292     0.181748
Name: 198312, dtype: float64

198386
user
686640    1.000000
612464    0.872872
906552    0.606339
89999     0.539164
390671    0.370625
134807    0.348155
5311      0.304997
364545    0.177778
64301     0.164399
Name: 198386, dtype: float64

198419
user
90292     0.321288
950331    0.000000
172504    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
Name: 198419, dtype: float64

198798
user
198798    1.000000
386997    0.216574
950331    0.000000
173146    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
Name: 198798, dtype: float64

198805
user
393935    1.000000
423011    1.000000
252216    0.227429
173126    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173146    0.000000
Name: 198805, dtype: float64

198833
user
129686    0.265489
215042    0.254824
950331    0.000000
172770    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 198833, dtype: float64

198873
user
317740    1.000000
28330     0.800000
50007     0.624695
789207    0.603023
173428    0.441726
652365    0.348155
82952     0.311286
73577     0.310460
73273     0.298142
Name: 198873, dtype: float64

199034
user
199034    1.000000
753519    1.000000
318884    1.000000
476529    1.000000
284559    0.894427
105338    0.662266
212036    0.529813
361582    0.333333
820908    0.246932
Name: 199034, dtype: float64

199038
user
179859    1.0
950331    0.0
172504    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 199038, dtype: float64

199077
user
630347    0.428746
43235     0.428746
337914    0.428746
154897    0.342997
788114    0.158550
150968    0.127386
391153    0.110702
172955    0.000000
173038    0.000000
Name: 199077, dtype: float64

199091
user
172946    0.624695
101449    0.624695
122394    0.624695
156256    0.624695
397299    0.624695
574786    0.624695
149217    0.624695
359293    0.624695
16704     0.499756
Name: 199091, dtype: float64

199124
user
840293    0.348155
950331    0.000000
173141    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173187    0.000000
Name: 199124, dtype: float64

199172
user
51752     1.0
219458    1.0
199172    1.0
295792    1.0
261822    1.0
193795    1.0
260171    1.0
329184    1.0
365315    1.0
Name: 199172, dtype: float64

199178
user
648839    1.0
783345    1.0
111561    1.0
786717    1.0
753506    1.0
314345    1.0
596425    1.0
257101    1.0
44077     1.0
Name: 199178, dtype: float64

199202
user
199202    1.000000
151373    0.624695
452187    0.577350
136933    0.577350
67088     0.457496
334694    0.357771
290423    0.339276
72849     0.334825
127971    0.300000
Name: 199202, dtype: float64

199406
user
392082    0.260378
85688     0.215041
516840    0.209020
391794    0.141762
171853    0.000000
171871    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
Name: 199406, dtype: float64

199410
user
448633    0.780869
761773    0.780869
132641    0.780869
45836     0.780869
92068     0.698430
813771    0.624695
46607     0.624695
212057    0.552158
4347      0.413714
Name: 199410, dtype: float64

199739
user
950331    0.0
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 199739, dtype: float64

199828
user
325255    0.447214
239894    0.447214
417545    0.447214
593182    0.157347
485567    0.064846
861280    0.048957
172589    0.000000
172770    0.000000
172946    0.000000
Name: 199828, dtype: float64

200652
user
200652    1.000000
126931    1.000000
839712    1.000000
148206    0.707107
441889    0.707107
2419      0.468165
33061     0.441726
93647     0.424264
531388    0.371391
Name: 200652, dtype: float64

200742
user
292194    0.346410
117820    0.326599
18783     0.319235
884890    0.130931
173141    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
Name: 200742, dtype: float64

200786
user
139218    1.00000
103928    0.57735
950331    0.00000
173293    0.00000
173236    0.00000
173218    0.00000
173187    0.00000
173146    0.00000
173141    0.00000
Name: 200786, dtype: float64

200843
user
259513    1.0
48575     1.0
200843    1.0
678481    1.0
950331    0.0
173038    0.0
173126    0.0
173141    0.0
173146    0.0
Name: 200843, dtype: float64

200875
user
899377    1.000000
42721     1.000000
709700    1.000000
757228    1.000000
87724     1.000000
8323      1.000000
501746    1.000000
470673    0.800000
131375    0.707107
Name: 200875, dtype: float64

201157
user
219760    1.000000
794785    1.000000
23255     1.000000
358700    1.000000
792019    1.000000
506648    0.780869
598467    0.707107
848512    0.707107
149784    0.707107
Name: 201157, dtype: float64

201162
user
908860    1.000000
209415    1.000000
201162    1.000000
644110    1.000000
152603    1.000000
351982    1.000000
554398    0.707107
848512    0.707107
427422    0.624695
Name: 201162, dtype: float64

201349
user
91251     0.707107
886848    0.707107
822237    0.565685
556845    0.565685
943069    0.565685
148723    0.565685
440081    0.565685
135920    0.326599
351808    0.282843
Name: 201349, dtype: float64

201482
user
149905    0.577350
482273    0.577350
67211     0.408248
252734    0.360668
397051    0.350070
135044    0.333333
95985     0.255031
514754    0.221404
31285     0.219476
Name: 201482, dtype: float64

201564
user
853410    1.000000
39314     1.000000
622340    1.000000
944394    1.000000
828625    0.894427
49805     0.780869
83257     0.577350
4347      0.529813
310557    0.514496
Name: 201564, dtype: float64

201575
user
248657    0.707107
321594    0.424264
390006    0.424264
87516     0.424264
1409      0.424264
170923    0.424264
326545    0.424264
71242     0.348155
334694    0.252982
Name: 201575, dtype: float64

201892
user
316768    1.0
695760    1.0
27939     1.0
50690     1.0
134761    1.0
50739     1.0
147932    1.0
29070     1.0
256789    1.0
Name: 201892, dtype: float64

202032
user
365419    1.000000
117869    1.000000
202032    1.000000
244614    1.000000
132262    1.000000
626627    1.000000
702417    0.386912
110348    0.369274
91720     0.345857
Name: 202032, dtype: float64

202044
user
918706    0.685994
89719     0.353381
74751     0.216695
72849     0.200895
921028    0.181959
72686     0.153897
133400    0.118383
250495    0.110822
172049    0.000000
Name: 202044, dtype: float64

202112
user
774737    0.707107
197081    0.527046
108457    0.468293
4347      0.468293
65081     0.468293
71789     0.435194
355767    0.435194
252211    0.363803
251266    0.318788
Name: 202112, dtype: float64

203033
user
487400    1.000000
159773    1.000000
342978    1.000000
106216    1.000000
899670    1.000000
267306    1.000000
203033    1.000000
177362    0.970143
135354    0.707107
Name: 203033, dtype: float64

203647
user
92831     1.000000
475865    1.000000
318073    1.000000
420587    1.000000
398867    0.780869
3357      0.707107
518696    0.624695
13006     0.624695
613041    0.577350
Name: 203647, dtype: float64

203872
user
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 203872, dtype: float64

204033
user
204033    1.000000
48814     1.000000
931768    1.000000
719811    1.000000
75174     1.000000
707460    1.000000
98330     0.780869
62904     0.585206
211914    0.492366
Name: 204033, dtype: float64

204788
user
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 204788, dtype: float64

205093
user
194231    0.242536
276312    0.226455
132504    0.162459
678384    0.129099
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
Name: 205093, dtype: float64

205118
user
744060    0.447214
950331    0.000000
173421    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 205118, dtype: float64

206561
user
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 206561, dtype: float64

206816
user
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 206816, dtype: float64

207381
user
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 207381, dtype: float64

207470
user
367228    0.685994
950331    0.000000
172770    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 207470, dtype: float64

207711
user
334694    0.357771
284695    0.225647
222718    0.203186
172770    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 207711, dtype: float64

207720
user
470723    0.276501
950331    0.000000
172770    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 207720, dtype: float64

208228
user
54441     0.685994
859898    0.514496
72566     0.514496
132480    0.514496
648265    0.485071
65081     0.363449
226757    0.351330
706437    0.321403
396276    0.316650
Name: 208228, dtype: float64

208452
user
392437    0.780869
696492    0.624695
950331    0.000000
173141    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173187    0.000000
Name: 208452, dtype: float64

208774
user
908860    1.000000
209415    1.000000
201162    1.000000
644110    1.000000
152603    1.000000
351982    1.000000
554398    0.707107
848512    0.707107
427422    0.624695
Name: 208774, dtype: float64

208839
user
950331    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
173126    0.0
Name: 208839, dtype: float64

209069
user
391957    0.305995
386968    0.199007
173146    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
173187    0.000000
Name: 209069, dtype: float64

209415
user
908860    1.000000
209415    1.000000
201162    1.000000
644110    1.000000
152603    1.000000
351982    1.000000
554398    0.707107
848512    0.707107
427422    0.624695
Name: 209415, dtype: float64

209755
user
200875    0.431331
899377    0.431331
709700    0.431331
42721     0.431331
757228    0.431331
8323      0.431331
87724     0.431331
501746    0.431331
670466    0.422955
Name: 209755, dtype: float64

209783
user
175861    1.000000
52776     0.707107
145101    0.219860
781898    0.147743
845485    0.128037
950331    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
Name: 209783, dtype: float64

209839
user
209839    1.000000
439699    1.000000
170268    1.000000
745938    1.000000
463997    1.000000
419353    0.780869
59146     0.707107
609485    0.529813
423674    0.514496
Name: 209839, dtype: float64

210944
user
950331    0.0
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 210944, dtype: float64

211039
user
1190      0.468293
237982    0.468293
88648     0.468293
699433    0.468293
776502    0.374634
927595    0.374634
281732    0.374634
700993    0.374634
894693    0.292540
Name: 211039, dtype: float64

211068
user
605904    1.000000
11328     0.780869
68977     0.370625
173146    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
Name: 211068, dtype: float64

211085
user
662901    0.707107
950331    0.000000
173141    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173187    0.000000
Name: 211085, dtype: float64

211148
user
4974      0.666667
950331    0.000000
173146    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
173218    0.000000
Name: 211148, dtype: float64

211542
user
350949    1.000000
211542    1.000000
7226      0.970143
179191    0.752577
108936    0.265513
724982    0.137767
950331    0.000000
173038    0.000000
173126    0.000000
Name: 211542, dtype: float64

211914
user
224545    0.492366
719811    0.492366
48814     0.492366
212395    0.492366
173796    0.492366
204033    0.492366
75174     0.492366
319979    0.492366
707460    0.492366
Name: 211914, dtype: float64

211949
user
295633    1.0
950331    0.0
172770    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
Name: 211949, dtype: float64

211972
user
459047    0.468293
715137    0.468293
192836    0.374634
596425    0.374634
814610    0.374634
186572    0.374634
923681    0.374634
44077     0.374634
257101    0.374634
Name: 211972, dtype: float64

211981
user
25840     0.187936
249051    0.140797
32143     0.069171
173126    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
950331    0.000000
Name: 211981, dtype: float64

212036
user
753519    0.529813
318884    0.529813

Name: 215860, dtype: float64

215917
user
136661    0.337869
194854    0.337869
30184     0.337869
835141    0.337869
820044    0.337869
815556    0.337869
782157    0.337869
739296    0.337869
524501    0.337869
Name: 215917, dtype: float64

215995
user
294245    0.424094
26888     0.424094
487400    0.339276
899670    0.339276
642291    0.339276
106216    0.339276
342978    0.339276
901025    0.339276
10762     0.339276
Name: 215995, dtype: float64

216052
user
132799    1.0
105855    1.0
196696    1.0
216052    1.0
26996     1.0
28644     1.0
197937    1.0
87286     1.0
359458    1.0
Name: 216052, dtype: float64

216288
user
308732    1.000000
216288    1.000000
333372    0.666667
682485    0.457496
391794    0.113410
173141    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
Name: 216288, dtype: float64

216435
user
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 216435, dtype: float64

216476
user
116524    0.435194
485567    0.102530
171678    0.000000
171853    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 216476, dtype: float64

216632
user
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 216632, dtype: float64

216642
user
218336    0.529813
133470    0.299707
30196     0.161124
252216    0.160660
177278    0.154975
385612    0.115960
103304    0.104632
53368     0.087695
213301    0.074028
Name: 216642, dtype: float64

216704
user
885428    0.780869
851090    0.624695
732125    0.624695
340105    0.624695
61770     0.624695
439187    0.624695
188061    0.624695
401305    0.558744
263524    0.499756
Name: 216704, dtype: float64

216874
user
216874    1.000000
70651     0.615457
831703    0.589768
784555    0.369274
46592     0.270914
215917    0.270295
172946    0.000000
172955    0.000000
173038    0.000000
Name: 216874, dtype: float64

217007
user
564331    1.0
217007    1.0
171636    0.0
171678    0.0
171582    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
Name: 217007, dtype: float64

217331
user
223211    0.894427
220647    0.447214
46154     0.356915
314389    0.197546
947671    0.149071
328775    0.063285
173236    0.000000
173218    0.000000
173187    0.000000
Name: 217331, dtype: float64

217350
user
45308     0.194772
74666     0.194772
321082    0.194772
107751    0.194772
834840    0.194772
282529    0.194772
110208    0.194772
51021     0.194772
163201    0.194772
Name: 217350, dtype: float64

217380
user
950331    0.0
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 217380, dtype: float64

217426
user
446157    0.57735
459734    0.57735
546902    0.57735
367815    0.57735
149217    0.46188
101449    0.46188
158717    0.46188
820044    0.46188
815556    0.46188
Name: 217426, dtype: float64

218336
user
133470    0.565685
216642    0.529813
30196     0.304114
252216    0.303239
177278    0.292509
385612    0.218870
53368     0.165521
213301    0.139724
173038    0.000000
Name: 218336, dtype: float64

218450
user
332593    0.577350
168899    0.577350
417312    0.577350
424678    0.408248
285213    0.408248
721055    0.408248
67245     0.355335
385138    0.326599
366772    0.235702
Name: 218450, dtype: float64

218451
user
218451    1.000000
190541    1.000000
193020    1.000000
320837    0.800000
137630    0.707107
932113    0.369274
247421    0.188044
724982    0.137767
173146    0.000000
Name: 218451, dtype: float64

218625
user
650202    0.399043
485567    0.181250
172589    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 218625, dtype: float64

218745
user
171582    0.577350
132873    0.466252
710291    0.350823
194387    0.305888
697977    0.285714
145101    0.219860
172955    0.000000
173038    0.000000
173126    0.000000
Name: 218745, dtype: float64

218901
user
913037    0.222171
262112    0.213785
173038    0.213785
67890     0.213785
158492    0.207003
448633    0.171028
606620    0.171028
703342    0.171028
74871     0.171028
Name: 218901, dtype: float64

219148
user
386287    0.780869
256392    0.780869
1557      0.780869
21052     0.780869
171329    0.780869
557732    0.780869
351769    0.780869
29192     0.624695
173796    0.624695
Name: 219148, dtype: float64

219166
user
108936    0.331891
950331    0.000000
172589    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 219166, dtype: float64

219293
user
71798     0.431934
397502    0.431934
551366    0.431934
759526    0.431934
557834    0.431934
96373     0.431934
290662    0.431934
893228    0.431934
864883    0.431934
Name: 219293, dtype: float64

219299
user
219299    1.000000
879835    1.000000
780657    1.000000
599892    1.000000
350912    0.780869
132734    0.624695
85808     0.408248
256163    0.133897
580520    0.130189
Name: 219299, dtype: float64

219406
user
219406    1.000000
879926    1.000000
833785    1.000000
480616    1.000000
463007    1.000000
250828    1.000000
551133    0.545545
135672    0.278207
283160    0.201008
Name: 219406, dtype: float64

219433
user
53433     0.780869
419560    0.390434
173126    0.000000
172589    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173146    0.000000
Name: 219433, dtype: float64

219458
user
51752     1.0
219458    1.0
199172    1.0
295792    1.0
261822    1.0
193795    1.0
260171    1.0
329184    1.0
365315    1.0
Name: 219458, dtype: float64

219577
user
775796    0.730297
169608    0.547723
648676    0.547723
46312     0.547723
599838    0.547723
582482    0.547723
87328     0.427699
732125    0.365148
439187    0.365148
Name: 219577, dtype: float64

219586
user
131154    1.0
114081    0.6
950331    0.0
173141    0.0
172946    0.0
172955    0.0
173038    0.0
173126    0.0
173187    0.0
Name: 219586, dtype: float64

219615
user
394415    1.000000
67485     1.000000
219615    1.000000
196448    0.596285
811088    0.369274
194387    0.305888
109622    0.258738
163884    0.237356
179727    0.132324
Name: 219615, dtype: float64

219678
user
950331    0.0
172490    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
173126    0.0
Name: 219678, dtype: float64

219760
user
219760    1.000000
794785    1.000000
23255     1.000000
358700    1.000000
792019    1.000000
506648    0.780869
598467    0.707107
848512    0.707107
149784    0.707107
Name: 219760, dtype: float64

219765
user
47493     0.331042
326587    0.331042
5036      0.331042
353901    0.331042
348141    0.331042
321549    0.331042
353565    0.234082
279303    0.234082
947671    0.193108
Name: 219765, dtype: float64

219792
user
776304    1.000000
219792    1.000000
217350    0.116863
172589    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 219792, dtype: float64

220047
user
220047    1.000000
402190    0.514496
173428    0.331295
220831    0.314485
652365    0.261116
950331    0.000000
172770    0.000000
172504    0.000000
172589    0.000000
Name: 220047, dtype: float64

220136
user
281748    0.707107
950331    0.000000
173141    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173146    0.000000
Name: 220136, dtype: float64

220389
user
135354    0.707107
247085    0.624695
950331    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
172504    0.000000
Name: 220389, dtype: float64

220647
user
217331    0.447214
314389    0.441726
947671    0.333333
328775    0.141510
173126    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173146    0.000000
Name: 220647, dtype: float64

220695
user
793074    0.650945
158492    0.508302
399142    0.431099
263894    0.431099
174466    0.406642
393981    0.344879
419534    0.328777
791637    0.319152
131485    0.302193
Name: 220695, dtype: float64

220731
user
365596    0.36823
172504    0.00000
173300    0.00000
173293    0.00000
173236    0.00000
173218    0.00000
173187    0.00000
173146    0.00000
173141    0.00000
Name: 220731, dtype: float64

220825
user
421743    1.000000
109581    0.512148
622936    0.512148
783730    0.512148
61776     0.512148
53332     0.512148
107059    0.512148
27962     0.512148
16096     0.384111
Name: 220825, dtype: float64

220831
user
64412     0.322587
249421    0.322587
220047    0.314485
158472    0.314485
3153      0.296500
173146    0.222158
402190    0.161801
190725    0.158486
184471    0.147150
Name: 220831, dtype: float64

220853
user
159381    0.565685
40447     0.565685
308373    0.424264
922940    0.424264
288121    0.424264
279375    0.424264
181135    0.424264
167525    0.424264
531322    0.282843
Name: 220853, dtype: float64

220866
user
806720    0.624695
950331    0.000000
172589    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
Name: 220866, dtype: float64

220887
user
220887    1.000000
814144    0.962250
101994    0.377964
132614    0.369274
17211     0.298142
51405     0.214423
43793     0.101274
215917    0.067574
172955    0.000000
Name: 220887, dtype: float64

221495
user
127689    0.707107
91136     0.577350
276312    0.226455
884890    0.130931
172770    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 221495, dtype: float64

221510
user
357985    0.707107
48442     0.707107
118351    0.525226
294618    0.500000
65621     0.441726
791637    0.346688
180539    0.316228
293161    0.310460
391017    0.194257
Name: 221510, dtype: float64

221747
user
254255    1.000000
616906    1.000000
797488    0.707107
152915    0.500000
316376    0.452267
312492    0.281439
632095    0.241747
350771    0.220193
173141    0.000000
Name: 221747, dtype: float64

221863
user
221863    1.0
950331    0.0
173415    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 221863, dtype: float64

222032
user
950331    0.0
172504    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
173126    0.0
Name: 222032, dtype: float64

222092
user
195083    1.000000
823508    1.000000
353976    1.000000
149737    1.000000
222092    1.000000
65345     1.000000
129294    0.707107
570294    0.650945
550554    0.554700
Name: 222092, dtype: float64

222193
user
193185    0.502395
355775    0.471405
29491     0.334771
875286    0.303046
614124    0.303046
61892     0.303046
224561    0.233285
514754    0.216930
609485    0.200697
Name: 222193, dtype: float64

222718
user
110811    0.270914
321619    0.270914
197904    0.232307
96722     0.203186
207711    0.203186
51496     0.203186
43065     0.203186
135062    0.176350
776175    0.162549
Name: 222718, dtype: float64

222975
user
22636     1.0
261654    1.0
222975    1.0
153678    1.0
321692    1.0
37980     1.0
780237    1.0
55705     1.0
194122    1.0
Name: 222975, dtype: float64

223011
user
950331    0.0
172504    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
173126    0.0
Name: 223011, dtype: float64

223096
user
711447    1.000000
129686    0.265489
173141    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
950331    0.000000
Name: 223096, dtype: float64

223211
user
217331    0.894427
46154     0.399043
172770    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 223211, dtype: float64

223400
user
786333    0.857493
846528    0.514496
840243    0.253320
730158    0.235380
638780    0.234529
537372    0.232689
31624     0.230089
51405     0.229832
132873    0.191908
Name: 223400, dtype: float64

223459
user
887956    0.569803
950331    0.000000
172504    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
Name: 223459, dtype: float64

223956
user
353565    0.707107
950331    0.000000
172770    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 223956, dtype: float64

224347
user
376636    0.279372
550105    0.279372
877370    0.279372
491073    0.279372
112180    0.279372
890873    0.279372
172955    0.279372
251629    0.279372
143267    0.279372
Name: 224347, dtype: float64

224377
user
336473    1.000000
397183    0.780869
193723    0.707107
26843     0.464238
164819    0.447214
48793     0.339276
816423    0.315000
2109      0.310460
108338    0.276172
Name: 224377, dtype: float64

224421
user
560061    0.624695
50758     0.624695
23999     0.624695
116524    0.307579
127843    0.250435
74527     0.217491
315409    0.195122
174016    0.192277
397119    0.182788
Name: 224421, dtype: float64

224545
user
319979    1.000000
212395    1.000000
284794    1.000000
280639    1.000000
173796    1.000000
412528    1.000000
111635    1.000000
29192     1.000000
70203     0.780869
Name: 224545, dtype: float64

224561
user
287964    0.577350
193185    0.495074
355775    0.384900
443344    0.295689
79647     0.240192
222193    0.233285
514754    0.221404
29491     0.212598
114074    0.135379
Name: 224561, dtype: float64

224630
user
950331    0.0
173415    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 224630, dtype: float64

224662
user
353104    1.000000
224662    1.000000
136730    1.000000
85149     1.000000
6899      1.000000
335411    1.000000
531388    0.928477
536176    0.780869
169956    0.707107
Name: 224662, dtype: float64

224755
user
695760    0.524142
367017    0.524142
361193    0.524142
668508    0.524142
201892    0.524142
282732    0.524142
29070     0.524142
113732    0.524142
93267     0.524142
Name: 224755, dtype: float64

224927
user
350965    0.339276
536176    0.264930
152915    0.169638
70333     0.162205
65483     0.143942
385612    0.092822
64301     0.069721
247421    0.063799
820908    0.062834
Name: 224927, dtype: float64

224934
user
291502    0.404061
744064    0.404061
442013    0.404061
281745    0.404061
23370     0.252415
502763    0.189311
292194    0.186628
140829    0.180702
752650    0.151428
Name: 224934, dtype: float64

225757
user
950331    0.0
173415    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 225757, dtype: float64

225769
user
950331    0.0
173415    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 225769, dtype: float64

225910
user
33053     0.499756
179544    0.441726
500373    0.441726
276191    0.441726
194777    0.331295
76564     0.331295
148169    0.331295
148777    0.331295
63763     0.331295
Name: 225910, dtype: float64

225985
user
178016    0.47036
950331    0.00000
173038    0.00000
172589    0.00000
172770    0.00000
172946    0.00000
172955    0.00000
173126    0.00000
172490    0.00000
Name: 225985, dtype: float64

226057
user
129160    0.780869
148797    0.624695
65483     0.441726
74751     0.282017
149300    0.213516
921028    0.177608
356471    0.154825
364545    0.111057
350771    0.085971
Name: 226057, dtype: float64

226070
user
215608    0.577350
728009    0.201948
247421    0.188044
103304    0.157991
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
172589    0.000000
Name: 226070, dtype: float64

226106
user
343630    0.392232
445293    0.392232
821511    0.392232
289156    0.392232
170852    0.392232
249802    0.313786
124281    0.294174
5995      0.294174
389704    0.294174
Name: 226106, dtype: float64

226339
user
132799    1.0
105855    1.0
196696    1.0
216052    1.0
26996     1.0
28644     1.0
197937    1.0
87286     1.0
359458    1.0
Name: 226339, dtype: float64

226488
user
950331    0.0
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 226488, dtype: float64

226606
user
392977    0.424264
135044    0.346410
593954    0.291386
820908    0.148159
171853    0.000000
171678    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
Name: 226606, dtype: float64

226757
user
54441     0.512148
212461    0.384111
150433    0.384111
173943    0.384111
57125     0.384111
149684    0.384111
129223    0.384111
195667    0.384111
292280    0.384111
Name: 226757, dtype: float64

227120
user
320723    0.492366
133270    0.369274
764772    0.284268
151201    0.261116
212036    0.260862
85615     0.224441
129831    0.213201
292085    0.163118
46987     0.163118
Name: 227120, dtype: float64

227237
user
735473    0.585206
320937    0.585206
173300    0.468165
150353    0.189167
470723    0.103558
390564    0.095124
884890    0.081730
194482    0.000000
173236    0.000000
Name: 227237, dtype: float64

227238
user
227238    1.0
950331    0.0
173141    0.0
172770    0.0
172946    0.0
172955    0.0
173038    0.0
173126    0.0
173187    0.0
Name: 227238, dtype: float64

227331
user
152413    0.552158
419505    0.552158
321283    0.552158
152603    0.441726
908860    0.441726
644110    0.441726
351982    0.441726
209415    0.441726
208774    0.441726
Name: 227331, dtype: float64

227388
user
227388    1.000000
85663     0.780869
361727    0.328798
175469    0.300000
169940    0.259161
173038    0.000000
173126    0.000000
173141    0.000000
173146    0.000000
Name: 227388, dtype: float64

227401
user
752281    1.000000
475240    1.000000
111719    1.000000
227401    1.000000
641062    1.000000
213776    1.000000
100771    1.000000
805528    0.707107
110095    0.707107
Name: 227401, dtype: float64

227462
user
88901     0.600000
5600      0.600000
151201    0.424264
373775    0.252646
156230    0.202721
646881    0.186276
446951    0.115470
70650     0.045356
593182    0.026388
Name: 227462, dtype: float64

227485
user
863840    1.000000
8055      1.000000
928303    1.000000
756238    1.000000
424498    1.000000
710581    0.894427
334520    0.707107
420344    0.707107
926948    0.707107
Name: 227485, dtype: float64

227541
user
921784    0.970143
190236    0.600000
132504    0.270765
283160    0.150756
173038    0.000000
172504    0.000000
172589    0.000000
172770    0.000000
172946    0.000000
Name: 227541, dtype: float64

228404
user
312492    0.211079
950331    0.000000
172589    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 228404, dtype: float64

229007
user
229007    1.000000
18966     1.000000
707972    0.707107
197504    0.417029
79647     0.416025
395948    0.296500
172946    0.000000
172955    0.000000
173038    0.000000
Name: 229007, dtype: float64

229208
user
398658    1.000000
44848     1.000000
229208    1.000000
43926     0.707107
389198    0.615457
173146    0.529813
350644    0.500000
359001    0.404061
72749     0.390360
Name: 229208, dtype: float64

229831
user
885428    0.375000
216704    0.292826
74618     0.225000
65483     0.212132
749783    0.171561
26843     0.139272
887400    0.125000
43325     0.115470
391957    0.114748
Name: 229831, dtype: float64

230190
user
882402    1.0
465152    1.0
43207     1.0
239439    1.0
648094    1.0
169215    1.0
2175      1.0
642214    1.0
230190    1.0
Name: 230190, dtype: float64

230207
user
328925    0.780869
710291    0.263117
950331    0.000000
172589    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
Name: 230207, dtype: float64

230662
user
305522    0.688303
418830    0.642857
179653    0.626295
677778    0.505076
46758     0.505076
422401    0.505076
321865    0.505076
254215    0.505076
539803    0.505076

Name: 246134, dtype: float64

246466
user
950331    0.0
172504    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
173126    0.0
Name: 246466, dtype: float64

246508
user
148748    0.662266
249570    0.328798
391794    0.085057
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
172504    0.000000
Name: 246508, dtype: float64

246534
user
213564    0.273434
745537    0.156412
53368     0.124141
950331    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
Name: 246534, dtype: float64

246545
user
22636     1.0
261654    1.0
222975    1.0
153678    1.0
321692    1.0
37980     1.0
780237    1.0
55705     1.0
194122    1.0
Name: 246545, dtype: float64

246758
user
950331    0.0
172490    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
173126    0.0
Name: 246758, dtype: float64

247028
user
247028    1.000000
26162     0.707107
745537    0.156412
950331    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
Name: 247028, dtype: float64

247060
user
24006     0.624695
861280    0.145962
173038    0.000000
172589    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173126    0.000000
172490    0.000000
Name: 247060, dtype: float64

247085
user
220389    0.624695
135354    0.441726
351825    0.315519
49999     0.315519
323570    0.310613
171853    0.000000
172589    0.000000
173300    0.000000
173293    0.000000
Name: 247085, dtype: float64

247129
user
317375    0.624695
745537    0.156412
950331    0.000000
172589    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
Name: 247129, dtype: float64

247348
user
59764     0.662266
537947    0.529813
149576    0.529813
362085    0.529813
809373    0.529813
775813    0.529813
12285     0.468293
388041    0.468293
522869    0.468293
Name: 247348, dtype: float64

247355
user
950331    0.0
172490    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
173126    0.0
Name: 247355, dtype: float64

247421
user
320837    0.263262
4347      0.224164
748583    0.188044
190541    0.188044
226070    0.188044
774737    0.188044
350778    0.188044
48814     0.188044
761773    0.188044
Name: 247421, dtype: float64

247634
user
386072    0.396526
798855    0.396526
470215    0.396526
159024    0.396526
261998    0.396526
282875    0.368165
114081    0.317221
770493    0.309635
389608    0.280386
Name: 247634, dtype: float64

247649
user
75794     0.486664
950331    0.000000
173141    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173146    0.000000
Name: 247649, dtype: float64

247685
user
71242     0.492366
724982    0.137767
172504    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
Name: 247685, dtype: float64

247859
user
24943     0.302614
880552    0.302614
72697     0.302614
360079    0.302614
5244      0.302614
321549    0.302614
410084    0.302614
426302    0.302614
128662    0.302614
Name: 247859, dtype: float64

248011
user
377537    0.435194
704888    0.435194
92831     0.435194
420587    0.435194
203647    0.435194
318073    0.435194
475865    0.435194
681355    0.348155
398867    0.339830
Name: 248011, dtype: float64

248016
user
169636    1.000000
495195    1.000000
314348    0.360668
264572    0.305888
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
Name: 248016, dtype: float64

248474
user
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
173126    0.0
Name: 248474, dtype: float64

248496
user
857499    0.589768
157659    0.529813
347289    0.500000
196412    0.500000
906552    0.363803
155100    0.357771
370681    0.289430
385612    0.218870
504746    0.215041
Name: 248496, dtype: float64

248522
user
248522    1.000000
620236    0.800000
46322     0.639602
257876    0.514496
641859    0.322078
686300    0.316228
256163    0.178529
950331    0.000000
173038    0.000000
Name: 248522, dtype: float64

248626
user
245621    1.0
314118    1.0
196360    1.0
248626    1.0
290161    1.0
738464    1.0
316074    1.0
442004    1.0
950331    0.0
Name: 248626, dtype: float64

248636
user
316768    1.0
695760    1.0
27939     1.0
50690     1.0
134761    1.0
50739     1.0
147932    1.0
29070     1.0
256789    1.0
Name: 248636, dtype: float64

248657
user
201575    0.707107
71242     0.492366
334694    0.357771
169940    0.345547
173146    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
Name: 248657, dtype: float64

248694
user
950331    0.0
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 248694, dtype: float64

248809
user
388198    1.000000
93563     0.269069
209755    0.215666
884890    0.174574
172589    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
950331    0.000000
Name: 248809, dtype: float64

249051
user
74904     0.265489
630504    0.234662
319753    0.234662
169608    0.234662
130789    0.234662
46312     0.234662
5995      0.234662
599838    0.234662
365420    0.234662
Name: 249051, dtype: float64

249391
user
97666     0.365148
630210    0.360060
919073    0.292119
157628    0.164317
917934    0.122474
322844    0.108821
87338     0.105409
91720     0.101031
89719     0.090729
Name: 249391, dtype: float64

249421
user
64412     0.378788
220831    0.322587
3882      0.295420
190725    0.186097
42484     0.182483
96360     0.171942
96575     0.167135
321572    0.159222
641859    0.126864
Name: 249421, dtype: float64

249441
user
621199    0.662266
470036    0.624695
389973    0.624695
49805     0.624695
609485    0.529813
156156    0.500000
658421    0.500000
1582      0.492366
29491     0.460287
Name: 249441, dtype: float64

249570
user
108884    0.410997
198167    0.410997
179544    0.328798
246508    0.328798
171153    0.272190
148748    0.217752
85331     0.207585
110348    0.202361
361309    0.197279
Name: 249570, dtype: float64

249572
user
283160    0.147828
950331    0.000000
172770    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 249572, dtype: float64

249595
user
803650    0.514496
493676    0.514496
130120    0.514496
360460    0.514496
434598    0.514496
65433     0.291043
401935    0.218282
245897    0.115771
237668    0.074394
Name: 249595, dtype: float64

249802
user
343630    0.800000
537282    0.600000
315596    0.461880
707972    0.452548
186982    0.436436
107593    0.325396
112229    0.317888
226106    0.313786
5015      0.312288
Name: 249802, dtype: float64

249880
user
177140    0.422577
20754     0.338062
288451    0.230535
131428    0.223887
30101     0.220059
63399     0.211185
388218    0.179109
283542    0.165203
459433    0.142350
Name: 249880, dtype: float64

250391
user
894693    0.624695
192676    0.311400
173415    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 250391, dtype: float64

250393
user
108692    0.680414
950331    0.000000
172504    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
Name: 250393, dtype: float64

250495
user
158717    0.230879
317949    0.230879
739296    0.230879
393032    0.230879
782157    0.230879
321000    0.230879
815556    0.230879
820044    0.230879
319105    0.230879
Name: 250495, dtype: float64

250513
user
309828    1.000000
250513    1.000000
461917    1.000000
105989    1.000000
197893    1.000000
63622     1.000000
252432    1.000000
721134    0.970143
721787    0.707107
Name: 250513, dtype: float64

250546
user
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 250546, dtype: float64

250560
user
24953     0.780869
674768    0.500000
133993    0.266880
90296     0.252478
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
Name: 250560, dtype: float64

250580
user
52424     0.390360
170611    0.292509
950331    0.000000
172770    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 250580, dtype: float64

250820
user
108666    0.400000
35172     0.400000
195653    0.368230
917504    0.353381
129831    0.326599
71232     0.299813
41555     0.273434
129316    0.270449
652898    0.268462
Name: 250820, dtype: float64

250828
user
219406    1.000000
879926    1.000000
833785    1.000000
480616    1.000000
463007    1.000000
250828    1.000000
551133    0.545545
135672    0.278207
283160    0.201008
Name: 250828, dtype: float64

251260
user
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 251260, dtype: float64

251266
user
855363    0.633677
112616    0.450835
107432    0.450835
47297     0.450835
158481    0.450835
66431     0.450835
774737    0.450835
504649    0.450835
85705     0.450835
Name: 251266, dtype: float64

251283
user
22074     1.000000
114146    1.000000
905082    0.707107
950331    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 251283, dtype: float64

251311
user
96722     0.492366
487327    0.492366
42615     0.492366
790296    0.492366
645667    0.492366
294354    0.492366
82581     0.492366
51496     0.492366
703432    0.492366
Name: 251311, dtype: float64

251361
user
361727    0.290619
159599    0.276026
246061    0.255822
600241    0.224309
190766    0.168742
67868     0.160128
284357    0.151402
218901    0.120935
132504    0.114876
Name: 251361, dtype: float64

251424
user
667504    1.000000
114961    1.000000
684910    0.505076
173126    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
950331    0.000000
Name: 251424, dtype: float64

251474
user
75433     0.374634
113970    0.374634
175320    0.374634
116307    0.374634
551587    0.374634
725466    0.374634
110348    0.368914
651501    0.367359
469418    0.337796
Name: 251474, dtype: float64

251567
user
198067    0.363696
232697    0.363696
23999     0.290957
359959    0.290957
261998    0.290957
560061    0.290957
50758     0.290957
798855    0.290957
470215    0.290957
Name: 251567, dtype: float64

251581
user
670976    0.431934
606979    0.431934
572599    0.431934
606826    0.386334
822237    0.345547
943069    0.345547
148723    0.345547
440081    0.345547
556845    0.345547
Name: 251581, dtype: float64

251629
user
890873    1.000000
537352    1.000000
251629    1.000000
949019    0.577350
856133    0.307148
194387    0.305888
224347    0.279372
568971    0.231455
745537    0.156412
Name: 251629, dtype: float64

251672
user
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 251672, dtype: float64

251729
user
106725    0.662266
709700    0.529813
899377    0.529813
200875    0.529813
42721     0.529813
8323      0.529813
501746    0.529813
87724     0.529813
757228    0.529813
Name: 251729, dtype: float64

251765
user
359399    0.410997
264539    0.410997
282427    0.410997
11194     0.328798
450355    0.328798
168468    0.328798
389100    0.328798
199091    0.320935
946575    0.256748
Name: 251765, dtype: float64

251960
user
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 251960, dtype: float64

252160
user
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 252160, dtype: float64

252207
user
72697     0.468165
3882      0.374532
5010      0.292460
31926     0.292460
135920    0.270295
85130     0.221187
710581    0.209370
157653    0.177745
359001    0.177344
Name: 252207, dtype: float64

252211
user
634851    0.857493
427974    0.606339
202112    0.363803
42484     0.317808
133400    0.169188
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 252211, dtype: float64

252216
user
148777    0.303239
194777    0.303239
63763     0.303239
148169    0.303239
940225    0.303239
76564     0.303239
44204     0.303239
388521    0.303239
256981    0.303239
Name: 252216, dtype: float64

252295
user
882402    0.639602
648094    0.639602
2175      0.639602
465152    0.639602
43207     0.639602
239439    0.639602
929369    0.639602
230190    0.639602
38120     0.639602
Name: 252295, dtype: float64

252323
user
857499    0.109517
950331    0.000000
172504    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
Name: 252323, dtype: float64

252394
user
356674    0.529813
351808    0.300000
950331    0.000000
173141    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173146    0.000000
Name: 252394, dtype: float64

252419
user
373622    0.606339
423159    0.562181
12285     0.428746
721787    0.257248
25840     0.051279
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
Name: 252419, dtype: float64

252432
user
309828    1.000000
250513    1.000000
461917    1.000000
105989    1.000000
197893    1.000000
63622     1.000000
252432    1.000000
721134    0.970143
721787    0.707107
Name: 252432, dtype: float64

252479
user
632095    0.322329
950331    0.000000
173126    0.000000
172589    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173141    0.000000
Name: 252479, dtype: float64

252491
user
8647      0.249029
728009    0.121169
950331    0.000000
173146    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
173187    0.000000
Name: 252491, dtype: float64

252541
user
283646    1.000000
252541    1.000000
716619    0.707107
173141    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
950331    0.000000
Name: 252541, dtype: float64

252583
user
283659    0.707107
513840    0.707107
88042     0.435194
328775    0.100063
950331    0.000000
173141    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
Name: 252583, dtype: float64

252734
user
149905    0.624695
482273    0.624695
281939    0.624695
67211     0.441726
153040    0.390244
397051    0.378777
201482    0.360668
665848    0.285795
95985     0.275944
Name: 252734, dtype: float64

252964
user
252964    1.000000
642291    1.000000
21351     1.000000
10762     1.000000
387303    0.529813
817844    0.514496
230662    0.404061
215995    0.339276
85688     0.268802
Name: 252964, dtype: float64

253041
user
703342    1.000000
627098    1.000000
253041    1.000000
729240    1.000000
27339     1.000000
360829    0.707107
269477    0.545545
65219     0.421076
172770    0.416025
Name: 253041, dtype: float64

253153
user
253154    1.000000
400110    0.707107
26450     0.707107
401104    0.707107
392903    0.707107
22268     0.552158
905460    0.500000
550014    0.490290
130006    0.374634
Name: 253153, dtype: float64

253154
user
253154    1.000000
400110    0.707107
26450     0.707107
401104    0.707107
392903    0.707107
22268     0.552158
905460    0.500000
550014    0.490290
130006    0.374634
Name: 253154, dtype: float64

253490
user
391631    0.180794
44923     0.179124
482273    0.150756
149905    0.150756
156230    0.122245
67211     0.106600
252734    0.094176
397051    0.091409
201482    0.087039
Name: 253490, dtype: float64

253720
user
107324    1.000000
561911    1.000000
148730    0.780869
636781    0.208514
173126    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
Name: 253720, dtype: float64

254149
user
665569    0.295141
5666      0.256600
175405    0.242091
516840    0.209020
103304    0.157991
173293    0.000000
173038    0.000000
172770    0.000000
172946    0.000000
Name: 254149, dtype: float64

254215
user
422401    1.000000
321865    1.000000
677778    1.000000
254215    1.000000
46758     1.000000
539803    1.000000
418830    0.707107
179653    0.600000
305522    0.524142
Name: 254215, dtype: float64

254239
user
328802    1.000000
73653     1.000000
400694    1.000000
162500    1.000000
254239    1.000000
65017     0.928477
147610    0.857493
891451    0.529813
319754    0.514496
Name: 254239, dtype: float64

254255
user
254255    1.000000
616906    1.000000
797488    0.707107
152915    0.500000
316376    0.452267
312492    0.281439
632095    0.241747
350771    0.220193
173141    0.000000
Name: 254255, dtype: float64

254431
user
254431    1.000000
89999     0.539164
357677    0.321288
646881    0.310460
288157    0.287242
85688     0.215041
950331    0.000000
172955    0.000000
173038    0.000000
Name: 254431, dtype: float64

254837
user
173141    1.000000
131540    1.000000
701499    1.000000
243313    0.371391
710618    0.291730
923208    0.284747
173146    0.000000
173187    0.000000
173218    0.000000
Name: 254837, dtype: float64

255093
user
70799     0.609994
128414    0.609994
54441     0.457496
648265    0.323498
208228    0.313839
71232     0.258637
65081     0.242387
354874    0.235380
226757    0.234305
Name: 255093, dtype: float64

255258
user
786717    0.328798
502484    0.328798
401104    0.328798
596425    0.328798
814610    0.328798
400110    0.328798
147193    0.328798
26450     0.328798
186572    0.328798
Name: 255258, dtype: float64

255287
user
151661    0.707107
60853     0.707107
841437    0.707107
31926     0.552158
32306     0.408248
476834    0.363803
157653    0.335578
923459    0.234146
5142      0.231455
Name: 255287, dtype: float64

255464
user
132799    1.0
105855    1.0
196696    1.0
216052    1.0
26996     1.0
28644     1.0
197937    1.0
87286     1.0
359458    1.0
Name: 255464, dtype: float64

256001
user
256001    1.000000
400150    1.000000
885234    1.000000
180718    0.800000
688990    0.577350
159313    0.520756
308702    0.323423
360130    0.250490
572720    0.242983
Name: 256001, dtype: float64

256038
user
950331    0.0
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 256038, dtype: float64

256163
user
411020    0.223161
191321    0.191359
138663    0.180379
133997    0.178529
57262     0.178529
562349    0.178529
388333    0.178529
14959     0.178529
47528     0.178529
Name: 256163, dtype: float64

256176
user
256176    1.000000
589791    0.617213
31624     0.447214
173126    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173141    0.000000
172589    0.000000
Name: 256176, dtype: float64

256181
user
512463    1.000000
360381    0.577350
314366    0.461880
5142      0.436436
72849     0.334825
237668    0.180746
172946    0.000000
172955    0.000000
173038    0.000000
Name: 256181, dtype: float64

256325
user
794785    0.229794
49742     0.229794
696769    0.229794
318671    0.229794
219760    0.229794
168976    0.229794
201157    0.229794
792019    0.229794
353069    0.229794
Name: 256325, dtype: float64

256332
user
321677    0.552158
180541    0.350823
173415    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 256332, dtype: float64

256348
user
94677     0.511718
176544    0.441726
198226    0.331295
109752    0.265036
328899    0.234261
133993    0.070733
173146    0.000000
172955    0.000000
173038    0.000000
Name: 256348, dtype: float64

256392
user
386287    1.000000
171329    1.000000
351769    1.000000
1557      1.000000
21052     1.000000
557732    1.000000
219148    0.780869
392992    0.615457
684910    0.404061

user
316443    0.544331
499267    0.544331
326578    0.544331
48295     0.408248
88424     0.408248
449148    0.384900
9895      0.335013
137065    0.318788
315596    0.314270
Name: 261456, dtype: float64

261654
user
22636     1.0
261654    1.0
222975    1.0
153678    1.0
321692    1.0
37980     1.0
780237    1.0
55705     1.0
194122    1.0
Name: 261654, dtype: float64

261659
user
269130    0.857493
168468    0.514496
197936    0.241052
251765    0.169165
728009    0.062341
173146    0.000000
173141    0.000000
173126    0.000000
172504    0.000000
Name: 261659, dtype: float64

261748
user
922940    0.615457
279375    0.615457
288121    0.615457
308373    0.615457
181135    0.615457
167525    0.615457
108796    0.492366
129947    0.492366
613864    0.492366
Name: 261748, dtype: float64

261757
user
484341    1.000000
314531    0.431934
424678    0.424264
224347    0.279372
364545    0.177778
328775    0.141510
171636    0.000000
173146    0.000000
173038    0.000000
Name: 261757, dtype: float64

261822
user
51752     1.0
219458    1.0
199172    1.0
295792    1.0
261822    1.0
193795    1.0
260171    1.0
329184    1.0
365315    1.0
Name: 261822, dtype: float64

261984
user
908867    0.371391
85694     0.357771
950331    0.000000
172770    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 261984, dtype: float64

261998
user
798855    1.000000
261998    1.000000
282875    0.928477
114081    0.800000
770493    0.780869
389608    0.707107
887586    0.554700
247634    0.396526
68203     0.390567
Name: 261998, dtype: float64

262002
user
82914     0.363803
47478     0.363803
147927    0.257248
247859    0.234863
92767     0.205798
855589    0.200877
88316     0.193908
279652    0.153189
284695    0.136818
Name: 262002, dtype: float64

262112
user
262112    1.000000
173038    1.000000
913037    0.577350
85626     0.492366
218901    0.213785
64301     0.205499
728009    0.121169
172770    0.000000
172946    0.000000
Name: 262112, dtype: float64

262368
user
136661    0.438529
835141    0.438529
820044    0.438529
815556    0.438529
319105    0.438529
194854    0.438529
524501    0.438529
393032    0.438529
465115    0.438529
Name: 262368, dtype: float64

263360
user
263360    1.000000
510431    0.470360
459433    0.336861
153457    0.263890
950331    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
Name: 263360, dtype: float64

263524
user
851090    0.800000
439187    0.800000
61770     0.800000
340105    0.800000
188061    0.800000
732125    0.800000
401305    0.715542
28032     0.640000
744990    0.640000
Name: 263524, dtype: float64

263894
user
793074    0.662266
72699     0.529813
446105    0.529813
113066    0.529813
42450     0.529813
158492    0.517143
399142    0.438596
220695    0.431099
174466    0.413714
Name: 263894, dtype: float64

264539
user
282427    1.000000
264539    1.000000
574807    0.600000
243313    0.464238
251765    0.410997
950331    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
Name: 264539, dtype: float64

264572
user
780237    0.305888
746       0.305888
153678    0.305888
261654    0.305888
321692    0.305888
245798    0.305888
8338      0.305888
37980     0.305888
248016    0.305888
Name: 264572, dtype: float64

264581
user
284695    0.225647
950331    0.000000
172589    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 264581, dtype: float64

264944
user
264944    1.000000
4668      1.000000
946652    1.000000
75468     1.000000
260632    1.000000
937146    0.447214
173126    0.000000
172946    0.000000
172955    0.000000
Name: 264944, dtype: float64

265934
user
950331    0.0
172490    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
173126    0.0
Name: 265934, dtype: float64

266792
user
950331    0.0
172490    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
173126    0.0
Name: 266792, dtype: float64

267306
user
487400    1.000000
159773    1.000000
342978    1.000000
106216    1.000000
899670    1.000000
267306    1.000000
203033    1.000000
177362    0.970143
135354    0.707107
Name: 267306, dtype: float64

268107
user
286962    1.000000
268107    1.000000
899799    0.707107
33179     0.544331
85626     0.492366
855589    0.441726
171967    0.327693
179719    0.308607
665569    0.295141
Name: 268107, dtype: float64

269130
user
261659    0.857493
950331    0.000000
172504    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
Name: 269130, dtype: float64

269477
user
729240    0.545545
322689    0.545545
253041    0.545545
471179    0.545545
606620    0.545545
386149    0.545545
43128     0.545545
27339     0.545545
327506    0.545545
Name: 269477, dtype: float64

269509
user
885332    0.495434
288030    0.447214
318198    0.447214
818821    0.447214
397753    0.447214
171136    0.447214
696729    0.447214
793692    0.447214
459702    0.447214
Name: 269509, dtype: float64

269788
user
325654    0.857493
364818    0.857493
33179     0.583450
664138    0.495074
510431    0.403331
154501    0.311045
314348    0.309270
401684    0.241189
315462    0.229832
Name: 269788, dtype: float64

270590
user
339218    1.000000
288042    1.000000
270590    1.000000
535452    0.624695
319153    0.239046
862633    0.196116
250495    0.184703
173038    0.000000
173126    0.000000
Name: 270590, dtype: float64

270595
user
270595    1.000000
116734    1.000000
79511     1.000000
361531    1.000000
882571    0.542326
924558    0.390360
87153     0.350823
173187    0.000000
172770    0.000000
Name: 270595, dtype: float64

271060
user
169063    0.499756
716619    0.441726
287074    0.390244
419560    0.146341
64301     0.128374
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 271060, dtype: float64

271634
user
950331    0.0
172504    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
173126    0.0
Name: 271634, dtype: float64

272301
user
921150    1.000000
798609    0.404061
600241    0.317221
145101    0.219860
284357    0.214115
391794    0.113410
173187    0.000000
173218    0.000000
173236    0.000000
Name: 272301, dtype: float64

272354
user
272354    1.000000
568330    0.624695
20363     0.205196
900562    0.197814
921028    0.181959
469245    0.171701
172955    0.000000
173038    0.000000
173126    0.000000
Name: 272354, dtype: float64

273043
user
190972    0.707107
112416    0.363803
399680    0.299880
2109      0.219529
702417    0.218870
176544    0.000000
173187    0.000000
176665    0.000000
173146    0.000000
Name: 273043, dtype: float64

273350
user
356593    0.615457
461242    0.615457
282529    0.615457
289483    0.355335
93647     0.348155
784555    0.303030
116780    0.271864
71232     0.260953
127617    0.203742
Name: 273350, dtype: float64

274267
user
194342    0.57735
277858    0.57735
67429     0.57735
72150     0.57735
389047    0.57735
85315     0.57735
350778    0.57735
332711    0.57735
159824    0.57735
Name: 274267, dtype: float64

274810
user
3123      1.000000
274810    1.000000
314010    1.000000
164819    0.894427
448451    0.468165
632495    0.404061
175356    0.000000
172339    0.000000
173146    0.000000
Name: 274810, dtype: float64

275243
user
54805     1.000000
284374    0.707107
172770    0.693375
193549    0.435194
315409    0.390434
194387    0.382360
127617    0.331042
305856    0.324443
365596    0.276172
Name: 275243, dtype: float64

275746
user
409694    1.000000
11951     0.279372
105881    0.218218
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
172589    0.000000
173187    0.000000
Name: 275746, dtype: float64

276191
user
225910    0.441726
593182    0.131940
173141    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
950331    0.000000
Name: 276191, dtype: float64

276312
user
782157    0.226455
835141    0.226455
393032    0.226455
2849      0.226455
132641    0.226455
136661    0.226455
30184     0.226455
327668    0.226455
321000    0.226455
Name: 276312, dtype: float64

276515
user
341578    1.0
172770    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 276515, dtype: float64

276610
user
70333     0.332923
510431    0.104812
950331    0.000000
173141    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173187    0.000000
Name: 276610, dtype: float64

277258
user
277258    1.000000
740367    0.707107
678384    0.387298
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
173146    0.000000
950331    0.000000
Name: 277258, dtype: float64

277858
user
389047    1.0
558567    1.0
277858    1.0
256861    1.0
159824    1.0
67429     1.0
106580    1.0
72150     1.0
726820    1.0
Name: 277858, dtype: float64

278067
user
276312    0.160128
148254    0.109109
173300    0.000000
173293    0.000000
173236    0.000000
173325    0.000000
173218    0.000000
172589    0.000000
173187    0.000000
Name: 278067, dtype: float64

279238
user
262368    0.438529
950331    0.000000
172504    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
Name: 279238, dtype: float64

279303
user
181027    0.707107
321549    0.707107
6574      0.707107
611186    0.707107
192257    0.707107
353565    0.500000
286366    0.408248
319153    0.253546
219765    0.234082
Name: 279303, dtype: float64

279375
user
279375    1.000000
308373    1.000000
288121    1.000000
167525    1.000000
181135    1.000000
261748    0.615457
256985    0.600000
129316    0.597614
85808     0.544331
Name: 279375, dtype: float64

279615
user
314217    0.354298
64762     0.306570
618544    0.306570
305319    0.306570
383336    0.306570
232697    0.306570
794560    0.306570
356471    0.246177
148169    0.245256
Name: 279615, dtype: float64

279618
user
950331    0.0
173415    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 279618, dtype: float64

279641
user
936844    0.780869
90754     0.228292
950331    0.000000
173141    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173146    0.000000
Name: 279641, dtype: float64

279652
user
82914     0.421076
47478     0.421076
123336    0.421076
670976    0.336861
606979    0.336861
606826    0.301297
147927    0.297746
240289    0.252646
72531     0.252646
Name: 279652, dtype: float64

279778
user
293161    0.310460
8647      0.176090
74999     0.171184
30196     0.161281
132504    0.153168
950331    0.000000
173187    0.000000
173038    0.000000
173126    0.000000
Name: 279778, dtype: float64

279785
user
500916    0.290129
791844    0.290129
387478    0.290129
360002    0.290129
14914     0.232104
885308    0.232104
327468    0.232104
804396    0.232104
45370     0.232104
Name: 279785, dtype: float64

279865
user
950331    0.0
173415    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 279865, dtype: float64

279978
user
45308     1.000000
74666     1.000000
107751    1.000000
279978    1.000000
24006     0.780869
358118    0.707107
3153      0.707107
29563     0.624695
28330     0.600000
Name: 279978, dtype: float64

280011
user
534551    0.857493
665344    0.707107
890235    0.615457
745622    0.544331
85694     0.447214
189901    0.427179
68632     0.201456
173141    0.000000
173126    0.000000
Name: 280011, dtype: float64

280081
user
285457    0.707107
148115    0.707107
178745    0.707107
3629      0.424264
138572    0.363803
177951    0.357143
29491     0.325472
158711    0.291606
211972    0.264906
Name: 280081, dtype: float64

280132
user
72764     0.577350
362085    0.577350
809373    0.577350
194941    0.408248
308086    0.384900
386517    0.346410
664138    0.333333
215649    0.318788
247348    0.305888
Name: 280132, dtype: float64

280475
user
950331    0.0
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 280475, dtype: float64

280573
user
810011    0.301511
876575    0.301511
692540    0.301511
669370    0.295656
325034    0.188353
688620    0.148454
350644    0.120605
906552    0.109691
184471    0.105810
Name: 280573, dtype: float64

280639
user
319979    1.000000
212395    1.000000
284794    1.000000
280639    1.000000
173796    1.000000
412528    1.000000
111635    1.000000
29192     1.000000
70203     0.780869
Name: 280639, dtype: float64

280698
user
87724     0.707107
8323      0.707107
501746    0.707107
709700    0.707107
42721     0.707107
757228    0.707107
899377    0.707107
200875    0.707107
470673    0.565685
Name: 280698, dtype: float64

280787
user
213564    0.273434
172504    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
Name: 280787, dtype: float64

280795
user
950331    0.0
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 280795, dtype: float64

280826
user
899381    0.577350
334694    0.206559
288157    0.165840
179727    0.101863
315462    0.092848
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 280826, dtype: float64

280855
user
745622    0.544331
811088    0.492366
128271    0.396526
89781     0.371391
372209    0.320092
356252    0.319235
173141    0.000000
172955    0.000000
173038    0.000000
Name: 280855, dtype: float64

280872
user
597752    0.624695
109583    0.624695
642082    0.624695
322597    0.200707
705731    0.168852
504746    0.134335
814144    0.120223
215042    0.063675
175043    0.000000
Name: 280872, dtype: float64

280902
user
838134    1.000000
4891      1.000000
6791      1.000000
793871    1.000000
945633    1.000000
288137    1.000000
686161    1.000000
75794     0.648886
906467    0.624695
Name: 280902, dtype: float64

280976
user
96856     1.000000
724982    0.137767
728009    0.121169
172589    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 280976, dtype: float64

280981
user
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 280981, dtype: float64

280983
user
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
173126    0.0
Name: 280983, dtype: float64

281732
user
700993    1.000000
776502    1.000000
894693    0.780869
26162     0.707107
196412    0.500000
211039    0.374634
788114    0.277350
194979    0.190500
745537    0.156412
Name: 281732, dtype: float64

281745
user
281745    1.000000
292194    0.461880
224934    0.404061
173141    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
950331    0.000000
Name: 281745, dtype: float64

281748
user
220136    0.707107
28339     0.296500
252216    0.268028
130044    0.254989
861280    0.103211
172955    0.000000
172589    0.000000
172770    0.000000
172946    0.000000
Name: 281748, dtype: float64

281932
user
559832    0.707107
44555     0.468293
501799    0.408248
351878    0.393919
616058    0.341793
823651    0.262613
314604    0.248282
155466    0.246183
308702    0.137217
Name: 281932, dtype: float64

281939
user
153040    0.624695
252734    0.624695
665848    0.457496
282032    0.408248
133993    0.213504
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
Name: 281939, dtype: float64

282032
user
214780    0.408248
281939    0.408248
445567    0.408248
837685    0.408248
44853     0.277778
182       0.270369
398867    0.255031
153040    0.255031
252734    0.255031
Name: 282032, dtype: float64

282047
user
562381    0.577350
950331    0.577350
197504    0.300965
347289    0.288675
290423    0.244851
213301    0.134449
593182    0.126959
173236    0.000000
173218    0.000000
Name: 282047, dtype: float64

282218
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 282218, dtype: float64

282336
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 282336, dtype: float64

282426
user
914284    0.3
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 282426, dtype: float64

282427
user
282427    1.000000
264539    1.000000
574807    0.600000
243313    0.464238
251765    0.410997
950331    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
Name: 282427, dtype: float64

282529
user
461242    1.000000
282529    1.000000
273350    0.615457
289483    0.577350
93647     0.565685
784555    0.492366
116780    0.441726
71232     0.423999
127617    0.331042
Name: 282529, dtype: float64

282534
user
256395    0.780869
630195    0.780869
924719    0.780869
2368      0.698430
302395    0.552158
881353    0.450835
284839    0.450835
283160    0.282529
4629      0.232810
Name: 282534, dtype: float64

282575
user
355767    0.435194
687969    0.326599
180519    0.304997
68122     0.264906
95336     0.192450
179727    0.124757
950331    0.000000
173126    0.000000
173141    0.000000
Name: 282575, dtype: float64

282732
user
316768    1.0
695760    1.0
27939     1.0
50690     1.0
134761    1.0
50739     1.0
147932    1.0
29070     1.0
256789    1.0
Name: 282732, dtype: float64

282857
user
674747    1.0
173415    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 282857, dtype: float64

282864
user
950331    0.0
173421    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 282864, dtype: float64

282875
user
470215    0.928477
261998    0.928477
798855    0.928477
114081    0.742781
770493    0.725018
389608    0.656532
887586    0.515026
87724     0.371391
200875    0.371391
Name: 282875, dtype: float64

282957
user
950331    0.0
173421    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 282957, dtype: float64

283160
user
282534    0.282529
53332     0.251259
622936    0.251259
61776     0.251259
879926    0.201008
2131      0.201008
10598     0.201008
287964    0.201008
463007    0.201008
Name: 283160, dtype: float64

283360
user
551366    0.577350
71798     0.577350
356575    0.450835
382866    0.408248
157653    0.273998
85130     0.272772
219293    0.249377
48793     0.244851
365596    0.212598
Name: 283360, dtype: float64

283383
user
283383    1.0
950331    0.0
173421    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
Name: 283383, dtype: float64

283386
user
154154    0.780869
150433    0.780869
292280    0.780869
129223    0.780869
212461    0.780869
149684    0.780869
57125     0.780869
195667    0.780869
173943    0.780869
Name: 283386, dtype: float64

283440
user
950331    0.0
173421    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 283440, dtype: float64

283542
user
501746    0.488678
709700    0.488678
757228    0.488678
42721     0.488678
8323      0.488678
87724     0.488678
200875    0.488678
899377    0.488678
470673    0.390942
Name: 283542, dtype: float64

283646
user
283646    1.000000
252541    1.000000
716619    0.707107
173141    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
950331    0.000000
Name: 283646, dtype: float64

283659
user
513840    1.000000
252583    0.707107
88042     0.615457
950331    0.000000
173126    0.000000
172946    0.000000

user
279375    1.000000
308373    1.000000
288121    1.000000
167525    1.000000
181135    1.000000
261748    0.615457
256985    0.600000
129316    0.597614
85808     0.544331
Name: 288121, dtype: float64

288137
user
838134    1.000000
4891      1.000000
6791      1.000000
793871    1.000000
945633    1.000000
288137    1.000000
686161    1.000000
75794     0.648886
906467    0.624695
Name: 288137, dtype: float64

288138
user
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 288138, dtype: float64

288157
user
446157    0.287242
127163    0.287242
191191    0.287242
546902    0.287242
254431    0.287242
179325    0.287242
921446    0.287242
367815    0.287242
899381    0.287242
Name: 288157, dtype: float64

288190
user
288190    1.000000
149300    0.341793
385612    0.164153
950331    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
Name: 288190, dtype: float64

288222
user
906243    0.707107
23533     0.707107
317949    0.707107
194854    0.707107
930037    0.707107
158717    0.707107
820044    0.707107
465115    0.707107
177065    0.707107
Name: 288222, dtype: float64

288240
user
87516     0.308607
390006    0.308607
1409      0.308607
326545    0.308607
321594    0.308607
170923    0.308607
314002    0.302614
745127    0.192785
71245     0.171184
Name: 288240, dtype: float64

288312
user
130789    0.554700
127106    0.554700
290423    0.352868
56796     0.320256
395537    0.203302
73577     0.193739
391957    0.169736
395948    0.164468
26843     0.154508
Name: 288312, dtype: float64

288451
user
47297     0.545545
107432    0.545545
85705     0.545545
158481    0.545545
177140    0.545545
112616    0.545545
504649    0.545545
874578    0.534951
425396    0.529256
Name: 288451, dtype: float64

288873
user
677551    0.707107
213740    0.707107
66608     0.707107
173236    0.707107
867166    0.441726
698792    0.441726
192437    0.358569
198312    0.300000
851312    0.196116
Name: 288873, dtype: float64

289156
user
170852    1.000000
289156    1.000000
74904     0.707107
215860    0.707107
133983    0.700140
93992     0.685994
213694    0.624695
886698    0.600000
153279    0.577350
Name: 289156, dtype: float64

289279
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 289279, dtype: float64

289483
user
461242    0.577350
356593    0.577350
282529    0.577350
273350    0.355335
93647     0.326599
784555    0.284268
116780    0.255031
71232     0.244796
127617    0.191127
Name: 289483, dtype: float64

289531
user
112616    0.696311
107432    0.696311
85705     0.696311
158481    0.696311
47297     0.696311
504649    0.696311
874578    0.682789
855363    0.543727
192236    0.543727
Name: 289531, dtype: float64

290161
user
245621    1.0
314118    1.0
196360    1.0
248626    1.0
290161    1.0
738464    1.0
316074    1.0
442004    1.0
950331    0.0
Name: 290161, dtype: float64

290423
user
950331    0.424094
562381    0.424094
45482     0.424094
288312    0.352868
199202    0.339276
197460    0.339276
282047    0.244851
347289    0.212047
151373    0.211944
Name: 290423, dtype: float64

290485
user
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 290485, dtype: float64

290566
user
50713     0.800000
321581    0.800000
501275    0.369274
789207    0.361814
84840     0.353009
71595     0.346410
130558    0.312288
459433    0.269489
399680    0.203565
Name: 290566, dtype: float64

290659
user
355931    1.0
950331    0.0
172770    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
Name: 290659, dtype: float64

290662
user
864883    1.000000
893228    1.000000
290662    1.000000
759526    1.000000
918040    0.455842
173428    0.441726
219293    0.431934
73273     0.372678
395948    0.370625
Name: 290662, dtype: float64

290704
user
574807    0.800000
31285     0.304114
42484     0.296500
820908    0.246932
186286    0.160357
32143     0.138343
171871    0.000000
171678    0.000000
173293    0.000000
Name: 290704, dtype: float64

290708
user
19325     1.000000
290708    1.000000
129333    0.099504
950331    0.000000
172946    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
Name: 290708, dtype: float64

290744
user
115682    0.368230
845485    0.256074
950331    0.000000
172589    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 290744, dtype: float64

291126
user
419534    0.505076
728009    0.121169
950331    0.000000
173141    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173146    0.000000
Name: 291126, dtype: float64

291502
user
442013    1.000000
140829    0.447214
224934    0.404061
950331    0.000000
173141    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
Name: 291502, dtype: float64

291540
user
250495    0.138527
950331    0.000000
172770    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 291540, dtype: float64

291704
user
740123    1.0
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 291704, dtype: float64

292003
user
87338     0.544331
554398    0.500000
732073    0.363803
950331    0.000000
173141    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
Name: 292003, dtype: float64

292049
user
76488     0.270914
950331    0.000000
172770    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 292049, dtype: float64

292085
user
481628    0.535672
138572    0.473471
936541    0.441726
591369    0.441726
133270    0.441726
95763     0.441726
96613     0.441726
562349    0.441726
930847    0.390434
Name: 292085, dtype: float64

292194
user
902808    0.577350
394365    0.577350
427412    0.577350
476834    0.495074
5710      0.461880
744064    0.461880
281745    0.461880
48786     0.346410
85601     0.346410
Name: 292194, dtype: float64

292280
user
212461    1.000000
129223    1.000000
173943    1.000000
57125     1.000000
150433    1.000000
195667    1.000000
292280    1.000000
149684    1.000000
283386    0.780869
Name: 292280, dtype: float64

292753
user
821502    0.707107
370833    0.632456
861992    0.435194
111904    0.326599
173126    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173141    0.000000
Name: 292753, dtype: float64

292967
user
132504    0.216612
114074    0.175863
173146    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
950331    0.000000
172946    0.000000
Name: 292967, dtype: float64

293073
user
455886    1.000000
821860    0.424264
179727    0.132324
950331    0.000000
173325    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 293073, dtype: float64

293102
user
521321    0.948683
461939    0.948683
656737    0.948683
321090    0.948683
830007    0.346410
7467      0.316228
572720    0.288142
818006    0.173931
391794    0.080692
Name: 293102, dtype: float64

293161
user
48442     0.439057
357985    0.439057
198167    0.329293
118351    0.326123
294618    0.310460
279778    0.310460
221510    0.310460
65621     0.274277
808968    0.263434
Name: 293161, dtype: float64

293300
user
389037    0.624695
46255     0.624695
327434    0.624695
399266    0.390244
851312    0.346518
882082    0.307579
361582    0.166585
8647      0.155567
728009    0.100925
Name: 293300, dtype: float64

293382
user
131358    0.447270
2849      0.431331
161783    0.431331
896394    0.431331
400268    0.345065
763520    0.323498
778423    0.269167
393981    0.228525
367228    0.221918
Name: 293382, dtype: float64

293480
user
950331    0.0
172770    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 293480, dtype: float64

294245
user
26888     1.000000
24325     0.500000
215995    0.424094
950331    0.000000
172946    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
Name: 294245, dtype: float64

294292
user
215042    0.254824
250495    0.230879
950331    0.000000
173415    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 294292, dtype: float64

294354
user
82581     1.0
487327    1.0
652607    1.0
42615     1.0
7488      1.0
721140    1.0
645667    1.0
664747    1.0
192450    1.0
Name: 294354, dtype: float64

294618
user
194854    0.707107
158717    0.707107
835141    0.707107
820044    0.707107
524501    0.707107
357985    0.707107
465115    0.707107
393032    0.707107
317949    0.707107
Name: 294618, dtype: float64

294688
user
950331    0.0
172770    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 294688, dtype: float64

294912
user
950331    0.0
172770    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 294912, dtype: float64

295633
user
295633    1.0
950331    0.0
172770    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
Name: 295633, dtype: float64

295763
user
129098    1.000000
840877    1.000000
551576    1.000000
444370    0.707107
28304     0.624695
50137     0.624695
92767     0.424264
127843    0.400892
652898    0.284747
Name: 295763, dtype: float64

295792
user
51752     1.0
219458    1.0
199172    1.0
295792    1.0
261822    1.0
193795    1.0
260171    1.0
329184    1.0
365315    1.0
Name: 295792, dtype: float64

296014
user
31000     0.514496
48740     0.514496
138698    0.514496
697629    0.514496
256643    0.514496
171046    0.514496
109566    0.514496
354616    0.514496
328852    0.514496
Name: 296014, dtype: float64

296122
user
603829    0.707107
950331    0.000000
173126    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173141    0.000000
172504    0.000000
Name: 296122, dtype: float64

296331
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 296331, dtype: float64

296334
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 296334, dtype: float64

296695
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 296695, dtype: float64

298395
user
31984     0.505076
191363    0.505076
74904     0.357143
244670    0.285714
2847      0.248682
180519    0.217855
177951    0.204082
2109      0.196008
46560     0.169112
Name: 298395, dtype: float64

298886
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 298886, dtype: float64

300319
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 300319, dtype: float64

300358
user
462894    0.928477
143948    0.492366
70779     0.215945
63246     0.140028
173187    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
173146    0.000000
Name: 300358, dtype: float64

300846
user
201564    0.468165
48814     0.468165
944394    0.468165
719811    0.468165
853410    0.468165
622340    0.468165
707460    0.468165
748583    0.468165
204033    0.468165
Name: 300846, dtype: float64

302395
user
131822    0.707107
924719    0.707107
630195    0.707107
256395    0.707107
2368      0.632456
282534    0.552158
881353    0.408248
284839    0.408248
4629      0.210819
Name: 302395, dtype: float64

302442
user
582183    1.000000
195632    1.000000
260179    1.000000
811088    0.492366
1582      0.369274
29491     0.368230
159353    0.266667
114074    0.117242
950331    0.000000
Name: 302442, dtype: float64

303258
user
45410     1.000000
768680    1.000000
836071    0.780869
179727    0.132324
173146    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
Name: 303258, dtype: float64

303477
user
172770    0.0
173415    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 303477, dtype: float64

303595
user
179325    1.000000
127163    1.000000
823651    0.928477
692299    0.707107
307072    0.707107
534410    0.373002
935084    0.370625
138679    0.340207
288157    0.287242
Name: 303595, dtype: float64

303924
user
485651    1.000000
386315    0.707107
171636    0.000000
172946    0.000000
171582    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
Name: 303924, dtype: float64

305160
user
546256    0.577350
114074    0.293105
173415    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 305160, dtype: float64

305319
user
383336    1.000000
279615    0.306570
356471    0.247841
173415    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 305319, dtype: float64

305395
user
112416    0.857493
559469    0.780869
435544    0.624695
159353    0.133333
194393    0.000000
173300    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 305395, dtype: float64

305522
user
418830    0.741249
179653    0.733799
230662    0.688303
422401    0.524142
539803    0.524142
86501     0.524142
46758     0.524142
254215    0.524142
410904    0.524142
Name: 305522, dtype: float64

305856
user
72531     0.405554
240289    0.405554
151203    0.324443
267306    0.324443
203033    0.324443
140931    0.324443
54805     0.324443
460437    0.324443
487400    0.324443
Name: 305856, dtype: float64

306746
user
306746    1.0
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 306746, dtype: float64

307072
user
303595    0.707107
179325    0.707107
127163    0.707107
823651    0.656532
692299    0.500000
534410    0.263752
935084    0.262071
138679    0.240563
288157    0.203111
Name: 307072, dtype: float64

308086
user
362085    0.666667
809373    0.666667
194941    0.471405
280132    0.384900
664138    0.384900
215649    0.368105
247348    0.353209
131428    0.353209
259023    0.342997
Name: 308086, dtype: float64

308373
user
279375    1.000000
308373    1.000000
288121    1.000000
167525    1.000000
181135    1.000000
261748    0.615457
256985    0.600000
129316    0.597614
85808     0.544331
Name: 308373, dtype: float64

308702
user
427422    0.363673
200875    0.323423
256001    0.323423
358746    0.323423
8323      0.323423
899377    0.323423
885234    0.323423
621501    0.323423
757228    0.323423
Name: 308702, dtype: float64

308732
user
308732    1.000000
216288    1.000000
333372    0.666667
682485    0.457496
391794    0.113410
173141    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
Name: 308732, dtype: float64

309102
user
198045    0.780869
46715     0.780869
148702    0.237473
315118    0.202041
820908    0.154257
171967    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
Name: 309102, dtype: float64

309828
user
309828    1.000000
250513    1.000000
461917    1.000000
105989    1.000000
197893    1.000000
63622     1.000000
252432    1.000000
721134    0.970143
721787    0.707107
Name: 309828, dtype: float64

310557
user
944394    0.514496
254239    0.514496
63030     0.514496
328802    0.514496
400694    0.514496
853410    0.514496
73653     0.514496
39314     0.514496
201564    0.514496
Name: 310557, dtype: float64

311066
user
423735    1.0
172490    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
173126    0.0
Name: 311066, dtype: float64

311244
user
950331    0.0
172770    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 311244, dtype: float64

311334
user
159824    0.707107
726820    0.707107
389047    0.707107
558567    0.707107
256861    0.707107
72150     0.707107
106580    0.707107
428771    0.707107
277858    0.707107
Name: 311334, dtype: float64

312492
user
797488    0.398015
883188    0.281439
367017    0.281439
282732    0.281439
27939     0.281439
616906    0.281439
316768    0.281439
93267     0.281439
147932    0.281439
Name: 312492, dtype: float64

312989
user
950331    0.0
172770    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 312989, dtype: float64

313319
user
913037    0.577350
284695    0.225647
42484     0.222375
218901    0.171028
129333    0.149256
950331    0.000000
173141    0.000000
173038    0.000000
173126    0.000000
Name: 313319, dtype: float64

314002
user
745127    0.612564
28600     0.513964
531322    0.490290
475084    0.433148
288240    0.302614
105881    0.213980
51496     0.196116
43065     0.196116
96722     0.196116
Name: 314002, dtype: float64

314010
user
3123      1.000000
274810    1.000000
314010    1.000000
164819    0.894427
448451    0.468165
632495    0.404061
175356    0.000000
172339    0.000000
173146    0.000000
Name: 314010, dtype: float64

314022
user
169940    0.345547
312492    0.281439
950331    0.000000
173415    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 314022, dtype: float64

314118
user
245621    1.0
314118    1.0
196360    1.0
248626    1.0
290161    1.0
738464    1.0
316074    1.0
442004    1.0
950331    0.0
Name: 314118, dtype: float64

314217
user
232697    0.780869
279615    0.354298
251567    0.283999
85694     0.279372
156952    0.194489
68632     0.125848
356471    0.123860
173141    0.000000
173038    0.000000
Name: 314217, dtype: float64

314255
user
950331    0.0
172770    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 314255, dtype: float64

314345
user
648839    1.0
783345    1.0
111561    1.0
786717    1.0
753506    1.0
314345    1.0
596425    1.0
257101    1.0
44077     1.0
Name: 314345, dtype: float64

314348
user
169636    0.360668
325654    0.360668
107751    0.360668
74666     0.360668
279978    0.360668
364818    0.360668
45308     0.360668
248016    0.360668
495195    0.360668
Name: 314348, dtype: float64

314366
user
287274    0.577350
172955    0.577350
752559    0.577350
380098    0.461880
190973    0.461880
256181    0.461880
512463    0.461880
257712    0.450835
61892     0.346410
Name: 314366, dtype: float64

314389
user
220647    0.441726
791844    0.441726
28304     0.344930
328775    0.300823
105794    0.249878
217331    0.197546
115682    0.162657
947671    0.147242
702417    0.136727
Name: 314389, dtype: float64

314531
user
128498    0.449864
122394    0.431934
676064    0.431934
397299    0.431934
484341    0.431934
156256    0.431934
149217    0.431934
385886    0.431934
359293    0.431934
Name: 314531, dtype: float64

314604
user
750325    0.468165
926401    0.468165
66431     0.468165
245897    0.395045
182213    0.374821
192450    0.351123
42615     0.351123
652607    0.351123
790296    0.351123
Name: 314604, dtype: float64

314966
user
515356    0.408248
91987     0.408248
348141    0.408248
240369    0.408248
318686    0.326599
794907    0.288675
692299    0.230940
269509    0.182574
947671    0.136083
Name: 314966, dtype: float64

315073
user
589791    0.617213
246061    0.361787
481628    0.242536
51405     0.214423
215917    0.067574
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 315073, dtype: float64

315118
user
6838      0.263667

Name: 318686, dtype: float64

318736
user
621426    0.707107
510431    0.332595
213564    0.145010
950331    0.000000
173126    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
Name: 318736, dtype: float64

318831
user
137104    0.299813
250495    0.163256
132504    0.153168
53368     0.117041
179727    0.093567
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
Name: 318831, dtype: float64

318832
user
538359    0.8
950331    0.0
172504    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 318832, dtype: float64

318843
user
137615    1.000000
902743    1.000000
902931    0.780869
380098    0.600000
652365    0.348155
516840    0.278693
392082    0.260378
308702    0.258738
665569    0.236113
Name: 318843, dtype: float64

318884
user
199034    1.000000
753519    1.000000
318884    1.000000
476529    1.000000
284559    0.894427
105338    0.662266
212036    0.529813
361582    0.333333
820908    0.246932
Name: 318884, dtype: float64

318930
user
387438    1.0
354968    1.0
24895     1.0
392580    1.0
1727      1.0
25573     1.0
245724    1.0
28763     1.0
318930    1.0
Name: 318930, dtype: float64

319105
user
23533     1.0
317949    1.0
158717    1.0
524501    1.0
820044    1.0
739296    1.0
946187    1.0
465115    1.0
835141    1.0
Name: 319105, dtype: float64

319153
user
676118    0.478091
391585    0.478091
256539    0.478091
154119    0.478091
6574      0.358569
192257    0.358569
108742    0.358569
550105    0.358569
191613    0.358569
Name: 319153, dtype: float64

319612
user
319612    1.000000
88418     0.416025
950331    0.000000
172589    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 319612, dtype: float64

319753
user
630504    1.000000
5995      1.000000
319753    1.000000
869698    1.000000
849404    1.000000
389704    1.000000
412468    0.980581
7265      0.780869
134131    0.780869
Name: 319753, dtype: float64

319754
user
63030     0.514496
328802    0.514496
73653     0.514496
400694    0.514496
162500    0.514496
254239    0.514496
65017     0.477697
147610    0.441176
891451    0.272587
Name: 319754, dtype: float64

319818
user
6169      0.825192
175043    0.762493
70299     0.762493
781898    0.281633
286800    0.214183
129333    0.068284
173146    0.000000
173141    0.000000
173126    0.000000
Name: 319818, dtype: float64

319891
user
608132    0.771517
420421    0.606339
321677    0.552158
65219     0.421076
157653    0.379663
856133    0.245718
173187    0.000000
173146    0.000000
173141    0.000000
Name: 319891, dtype: float64

319946
user
831703    0.294884
370681    0.289430
950331    0.000000
172770    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 319946, dtype: float64

319969
user
172504    0.492366
630504    0.369274
5995      0.369274
389704    0.369274
849404    0.369274
319753    0.369274
869698    0.369274
365420    0.369274
412468    0.362103
Name: 319969, dtype: float64

319979
user
319979    1.000000
212395    1.000000
284794    1.000000
280639    1.000000
173796    1.000000
412528    1.000000
111635    1.000000
29192     1.000000
70203     0.780869
Name: 319979, dtype: float64

320261
user
247028    1.000000
26162     0.707107
745537    0.156412
950331    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
Name: 320261, dtype: float64

320473
user
320473    1.000000
150279    1.000000
198103    1.000000
215042    0.254824
197277    0.235702
950331    0.000000
173126    0.000000
172946    0.000000
172955    0.000000
Name: 320473, dtype: float64

320524
user
320524    1.0
173325    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
173126    0.0
Name: 320524, dtype: float64

320562
user
318665    0.400629
149655    0.390567
364509    0.304749
322627    0.258116
72749     0.254103
53368     0.107745
950331    0.000000
173141    0.000000
172946    0.000000
Name: 320562, dtype: float64

320723
user
764772    0.577350
212036    0.529813
227120    0.492366
46987     0.331295
369062    0.303046
312492    0.211079
133400    0.197305
315118    0.194054
469245    0.171701
Name: 320723, dtype: float64

320837
user
817367    0.800000
218451    0.800000
190541    0.800000
193020    0.800000
137630    0.565685
932113    0.295420
247421    0.263262
724982    0.110214
173146    0.000000
Name: 320837, dtype: float64

320937
user
320937    1.000000
227237    0.585206
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
172589    0.000000
173146    0.000000
Name: 320937, dtype: float64

321000
user
804396    0.5
317949    0.5
906243    0.5
194854    0.5
835141    0.5
224545    0.5
393032    0.5
158717    0.5
280639    0.5
Name: 321000, dtype: float64

321062
user
321062    1.000000
676064    1.000000
385886    1.000000
328925    0.624695
245897    0.450035
323845    0.441726
314531    0.431934
359001    0.404061
369062    0.404061
Name: 321062, dtype: float64

321082
user
321082    1.000000
397183    0.624695
531322    0.500000
197268    0.485071
50553     0.423999
579530    0.419314
798609    0.404061
84840     0.392232
397051    0.363803
Name: 321082, dtype: float64

321090
user
461939    1.000000
656737    1.000000
321090    1.000000
293102    0.948683
830007    0.365148
572720    0.303728
818006    0.183340
391794    0.085057
161129    0.000000
Name: 321090, dtype: float64

321116
user
632364    1.000000
321116    1.000000
592038    1.000000
114663    1.000000
153839    1.000000
518696    0.780869
467642    0.742781
611078    0.529813
658421    0.500000
Name: 321116, dtype: float64

321253
user
950331    0.0
173421    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 321253, dtype: float64

321283
user
152413    1.000000
321283    1.000000
132614    0.615457
17211     0.596285
227331    0.552158
173141    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
Name: 321283, dtype: float64

321549
user
279303    0.707107
353565    0.707107
286366    0.577350
219765    0.331042
505806    0.309529
247859    0.302614
177362    0.242536
950331    0.000000
172770    0.000000
Name: 321549, dtype: float64

321572
user
247348    0.385496
809373    0.323381
153553    0.323381
907523    0.323381
362085    0.323381
550105    0.323381
156173    0.323381
765136    0.323381
191613    0.323381
Name: 321572, dtype: float64

321576
user
179262    0.454311
172490    0.374634
629675    0.350877
150196    0.151547
70650     0.060075
173038    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
Name: 321576, dtype: float64

321581
user
50713     1.000000
290566    0.800000
789207    0.452267
130558    0.390360
459433    0.336861
243883    0.115470
950331    0.000000
172955    0.000000
173038    0.000000
Name: 321581, dtype: float64

321594
user
390006    1.000000
321594    1.000000
326545    1.000000
87516     1.000000
170923    1.000000
71245     0.554700
88418     0.554700
153040    0.468521
665848    0.457496
Name: 321594, dtype: float64

321619
user
110811    1.000000
93615     0.529813
259415    0.502519
222718    0.270914
636781    0.208514
173187    0.000000
173146    0.000000
173141    0.000000
172504    0.000000
Name: 321619, dtype: float64

321677
user
319891    0.552158
256332    0.552158
212239    0.441726
35307     0.441726
608132    0.425999
420421    0.334795
65219     0.232500
52663     0.231527
157653    0.209634
Name: 321677, dtype: float64

321692
user
22636     1.0
261654    1.0
222975    1.0
153678    1.0
321692    1.0
37980     1.0
780237    1.0
55705     1.0
194122    1.0
Name: 321692, dtype: float64

321865
user
422401    1.000000
321865    1.000000
677778    1.000000
254215    1.000000
46758     1.000000
539803    1.000000
418830    0.707107
179653    0.600000
305522    0.524142
Name: 321865, dtype: float64

321985
user
321985    1.0
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 321985, dtype: float64

322019
user
360130    0.530643
149955    0.323423
922709    0.323423
155049    0.323423
785864    0.323423
66639     0.258738
447445    0.258738
354735    0.258738
340512    0.258738
Name: 322019, dtype: float64

322044
user
68203     0.390567
26298     0.256600
950331    0.000000
173146    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
173187    0.000000
Name: 322044, dtype: float64

322423
user
877370    0.800000
112180    0.800000
143267    0.800000
632235    0.800000
133152    0.800000
491073    0.800000
606877    0.800000
937146    0.715542
71789     0.492366
Name: 322423, dtype: float64

322597
user
172955    0.401610
752559    0.401610
380098    0.321288
597752    0.321288
524526    0.321288
197893    0.321288
105989    0.321288
642082    0.321288
109583    0.321288
Name: 322597, dtype: float64

322627
user
11935     0.396526
730867    0.396526
811320    0.396526
130712    0.396526
32793     0.396526
60473     0.280386
320562    0.258116
318665    0.244045
108338    0.211718
Name: 322627, dtype: float64

322640
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 322640, dtype: float64

322689
user
43128     1.000000
386149    1.000000
322689    1.000000
327506    1.000000
138663    0.577350
269477    0.545545
539244    0.390360
467850    0.361787
96575     0.217250
Name: 322689, dtype: float64

322844
user
7505      0.529813
886698    0.423850
527607    0.413714
157628    0.238416
85130     0.200250
917934    0.177705
46592     0.143534
630210    0.142481
305856    0.128921
Name: 322844, dtype: float64

323031
user
323031    1.000000
62113     0.685994
754864    0.445435
93563     0.336336
171853    0.000000
171678    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
Name: 323031, dtype: float64

323037
user
105931    1.000000
546411    0.529813
539244    0.390360
21542     0.365636
315118    0.258738
5311      0.228748
173126    0.000000
172770    0.000000
172946    0.000000
Name: 323037, dtype: float64

323358
user
613864    1.000000
827709    1.000000
108796    1.000000
129947    1.000000
190366    1.000000
389377    1.000000
678906    1.000000
194541    1.000000
721055    0.707107
Name: 323358, dtype: float64

323463
user
323463    1.000000
3044      1.000000
94030     1.000000
819045    0.600000
308086    0.333333
534410    0.279751
816423    0.236250
710291    0.175412
90754     0.171219
Name: 323463, dtype: float64

323570
user
49999     0.610762
351825    0.450035
697629    0.318223
31000     0.318223
49598     0.318223
328852    0.318223
109566    0.318223
354616    0.318223
50808     0.318223
Name: 323570, dtype: float64

323611
user
743691    1.000000
198050    0.317221
845485    0.256074
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
Name: 323611, dtype: float64

323839
user
32143     0.138343
172589    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 323839, dtype: float64

323845
user
155466    0.663216
179685    0.441726
173421    0.441726
321062    0.441726
924153    0.441726
313       0.441726
676064    0.441726
85786     0.441726
385886    0.441726
Name: 323845, dtype: float64

323893
user
394954    0.300000
488321    0.300000
553056    0.300000
74871     0.300000
611711    0.300000
159313    0.260378
117432    0.212132
158492    0.187409
169063    0.180000
Name: 323893, dtype: float64

324767
user
324767    1.000000
75773     1.000000
114860    0.436436
707972    0.424264
101994    0.377964
950331    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
Name: 324767, dtype: float64

324845
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 324845, dtype: float64

324856
user
446951    0.769800
53368     0.165521
315462    0.160817
179727    0.132324
728009    0.121169
243883    0.115470
950331    0.000000
173038    0.000000
172770    0.000000
Name: 324856, dtype: float64

325034
user
196651    0.725018
876575    0.624695
529160    0.552158
763655    0.487805
327420    0.362509
95916     0.318788
3816      0.289409
89963     0.269827
130044    0.225271
Name: 325034, dtype: float64

325116
user
32771     0.707107
492757    0.707107
487583    0.707107
22608     0.468293
507738    0.348155
115600    0.331295
224347    0.197546
284357    0.151402
237668    0.127807
Name: 325116, dtype: float64

325129
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 325129, dtype: float64

325142
user
393834    0.707107
88881     0.435194
190725    0.213809
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
Name: 325142, dtype: float64

325198
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 325198, dtype: float64

325255
user
417545    1.000000
239894    1.000000
199828    0.447214
485567    0.145000
861280    0.109472
950331    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
Name: 325255, dtype: float64

325654
user
364818    1.000000
269788    0.857493
33179     0.680414
664138    0.577350
510431    0.470360
154501    0.362738
314348    0.360668
401684    0.281272
315462    0.268028
Name: 325654, dtype: float64

326195
user
804396    0.624695
11203     0.577069
366858    0.487805
328956    0.441726
68246     0.441726
127770    0.413714
87328     0.390244
172066    0.384473
136933    0.360668
Name: 326195, dtype: float64

326210
user
850922    0.398081
286165    0.363803
169940    0.177783
143034    0.169165
212969    0.152130
74999     0.124555
18783     0.123184
745537    0.080474
32143     0.017794
Name: 326210, dtype: float64

326545
user
390006    1.000000
321594    1.000000
326545    1.000000
87516     1.000000
170923    1.000000
71245     0.554700
88418     0.554700
153040    0.468521
665848    0.457496
Name: 326545, dtype: float64

326578
user
261456    0.544331
744060    0.447214
189901    0.341743
950331    0.000000
173038    0.000000
172589    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
Name: 326578, dtype: float64

326587
user
47493     1.000000
326587    1.000000
147610    0.514496
219765    0.331042
184471    0.280745
247859    0.242091
133400    0.197305
53368     0.165521
856133    0.122859
Name: 326587, dtype: float64

326607
user
520926    0.552158
168906    0.552158
785864    0.441726
922709    0.441726
149955    0.441726
132734    0.344930
148254    0.340799
24319     0.337284
259415    0.277470
Name: 326607, dtype: float64

326701
user
326701    1.0
950331    0.0
172504    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 326701, dtype: float64

326966
user
5732      0.707107
950331    0.000000
172770    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 326966, dtype: float64

327058
user
437478    0.447214
114691    0.447214
354580    0.316228
770493    0.279372
178016    0.168281
211914    0.165145
49680     0.155700
184471    0.125553
94677     0.109068
Name: 327058, dtype: float64

327334
user
190080    0.362509
950331    0.000000
172589    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 327334, dtype: float64

327363
user
327363    1.000000
90709     0.606339
950331    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
172589    0.000000
Name: 327363, dtype: float64

327420
user
196651    0.431034
325034    0.362509
529160    0.328266
763655    0.290007
179544    0.278543
95916     0.189525
3816      0.172058
110348    0.171431
361309    0.167126
Name: 327420, dtype: float64

327434
user
46255     1.000000
327434    1.000000
399266    0.624695
293300    0.624695
851312    0.554700
882082    0.492366
361582    0.266667
8647      0.249029
728009    0.161558
Name: 327434, dtype: float64

327446
user
166       0.328266
385272    0.316228
950331    0.000000
173141    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173187    0.000000
Name: 327446, dtype: float64

327468
user
90296     0.315597
279785    0.232104
173293    0.000000
173236    0.000000
173300    0.000000
173218    0.000000
173187    0.000000
172589    0.000000
173146    0.000000
Name: 327468, dtype: float64

327506
user
43128     1.000000
386149    1.000000
322689    1.000000
327506    1.000000
138663    0.577350
269477    0.545545
539244    0.390360
467850    0.361787
96575     0.217250
Name: 327506, dtype: float64

327538
user
327538    1.000000
334694    0.357771
172770    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 327538, dtype: float64

327552
user
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 327552, dtype: float64

327601
user
828218    1.000000
856133    0.245718
315462    0.214423
224347    0.209529
745537    0.156412
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
Name: 327601, dtype: float64

327668
user
137126    1.000000
25002     1.000000
473329    0.685994
452187    0.577350
276312    0.226455
390564    0.203186
884890    0.174574
173236    0.000000
173293    0.000000
Name: 327668, dtype: float64

327755
user
710291    0.263117
171549    0.000000
172589    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 327755, dtype: float64

327820
user
306746    1.0
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 327820, dtype: float64

328086
user
632495    0.303046
724982    0.137767
173325    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
Name: 328086, dtype: float64

328674
user
643010    0.242536
950331    0.000000
173415    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 328674, dtype: float64

328754
user
535       0.391630
833379    0.322078
173187    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
173146    0.000000
950331    0.000000
Name: 328754, dtype: float64

328775
user
314389    0.300823
573377    0.226526
16928     0.176887
791844    0.176887
86590     0.176887
136660    0.176887
446157    0.176887
367815    0.176887
546902    0.176887
Name: 328775, dtype: float64

328802
user
328802    1.000000
73653     1.000000
400694    1.000000
162500    1.000000
254239    1.000000
65017     0.928477
147610    0.857493
891451    0.529813
319754    0.514496
Name: 328802, dtype: float64

328852
user
109566    1.0
697629    1.0
256643    1.0
354616    1.0
49598     1.0
48740     1.0
352086    1.0
176896    1.0
357454    1.0
Name: 328852, dtype: float64

328899
user
434980    0.707107
112521    0.707107
500728    0.707107
85601     0.707107
48786     0.707107
148013    0.707107
386300    0.707107
52558     0.707107
198226    0.707107
Name: 328899, dtype: float64

328925
user
230207    0.780869
924153    0.624695
385886    0.624695
321062    0.624695
676064    0.624695
245897    0.281135
323845    0.275944
314531    0.269827
359001    0.252415
Name: 328925, dtype: float64

328956
user

user
417735    1.000000
65841     1.000000
340512    1.000000
66639     1.000000
643010    0.970143
667169    0.780869
65433     0.707107
47484     0.707107
870790    0.685994
Name: 340512, dtype: float64

340702
user
707094    1.00000
67607     1.00000
148839    0.57735
153457    0.26389
173146    0.00000
173038    0.00000
173126    0.00000
173141    0.00000
173218    0.00000
Name: 340702, dtype: float64

341578
user
341578    1.0
172770    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 341578, dtype: float64

341899
user
341899    1.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 341899, dtype: float64

342506
user
342506    1.000000
469069    0.780869
388896    0.707107
70333     0.478091
315409    0.312348
312492    0.281439
364545    0.177778
173236    0.000000
173218    0.000000
Name: 342506, dtype: float64

342669
user
152151    0.316228
343008    0.316228
357259    0.316228
354874    0.271163
444370    0.223607
467642    0.176166
134807    0.110096
705731    0.106843
224347    0.066259
Name: 342669, dtype: float64

342978
user
487400    1.000000
159773    1.000000
342978    1.000000
106216    1.000000
899670    1.000000
267306    1.000000
203033    1.000000
177362    0.970143
135354    0.707107
Name: 342978, dtype: float64

343008
user
343008    1.000000
357259    1.000000
354874    0.857493
444370    0.707107
467642    0.557086
134807    0.348155
705731    0.337869
342669    0.316228
224347    0.209529
Name: 343008, dtype: float64

343394
user
417785    1.0
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 343394, dtype: float64

343630
user
249802    0.800000
315596    0.577350
707972    0.565685
186982    0.545545
226106    0.392232
5015      0.390360
314531    0.259161
96575     0.217250
103304    0.118493
Name: 343630, dtype: float64

343708
user
950331    0.0
172770    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 343708, dtype: float64

344232
user
950331    0.0
172770    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 344232, dtype: float64

345311
user
836071    0.624695
92767     0.424264
71205     0.259828
179727    0.132324
950331    0.000000
173141    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
Name: 345311, dtype: float64

345526
user
85688     0.161281
950331    0.000000
172946    0.000000
173415    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
Name: 345526, dtype: float64

347151
user
544656    1.000000
212969    0.295689
572720    0.242983
173126    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173141    0.000000
172589    0.000000
Name: 347151, dtype: float64

347289
user
950331    0.500000
599838    0.500000
248496    0.500000
562381    0.500000
169608    0.500000
582482    0.500000
648676    0.500000
46312     0.500000
87328     0.390434
Name: 347289, dtype: float64

347542
user
950331    0.0
172770    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 347542, dtype: float64

347834
user
85688     0.161281
950331    0.000000
173428    0.000000
173415    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
Name: 347834, dtype: float64

348141
user
692299    0.565685
314966    0.408248
947671    0.333333
219765    0.331042
257609    0.292509
194979    0.190500
53368     0.165521
161129    0.000000
161601    0.000000
Name: 348141, dtype: float64

348417
user
369524    0.360668
76488     0.270914
218901    0.171028
950331    0.000000
173146    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
Name: 348417, dtype: float64

348657
user
950331    0.0
172770    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 348657, dtype: float64

348677
user
838116    0.707107
532525    0.707107
169657    0.485071
503594    0.441726
197936    0.441726
69676     0.299813
172770    0.294174
363254    0.191460
190766    0.168742
Name: 348677, dtype: float64

349287
user
950331    0.0
172770    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 349287, dtype: float64

349887
user
170364    1.000000
781718    1.000000
91788     0.707107
615574    0.624695
334694    0.357771
173141    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
Name: 349887, dtype: float64

350644
user
229208    0.500000
43510     0.500000
44848     0.500000
398658    0.500000
935034    0.500000
358417    0.500000
43926     0.353553
389198    0.307729
776878    0.300000
Name: 350644, dtype: float64

350743
user
350743    1.0
950331    0.0
173415    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 350743, dtype: float64

350771
user
500728    0.220193
148013    0.220193
616906    0.220193
386300    0.220193
132480    0.220193
439060    0.220193
151203    0.220193
66639     0.220193
106216    0.220193
Name: 350771, dtype: float64

350778
user
350778    1.000000
557866    1.000000
332711    1.000000
586606    0.742781
506648    0.624695
88881     0.615457
274267    0.577350
24614     0.529813
93992     0.514496
Name: 350778, dtype: float64

350912
user
780657    0.780869
879835    0.780869
599892    0.780869
219299    0.780869
424722    0.780869
198110    0.624695
696746    0.558744
132734    0.487805
507859    0.384473
Name: 350912, dtype: float64

350938
user
402496    1.000000
534410    0.373002
950331    0.000000
173126    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173141    0.000000
172589    0.000000
Name: 350938, dtype: float64

350949
user
350949    1.000000
211542    1.000000
7226      0.970143
179191    0.752577
108936    0.265513
724982    0.137767
950331    0.000000
173038    0.000000
173126    0.000000
Name: 350949, dtype: float64

350965
user
152915    0.500000
70333     0.478091
224927    0.339276
172589    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
950331    0.000000
Name: 350965, dtype: float64

351552
user
351552    1.000000
501275    0.492366
49642     0.243396
173038    0.000000
173126    0.000000
173141    0.000000
173146    0.000000
173187    0.000000
172946    0.000000
Name: 351552, dtype: float64

351590
user
706227    0.445435
92295     0.445435
449148    0.314970
85808     0.303080
107751    0.178174
45308     0.178174
113136    0.178174
74666     0.178174
279978    0.178174
Name: 351590, dtype: float64

351740
user
351740    1.0
173187    0.0
172955    0.0
173038    0.0
173126    0.0
173141    0.0
173146    0.0
950331    0.0
172770    0.0
Name: 351740, dtype: float64

351769
user
386287    1.000000
171329    1.000000
351769    1.000000
1557      1.000000
21052     1.000000
557732    1.000000
219148    0.780869
392992    0.615457
684910    0.404061
Name: 351769, dtype: float64

351793
user
351793    1.000000
175405    0.302614
283160    0.201008
593182    0.175920
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
173146    0.000000
Name: 351793, dtype: float64

351808
user
556845    0.500000
148723    0.500000
822237    0.500000
440081    0.500000
943069    0.500000
8036      0.400000
24902     0.400000
706290    0.400000
388390    0.312348
Name: 351808, dtype: float64

351825
user
49999     0.530612
323570    0.450035
45381     0.404061
869332    0.404061
550031    0.404061
195546    0.341494
247085    0.315519
177628    0.242437
546256    0.233285
Name: 351825, dtype: float64

351878
user
153097    0.742781
281932    0.393919
44555     0.368939
501799    0.321634
823651    0.206897
314604    0.195606
155466    0.193952
327420    0.137931
308702    0.108105
Name: 351878, dtype: float64

351982
user
908860    1.000000
209415    1.000000
201162    1.000000
644110    1.000000
152603    1.000000
351982    1.000000
554398    0.707107
848512    0.707107
427422    0.624695
Name: 351982, dtype: float64

352086
user
109566    1.0
697629    1.0
256643    1.0
354616    1.0
49598     1.0
48740     1.0
352086    1.0
176896    1.0
357454    1.0
Name: 352086, dtype: float64

352205
user
562119    0.707107
366520    0.707107
663333    0.707107
93916     0.707107
195327    0.500000
630210    0.338062
44923     0.280056
328775    0.100063
53368     0.087781
Name: 352205, dtype: float64

352218
user
172770    0.0
173415    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 352218, dtype: float64

352500
user
172770    0.0
173415    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 352500, dtype: float64

352507
user
38738     0.707107
172770    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 352507, dtype: float64

352512
user
82581     1.0
487327    1.0
652607    1.0
42615     1.0
7488      1.0
721140    1.0
645667    1.0
664747    1.0
192450    1.0
Name: 352512, dtype: float64

352716
user
353104    1.000000
224662    1.000000
136730    1.000000
85149     1.000000
6899      1.000000
335411    1.000000
531388    0.928477
536176    0.780869
169956    0.707107
Name: 352716, dtype: float64

352771
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 352771, dtype: float64

353069
user
150336    1.000000
138663    0.577350
4629      0.298142
255258    0.246598
243883    0.230940
256325    0.229794
249051    0.187729
256163    0.178529
173218    0.000000
Name: 353069, dtype: float64

353104
user
353104    1.000000
224662    1.000000
136730    1.000000
85149     1.000000
6899      1.000000
335411    1.000000
531388    0.928477
536176    0.780869
169956    0.707107
Name: 353104, dtype: float64

353401
user
591817    0.492366
776878    0.492366
371282    0.393893
5010      0.384473
112746    0.303030
628053    0.261116
5847      0.260862
159353    0.205152
824879    0.201008
Name: 353401, dtype: float64

353424
user
745537    0.156412
950331    0.000000
172770    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 353424, dtype: float64

353436
user
45970     1.000000
385514    1.000000
353436    1.000000
679280    1.000000
505806    0.386912
109622    0.323423
623554    0.285714
173187    0.000000
173218    0.000000
Name: 353436, dtype: float64

353540
user
213971    0.421076
950331    0.000000
172946    0.000000
173415    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
Name: 353540, dtype: float64

353565
user
223956    0.707107
321549    0.707107
279303    0.500000
286366    0.408248
219765    0.234082
505806    0.218870
247859    0.213980
177362    0.171499
173038    0.000000
Name: 353565, dtype: float64

353715
user
362878    0.363449
773716    0.316847
469245    0.117786
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
950331    0.000000
Name: 353715, dtype: float64

353809
user
194854    0.707107
835141    0.707107
317949    0.707107
158717    0.707107
524501    0.707107
820044    0.707107
739296    0.707107
946187    0.707107
23533     0.707107
Name: 353809, dtype: float64

353901
user
47493     1.000000
326587    1.000000
147610    0.514496
219765    0.331042
184471    0.280745
247859    0.242091
133400    0.197305
53368     0.165521
856133    0.122859
Name: 353901, dtype: float64

353976
user
195083    1.000000
823508    1.000000
353976    1.000000
149737    1.000000
222092    1.000000
65345     1.000000
129294    0.707107
570294    0.650945
550554    0.554700
Name: 353976, dtype: float64

354228
user
162500    0.298142
328802    0.298142
73653     0.298142
254239    0.298142
400694    0.298142
63030     0.298142
65017     0.276818
96278     0.268328
147610    0.255655
Name: 354228, dtype: float64

354415
user
138402    0.624695
397331    0.624695
12225     0.624695
50592     0.624695
18611     0.624695
43926     0.552158
650429    0.552158
329189    0.517143
89719     0.344930
Name: 354415, dtype: float64

354456
user
950331    0.0
172770    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 354456, dtype: float64

354542
user
148702    0.268802
662925    0.239904
950331    0.000000
173141    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173187    0.000000
Name: 354542, dtype: float64

354580
user
380154    0.707107
437478    0.707107
386131    0.707107
173146    0.468293
498923    0.435194
327058    0.316228
74527     0.307729
178016    0.266076
68977     0.262071
Name: 354580, dtype: float64

354616
user
109566    1.0
697629    1.0
256643    1.0
354616    1.0
49598     1.0
48740     1.0
352086    1.0
176896    1.0
357454    1.0
Name: 354616, dtype: float64

354638
user
950331    0.0
172770    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 354638, dtype: float64

354735
user
3816      0.370625
108338    0.368230
399680    0.339276
323570    0.318223
198050    0.317221
322019    0.258738
129333    0.199007
72749     0.195180
218901    0.171028
Name: 354735, dtype: float64

354771
user
22268     0.624695
305856    0.243332
106056    0.211079
947671    0.166667
328775    0.106132
950331    0.000000
173141    0.000000
172955    0.000000
173038    0.000000
Name: 354771, dtype: float64

354874
user
152151    0.857493
357259    0.857493
343008    0.857493
444370    0.606339
467642    0.477697
134807    0.298541
705731    0.289720
342669    0.271163
255093    0.235380
Name: 354874, dtype: float64

354968
user
387438    1.0
354968    1.0
24895     1.0
392580    1.0
1727      1.0
25573     1.0
245724    1.0
28763     1.0
318930    1.0
Name: 354968, dtype: float64

355382
user
671505    1.0
44140     1.0
950331    0.0
172770    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
Name: 355382, dtype: float64

355465
user
950331    0.0
172770    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 355465, dtype: float64

355707
user
950331    0.0
172770    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 355707, dtype: float64

355746
user
172770    0.0
173415    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 355746, dtype: float64

355767
user
774737    0.615457
197081    0.458735
202112    0.435194
282575    0.435194
65081     0.407597
108457    0.407597
4347      0.407597
71789     0.378788
687969    0.284268
Name: 355767, dtype: float64

355775
user
193185    0.571662
29491     0.490973
222193    0.471405
224561    0.384900
514754    0.255655
195870    0.166667
150196    0.031782
173236    0.000000
173218    0.000000
Name: 355775, dtype: float64

355931
user
355931    1.0
950331    0.0
172770    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
Name: 355931, dtype: float64

356252
user
101449    0.319235
122394    0.319235
574786    0.319235
151661    0.319235
359293    0.319235
5710      0.319235
280855    0.319235
149217    0.319235
172946    0.319235
Name: 356252, dtype: float64

356274
user
319612    1.000000
88418     0.416025
950331    0.000000
172589    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 356274, dtype: float64

356277
user
36636     0.928477
498185    0.800000
470036    0.780869
441024    0.780869
863771    0.529813
887956    0.455842
252295    0.426401
359001    0.404061
836186    0.255031
Name: 356277, dtype: float64

356300
user
950331    0.0
172770    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 356300, dtype: float64

356415
user
316768    1.0
695760    1.0
27939     1.0
50690     1.0
134761    1.0
50739     1.0
147932    1.0
29070     1.0
256789    1.0
Name: 356415, dtype: float64

356446
user
356446    1.000000
491634    0.685994
322019    0.194054
950331    0.000000
173126    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173141    0.000000
Name: 356446, dtype: float64

356471
user
148797    0.247841
43065     0.247841
51496     0.247841
50592     0.247841
49936     0.247841
397331    0.247841
383336    0.247841
93168     0.247841
138402    0.247841
Name: 356471, dtype: float64

356575
user
283360    0.450835
251567    0.181760
76488     0.126929
215917    0.126639
836186    0.119487
64301     0.102699
173126    0.000000
173141    0.000000
173146    0.000000
Name: 356575, dtype: float64

356593
user
461242    1.000000
282529    1.000000
273350    0.615457
289483    0.577350
93647     0.565685
784555    0.492366
116780    0.441726
71232     0.423999
127617    0.331042
Name: 356593, dtype: float64

356674
user
252394    0.529813
351808    0.158944
950331    0.000000
173141    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173146    0.000000
Name: 356674, dtype: float64

356789
user
4629      0.298142
950331    0.000000
172589    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 356789, dtype: float64

357207
user
283646    1.000000
252541    1.000000
716619    0.707107
173141    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
950331    0.000000
Name: 357207, dtype: float64

357259
user
343008    1.000000
357259    1.000000
354874    0.857493
444370    0.707107
467642    0.557086
134807    0.348155
705731    0.337869
342669    0.316228
224347    0.209529
Name: 357259, dtype: float64

357454
user
109566    1.0
697629    1.0
256643    1.0
354616    1.0
49598     1.0
48740     1.0
352086    1.0
176896    1.0
357454    1.0
Name: 357454, dtype: float64

357672
user
30758     0.948683
29939     0.758947
690482    0.316228
814144    0.060858
315169    0.060858
950331    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
Name: 357672, dtype: float64

357677
user
254431    0.321288
191191    0.321288
22782     0.308436
89999     0.173227
190145    0.170222
143948    0.158191
30202     0.136311
170611    0.117474
96360     0.112199
Name: 357677, dtype: float64

357747
user
255464    0.624695
105855    0.624695
28644     0.624695
193211    0.624695
26996     0.624695
132799    0.624695
87286     0.624695
197937    0.624695
196696    0.624695
Name: 357747, dtype: float64

357798
user
170161    0.349215
365420    0.312348
630504    0.312348
21105     0.312348
869698    0.312348
237982    0.312348
849404    0.312348
319753    0.312348
607450    0.312348
Name: 357798, dtype: float64

357985
user
357985    1.000000
118351    0.742781
294618    0.707107
221510    0.707107
65621     0.624695
791637    0.490290
180539    0.447214
293161    0.439057
391017    0.274721
Name: 357985, dtype: float64

358081
user
93647     0.565685
391017    0.343401
8647      0.311286
752650    0.224860
950331    0.000000
173187    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
Name: 358081, dtype: float64

358109
user
194854    0.707107
835141    0.707107
317949    0.707107
158717    0.707107
524501    0.707107
820044    0.707107
739296    0.707107
946187    0.707107
23533     0.707107
Name: 358109, dtype: float64

358118
user
113136    0.707107
74666     0.707107
45308     0.707107
423140    0.707107
107751    0.707107
445612    0.707107

user
63763     0.57735
148777    0.57735
194777    0.57735
940225    0.57735
113896    0.57735
148169    0.57735
76564     0.57735
256181    0.57735
44204     0.57735
Name: 360381, dtype: float64

360460
user
493676    1.000000
130120    1.000000
360460    1.000000
434598    1.000000
65433     0.565685
249595    0.514496
401935    0.424264
245897    0.225018
237668    0.144597
Name: 360460, dtype: float64

360476
user
2131      1.000000
95985     0.552158
30196     0.380143
180729    0.261116
175405    0.242091
283160    0.201008
728009    0.161558
386997    0.129944
171918    0.000000
Name: 360476, dtype: float64

360829
user
110773    0.707107
703342    0.707107
606620    0.707107
213231    0.707107
729240    0.707107
253041    0.707107
27339     0.707107
627098    0.707107
43325     0.408248
Name: 360829, dtype: float64

361193
user
316768    1.0
695760    1.0
27939     1.0
50690     1.0
134761    1.0
50739     1.0
147932    1.0
29070     1.0
256789    1.0
Name: 361193, dtype: float64

361303
user
212056    0.696311
359203    0.696311
285710    0.696311
91092     0.696311
861818    0.696311
922962    0.696311
573377    0.543727
234398    0.543727
17211     0.518999
Name: 361303, dtype: float64

361309
user
179544    0.600000
420344    0.565685
409870    0.461880
171918    0.411597
110348    0.369274
180519    0.345065
316376    0.271360
225910    0.265036
227331    0.265036
Name: 361309, dtype: float64

361497
user
155049    0.492366
447445    0.369274
417735    0.369274
65841     0.369274
340512    0.369274
66639     0.369274
643010    0.358249
667169    0.288355
664880    0.284268
Name: 361497, dtype: float64

361531
user
270595    1.000000
116734    1.000000
79511     1.000000
361531    1.000000
882571    0.542326
924558    0.390360
87153     0.350823
173187    0.000000
172770    0.000000
Name: 361531, dtype: float64

361582
user
509003    0.333333
753519    0.333333
837685    0.333333
43207     0.333333
2175      0.333333
642214    0.333333
841553    0.333333
318884    0.333333
230190    0.333333
Name: 361582, dtype: float64

361663
user
361663    1.000000
752963    1.000000
155666    0.707107
745537    0.195515
950331    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
Name: 361663, dtype: float64

361727
user
428337    0.410997
227388    0.328798
157628    0.328798
110279    0.328798
251361    0.290619
85663     0.256748
172079    0.135135
175469    0.098639
600241    0.097783
Name: 361727, dtype: float64

361892
user
563103    1.000000
385143    1.000000
361892    1.000000
63998     1.000000
170172    0.707107
364520    0.624695
778423    0.554700
840243    0.492366
179488    0.350823
Name: 361892, dtype: float64

362002
user
469245    0.03434
950331    0.00000
172589    0.00000
173300    0.00000
173293    0.00000
173236    0.00000
173218    0.00000
173187    0.00000
173146    0.00000
Name: 362002, dtype: float64

362085
user
362085    1.000000
194941    0.707107
308086    0.666667
664138    0.577350
280132    0.577350
215649    0.552158
247348    0.529813
259023    0.514496
151133    0.461880
Name: 362085, dtype: float64

362703
user
936844    0.624695
71632     0.248452
172770    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 362703, dtype: float64

362737
user
189901    0.341743
173421    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 362737, dtype: float64

362748
user
391405    1.000000
584514    1.000000
362748    1.000000
441682    0.742781
678384    0.645497
730352    0.431331
950331    0.000000
172946    0.000000
172504    0.000000
Name: 362748, dtype: float64

362768
user
362768    1.0
135113    0.8
173325    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 362768, dtype: float64

362878
user
445567    0.529813
353715    0.363449
282032    0.216295
651198    0.184457
106056    0.139791
217350    0.103193
250495    0.097858
469245    0.090969
728009    0.085596
Name: 362878, dtype: float64

362905
user
950331    0.0
173421    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 362905, dtype: float64

362955
user
497072    1.0
950331    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 362955, dtype: float64

363072
user
479885    0.577350
156698    0.577350
691613    0.577350
806497    0.577350
67395     0.577350
59146     0.408248
286366    0.333333
85669     0.288675
373775    0.243108
Name: 363072, dtype: float64

363134
user
88172     1.0
692426    1.0
529676    1.0
593945    1.0
944033    1.0
473854    1.0
363134    1.0
569529    1.0
182301    1.0
Name: 363134, dtype: float64

363254
user
190766    0.413533
250513    0.270765
159381    0.270765
172955    0.270765
752559    0.270765
524526    0.270765
793871    0.270765
838134    0.270765
6791      0.270765
Name: 363254, dtype: float64

363446
user
48699     1.0
170196    1.0
950331    0.0
173146    0.0
172955    0.0
173038    0.0
173126    0.0
173141    0.0
173218    0.0
Name: 363446, dtype: float64

363944
user
392159    1.000000
42317     1.000000
836480    1.000000
363944    1.000000
859147    0.390567
284695    0.225647
173141    0.000000
172946    0.000000
172955    0.000000
Name: 363944, dtype: float64

364156
user
137065    0.624695
74592     0.327327
154501    0.217643
250495    0.138527
950331    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
Name: 364156, dtype: float64

364233
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 364233, dtype: float64

364382
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 364382, dtype: float64

364463
user
357798    0.312348
20363     0.205196
283160    0.201008
173038    0.000000
173126    0.000000
173141    0.000000
173146    0.000000
950331    0.000000
172946    0.000000
Name: 364463, dtype: float64

364504
user
647960    0.707107
89963     0.305424
85688     0.190071
129333    0.140720
950331    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
Name: 364504, dtype: float64

364509
user
147193    0.468165
502484    0.468165
648839    0.468165
44077     0.468165
328802    0.468165
636320    0.468165
814610    0.468165
400694    0.468165
111561    0.468165
Name: 364509, dtype: float64

364520
user
385143    0.624695
63998     0.624695
36587     0.624695
563103    0.624695
361892    0.624695
135113    0.468521
115161    0.450835
170172    0.441726
778423    0.346518
Name: 364520, dtype: float64

364545
user
47478     0.222222
82914     0.222222
387463    0.222222
329217    0.222222
214528    0.222222
357259    0.200000
152151    0.200000
343008    0.200000
816423    0.189000
Name: 364545, dtype: float64

364626
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 364626, dtype: float64

364818
user
364818    1.000000
269788    0.857493
33179     0.680414
664138    0.577350
510431    0.470360
154501    0.362738
314348    0.360668
401684    0.281272
315462    0.268028
Name: 364818, dtype: float64

365315
user
51752     1.0
219458    1.0
199172    1.0
295792    1.0
261822    1.0
193795    1.0
260171    1.0
329184    1.0
365315    1.0
Name: 365315, dtype: float64

365419
user
365419    1.000000
117869    1.000000
202032    1.000000
244614    1.000000
132262    1.000000
626627    1.000000
702417    0.386912
110348    0.369274
91720     0.345857
Name: 365419, dtype: float64

365420
user
630504    1.000000
5995      1.000000
319753    1.000000
869698    1.000000
849404    1.000000
389704    1.000000
412468    0.980581
7265      0.780869
134131    0.780869
Name: 365420, dtype: float64

365596
user
72150     0.36823
85315     0.36823
389047    0.36823
256861    0.36823
106580    0.36823
428771    0.36823
71798     0.36823
277858    0.36823
558567    0.36823
Name: 365596, dtype: float64

365662
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 365662, dtype: float64

365881
user
109566    1.0
697629    1.0
256643    1.0
354616    1.0
49598     1.0
48740     1.0
352086    1.0
176896    1.0
357454    1.0
Name: 365881, dtype: float64

366520
user
195327    0.707107
352205    0.707107
630210    0.478091
44923     0.396059
173141    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
Name: 366520, dtype: float64

366741
user
581612    0.360668
68072     0.270501
169956    0.255031
858004    0.208232
947671    0.120223
923208    0.102699
391631    0.081100
51405     0.077335
249051    0.067708
Name: 366741, dtype: float64

366772
user
446157    0.408248
367815    0.408248
395445    0.408248
376096    0.408248
546902    0.408248
816326    0.408248
459734    0.408248
505936    0.326599
198167    0.326599
Name: 366772, dtype: float64

366858
user
804396    0.780869
4548      0.624695
510614    0.624695
155793    0.624695
419237    0.624695
60263     0.624695
775370    0.624695
328956    0.552158
68246     0.552158
Name: 366858, dtype: float64

366907
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 366907, dtype: float64

367017
user
316768    1.0
695760    1.0
27939     1.0
50690     1.0
134761    1.0
50739     1.0
147932    1.0
29070     1.0
256789    1.0
Name: 367017, dtype: float64

367079
user
543432    1.000000
359997    0.780869
950331    0.000000
173141    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173146    0.000000
Name: 367079, dtype: float64

367228
user
207470    0.685994
308373    0.514496
2849      0.514496
161783    0.514496
922940    0.514496
288121    0.514496
896394    0.514496
181135    0.514496
167525    0.514496
Name: 367228, dtype: float64

367232
user
10008     0.771517
950331    0.000000
172770    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 367232, dtype: float64

367276
user
418950    1.000000
367276    1.000000
637343    1.000000
881924    1.000000
90754     0.171219
175469    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 367276, dtype: float64

367648
user
367648    1.000000
71046     0.316228
441414    0.311086
173126    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
950331    0.000000
Name: 367648, dtype: float64

367815
user
459734    1.000000
546902    1.000000
367815    1.000000
665848    0.762493
725655    0.680414
95336     0.680414
31058     0.615457
171582    0.577350
858004    0.577350
Name: 367815, dtype: float64

368338
user
24325     0.400000
106056    0.281439
950331    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 368338, dtype: float64

368907
user
799055    0.610847
395512    0.610847
380394    0.488678
5282      0.345547
864133    0.345547
535452    0.305275
180718    0.293207
783096    0.130896
180541    0.128580
Name: 368907, dtype: float64

369062
user
924153    0.404061
105921    0.404061
851090    0.404061
676064    0.404061
61770     0.404061
896394    0.404061
732125    0.404061
2849      0.404061
340105    0.404061
Name: 369062, dtype: float64

369524
user
479278    0.506942
558567    0.450835
85315     0.450835
106580    0.450835
428771    0.450835
67429     0.450835
726820    0.450835
256861    0.450835
389047    0.450835
Name: 369524, dtype: float64

370084
user
950331    0.0
173421    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 370084, dtype: float64

370681
user
319946    0.28943
899377    0.28943
179832    0.28943
667101    0.28943
248496    0.28943
200875    0.28943
42721     0.28943
757228    0.28943
87724     0.28943
Name: 370681, dtype: float64

370833
user
292753    0.632456
861992    0.550482
111904    0.413118
397119    0.130856
950331    0.000000
173126    0.000000
172955    0.000000
173038    0.000000
173141    0.000000
Name: 370833, dtype: float64

371282
user
776878    0.800000
5010      0.624695
112746    0.492366
5847      0.423850
353401    0.393893
824879    0.326599
924558    0.292770
632095    0.257863
1705      0.254558
Name: 371282, dtype: float64

371474
user
135938    0.624695
110846    0.624695
28339     0.314485
390564    0.270914
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
950331    0.000000
Name: 371474, dtype: float64

372209
user
280855    0.320092
2709      0.320092
924153    0.256074
321062    0.256074
359723    0.256074
385886    0.256074
177506    0.256074
944343    0.256074
676064    0.256074
Name: 372209, dtype: float64

372398
user
318073    0.354375
420587    0.354375
92831     0.354375
475865    0.354375
203647    0.354375
287274    0.315000
875286    0.315000
927595    0.315000
614124    0.315000
Name: 372398, dtype: float64

373622
user
252419    0.606339
423159    0.529813
173141    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
950331    0.000000
Name: 373622, dtype: float64

373775
user
5600      0.421076
479885    0.421076
931768    0.421076
748583    0.421076
707460    0.421076
88901     0.421076
719811    0.421076
75174     0.421076
691613    0.421076
Name: 373775, dtype: float64

376096
user
395445    1.000000
376096    1.000000
465110    0.707107
256497    0.707107
126946    0.707107
397159    0.707107
611078    0.662266
46322     0.639602
464677    0.577350
Name: 376096, dtype: float64

376636
user
890873    1.000000
537352    1.000000
251629    1.000000
949019    0.577350
856133    0.307148
194387    0.305888
224347    0.279372
568971    0.231455
745537    0.156412
Name: 376636, dtype: float64

376736
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 376736, dtype: float64

377242
user
789611    1.000000
377242    1.000000
24308     1.000000
612464    0.218218
173187    0.000000
173146    0.000000
173141    0.000000
173218    0.000000
173126    0.000000
Name: 377242, dtype: float64

377537
user
704888    1.000000
248011    0.435194
171582    0.000000
171636    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 377537, dtype: float64

377841
user
86173     0.894427
46936     0.218952
107593    0.145521
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
173146    0.000000
173218    0.000000
Name: 377841, dtype: float64

379795
user
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 379795, dtype: float64

380098
user
172955    0.800000
752559    0.800000
190973    0.640000
137615    0.600000
318843    0.600000
902743    0.600000
902931    0.468521
314366    0.461880
322597    0.321288
Name: 380098, dtype: float64

380154
user
380154    1.000000
354580    0.707107
173146    0.662266
498923    0.615457
74527     0.435194
68977     0.370625
198050    0.317221
71205     0.259828
171967    0.245770
Name: 380154, dtype: float64

380394
user
864133    0.707107
5282      0.707107
535452    0.624695
180718    0.600000
368907    0.488678
180541    0.263117
328775    0.176887
593182    0.175920
173126    0.000000
Name: 380394, dtype: float64

382000
user
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 382000, dtype: float64

382215
user
382215    1.000000
1521      1.000000
608997    0.980581
279785    0.232104
593182    0.219900
197504    0.208514
469245    0.171701
182213    0.152499
173141    0.000000
Name: 382215, dtype: float64

382523
user
442748    0.662266
824879    0.540738
13006     0.517143
398891    0.468293
358508    0.305888
148702    0.251756
154501    0.240229
807425    0.164817
67868     0.149974
Name: 382523, dtype: float64

382866
user
110208    0.707107
51021     0.707107
699829    0.707107
283360    0.408248
88042     0.348155
401684    0.198889
425396    0.171499
391631    0.159000
217350    0.137725
Name: 382866, dtype: float64

383336
user
383336    1.000000
279615    0.306570
356471    0.247841
173415    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 383336, dtype: float64

384572
user
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 384572, dtype: float64

384587
user
351808    0.1
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 384587, dtype: float64

384721
user
95985     0.552158
950331    0.000000
172589    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 384721, dtype: float64

385138
user
332593    0.565685
168899    0.565685
417312    0.565685
424678    0.400000
721055    0.400000
67245     0.348155
218450    0.326599
572720    0.137452
53368     0.093633
Name: 385138, dtype: float64

385143
user
563103    1.000000
385143    1.000000
361892    1.000000
63998     1.000000
170172    0.707107
364520    0.624695
778423    0.554700
840243    0.492366
179488    0.350823
Name: 385143, dtype: float64

385219
user
319105    0.424094
140931    0.424094
136661    0.424094
524501    0.424094
465115    0.424094
393032    0.424094
739296    0.424094
460437    0.424094
782157    0.424094
Name: 385219, dtype: float64

385272
user
24902     0.316228
133586    0.316228
327446    0.316228
113970    0.316228
8036      0.316228
651501    0.310087
589446    0.237171
106216    0.237171
358417    0.237171
Name: 385272, dtype: float64

385366
user
172504    0.500000
396276    0.307729
319969    0.246183
114160    0.155946
314389    0.099388
172079    0.098639
217350    0.077909
138574    0.074231
192676    0.070065
Name: 385366, dtype: float64

385514
user
45970     1.000000
385514    1.000000
353436    1.000000
679280    1.000000
505806    0.386912
109622    0.323423
623554    0.285714
173187    0.000000
173218    0.000000
Name: 385514, dtype: float64

385612
user
328802    0.21887
97130     0.21887
400694    0.21887
191023    0.21887
551587    0.21887
790247    0.21887
254239    0.21887
315174    0.21887
218336    0.21887
Name: 385612, dtype: float64

385886
user
321062    1.000000
676064    1.000000
385886    1.000000
328925    0.624695
245897    0.450035
323845    0.441726
314531    0.431934
359001    0.404061
369062    0.404061
Name: 385886, dtype: float64

386010
user
47528     0.707107
91034     0.328266
211972    0.264906
68977     0.262071
156230    0.238909
256163    0.126239
171871    0.000000
172955    0.000000
173325    0.000000
Name: 386010, dtype: float64

386072
user
159024    1.000000
31997     0.600000
51766     0.529813
247634    0.396526
485567    0.145000
173141    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
Name: 386072, dtype: float64

386131
user
380154    1.000000
354580    0.707107
173146    0.662266
498923    0.615457
74527     0.435194
68977     0.370625
198050    0.317221
71205     0.259828
171967    0.245770
Name: 386131, dtype: float64

386149
user
43128     1.000000
386149    1.000000
322689    1.000000
327506    1.000000
138663    0.577350
269477    0.545545
539244    0.390360
467850    0.361787
96575     0.217250
Name: 386149, dtype: float64

386253
user
186286    0.213809
950331    0.000000
172589    0.000000

user
434550    0.707107
340113    0.707107
342506    0.707107
261432    0.707107
469069    0.552158
315409    0.441726
70333     0.338062
312492    0.199007
90754     0.161427
Name: 388896, dtype: float64

389013
user
140931    0.639602
460437    0.639602
71170     0.548454
51466     0.452267
2847      0.393648
2379      0.393648
215860    0.301511
73676     0.299667
385219    0.271252
Name: 389013, dtype: float64

389037
user
46255     1.000000
327434    1.000000
399266    0.624695
293300    0.624695
851312    0.554700
882082    0.492366
361582    0.266667
8647      0.249029
728009    0.161558
Name: 389037, dtype: float64

389047
user
389047    1.0
558567    1.0
277858    1.0
256861    1.0
159824    1.0
67429     1.0
106580    1.0
72150     1.0
726820    1.0
Name: 389047, dtype: float64

389099
user
950331    0.0
172770    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 389099, dtype: float64

389100
user
450355    1.000000
389100    1.000000
29491     0.368230
251765    0.328798
686300    0.316228
32143     0.103757
173038    0.000000
173126    0.000000
173141    0.000000
Name: 389100, dtype: float64

389198
user
398658    0.615457
44848     0.615457
229208    0.615457
534984    0.615457
358417    0.615457
682485    0.469282
43926     0.435194
937122    0.435194
173146    0.326077
Name: 389198, dtype: float64

389273
user
387274    1.000000
500162    0.662266
404491    0.447214
485567    0.145000
173126    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173146    0.000000
Name: 389273, dtype: float64

389377
user
613864    1.000000
827709    1.000000
108796    1.000000
129947    1.000000
190366    1.000000
389377    1.000000
678906    1.000000
194541    1.000000
721055    0.707107
Name: 389377, dtype: float64

389608
user
470215    0.707107
798855    0.707107
261998    0.707107
282875    0.656532
114081    0.565685
770493    0.552158
887586    0.392232
247634    0.280386
68203     0.276172
Name: 389608, dtype: float64

389704
user
630504    1.000000
5995      1.000000
319753    1.000000
869698    1.000000
849404    1.000000
389704    1.000000
412468    0.980581
7265      0.780869
134131    0.780869
Name: 389704, dtype: float64

389728
user
24283     0.369274
804396    0.348155
46373     0.326236
366858    0.271864
328956    0.246183
68246     0.246183
127770    0.230571
326195    0.217491
87328     0.217491
Name: 389728, dtype: float64

389767
user
445612    1.000000
423140    1.000000
452036    1.000000
92150     0.894427
334520    0.707107
358118    0.707107
234398    0.624695
132873    0.466252
646881    0.310460
Name: 389767, dtype: float64

389789
user
67902     0.980581
519716    0.566139
788114    0.453274
173146    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
Name: 389789, dtype: float64

389798
user
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 389798, dtype: float64

389973
user
249441    0.624695
621199    0.413714
470036    0.390244
49805     0.390244
609485    0.330972
658421    0.312348
156156    0.312348
1582      0.307579
29491     0.287539
Name: 389973, dtype: float64

390006
user
390006    1.000000
321594    1.000000
326545    1.000000
87516     1.000000
170923    1.000000
71245     0.554700
88418     0.554700
153040    0.468521
665848    0.457496
Name: 390006, dtype: float64

390564
user
693398    0.270914
48799     0.270914
155233    0.270914
371474    0.270914
64632     0.270914
258080    0.270914
689905    0.251538
25002     0.203186
327668    0.203186
Name: 390564, dtype: float64

390639
user
46373     0.773021
566689    0.707107
172078    0.707107
193723    0.500000
155100    0.189737
350771    0.155700
129333    0.105540
145101    0.077732
173038    0.000000
Name: 390639, dtype: float64

390671
user
296014    0.470356
198386    0.370625
896394    0.370625
2849      0.370625
161783    0.370625
686640    0.370625
612464    0.323508
86868     0.296500
328852    0.296500
Name: 390671, dtype: float64

391017
user
318272    0.343401
358081    0.343401
48442     0.274721
357985    0.274721
847030    0.274721
388096    0.274721
393635    0.274721
118351    0.204058
93647     0.194257
Name: 391017, dtype: float64

391153
user
197277    0.304290
245798    0.258199
288121    0.258199
668508    0.258199
113732    0.258199
87516     0.258199
321000    0.258199
337914    0.258199
321594    0.258199
Name: 391153, dtype: float64

391247
user
391247    1.0
172946    0.0
172955    0.0
173038    0.0
173126    0.0
173141    0.0
173146    0.0
950331    0.0
172589    0.0
Name: 391247, dtype: float64

391405
user
391405    1.000000
584514    1.000000
362748    1.000000
441682    0.742781
678384    0.645497
730352    0.431331
950331    0.000000
172946    0.000000
172504    0.000000
Name: 391405, dtype: float64

391583
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 391583, dtype: float64

391585
user
391585    1.000000
676118    1.000000
256539    1.000000
319153    0.478091
196166    0.464238
171853    0.000000
172955    0.000000
173300    0.000000
171636    0.000000
Name: 391585, dtype: float64

391609
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 391609, dtype: float64

391631
user
470723    0.385478
71798     0.299813
551366    0.299813
896394    0.299813
2849      0.299813
161783    0.299813
400268    0.239850
191023    0.224860
707460    0.224860
Name: 391631, dtype: float64

391650
user
287274    0.552158
155049    0.552158
793074    0.441726
257712    0.431163
169618    0.349215
158492    0.344930
664880    0.318788
314366    0.318788
263894    0.292540
Name: 391650, dtype: float64

391794
user
5311      0.196728
389973    0.177116
32143     0.162778
688218    0.148356
308702    0.143049
200875    0.141762
8323      0.141762
8055      0.141762
199406    0.141762
Name: 391794, dtype: float64

391957
user
885428    0.305995
130789    0.305995
763520    0.305995
551587    0.305995
175320    0.305995
127106    0.305995
209069    0.305995
584895    0.305995
183443    0.305995
Name: 391957, dtype: float64

392082
user
516840    0.498888
504746    0.342951
137615    0.260378
318843    0.260378
199406    0.260378
902743    0.260378
151456    0.260378
1599      0.260378
152437    0.260378
Name: 392082, dtype: float64

392159
user
392159    1.000000
42317     1.000000
836480    1.000000
363944    1.000000
859147    0.390567
284695    0.225647
173141    0.000000
172946    0.000000
172955    0.000000
Name: 392159, dtype: float64

392437
user
208452    0.780869
950331    0.000000
172770    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 392437, dtype: float64

392532
user
882297    1.000000
214796    0.707107
674768    0.500000
173187    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
173146    0.000000
Name: 392532, dtype: float64

392580
user
387438    1.0
354968    1.0
24895     1.0
392580    1.0
1727      1.0
25573     1.0
245724    1.0
28763     1.0
318930    1.0
Name: 392580, dtype: float64

392680
user
815556    0.707107
23533     0.707107
500373    0.707107
739296    0.707107
524501    0.707107
820044    0.707107
194854    0.707107
158717    0.707107
835141    0.707107
Name: 392680, dtype: float64

392840
user
198312    0.374634
211972    0.310135
388883    0.293887
178898    0.173422
68632     0.133417
175875    0.000000
172589    0.000000
173300    0.000000
173293    0.000000
Name: 392840, dtype: float64

392887
user
318272    0.495074
400110    0.396059
26450     0.396059
401104    0.396059
392903    0.396059
224545    0.297044
29192     0.297044
319979    0.297044
284794    0.297044
Name: 392887, dtype: float64

392903
user
26450     1.000000
401104    1.000000
392903    1.000000
253154    0.707107
905460    0.707107
253153    0.707107
130006    0.529813
392887    0.396059
255258    0.328798
Name: 392903, dtype: float64

392977
user
541       0.424264
226606    0.424264
85694     0.202386
259415    0.170561
135044    0.146969
593954    0.123625
850922    0.118176
249051    0.099558
91720     0.088041
Name: 392977, dtype: float64

392992
user
149684    0.615457
1557      0.615457
150433    0.615457
21052     0.615457
212461    0.615457
173943    0.615457
292280    0.615457
256392    0.615457
154154    0.615457
Name: 392992, dtype: float64

393032
user
23533     1.0
317949    1.0
158717    1.0
524501    1.0
820044    1.0
739296    1.0
946187    1.0
465115    1.0
835141    1.0
Name: 393032, dtype: float64

393149
user
133983    0.70014
658421    0.50000
172770    0.00000
172946    0.00000
172955    0.00000
173038    0.00000
173126    0.00000
173141    0.00000
172504    0.00000
Name: 393149, dtype: float64

393293
user
750325    0.707107
66431     0.707107
926401    0.707107
33831     0.500000
855363    0.441726
314604    0.331042
251266    0.318788
101994    0.267261
90296     0.178529
Name: 393293, dtype: float64

393635
user
391017    0.274721
172589    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 393635, dtype: float64

393834
user
325142    0.707107
88881     0.615457
190725    0.302372
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
Name: 393834, dtype: float64

393935
user
393935    1.000000
423011    1.000000
252216    0.227429
173126    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173146    0.000000
Name: 393935, dtype: float64

393943
user
393943    1.0
717906    1.0
950331    0.0
173415    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
Name: 393943, dtype: float64

393950
user
950331    0.0
172770    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 393950, dtype: float64

393981
user
399142    0.701754
101449    0.662266
397299    0.662266
574786    0.662266
359293    0.662266
149217    0.662266
172946    0.662266
156256    0.662266
122394    0.662266
Name: 393981, dtype: float64

393997
user
950331    0.0
172770    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 393997, dtype: float64

394042
user
394042    1.000000
5311      0.228748
172946    0.000000
173415    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
Name: 394042, dtype: float64

394365
user
427412    1.000000
394365    1.000000
476834    0.857493
292194    0.577350
872014    0.363803
662925    0.339276
935084    0.222375
90296     0.189358
217350    0.116863
Name: 394365, dtype: float64

394404
user
221863    1.0
950331    0.0
173415    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 394404, dtype: float64

394415
user
394415    1.000000
67485     1.000000
219615    1.000000
196448    0.596285
811088    0.369274
194387    0.305888
109622    0.258738
163884    0.237356
179727    0.132324
Name: 394415, dtype: float64

394671
user
19252     1.000000
157739    1.000000
315462    0.214423
950331    0.000000
172946    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
Name: 394671, dtype: float64

394954
user
611711    1.000000
553056    1.000000
488321    1.000000
74871     1.000000
117432    0.707107
158492    0.624695
169063    0.600000
44555     0.529813
392992    0.492366
Name: 394954, dtype: float64

395445
user
395445    1.000000
376096    1.000000
465110    0.707107
256497    0.707107
126946    0.707107
397159    0.707107
611078    0.662266
46322     0.639602
464677    0.577350
Name: 395445, dtype: float64

395512
user
799055    1.000000
368907    0.610847
172946    0.000000
173415    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
Name: 395512, dtype: float64

395537
user
944394    0.305424
170268    0.305424
39314     0.305424
745938    0.305424
622340    0.305424
209839    0.305424
463997    0.305424
201564    0.305424
853410    0.305424
Name: 395537, dtype: float64

395685
user
172770    0.0
173415    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 395685, dtype: float64

395948
user
759526    0.370625
893228    0.370625
96373     0.370625
290662    0.370625
939233    0.370625
864883    0.370625
130789    0.296500
229007    0.296500
160404    0.296500
Name: 395948, dtype: float64

396035
user
249051    0.187729
950331    0.000000
172589    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 396035, dtype: float64

396107
user
14959     1.000000
396107    1.000000
179719    0.231455
256163    0.178529
171853    0.000000
172946    0.000000
173325    0.000000
173300    0.000000
171636    0.000000
Name: 396107, dtype: float64

396163
user
396163    1.0
950331    0.0
172770    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 396163, dtype: float64

396245
user
950331    0.0
172770    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 396245, dtype: float64

396247
user
4385      1.0
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 396247, dtype: float64

396276
user
72566     0.615457
132480    0.615457
706437    0.384473
239796    0.373176
208228    0.316650
385366    0.307729
21542     0.225034
63697     0.203898
114160    0.191956
Name: 396276, dtype: float64

397051
user
482273    0.606339
149905    0.606339
67211     0.428746
252734    0.378777
85785     0.363803
321082    0.363803
257950    0.363803
201482    0.350070
95985     0.267836
Name: 397051, dtype: float64

397119
user
415277    0.292603
23999     0.292603
560061    0.292603
521785    0.292603
50758     0.292603
93171     0.292603
706307    0.292603
158711    0.193068
224421    0.182788
Name: 397119, dtype: float64

397159
user
816326    0.707107
395445    0.707107
376096    0.707107
465110    0.500000
256497    0.500000
126946    0.500000
611078    0.468293
46322     0.452267
464677    0.408248
Name: 397159, dtype: float64

397183
user
224377    0.780869
336473    0.780869
321082    0.624695
85785     0.624695
193723    0.552158
26843     0.362509
164819    0.349215
531322    0.312348
197268    0.303022
Name: 397183, dtype: float64

397299
user
359293    1.000000
397299    1.000000
122394    1.000000
101449    1.000000
149217    1.000000
156256    1.000000
172946    1.000000
16704     0.800000
465110    0.707107
Name: 397299, dtype: float64

397331
user
138402    1.000000
50592     1.000000
397331    1.000000
18611     1.000000
354415    0.624695
197904    0.514496
69546     0.514496
539244    0.390360
90296     0.252478
Name: 397331, dtype: float64

397337
user
308702    0.323423
950331    0.000000
172589    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 397337, dtype: float64

397502
user
397502    1.000000
155466    0.435194
219293    0.431934
24614     0.397360
386997    0.173259
32143     0.069171
173236    0.000000
173218    0.000000
173187    0.000000
Name: 397502, dtype: float64

397635
user
50808     0.307692
128541    0.307692
98586     0.230769
168442    0.230769
576558    0.230769
339564    0.230769
194482    0.230769
709411    0.230769
834097    0.230769
Name: 397635, dtype: float64

397716
user
127124    0.255822
172490    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
173126    0.000000
Name: 397716, dtype: float64

397753
user
397753    1.000000
288030    1.000000
171136    1.000000
736492    1.000000
176888    0.707107
801415    0.662266
269509    0.447214
70779     0.359908
175875    0.000000
Name: 397753, dtype: float64

397767
user
54441     0.371391
322597    0.298308
648265    0.262613
96360     0.259390
208228    0.254772
255258    0.228961
921028    0.211181
593182    0.204172
65081     0.196768
Name: 397767, dtype: float64

398361
user
398361    1.000000
924557    1.000000
70861     1.000000
85645     0.707107
5666      0.256600
133400    0.246632
20363     0.205196
256325    0.172345
745537    0.156412
Name: 398361, dtype: float64

398557
user
179685    0.577350
407842    0.577350
677628    0.577350
256985    0.461880
491529    0.360668
194777    0.346410
148169    0.346410
63763     0.346410
940225    0.346410
Name: 398557, dtype: float64

398613
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 398613, dtype: float64

398658
user
398658    1.000000
44848     1.000000
229208    1.000000
43926     0.707107
389198    0.615457
173146    0.529813
350644    0.500000
359001    0.404061
72749     0.390360
Name: 398658, dtype: float64

398867
user
475865    0.780869
318073    0.780869
203647    0.780869
92831     0.780869
420587    0.780869
3357      0.552158
13006     0.487805
518696    0.487805
613041    0.450835
Name: 398867, dtype: float64

398874
user
697977    0.357143
172504    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
Name: 398874, dtype: float64

398891
user
111561    0.707107
626385    0.707107
186572    0.707107
814610    0.707107
648839    0.707107
923681    0.707107
753506    0.707107
44077     0.707107
502484    0.707107
Name: 398891, dtype: float64

399142
user
393981    0.701754
793074    0.662266
122394    0.529813
359293    0.529813
101449    0.529813
574786    0.529813
149217    0.529813
156256    0.529813
172946    0.529813
Name: 399142, dtype: float64

399266
user
389037    0.624695
46255     0.624695
327434    0.624695
293300    0.390244
851312    0.346518
882082    0.307579
361582    0.166585
8647      0.155567
728009    0.100925
Name: 399266, dtype: float64

399546
user
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 399546, dtype: float64

399680
user
150345    0.424094
387463    0.339276
214528    0.339276
354735    0.339276
329217    0.339276
273043    0.299880
467489    0.299880
109058    0.231362
112416    0.218195
Name: 399680, dtype: float64

399753
user
387438    1.0
354968    1.0
24895     1.0
392580    1.0
1727      1.0
25573     1.0
245724    1.0
28763     1.0
318930    1.0
Name: 399753, dtype: float64

399809
user
317295    0.529813
28724     0.514496
172504    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
Name: 399809, dtype: float64

400110
user
26450     1.000000
401104    1.000000
392903    1.000000
253154    0.707107
905460    0.707107
253153    0.707107
130006    0.529813
392887    0.396059
255258    0.328798
Name: 400110, dtype: float64

400150
user
256001    1.000000
400150    1.000000
885234    1.000000
180718    0.800000
688990    0.577350
159313    0.520756
308702    0.323423
360130    0.250490
572720    0.242983
Name: 400150, dtype: float64

400268
user
896394    0.800000
2849      0.800000
161783    0.800000
393981    0.423850
131358    0.414781
367228    0.411597
293382    0.345065
369062    0.323249
390671    0.296500
Name: 400268, dtype: float64

400694
user
328802    1.000000
73653     1.000000
400694    1.000000
162500    1.000000
254239    1.000000
65017     0.928477
147610    0.857493
891451    0.529813
319754    0.514496

user
168899    1.000000
417312    1.000000
424678    0.707107
721055    0.707107
67245     0.615457
218450    0.577350
385138    0.565685
572720    0.242983
53368     0.165521
Name: 417312, dtype: float64

417464
user
950331    0.0
173421    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 417464, dtype: float64

417545
user
417545    1.000000
239894    1.000000
199828    0.447214
485567    0.145000
861280    0.109472
950331    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
Name: 417545, dtype: float64

417735
user
417735    1.000000
65841     1.000000
340512    1.000000
66639     1.000000
643010    0.970143
667169    0.780869
65433     0.707107
47484     0.707107
870790    0.685994
Name: 417735, dtype: float64

417785
user
417785    1.0
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 417785, dtype: float64

418510
user
200652    1.000000
126931    1.000000
839712    1.000000
148206    0.707107
441889    0.707107
2419      0.468165
33061     0.441726
93647     0.424264
531388    0.371391
Name: 418510, dtype: float64

418830
user
179653    0.989949
305522    0.741249
254215    0.707107
46758     0.707107
539803    0.707107
790931    0.707107
556749    0.707107
677778    0.707107
422401    0.707107
Name: 418830, dtype: float64

418950
user
418950    1.000000
367276    1.000000
637343    1.000000
881924    1.000000
90754     0.171219
175469    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 418950, dtype: float64

419237
user
510614    1.000000
419237    1.000000
155793    1.000000
60263     1.000000
775370    1.000000
821860    0.707107
366858    0.624695
257535    0.483368
54197     0.424264
Name: 419237, dtype: float64

419353
user
191379    0.780869
745938    0.780869
170268    0.780869
439699    0.780869
209839    0.780869
463997    0.780869
59146     0.552158
609485    0.413714
423674    0.401754
Name: 419353, dtype: float64

419505
user
152413    1.000000
321283    1.000000
132614    0.615457
17211     0.596285
227331    0.552158
173141    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
Name: 419505, dtype: float64

419534
user
793074    0.505076
291126    0.505076
250513    0.404061
252432    0.404061
359203    0.404061
922962    0.404061
105989    0.404061
91092     0.404061
197893    0.404061
Name: 419534, dtype: float64

419560
user
53433     0.500000
219433    0.390434
289156    0.390434
445293    0.390434
170852    0.390434
74904     0.276079
215860    0.276079
133983    0.273359
93992     0.267836
Name: 419560, dtype: float64

419576
user
701051    1.000000
419576    1.000000
173428    0.331295
923208    0.284747
173038    0.000000
172589    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
Name: 419576, dtype: float64

419748
user
272354    1.000000
568330    0.624695
20363     0.205196
900562    0.197814
921028    0.181959
469245    0.171701
172955    0.000000
173038    0.000000
173126    0.000000
Name: 419748, dtype: float64

420057
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 420057, dtype: float64

420344
user
928303    0.707107
756238    0.707107
8055      0.707107
863840    0.707107
424498    0.707107
227485    0.707107
710581    0.632456
361309    0.565685
926948    0.500000
Name: 420344, dtype: float64

420421
user
319891    0.606339
608132    0.467801
831341    0.363803
446105    0.363803
321677    0.334795
65219     0.255315
157653    0.230205
9339      0.210042
25134     0.210042
Name: 420421, dtype: float64

420587
user
92831     1.000000
475865    1.000000
318073    1.000000
420587    1.000000
398867    0.780869
3357      0.707107
518696    0.624695
13006     0.624695
613041    0.577350
Name: 420587, dtype: float64

420805
user
49529     0.297044
868283    0.297044
592764    0.297044
173428    0.218687
114860    0.216068
169881    0.210042
500162    0.157378
694627    0.108920
385612    0.108357
Name: 420805, dtype: float64

421319
user
465115    0.707107
757292    0.707107
31431     0.707107
158717    0.707107
760346    0.707107
194854    0.707107
317949    0.707107
524501    0.707107
820044    0.707107
Name: 421319, dtype: float64

421743
user
421743    1.000000
109581    0.512148
622936    0.512148
783730    0.512148
61776     0.512148
53332     0.512148
107059    0.512148
27962     0.512148
16096     0.384111
Name: 421743, dtype: float64

422310
user
921028    0.181959
391957    0.061199
950331    0.000000
173141    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173187    0.000000
Name: 422310, dtype: float64

422401
user
422401    1.000000
321865    1.000000
677778    1.000000
254215    1.000000
46758     1.000000
539803    1.000000
418830    0.707107
179653    0.600000
305522    0.524142
Name: 422401, dtype: float64

423011
user
393935    1.000000
423011    1.000000
252216    0.227429
173126    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173146    0.000000
Name: 423011, dtype: float64

423018
user
109581    0.514496
27962     0.514496
107059    0.514496
95763     0.514496
783730    0.514496
96613     0.514496
562349    0.514496
428481    0.411597
702397    0.363803
Name: 423018, dtype: float64

423140
user
445612    1.000000
423140    1.000000
452036    1.000000
92150     0.894427
334520    0.707107
358118    0.707107
234398    0.624695
132873    0.466252
646881    0.310460
Name: 423140, dtype: float64

423159
user
252419    0.562181
373622    0.529813
108742    0.529813
721787    0.468293
319153    0.189974
173141    0.000000
173146    0.000000
173126    0.000000
173187    0.000000
Name: 423159, dtype: float64

423674
user
463997    0.514496
191379    0.514496
745938    0.514496
209839    0.514496
170268    0.514496
439699    0.514496
419353    0.401754
59146     0.363803
609485    0.272587
Name: 423674, dtype: float64

423735
user
423735    1.0
172490    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
173126    0.0
Name: 423735, dtype: float64

424278
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 424278, dtype: float64

424498
user
863840    1.000000
8055      1.000000
928303    1.000000
756238    1.000000
424498    1.000000
710581    0.894427
334520    0.707107
420344    0.707107
926948    0.707107
Name: 424498, dtype: float64

424678
user
168899    0.707107
332593    0.707107
417312    0.707107
5121      0.565685
618570    0.565685
721055    0.500000
491529    0.441726
67245     0.435194
261757    0.424264
Name: 424678, dtype: float64

424722
user
219299    1.000000
879835    1.000000
780657    1.000000
599892    1.000000
350912    0.780869
132734    0.624695
85808     0.408248
256163    0.133897
580520    0.130189
Name: 424722, dtype: float64

425059
user
699447    0.474579
861818    0.410997
359203    0.410997
59764     0.410997
285710    0.410997
922962    0.410997
212056    0.410997
91092     0.410997
928303    0.328798
Name: 425059, dtype: float64

425198
user
923208    0.284747
11951     0.279372
650646    0.255377
650202    0.239426
745537    0.039103
176336    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 425198, dtype: float64

425396
user
288451    0.529256
110208    0.242536
51021     0.242536
699829    0.242536
382866    0.171499
88042     0.119416
401684    0.068218
391631    0.054536
217350    0.047239
Name: 425396, dtype: float64

426302
user
24943     1.000000
95664     1.000000
360079    1.000000
880552    1.000000
426302    1.000000
286800    0.585206
158429    0.419314
79647     0.416025
217426    0.346410
Name: 426302, dtype: float64

426352
user
392082    0.260378
516840    0.209020
504746    0.161281
950331    0.000000
173038    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173126    0.000000
Name: 426352, dtype: float64

426952
user
28722     1.000000
26352     1.000000
885528    1.000000
666409    0.707107
193499    0.577350
193549    0.435194
166       0.328266
173141    0.000000
173126    0.000000
Name: 426952, dtype: float64

427396
user
950331    0.0
173421    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 427396, dtype: float64

427412
user
427412    1.000000
394365    1.000000
476834    0.857493
292194    0.577350
872014    0.363803
662925    0.339276
935084    0.222375
90296     0.189358
217350    0.116863
Name: 427412, dtype: float64

427422
user
578647    0.780869
294354    0.780869
7488      0.780869
42615     0.780869
886362    0.780869
703432    0.780869
645667    0.780869
652607    0.780869
487327    0.780869
Name: 427422, dtype: float64

427974
user
634851    0.707107
252211    0.606339
42484     0.262071
215917    0.238909
70779     0.203595
133400    0.139516
173218    0.000000
173236    0.000000
173187    0.000000
Name: 427974, dtype: float64

428337
user
361727    0.410997
950331    0.000000
173415    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 428337, dtype: float64

428481
user
96613     0.8
95763     0.8
562349    0.8
439187    0.6
851090    0.6
61770     0.6
188061    0.6
340105    0.6
732125    0.6
Name: 428481, dtype: float64

428771
user
389047    1.0
558567    1.0
277858    1.0
256861    1.0
159824    1.0
67429     1.0
106580    1.0
72150     1.0
726820    1.0
Name: 428771, dtype: float64

429443
user
214796    0.707107
101994    0.377964
950331    0.000000
172770    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 429443, dtype: float64

430904
user
467489    0.565685
106056    0.281439
950331    0.000000
173300    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
Name: 430904, dtype: float64

431662
user
43742     0.615457
90709     0.606339
132144    0.269680
861280    0.182453
950331    0.000000
173038    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
Name: 431662, dtype: float64

431688
user
3123      1.000000
274810    1.000000
314010    1.000000
164819    0.894427
448451    0.468165
632495    0.404061
175356    0.000000
172339    0.000000
173146    0.000000
Name: 431688, dtype: float64

432706
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 432706, dtype: float64

433032
user
433032    1.000000
752650    0.299813
247421    0.188044
173126    0.000000
172589    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
Name: 433032, dtype: float64

433327
user
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 433327, dtype: float64

434224
user
107704    1.0
950331    0.0
172490    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
173126    0.0
Name: 434224, dtype: float64

434550
user
342506    1.000000
469069    0.780869
388896    0.707107
70333     0.478091
315409    0.312348
312492    0.281439
364545    0.177778
173236    0.000000
173218    0.000000
Name: 434550, dtype: float64

434598
user
493676    1.000000
130120    1.000000
360460    1.000000
434598    1.000000
65433     0.565685
249595    0.514496
401935    0.424264
245897    0.225018
237668    0.144597
Name: 434598, dtype: float64

434980
user
148013    1.000000
85601     1.000000
434980    1.000000
48786     1.000000
500728    1.000000
386300    1.000000
112521    1.000000
328899    0.707107
469069    0.624695
Name: 434980, dtype: float64

435544
user
305395    0.624695
112416    0.535672
559469    0.487805
52284     0.401754
264572    0.238858
46936     0.191154
485567    0.113226
159353    0.083293
161601    0.000000
Name: 435544, dtype: float64

435599
user
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 435599, dtype: float64

436536
user
419560    0.234261
950331    0.000000
172589    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 436536, dtype: float64

437478
user
354580    0.707107
327058    0.447214
178016    0.376288
211914    0.369274
184471    0.280745
308702    0.194054
469245    0.171701
186286    0.160357
391794    0.085057
Name: 437478, dtype: float64

437764
user
52663     0.524142
190348    0.436436
95703     0.328798
363254    0.270765
190766    0.238637
745537    0.156412
53368     0.124141
172589    0.000000
172770    0.000000
Name: 437764, dtype: float64

439060
user
439060    1.000000
191551    1.000000
405980    1.000000
159583    0.780869
821860    0.565685
546411    0.529813
880907    0.492366
49954     0.421076
175405    0.302614
Name: 439060, dtype: float64

439187
user
851090    1.000000
188061    1.000000
732125    1.000000
439187    1.000000
61770     1.000000
401305    0.894427
263524    0.800000
744990    0.800000
28032     0.800000
Name: 439187, dtype: float64

439699
user
209839    1.000000
439699    1.000000
170268    1.000000
745938    1.000000
463997    1.000000
419353    0.780869
59146     0.707107
609485    0.529813
423674    0.514496
Name: 439699, dtype: float64

440081
user
556845    1.000000
440081    1.000000
148723    1.000000
822237    1.000000
135920    0.577350
201349    0.565685
351808    0.500000
251581    0.345547
106083    0.336861
Name: 440081, dtype: float64

441024
user
356277    0.780869
36636     0.725018
498185    0.624695
725466    0.624695
75433     0.624695
116307    0.624695
470036    0.609756
887586    0.519778
863771    0.413714
Name: 441024, dtype: float64

441050
user
86590     1.000000
136660    1.000000
441050    1.000000
16928     1.000000
62113     0.514496
328775    0.176887
173187    0.000000
173126    0.000000
173141    0.000000
Name: 441050, dtype: float64

441414
user
443480    0.311086
367648    0.311086
134866    0.311086
71046     0.098374
173038    0.000000
172589    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
Name: 441414, dtype: float64

441682
user
362748    0.742781
391405    0.742781
548019    0.742781
584514    0.742781
678384    0.479463
730352    0.320385
103529    0.116797
172946    0.000000
172504    0.000000
Name: 441682, dtype: float64

441889
user
418510    0.707107
126931    0.707107
200652    0.707107
839712    0.707107
148206    0.500000
169585    0.374766
2419      0.331042
33061     0.312348
93647     0.300000
Name: 441889, dtype: float64

442004
user
245621    1.0
314118    1.0
196360    1.0
248626    1.0
290161    1.0
738464    1.0
316074    1.0
442004    1.0
950331    0.0
Name: 442004, dtype: float64

442013
user
442013    1.000000
140829    0.447214
224934    0.404061
950331    0.000000
173141    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
Name: 442013, dtype: float64

442382
user
929369    0.800000
252295    0.511682
728009    0.201948
96360     0.167623
172955    0.000000
172589    0.000000
172770    0.000000
172946    0.000000
950331    0.000000
Name: 442382, dtype: float64

442748
user
824879    0.816497
13006     0.780869
398891    0.707107
382523    0.662266
148702    0.380143
154501    0.362738
67868     0.226455
386997    0.129944
32143     0.069171
Name: 442748, dtype: float64

442981
user
950331    0.0
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 442981, dtype: float64

443344
user
287964    0.512148
551587    0.512148
855097    0.512148
175320    0.512148
50137     0.399920
479278    0.399920
57125     0.384111
292280    0.384111
212461    0.384111
Name: 443344, dtype: float64

443388
user
950331    0.0
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 443388, dtype: float64

443480
user
441414    0.311086
950331    0.000000
172490    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
173126    0.000000
Name: 443480, dtype: float64

443634
user
42540     0.371391
172490    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
173126    0.000000
Name: 443634, dtype: float64

443815
user
362768    1.0
135113    0.8
173325    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 443815, dtype: float64

444150
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 444150, dtype: float64

444370
user
840877    0.707107
129098    0.707107
551576    0.707107
357259    0.707107
295763    0.707107
343008    0.707107
152151    0.707107
354874    0.606339
28304     0.441726
Name: 444370, dtype: float64

445039
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 445039, dtype: float64

445133
user
189901    0.341743
172504    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
Name: 445133, dtype: float64

445292
user
132144    0.20226
950331    0.00000
173146    0.00000
172946    0.00000
172955    0.00000
173038    0.00000
173126    0.00000
173141    0.00000
173218    0.00000
Name: 445292, dtype: float64

445293
user
170852    1.000000
289156    1.000000
74904     0.707107
215860    0.707107
133983    0.700140
93992     0.685994
213694    0.624695
886698    0.600000
153279    0.577350
Name: 445293, dtype: float64

445567
user
362878    0.529813
282032    0.408248
651198    0.348155
217350    0.194772
250495    0.184703
728009    0.161558
173038    0.000000
172770    0.000000
172946    0.000000
Name: 445567, dtype: float64

445612
user
445612    1.000000
423140    1.000000
452036    1.000000
92150     0.894427
334520    0.707107
358118    0.707107
234398    0.624695
132873    0.466252
646881    0.310460
Name: 445612, dtype: float64

445791
user
445791    1.00000
328775    0.14151
950331    0.00000
172589    0.00000
173293    0.00000
173236    0.00000
173218    0.00000
173187    0.00000
173146    0.00000
Name: 445791, dtype: float64

446105
user
9339      0.577350
25134     0.577350
263894    0.529813
89287     0.524142
923208    0.379663
752650    0.374766
420421    0.363803
20363     0.256495
315462    0.214423
Name: 446105, dtype: float64

446157
user
459734    1.000000
546902    1.000000
367815    1.000000
665848    0.762493
725655    0.680414
95336     0.680414
31058     0.615457
171582    0.577350
858004    0.577350
Name: 446157, dtype: float64

446951
user
324856    0.769800
589446    0.577350
129294    0.408248
132873    0.215353
818006    0.211702
5600      0.192450
88901     0.192450
385272    0.136931
26760     0.136797
Name: 446951, dtype: float64

447025
user
447025    1.000000
49486     0.577350
652898    0.284747
172770    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 447025, dtype: float64

447059
user
447059    1.0
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 447059, dtype: float64

447445
user
417735    1.000000
65841     1.000000
340512    1.000000
66639     1.000000
643010    0.970143
667169    0.780869
65433     0.707107
47484     0.707107
870790    0.685994
Name: 447445, dtype: float64

448451
user
539803    0.468165
422401    0.468165
431688    0.468165
790931    0.468165
274810    0.468165
314010    0.468165
46758     0.468165
3123      0.468165
321865    0.468165
Name: 448451, dtype: float64


user
592038    0.742781
153839    0.742781
114663    0.742781
321116    0.742781
89133     0.742781
632364    0.742781
518696    0.580015
343008    0.557086
357259    0.557086
Name: 467642, dtype: float64

467717
user
950331    0.0
172770    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 467717, dtype: float64

467850
user
386149    0.361787
43128     0.361787
471179    0.361787
249441    0.361787
327506    0.361787
174892    0.361787
322689    0.361787
69329     0.255822
740988    0.255822
Name: 467850, dtype: float64

468337
user
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 468337, dtype: float64

468444
user
194231    0.685994
196398    0.396059
169585    0.299813
369062    0.285714
388812    0.231455
257609    0.206835
818006    0.194461
114160    0.176432
44878     0.163846
Name: 468444, dtype: float64

469069
user
342506    0.780869
434550    0.780869
112521    0.624695
500728    0.624695
85601     0.624695
48786     0.624695
148013    0.624695
52558     0.624695
434980    0.624695
Name: 469069, dtype: float64

469245
user
217426    0.178437
446157    0.171701
709700    0.171701
501746    0.171701
551587    0.171701
73020     0.171701
546902    0.171701
133586    0.171701
8323      0.171701
Name: 469245, dtype: float64

469418
user
116307    0.450835
725466    0.450835
113970    0.450835
75433     0.450835
651501    0.442080
887586    0.375117
931768    0.360668
75174     0.360668
48814     0.360668
Name: 469418, dtype: float64

469607
user
48688     0.492366
3906      0.408248
950331    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
173146    0.000000
173187    0.000000
Name: 469607, dtype: float64

470036
user
356277    0.780869
36636     0.725018
498185    0.624695
249441    0.624695
441024    0.609756
863771    0.413714
621199    0.413714
49805     0.390244
389973    0.390244
Name: 470036, dtype: float64

470215
user
798855    1.000000
261998    1.000000
282875    0.928477
114081    0.800000
770493    0.780869
389608    0.707107
887586    0.554700
247634    0.396526
68203     0.390567
Name: 470215, dtype: float64

470252
user
91027     0.707107
64301     0.164399
950331    0.000000
173146    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
173187    0.000000
Name: 470252, dtype: float64

470349
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 470349, dtype: float64

470486
user
470486    1.0
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 470486, dtype: float64

470673
user
501746    0.800000
709700    0.800000
757228    0.800000
42721     0.800000
8323      0.800000
200875    0.800000
899377    0.800000
87724     0.800000
280698    0.565685
Name: 470673, dtype: float64

470723
user
391631    0.385478
207720    0.276501
191023    0.221201
315174    0.221201
2849      0.221201
790247    0.221201
191363    0.221201
896394    0.221201
526951    0.221201
Name: 470723, dtype: float64

470756
user
681355    0.624695
333372    0.260290
248011    0.217491
89781     0.174004
176336    0.000000
172339    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 470756, dtype: float64

471179
user
43128     1.000000
386149    1.000000
322689    1.000000
327506    1.000000
138663    0.577350
269477    0.545545
539244    0.390360
467850    0.361787
96575     0.217250
Name: 471179, dtype: float64

471483
user
196448    0.430331
598467    0.408248
73676     0.360668
74592     0.314970
172339    0.297044
26531     0.288675
46987     0.255031
110306    0.249377
662925    0.244851
Name: 471483, dtype: float64

471642
user
158718    0.948683
560395    0.707107
111192    0.624695
479278    0.624695
369524    0.360668
30196     0.304114
68977     0.296500
744       0.290021
171967    0.000000
Name: 471642, dtype: float64

473329
user
137126    0.685994
327668    0.685994
25002     0.685994
753506    0.514496
614812    0.514496
186572    0.514496
814610    0.514496
648839    0.514496
923681    0.514496
Name: 473329, dtype: float64

473363
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 473363, dtype: float64

473694
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 473694, dtype: float64

473854
user
88172     1.0
692426    1.0
529676    1.0
593945    1.0
944033    1.0
473854    1.0
363134    1.0
569529    1.0
182301    1.0
Name: 473854, dtype: float64

474647
user
474647    1.0
152915    0.5
950331    0.0
173141    0.0
172946    0.0
172955    0.0
173038    0.0
173126    0.0
173187    0.0
Name: 474647, dtype: float64

474854
user
88482     1.000000
318030    0.290957
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173300    0.000000
172504    0.000000
173146    0.000000
Name: 474854, dtype: float64

475084
user
889321    0.552158
696729    0.441726
137021    0.441726
793692    0.441726
818821    0.441726
314002    0.433148
140454    0.365675
242673    0.312348
745127    0.275944
Name: 475084, dtype: float64

475240
user
752281    1.000000
475240    1.000000
111719    1.000000
227401    1.000000
641062    1.000000
213776    1.000000
100771    1.000000
805528    0.707107
110095    0.707107
Name: 475240, dtype: float64

475865
user
92831     1.000000
475865    1.000000
318073    1.000000
420587    1.000000
398867    0.780869
3357      0.707107
518696    0.624695
13006     0.624695
613041    0.577350
Name: 475865, dtype: float64

476529
user
199034    1.000000
753519    1.000000
318884    1.000000
476529    1.000000
284559    0.894427
105338    0.662266
212036    0.529813
361582    0.333333
820908    0.246932
Name: 476529, dtype: float64

476674
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 476674, dtype: float64

476834
user
427412    0.857493
394365    0.857493
902808    0.857493
60853     0.514496
841437    0.514496
292194    0.495074
255287    0.363803
872014    0.311959
662925    0.290926
Name: 476834, dtype: float64

477119
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 477119, dtype: float64

477575
user
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 477575, dtype: float64

477891
user
477891    1.0
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 477891, dtype: float64

479054
user
479054    1.0
950331    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 479054, dtype: float64

479148
user
69019     0.221187
950331    0.000000
173421    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 479148, dtype: float64

479278
user
175320    0.780869
551587    0.780869
471642    0.624695
50137     0.609756
158718    0.592638
51466     0.552158
369524    0.506942
115161    0.450835
560395    0.441726
Name: 479278, dtype: float64

479885
user
691613    1.000000
363072    0.577350
373775    0.421076
196398    0.420084
568971    0.231455
923459    0.198680
25840     0.187936
138574    0.082479
950331    0.000000
Name: 479885, dtype: float64

480616
user
219406    1.000000
879926    1.000000
833785    1.000000
480616    1.000000
463007    1.000000
250828    1.000000
551133    0.545545
135672    0.278207
283160    0.201008
Name: 480616, dtype: float64

481086
user
950331    0.0
172770    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 481086, dtype: float64

481150
user
481150    1.000000
502763    0.468521
923459    0.264906
173146    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
Name: 481150, dtype: float64

481314
user
950331    0.0
172770    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 481314, dtype: float64

481628
user
138572    0.831890
936541    0.776114
591369    0.776114
292085    0.535672
68203     0.505207
68977     0.287647
315073    0.242536
589791    0.149696
20363     0.149302
Name: 481628, dtype: float64

482083
user
950331    0.0
172770    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 482083, dtype: float64

482273
user
149905    1.000000
67211     0.707107
252734    0.624695
397051    0.606339
201482    0.577350
95985     0.441726
514754    0.383482
31285     0.380143
149174    0.365148
Name: 482273, dtype: float64

483311
user
950331    0.0
172770    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 483311, dtype: float64

484341
user
484341    1.000000
314531    0.431934
424678    0.424264
224347    0.279372
364545    0.177778
328775    0.141510
171636    0.000000
173146    0.000000
173038    0.000000
Name: 484341, dtype: float64

484527
user
157928    0.857493
117820    0.408248
32143     0.138343
173187    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
173146    0.000000
173218    0.000000
Name: 484527, dtype: float64

485567
user
127163    0.18125
200875    0.18125
42721     0.18125
658169    0.18125
757228    0.18125
218625    0.18125
819615    0.18125
501746    0.18125
62880     0.18125
Name: 485567, dtype: float64

485651
user
485651    1.000000
386315    0.707107
171636    0.000000
172946    0.000000
171582    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
Name: 485651, dtype: float64

485831
user
133586    0.529813
85669     0.264906
861992    0.260862
385272    0.167542
243883    0.152944
153457    0.139812
82952     0.131939
138574    0.131095
25840     0.124464
Name: 485831, dtype: float64

486907
user
284357    0.214115
172589    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
Name: 486907, dtype: float64

487327
user
82581     1.0
487327    1.0
652607    1.0
42615     1.0
7488      1.0
721140    1.0
645667    1.0
664747    1.0
192450    1.0
Name: 487327, dtype: float64

487400
user
487400    1.000000
159773    1.000000
342978    1.000000
106216    1.000000
899670    1.000000
267306    1.000000
203033    1.000000
177362    0.970143
135354    0.707107
Name: 487400, dtype: float64

487583
user
325116    0.707107
328775    0.141510
950331    0.000000
172589    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 487583, dtype: float64

487983
user
45013     1.000000
26705     0.577350
579521    0.319801
172770    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 487983, dtype: float64

488321
user
611711    1.000000
553056    1.000000
488321    1.000000
74871     1.000000
117432    0.707107
158492    0.624695
169063    0.600000
44555     0.529813
392992    0.492366
Name: 488321, dtype: float64

488536
user
108338    0.36823
950331    0.00000
172504    0.00000
173293    0.00000
173236    0.00000
173218    0.00000
173187    0.00000
173146    0.00000
173141    0.00000
Name: 488536, dtype: float64

488981
user
91242     1.000000
722512    0.680414
728692    0.650945
288451    0.327327
783096    0.214286
171678    0.000000
172946    0.000000
173300    0.000000
173293    0.000000
Name: 488981, dtype: float64

489209
user
489209    1.000000
789449    1.000000
114625    1.000000
127610    1.000000
867166    0.780869
662901    0.707107
116016    0.707107
876665    0.624695
263524    0.600000
Name: 489209, dtype: float64

491073
user
112180    1.000000
143267    1.000000
632235    1.000000
133152    1.000000
491073    1.000000
606877    1.000000
937146    0.894427
322423    0.800000
71789     0.615457
Name: 491073, dtype: float64

491271
user
950331    0.0
172770    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 491271, dtype: float64

491529
user
618570    0.780869
5121      0.780869
407842    0.624695
677628    0.624695
725655    0.531314
424678    0.441726
79647     0.433148
398557    0.360668
795084    0.349215
Name: 491529, dtype: float64

491634
user
356446    0.685994
127821    0.685994
657132    0.297044
788114    0.142695
322019    0.133120
950331    0.000000
173038    0.000000
172946    0.000000
172955    0.000000
Name: 491634, dtype: float64

491888
user
49680     0.261116
109622    0.194054
386997    0.173259
950331    0.000000
173187    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
173146    0.000000
Name: 491888, dtype: float64

492063
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 492063, dtype: float64

492093
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 492093, dtype: float64

492757
user
492757    1.000000
325116    0.707107
22608     0.662266
507738    0.492366
115600    0.468521
224347    0.279372
284357    0.214115
237668    0.180746
728009    0.161558
Name: 492757, dtype: float64

493166
user
725655    0.272166
745243    0.242536
173146    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
950331    0.000000
Name: 493166, dtype: float64

493676
user
493676    1.000000
130120    1.000000
360460    1.000000
434598    1.000000
65433     0.565685
249595    0.514496
401935    0.424264
245897    0.225018
237668    0.144597
Name: 493676, dtype: float64

493816
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 493816, dtype: float64

495187
user
725789    0.198030
156230    0.135147
950331    0.000000
172504    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
Name: 495187, dtype: float64

495195
user
169636    1.000000
495195    1.000000
314348    0.360668
264572    0.305888
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
Name: 495195, dtype: float64

495957
user
155148    0.894427
68750     0.558744
724982    0.231043
950331    0.000000
173141    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
Name: 495957, dtype: float64

497072
user
497072    1.0
950331    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 497072, dtype: float64

497255
user
526184    1.0
950331    0.0
173126    0.0
172589    0.0
172770    0.0
172946    0.0
172955    0.0
173038    0.0
173146    0.0
Name: 497255, dtype: float64

497603
user
654512    1.0
950331    0.0
172490    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
173126    0.0
Name: 497603, dtype: float64

498185
user
356277    0.800000
36636     0.742781
441024    0.624695
470036    0.624695
190564    0.600000
863771    0.423850
887956    0.364674
252295    0.341121
359001    0.323249
Name: 498185, dtype: float64

498923
user
386131    0.615457
538853    0.615457
380154    0.615457
82581     0.492366
294354    0.492366
487327    0.492366
790296    0.492366
703432    0.492366
886362    0.492366
Name: 498923, dtype: float64

499267
user
499267    1.000000
449148    0.707107
9895      0.615457
315596    0.577350
261456    0.544331
170611    0.292509
105881    0.290957
269509    0.268328
49642     0.243396
Name: 499267, dtype: float64

500162
user
387274    0.662266
389273    0.662266
315852    0.529813
404491    0.296174
420805    0.157378
485567    0.096029
172770    0.000000
172946    0.000000
172955    0.000000
Name: 500162, dtype: float64

500209
user
124281    1.000000
714243    1.000000
132954    0.577350
213564    0.341793
226106    0.294174
218901    0.128271
173038    0.000000
172589    0.000000
172770    0.000000
Name: 500209, dtype: float64

500373
user
33053     0.707107
392680    0.707107
557847    0.624695
225910    0.441726
807425    0.414781
73273     0.372678
74999     0.242091
44878     0.231714
318030    0.218218
Name: 500373, dtype: float64

500654
user
753900    1.000000
191568    1.000000
117432    0.707107
572720    0.303728
68122     0.280976
186286    0.213809
173187    0.000000
173146    0.000000
172589    0.000000
Name: 500654, dtype: float64

500728
user
148013    1.000000
85601     1.000000
434980    1.000000
48786     1.000000
500728    1.000000
386300    1.000000
112521    1.000000
328899    0.707107
469069    0.624695
Name: 500728, dtype: float64

500916
user
360002    1.000000
387478    1.000000
131497    0.577350
114257    0.577350
74592     0.545545
26531     0.500000
725789    0.495074
702417    0.386912
674425    0.300000
Name: 500916, dtype: float64

501275
user
315530    0.615457
697795    0.492366
351552    0.492366
290566    0.369274
84840     0.362103
71595     0.355335
30101     0.240377
399680    0.208810
255258    0.202361
Name: 501275, dtype: float64

501408
user
90754     0.228292
172490    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
173126    0.000000
Name: 501408, dtype: float64

501746
user
899377    1.000000
42721     1.000000
709700    1.000000
757228    1.000000
87724     1.000000
8323      1.000000
501746    1.000000
470673    0.800000
131375    0.707107
Name: 501746, dtype: float64

501799
user
112268    0.577350
281932    0.408248
44555     0.382360
351878    0.321634
823651    0.214423
314604    0.202721
155466    0.201008
308702    0.112037
129333    0.086173
Name: 501799, dtype: float64

502438
user
950331    0.0
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 502438, dtype: float64

502484
user
648839    1.0
783345    1.0
111561    1.0
786717    1.0
753506    1.0
314345    1.0
596425    1.0
257101    1.0
44077     1.0
Name: 502484, dtype: float64

502763
user
481150    0.468521
53199     0.468521
126946    0.441726
388812    0.340799
9895      0.307579
745622    0.255031
224934    0.189311
127124    0.159811
923459    0.124114
Name: 502763, dtype: float64

503594
user
838116    0.624695
348677    0.441726
287074    0.365854
69676     0.264870
386997    0.108234
218901    0.106840
728009    0.100925
173141    0.000000
172589    0.000000
Name: 503594, dtype: float64

503661
user
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
173126    0.0
Name: 503661, dtype: float64

504329
user
755162    0.707107
817844    0.606339
197504    0.294884
96320     0.282166
178898    0.231455
72849     0.189405
215042    0.180187
816423    0.167054
68632     0.142451
Name: 504329, dtype: float64

504649
user
107432    1.000000
504649    1.000000
112616    1.000000
47297     1.000000
85705     1.000000
874578    0.980581
855363    0.780869
192236    0.780869
3019      0.762493
Name: 504649, dtype: float64

504746
user
392082    0.342951
516840    0.307144
488321    0.268802
5239      0.268802
611711    0.268802
394954    0.268802
553056    0.268802
74871     0.268802
248496    0.215041
Name: 504746, dtype: float64

505087
user
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 505087, dtype: float64

505806
user

user
565885    0.577350
841181    0.577350
67902     0.577350
389789    0.566139
788114    0.266880
694627    0.158777
96575     0.125429
315462    0.092848
172955    0.000000
Name: 519716, dtype: float64

520609
user
477891    1.0
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 520609, dtype: float64

520926
user
520926    1.000000
326607    0.552158
259415    0.502519
744060    0.447214
173141    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
Name: 520926, dtype: float64

521174
user
64301     0.205499
173146    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
173187    0.000000
Name: 521174, dtype: float64

521321
user
461939    1.000000
656737    1.000000
321090    1.000000
293102    0.948683
830007    0.365148
572720    0.303728
818006    0.183340
391794    0.085057
161129    0.000000
Name: 521321, dtype: float64

521785
user
415277    1.000000
397119    0.292603
950331    0.000000
172589    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 521785, dtype: float64

521972
user
545656    1.0
950331    0.0
172490    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
173126    0.0
Name: 521972, dtype: float64

522093
user
855097    0.577350
443344    0.295689
745537    0.067729
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
172490    0.000000
Name: 522093, dtype: float64

522619
user
789611    1.000000
377242    1.000000
24308     1.000000
612464    0.218218
173187    0.000000
173146    0.000000
173141    0.000000
173218    0.000000
173126    0.000000
Name: 522619, dtype: float64

522869
user
48104     0.707107
59764     0.707107
12285     0.500000
388041    0.500000
247348    0.468293
859147    0.460287
171582    0.408248
699447    0.408248
195147    0.357143
Name: 522869, dtype: float64

523537
user
315118    0.258738
820908    0.148159
950331    0.000000
173038    0.000000
172589    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173141    0.000000
Name: 523537, dtype: float64

524501
user
23533     1.0
317949    1.0
158717    1.0
524501    1.0
820044    1.0
739296    1.0
946187    1.0
465115    1.0
835141    1.0
Name: 524501, dtype: float64

524526
user
309828    1.000000
250513    1.000000
461917    1.000000
105989    1.000000
197893    1.000000
63622     1.000000
252432    1.000000
721134    0.970143
721787    0.707107
Name: 524526, dtype: float64

525593
user
30196     0.304114
950331    0.000000
173146    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
173218    0.000000
Name: 525593, dtype: float64

526184
user
526184    1.0
950331    0.0
173126    0.0
172589    0.0
172770    0.0
172946    0.0
172955    0.0
173038    0.0
173146    0.0
Name: 526184, dtype: float64

526951
user
27703     0.404061
5142      0.327327
71205     0.259828
752650    0.224860
470723    0.221201
173293    0.000000
173236    0.000000
173218    0.000000
173300    0.000000
Name: 526951, dtype: float64

527242
user
950331    0.0
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 527242, dtype: float64

527488
user
950331    0.0
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 527488, dtype: float64

527607
user
886698    0.624695
322844    0.413714
505806    0.241702
46592     0.211548
305856    0.190010
156952    0.155591
247421    0.146838
724982    0.107578
90296     0.098576
Name: 527607, dtype: float64

527869
user
950331    0.0
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 527869, dtype: float64

528915
user
689905    0.580015
360246    0.441726
163709    0.321403
50553     0.264870
390564    0.169239
950331    0.000000
173146    0.000000
173038    0.000000
173126    0.000000
Name: 528915, dtype: float64

529160
user
196651    0.656532
325034    0.552158
763655    0.441726
327420    0.328266
95916     0.288675
3816      0.262071
89963     0.244339
130044    0.203991
401684    0.198889
Name: 529160, dtype: float64

529676
user
88172     1.0
692426    1.0
529676    1.0
593945    1.0
944033    1.0
473854    1.0
363134    1.0
569529    1.0
182301    1.0
Name: 529676, dtype: float64

530433
user
793074    0.297044
63030     0.264039
254239    0.264039
328802    0.264039
400694    0.264039
73653     0.264039
162500    0.264039
65017     0.245154
158492    0.231953
Name: 530433, dtype: float64

530618
user
57262     1.000000
388333    1.000000
880907    0.615457
250495    0.184703
256163    0.178529
884890    0.174574
171853    0.000000
173293    0.000000
173236    0.000000
Name: 530618, dtype: float64

531322
user
159381    0.500000
40447     0.500000
321082    0.500000
85785     0.500000
314002    0.490290
745127    0.312348
397183    0.312348
220853    0.282843
28600     0.262071
Name: 531322, dtype: float64

531388
user
85149     0.928477
335411    0.928477
6899      0.928477
224662    0.928477
352716    0.928477
136730    0.928477
353104    0.928477
536176    0.725018
169956    0.656532
Name: 531388, dtype: float64

532525
user
348677    0.707107
169657    0.685994
197936    0.624695
172770    0.416025
363254    0.270765
190766    0.238637
172946    0.000000
172955    0.000000
173038    0.000000
Name: 532525, dtype: float64

532620
user
743850    0.235702
489209    0.235702
789449    0.235702
114625    0.235702
127610    0.235702
867166    0.184053
662901    0.166667
116016    0.166667
876665    0.147242
Name: 532620, dtype: float64

532636
user
950331    0.0
173415    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 532636, dtype: float64

532651
user
439060    1.000000
191551    1.000000
405980    1.000000
159583    0.780869
821860    0.565685
546411    0.529813
880907    0.492366
49954     0.421076
175405    0.302614
Name: 532651, dtype: float64

532716
user
186572    0.707107
814610    0.707107
783345    0.707107
111561    0.707107
786717    0.707107
753506    0.707107
314345    0.707107
596425    0.707107
257101    0.707107
Name: 532716, dtype: float64

534410
user
887400    0.466252
303595    0.373002
350938    0.373002
127163    0.373002
922709    0.373002
179325    0.373002
785864    0.373002
149955    0.373002
402496    0.373002
Name: 534410, dtype: float64

534551
user
280011    0.857493
665344    0.606339
890235    0.527750
745622    0.466760
85694     0.383482
189901    0.366303
872014    0.187175
68632     0.172747
249051    0.072439
Name: 534551, dtype: float64

534984
user
682485    0.762493
937122    0.707107
389198    0.615457
650202    0.319235
133993    0.213504
171871    0.000000
173038    0.000000
173325    0.000000
173300    0.000000
Name: 534984, dtype: float64

535452
user
288042    0.624695
197585    0.624695
339218    0.624695
380394    0.624695
270590    0.624695
658169    0.468521
865559    0.468521
819615    0.468521
140023    0.468521
Name: 535452, dtype: float64

536176
user
224662    0.780869
136730    0.780869
335411    0.780869
352716    0.780869
85149     0.780869
353104    0.780869
6899      0.780869
531388    0.725018
169956    0.552158
Name: 536176, dtype: float64

536199
user
835141    0.970143
815556    0.970143
136661    0.970143
319105    0.970143
30184     0.970143
739296    0.970143
820044    0.970143
524501    0.970143
158717    0.970143
Name: 536199, dtype: float64

536447
user
950331    0.0
173415    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 536447, dtype: float64

537282
user
249802    0.600000
107593    0.542326
112229    0.529813
840293    0.435194
149300    0.341793
900562    0.329690
816423    0.315000
18783     0.239426
173187    0.000000
Name: 537282, dtype: float64

537352
user
890873    1.000000
537352    1.000000
251629    1.000000
949019    0.577350
856133    0.307148
194387    0.305888
224347    0.279372
568971    0.231455
745537    0.156412
Name: 537352, dtype: float64

537372
user
588404    0.470882
846528    0.452267
223400    0.232689
840243    0.222681
730158    0.206910
638780    0.206162
31624     0.202260
132873    0.168696
832609    0.150756
Name: 537372, dtype: float64

537947
user
149576    1.000000
775813    1.000000
333372    0.666667
247348    0.529813
260469    0.386695
705731    0.270295
173218    0.000000
173187    0.000000
173146    0.000000
Name: 537947, dtype: float64

538359
user
318832    0.8
950331    0.0
172504    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 538359, dtype: float64

538853
user
864848    0.780869
498923    0.615457
68122     0.374634
361303    0.174078
808328    0.129099
950331    0.000000
173126    0.000000
172946    0.000000
172955    0.000000
Name: 538853, dtype: float64

539244
user
397331    0.39036
323037    0.39036
105931    0.39036
158378    0.39036
12225     0.39036
386149    0.39036
471179    0.39036
322689    0.39036
43128     0.39036
Name: 539244, dtype: float64

539803
user
422401    1.000000
321865    1.000000
677778    1.000000
254215    1.000000
46758     1.000000
539803    1.000000
418830    0.707107
179653    0.600000
305522    0.524142
Name: 539803, dtype: float64

540675
user
950331    0.0
172504    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
173126    0.0
Name: 540675, dtype: float64

542897
user
648265    0.707107
11951     0.279372
249051    0.187729
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
950331    0.000000
Name: 542897, dtype: float64

543432
user
543432    1.000000
359997    0.780869
950331    0.000000
173141    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173146    0.000000
Name: 543432, dtype: float64

543595
user
950331    0.0
172504    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
173126    0.0
Name: 543595, dtype: float64

544656
user
544656    1.000000
212969    0.295689
572720    0.242983
173126    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173141    0.000000
172589    0.000000
Name: 544656, dtype: float64

545656
user
545656    1.0
950331    0.0
172490    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
173126    0.0
Name: 545656, dtype: float64

545730
user
950331    0.0
172504    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
173126    0.0
Name: 545730, dtype: float64

546256
user
501746    0.57735
42721     0.57735
87724     0.57735
305160    0.57735
899377    0.57735
200875    0.57735
8323      0.57735
757228    0.57735
709700    0.57735
Name: 546256, dtype: float64

546411
user
880907    0.586939
439060    0.529813
105931    0.529813
191551    0.529813
532651    0.529813
85315     0.529813
405980    0.529813
256861    0.529813
558567    0.529813
Name: 546411, dtype: float64

546534
user
857499    0.73721
530433    0.19803
173038    0.00000
172504    0.00000
172589    0.00000
172770    0.00000
172946    0.00000
172955    0.00000
950331    0.00000
Name: 546534, dtype: float64

546554
user
279652    0.082580
190725    0.074125
318030    0.057061
364545    0.026149
173038    0.000000
172504    0.000000
172589    0.000000
172770    0.000000
172946    0.000000
Name: 546554, dtype: float64

546902
user
459734    1.000000
546902    1.000000
367815    1.000000
665848    0.762493
725655    0.680414
95336     0.680414
31058     0.615457
171582    0.577350
858004    0.577350
Name: 546902, dtype: float64

547062
user
388883    0.5547
172504    0.0000
173300    0.0000
173293    0.0000
173236    0.0000
173218    0.0000
173187    0.0000
173146    0.0000
173141    0.0000
Name: 547062, dtype: float64

548019
user
391405    1.000000
584514    1.000000
362748    1.000000
441682    0.742781
678384    0.645497
730352    0.431331
950331    0.000000
172946    0.000000
172504    0.000000
Name: 548019, dtype: float64

548644
user
708493    0.39736
950331    0.00000
172504    0.00000
173293    0.00000
173236    0.00000
173218    0.00000
173187    0.00000
173146    0.00000
173141    0.00000
Name: 548644, dtype: float64

550014
user
22268     0.541435
253153    0.490290
253154    0.490290
1028      0.416025
74344     0.332820
45978     0.266091
787677    0.240192
274267    0.240192
128615    0.230769
Name: 550014, dtype: float64

550031
user
869332    1.000000
550031    1.000000
195546    0.845154
903681    0.514496
351825    0.404061
950331    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
Name: 550031, dtype: float64

550105
user
550105    1.000000
195147    0.404061
192676    0.389249
319153    0.358569
321572    0.323381
224347    0.279372
173187    0.000000
173146    0.000000
173141    0.000000
Name: 550105, dtype: float64

550554
user
10258     0.832050
823508    0.554700
353976    0.554700
149737    0.554700
222092    0.554700
131505    0.554700
65345     0.554700
195083    0.554700
156156    0.416025
Name: 550554, dtype: float64

551060
user
42484     0.370625
950331    0.000000
173141    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173146    0.000000
Name: 551060, dtype: float64

551133
user
480616    0.545545
839006    0.545545
879926    0.545545
833785    0.545545
463007    0.545545
250828    0.545545
219406    0.545545
91342     0.327327
135672    0.151775
Name: 551133, dtype: float64

551366
user
551366    1.000000
283360    0.577350
157653    0.474579
85130     0.472456
219293    0.431934
48793     0.424094
365596    0.368230
391631    0.299813
51405     0.268028
Name: 551366, dtype: float64

551576
user
129098    1.000000
840877    1.000000
551576    1.000000
444370    0.707107
28304     0.624695
50137     0.624695
92767     0.424264
127843    0.400892
652898    0.284747
Name: 551576, dtype: float64

551587
user
175320    1.000000
479278    0.780869
50137     0.780869
51466     0.707107
115161    0.577350
443344    0.512148
110348    0.492366
117370    0.464238
409870    0.461880
Name: 551587, dtype: float64

552621
user
106083    0.252646
11951     0.209529
172504    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
Name: 552621, dtype: float64

553056
user
611711    1.000000
553056    1.000000
488321    1.000000
74871     1.000000
117432    0.707107
158492    0.624695
169063    0.600000
44555     0.529813
392992    0.492366
Name: 553056, dtype: float64

553649
user
74527     0.261116
172589    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 553649, dtype: float64

554398
user
908860    0.707107
351982    0.707107
152603    0.707107
209415    0.707107
208774    0.707107
201162    0.707107
644110    0.707107
292003    0.500000
848512    0.500000
Name: 554398, dtype: float64

554633
user
603870    0.970143
752559    0.242536
172955    0.242536
190973    0.194029
380098    0.194029
728009    0.156735
314366    0.140028
322597    0.097405
224347    0.067758
Name: 554633, dtype: float64

556430
user
556430    1.000000
388521    1.000000
183668    0.617213
252216    0.303239
170611    0.292509
22782     0.280976
173187    0.000000
173146    0.000000
172589    0.000000
Name: 556430, dtype: float64

556749
user
179653    0.800000
418830    0.707107
688218    0.565685
305522    0.524142
230662    0.404061
106056    0.281439
171582    0.000000
172504    0.000000
173236    0.000000
Name: 556749, dtype: float64

556845
user
556845    1.000000
440081    1.000000
148723    1.000000
822237    1.000000
135920    0.577350
201349    0.565685
351808    0.500000
251581    0.345547
106083    0.336861
Name: 556845, dtype: float64

556848
user
556848    1.000000
882571    0.325396
950331    0.000000
172589    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 556848, dtype: float64

557460
user
406004    1.0
557460    1.0
73069     1.0
950331    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 557460, dtype: float64

557732
user
386287    1.000000
171329    1.000000
351769    1.000000
1557      1.000000
21052     1.000000
557732    1.000000
219148    0.780869
392992    0.615457
684910    0.404061
Name: 557732, dtype: float64

557834
user
397502    1.000000
155466    0.435194
219293    0.431934
24614     0.397360
386997    0.173259
32143     0.069171
173236    0.000000
173218    0.000000
173187    0.000000
Name: 557834, dtype: float64

557847
user
159824    0.780869
428771    0.780869
558567    0.780869
277858    0.780869
85315     0.780869
106580    0.780869
72150     0.780869
67429     0.780869
194342    0.780869
Name: 557847, dtype: float64

557866
user
350778    1.000000
557866    1.000000
332711    1.000000
586606    0.742781
506648    0.624695
88881     0.615457
274267    0.577350
24614     0.529813
93992     0.514496
Name: 557866, dtype: float64

558567
user
389047    1.0
558567    1.0
277858    1.0
256861    1.0
159824    1.0
67429     1.0
106580    1.0
72150     1.0
726820    1.0
Name: 558567, dtype: float64

558763
user
950331    0.0
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 558763, dtype: float64

559469
user
305395    0.780869
112416    0.669589
435544    0.487805
682731    0.441726
833379    0.120720
159353    0.104116
173218    0.000000
173187    0.000000
173146    0.000000
Name: 559469, dtype: float64

559832
user
281932    0.707107
616058    0.483368
950331    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
173126    0.000000
Name: 559832, dtype: float64

559873
user
559873    1.0
950331    0.0
173415    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 559873, dtype: float64

560061
user
50758     1.000000
23999     1.000000
224421    0.624695
116524    0.492366
127843    0.400892
74527     0.348155
315409    0.312348
174016    0.307794
397119    0.292603
Name: 560061, dtype: float64

560395
user
471642    0.707107
715137    0.707107
459047    0.707107
158718    0.670820
568330    0.552158
52776     0.500000
479278    0.441726
111192    0.441726
170419    0.408248
Name: 560395, dtype: float64

561345
user
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 561345, dtype: float64

561646
user
213301    0.093149
950331    0.000000
172589    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 561646, dtype: float64

561911
user
107324    1.000000
561911    1.000000
148730    0.780869
636781    0.208514
173126    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
Name: 561911, dtype: float64

562119
user
93916     1.000000
562119    1.000000
352205    0.707107
328775    0.141510
53368     0.124141
175875    0.000000
172490    0.000000
176544    0.000000
173187    0.000000
Name: 562119, dtype: float64

562349
user
96613     1.000000
562349    1.000000
428481    0.800000
702397    0.707107
836215    0.600000
26705     0.577350
423018    0.514496
292085    0.441726
88418     0.416025
Name: 562349, dtype: float64

562381
user
562381    1.000000
282047    0.577350
347289    0.500000
290423    0.424094
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
172770    0.000000
Name: 562381, dtype: float64

562787
user
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0

Name: 574807, dtype: float64

576148
user
132614    0.492366
950331    0.000000
173141    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173146    0.000000
Name: 576148, dtype: float64

576558
user
576558    1.000000
339564    1.000000
132873    0.373002
174016    0.307794
25840     0.234920
397635    0.230769
156230    0.202721
724982    0.103325
172770    0.000000
Name: 576558, dtype: float64

578647
user
82581     1.0
487327    1.0
652607    1.0
42615     1.0
7488      1.0
721140    1.0
645667    1.0
664747    1.0
192450    1.0
Name: 578647, dtype: float64

578969
user
286962    1.000000
268107    1.000000
899799    0.707107
33179     0.544331
85626     0.492366
855589    0.441726
171967    0.327693
179719    0.308607
665569    0.295141
Name: 578969, dtype: float64

579173
user
418950    1.000000
367276    1.000000
637343    1.000000
881924    1.000000
90754     0.171219
175469    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 579173, dtype: float64

579521
user
76564     0.533002
63763     0.533002
148777    0.533002
113896    0.533002
194777    0.533002
148169    0.533002
44204     0.533002
940225    0.533002
89712     0.494880
Name: 579521, dtype: float64

579530
user
321082    0.419314
804396    0.419314
85785     0.419314
197268    0.406794
50553     0.355578
366858    0.327429
170923    0.314485
321594    0.314485
87516     0.314485
Name: 579530, dtype: float64

579661
user
950331    0.0
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 579661, dtype: float64

580520
user
194889    0.260378
800496    0.260378
15289     0.260378
25951     0.260378
591817    0.260378
191501    0.260378
647331    0.260378
661090    0.216647
259123    0.195283
Name: 580520, dtype: float64

580564
user
388156    1.0
950331    0.0
172504    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 580564, dtype: float64

581612
user
366741    0.360668
947671    0.333333
391631    0.224860
51405     0.214423
53368     0.041380
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
Name: 581612, dtype: float64

582183
user
582183    1.000000
195632    1.000000
260179    1.000000
811088    0.492366
1582      0.369274
29491     0.368230
159353    0.266667
114074    0.117242
950331    0.000000
Name: 582183, dtype: float64

582482
user
648676    1.000000
169608    1.000000
46312     1.000000
582482    1.000000
87328     0.780869
219577    0.547723
347289    0.500000
856133    0.245718
249051    0.234662
Name: 582482, dtype: float64

582741
user
950331    0.0
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 582741, dtype: float64

583035
user
45617     0.707107
686300    0.316228
807425    0.311086
173141    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173146    0.000000
Name: 583035, dtype: float64

584514
user
391405    1.000000
584514    1.000000
362748    1.000000
441682    0.742781
678384    0.645497
730352    0.431331
950331    0.000000
172946    0.000000
172504    0.000000
Name: 584514, dtype: float64

584895
user
584895    1.000000
391957    0.305995
724982    0.172209
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
172504    0.000000
173141    0.000000
Name: 584895, dtype: float64

585245
user
950331    0.0
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 585245, dtype: float64

586606
user
350778    0.742781
557866    0.742781
332711    0.742781
114908    0.742781
506648    0.464012
88881     0.457150
274267    0.428845
24614     0.393535
93992     0.382158
Name: 586606, dtype: float64

588237
user
870138    0.928477
35538     0.742781
172504    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
Name: 588237, dtype: float64

588404
user
706290    0.624695
872014    0.530288
537372    0.470882
827709    0.468521
678906    0.468521
108796    0.468521
389377    0.468521
323358    0.468521
194541    0.468521
Name: 588404, dtype: float64

589446
user
129294    0.707107
446951    0.577350
132873    0.373002
818006    0.366679
385272    0.237171
26760     0.236940
173146    0.000000
173141    0.000000
173126    0.000000
Name: 589446, dtype: float64

589569
user
589569    1.0
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 589569, dtype: float64

589791
user
95560     0.617213
315073    0.617213
256176    0.617213
632364    0.462910
114663    0.462910
321116    0.462910
153839    0.462910
89133     0.462910
592038    0.462910
Name: 589791, dtype: float64

589868
user
259023    0.441176
138541    0.297044
175469    0.257248
113023    0.257248
247421    0.161247
514754    0.157840
651198    0.134343
308702    0.133120
728009    0.083121
Name: 589868, dtype: float64

590203
user
464677    0.57735
950331    0.00000
173325    0.00000
173293    0.00000
173236    0.00000
173218    0.00000
173187    0.00000
173146    0.00000
173141    0.00000
Name: 590203, dtype: float64

591073
user
591073    1.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 591073, dtype: float64

591332
user
26506     1.0
950331    0.0
173415    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 591332, dtype: float64

591369
user
481628    0.776114
138572    0.685994
936541    0.640000
55705     0.600000
780237    0.600000
321692    0.600000
22636     0.600000
37980     0.600000
222975    0.600000
Name: 591369, dtype: float64

591817
user
353401    0.492366
260469    0.386695
46560     0.267860
580520    0.260378
249051    0.187729
218901    0.171028
470723    0.165900
175405    0.000000
175356    0.000000
Name: 591817, dtype: float64

592038
user
632364    1.000000
321116    1.000000
592038    1.000000
114663    1.000000
153839    1.000000
518696    0.780869
467642    0.742781
611078    0.529813
658421    0.500000
Name: 592038, dtype: float64

592634
user
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 592634, dtype: float64

592764
user
49529     1.000000
868283    1.000000
694627    0.366679
420805    0.297044
163884    0.237356
900562    0.197814
179727    0.088216
173218    0.000000
173187    0.000000
Name: 592764, dtype: float64

593182
user
73020     0.2199
1521      0.2199
367815    0.2199
130789    0.2199
821511    0.2199
546902    0.2199
382215    0.2199
446157    0.2199
606979    0.2199
Name: 593182, dtype: float64

593945
user
88172     1.0
692426    1.0
529676    1.0
593945    1.0
944033    1.0
473854    1.0
363134    1.0
569529    1.0
182301    1.0
Name: 593945, dtype: float64

593954
user
169215    0.485643
43207     0.485643
38120     0.485643
2175      0.485643
230190    0.485643
882402    0.485643
648094    0.485643
642214    0.485643
465152    0.485643
Name: 593954, dtype: float64

594845
user
728464    1.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 594845, dtype: float64

594913
user
787980    0.182089
135937    0.090075
25840     0.069798
534410    0.069265
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
Name: 594913, dtype: float64

596177
user
781898    0.295487
103304    0.157991
950331    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 596177, dtype: float64

596222
user
613041    0.140028
11203     0.112022
950331    0.000000
173038    0.000000
172589    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173141    0.000000
Name: 596222, dtype: float64

596425
user
648839    1.0
783345    1.0
111561    1.0
786717    1.0
753506    1.0
314345    1.0
596425    1.0
257101    1.0
44077     1.0
Name: 596425, dtype: float64

597189
user
710291    0.263117
172504    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
173126    0.000000
Name: 597189, dtype: float64

597369
user
721140    0.6
703432    0.6
7488      0.6
82581     0.6
294354    0.6
352512    0.6
886362    0.6
578647    0.6
790296    0.6
Name: 597369, dtype: float64

597706
user
918992    1.0
109916    0.6
950331    0.0
173300    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 597706, dtype: float64

597752
user
109583    1.000000
642082    1.000000
280872    0.624695
322597    0.321288
705731    0.270295
504746    0.215041
814144    0.192450
215042    0.101929
175043    0.000000
Name: 597752, dtype: float64

598467
user
358700    0.707107
201157    0.707107
219760    0.707107
792019    0.707107
23255     0.707107
794785    0.707107
506648    0.552158
149784    0.500000
848512    0.500000
Name: 598467, dtype: float64

599605
user
754864    0.445435
950331    0.000000
172589    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
Name: 599605, dtype: float64

599838
user
648676    1.000000
169608    1.000000
46312     1.000000
582482    1.000000
87328     0.780869
219577    0.547723
347289    0.500000
856133    0.245718
249051    0.234662
Name: 599838, dtype: float64

599892
user
219299    1.000000
879835    1.000000
780657    1.000000
599892    1.000000
350912    0.780869
132734    0.624695
85808     0.408248
256163    0.133897
580520    0.130189
Name: 599892, dtype: float64

600241
user
158717    0.396526
524501    0.396526
30184     0.396526
194854    0.396526
23533     0.396526
136661    0.396526
835141    0.396526
317949    0.396526
319105    0.396526
Name: 600241, dtype: float64

600381
user
249051    0.187729
950331    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
173126    0.000000
Name: 600381, dtype: float64

600727
user
950331    0.0
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 600727, dtype: float64

603829
user
296122    0.707107
950331    0.000000
173126    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173141    0.000000
172504    0.000000
Name: 603829, dtype: float64

603870
user
554633    0.970143
728009    0.161558
950331    0.000000
173126    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173141    0.000000
Name: 603870, dtype: float64

605060
user
950331    0.0
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 605060, dtype: float64

605904
user
605904    1.000000
11328     0.780869
68977     0.370625
173146    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
Name: 605904, dtype: float64

606053
user
116780    0.331295
754864    0.267261
218901    0.128271
391794    0.085057
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
172504    0.000000
Name: 606053, dtype: float64

606620
user
703342    1.000000
627098    1.000000
253041    1.000000
729240    1.000000
27339     1.000000
360829    0.707107
269477    0.545545
65219     0.421076
172770    0.416025
Name: 606620, dtype: float64

606826
user
670976    0.894427
606979    0.894427
135283    0.552052
163201    0.447214
834840    0.447214
112534    0.447214
251581    0.386334
213971    0.376622
279652    0.301297
Name: 606826, dtype: float64

606877
user
112180    1.000000
143267    1.000000
632235    1.000000
133152    1.000000
491073    1.000000
606877    1.000000
937146    0.894427
322423    0.800000
71789     0.615457
Name: 606877, dtype: float64

606979
user
606979    1.000000
606826    0.894427
135283    0.617213
251581    0.431934
213971    0.421076
279652    0.336861
593182    0.219900
173038    0.000000
172490    0.000000
Name: 606979, dtype: float64

607093
user
950331    0.0
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 607093, dtype: float64

607450
user
607450    1.000000
21105     1.000000
357798    0.312348
243883    0.288675
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
Name: 607450, dtype: float64

607983
user
53368     0.165521
950331    0.000000
172589    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 607983, dtype: float64

608132
user
319891    0.771517
700080    0.617213
420421    0.467801
321677    0.425999
65219     0.324867
157653    0.292917
31624     0.276026
856133    0.189576
172490    0.000000
Name: 608132, dtype: float64

608616
user
950331    0.0
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 608616, dtype: float64

608997
user
382215    0.980581
1521      0.980581
73020     0.980581
279785    0.227596
593182    0.215629
197504    0.204465
469245    0.168366
182213    0.149537
173141    0.000000
Name: 608997, dtype: float64

609485
user
614124    0.662266
875286    0.662266
61892     0.662266
249441    0.529813
170268    0.529813
463997    0.529813
191379    0.529813
439699    0.529813
209839    0.529813
Name: 609485, dtype: float64

609937
user
950331    0.0
172490    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
173126    0.0
Name: 609937, dtype: float64

610469
user
950331    0.0
172490    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
173126    0.0
Name: 610469, dtype: float64

610646
user
215634    1.0
950331    0.0
172504    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 610646, dtype: float64

611078
user
376096    0.662266
395445    0.662266
816326    0.662266
89133     0.529813
592038    0.529813
632364    0.529813
114663    0.529813
321116    0.529813
153839    0.529813
Name: 611078, dtype: float64

611186
user
6574      1.000000
611186    1.000000
181027    1.000000
279303    0.707107
319153    0.358569
950331    0.000000
172589    0.000000
172770    0.000000
172946    0.000000
Name: 611186, dtype: float64

611711
user
611711    1.000000
553056    1.000000
488321    1.000000
74871     1.000000
117432    0.707107
158492    0.624695
169063    0.600000
44555     0.529813
392992    0.492366
Name: 611711, dtype: float64

612464
user
198386    0.872872
686640    0.872872
906552    0.529256
89999     0.470621
390671    0.323508
134807    0.303895
5311      0.266223
24308     0.218218
377242    0.218218
Name: 612464, dtype: float64

613041
user
318073    0.577350
92831     0.577350
475865    0.577350
203647    0.577350
420587    0.577350
398867    0.450835
3357      0.408248
518696    0.360668
13006     0.360668
Name: 613041, dtype: float64

613481
user
27465     0.170020
652365    0.163118
836186    0.159316
172955    0.000000
172589    0.000000
172770    0.000000
172946    0.000000
173038    0.000000
172490    0.000000
Name: 613481, dtype: float64

613686
user
108959    0.707107
55852     0.707107
217350    0.110180
173038    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
950331    0.000000
172504    0.000000
Name: 613686, dtype: float64

613864
user
613864    1.000000
827709    1.000000
108796    1.000000
129947    1.000000
190366    1.000000
389377    1.000000
678906    1.000000
194541    1.000000
721055    0.707107
Name: 613864, dtype: float64

614124
user
875286    1.000000
614124    1.000000
609485    0.662266
193185    0.514496
257876    0.514496
314366    0.346410
372398    0.315000
222193    0.303046
90754     0.171219
Name: 614124, dtype: float64

614462
user
790296    0.624695
334992    0.624695
7488      0.624695
82581     0.624695
294354    0.624695
352512    0.624695
886362    0.624695
578647    0.624695
721140    0.624695
Name: 614462, dtype: float64

614812
user
648839    1.0
783345    1.0
111561    1.0
786717    1.0
753506    1.0
314345    1.0
596425    1.0
257101    1.0
44077     1.0
Name: 614812, dtype: float64

615574
user
349887    0.624695
170364    0.624695
781718    0.624695
91788     0.441726
764772    0.270501
334694    0.223498
724982    0.107578
173236    0.000000
173218    0.000000
Name: 615574, dtype: float64

616012
user
109622    0.258738
623554    0.214286
950331    0.000000
173293    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
173126    0.000000
Name: 616012, dtype: float64

616058
user
559832    0.483368
133270    0.386695
281932    0.341793
151201    0.273434
129831    0.223258
687969    0.223258
831703    0.213806
292085    0.170813
638780    0.165255
Name: 616058, dtype: float64

616906
user
254255    1.000000
616906    1.000000
797488    0.707107
152915    0.500000
316376    0.452267
312492    0.281439
632095    0.241747
350771    0.220193
173141    0.000000
Name: 616906, dtype: float64

617215
user
76488     0.203186
950331    0.000000
172589    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 617215, dtype: float64

617322
user
950331    0.0
172504    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
173126    0.0
Name: 617322, dtype: float64

618544
user
618544    1.00000
113000    0.80000
279615    0.30657
950331    0.00000
172946    0.00000
172955    0.00000
173038    0.00000
173126    0.00000
173141    0.00000
Name: 618544, dtype: float64

618570
user
618570    1.000000
491529    0.780869
725655    0.680414
424678    0.565685
79647     0.554700
795084    0.447214
694627    0.275010
173187    0.000000
173146    0.000000
Name: 618570, dtype: float64

619179
user
619179    1.0
950331    0.0
172504    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
173126    0.0
Name: 619179, dtype: float64

620236
user
94448     0.800000
248522    0.800000
46322     0.511682
257876    0.411597
641859    0.257663
686300    0.252982
256163    0.142823
950331    0.000000
173038    0.000000
Name: 620236, dtype: float64

621199
user
249441    0.662266
171046    0.529813
31000     0.529813
354616    0.529813
49598     0.529813
176896    0.529813
109566    0.529813
256643    0.529813
86868     0.529813
Name: 621199, dtype: float64

621426
user
318736    0.707107
510431    0.470360
213564    0.205076
950331    0.000000
173126    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
Name: 621426, dtype: float64

621469
user
137035    1.000000
762747    0.780869
53368     0.165521
173141    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
Name: 621469, dtype: float64

621501
user
730200    0.624695
308702    0.323423
46154     0.319235
816423    0.315000
256163    0.178529
171678    0.000000
172589    0.000000
173293    0.000000
173236    0.000000
Name: 621501, dtype: float64

622340
user
853410    1.000000
39314     1.000000
622340    1.000000
944394    1.000000
828625    0.894427
49805     0.780869
83257     0.577350
4347      0.529813
310557    0.514496
Name: 622340, dtype: float64

622705
user
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
173126    0.0
Name: 622705, dtype: float64

622858
user
137575    0.780869
178016    0.367290
24964     0.346455
149300    0.213516
950331    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
Name: 622858, dtype: float64

622936
user
53332     1.000000

user
571810    0.260643
197904    0.223500
193795    0.208514
149832    0.208514
295792    0.208514
107324    0.208514
321082    0.208514
253720    0.208514
680848    0.208514
Name: 636781, dtype: float64

637070
user
65902     0.780869
111192    0.487805
72686     0.160231
173293    0.000000
173300    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 637070, dtype: float64

637343
user
418950    1.000000
367276    1.000000
637343    1.000000
881924    1.000000
90754     0.171219
175469    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 637343, dtype: float64

638780
user
465599    0.455842
846528    0.455842
404067    0.341882
223400    0.234529
840243    0.224441
67245     0.210414
730158    0.208546
537372    0.206162
31624     0.203859
Name: 638780, dtype: float64

639547
user
950331    0.0
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 639547, dtype: float64

641062
user
752281    1.000000
475240    1.000000
111719    1.000000
227401    1.000000
641062    1.000000
213776    1.000000
100771    1.000000
805528    0.707107
110095    0.707107
Name: 641062, dtype: float64

641859
user
427422    0.362161
906243    0.322078
136764    0.322078
136661    0.322078
782157    0.322078
393032    0.322078
739296    0.322078
465115    0.322078
194854    0.322078
Name: 641859, dtype: float64

642082
user
109583    1.000000
642082    1.000000
280872    0.624695
322597    0.321288
705731    0.270295
504746    0.215041
814144    0.192450
215042    0.101929
175043    0.000000
Name: 642082, dtype: float64

642214
user
882402    1.0
465152    1.0
43207     1.0
239439    1.0
648094    1.0
169215    1.0
2175      1.0
642214    1.0
230190    1.0
Name: 642214, dtype: float64

642291
user
252964    1.000000
642291    1.000000
21351     1.000000
10762     1.000000
387303    0.529813
817844    0.514496
230662    0.404061
215995    0.339276
85688     0.268802
Name: 642291, dtype: float64

642339
user
642339    1.000000
156173    1.000000
157793    1.000000
97283     0.707107
505806    0.386912
783096    0.357143
321572    0.323381
154501    0.290191
71632     0.248452
Name: 642339, dtype: float64

643010
user
66639     0.970143
65841     0.970143
340512    0.970143
447445    0.970143
417735    0.970143
667169    0.757554
47484     0.685994
65433     0.685994
870790    0.665512
Name: 643010, dtype: float64

644110
user
908860    1.000000
209415    1.000000
201162    1.000000
644110    1.000000
152603    1.000000
351982    1.000000
554398    0.707107
848512    0.707107
427422    0.624695
Name: 644110, dtype: float64

645667
user
82581     1.0
487327    1.0
652607    1.0
42615     1.0
7488      1.0
721140    1.0
645667    1.0
664747    1.0
192450    1.0
Name: 645667, dtype: float64

646881
user
96613     0.388075
95763     0.388075
562349    0.388075
715137    0.310460
352716    0.310460
452036    0.310460
136730    0.310460
224662    0.310460
191191    0.310460
Name: 646881, dtype: float64

647331
user
580520    0.260378
950331    0.000000
172504    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
Name: 647331, dtype: float64

647834
user
730158    0.457496
103529    0.419314
950331    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
Name: 647834, dtype: float64

647960
user
364504    0.707107
950331    0.000000
172589    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 647960, dtype: float64

648094
user
882402    1.0
465152    1.0
43207     1.0
239439    1.0
648094    1.0
169215    1.0
2175      1.0
642214    1.0
230190    1.0
Name: 648094, dtype: float64

648265
user
542897    0.707107
54441     0.707107
208228    0.485071
65081     0.374634
226757    0.362143
255093    0.323498
130768    0.303046
397767    0.262613
73577     0.219529
Name: 648265, dtype: float64

648676
user
648676    1.000000
169608    1.000000
46312     1.000000
582482    1.000000
87328     0.780869
219577    0.547723
347289    0.500000
856133    0.245718
249051    0.234662
Name: 648676, dtype: float64

648839
user
648839    1.0
783345    1.0
111561    1.0
786717    1.0
753506    1.0
314345    1.0
596425    1.0
257101    1.0
44077     1.0
Name: 648839, dtype: float64

648897
user
950331    0.0
173415    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 648897, dtype: float64

649025
user
649025    1.000000
75782     0.492366
138574    0.164957
173187    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
173146    0.000000
950331    0.000000
Name: 649025, dtype: float64

650202
user
218625    0.399043
359723    0.399043
318272    0.319235
95887     0.319235
534984    0.319235
60246     0.311601
682485    0.243414
425198    0.239426
67211     0.225733
Name: 650202, dtype: float64

650429
user
88424     0.707107
354415    0.552158
137065    0.552158
43926     0.500000
329189    0.468293
89719     0.312348
213971    0.297746
261456    0.288675
85615     0.241747
Name: 650429, dtype: float64

650468
user
650468    1.0
171549    0.0
171582    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 650468, dtype: float64

650503
user
950331    0.0
172504    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
173126    0.0
Name: 650503, dtype: float64

650646
user
813771    0.340503
46607     0.340503
425198    0.255377
93325     0.255377
199410    0.212710
152406    0.192617
616058    0.164588
687969    0.157271
831703    0.150613
Name: 650646, dtype: float64

651150
user
934995    1.0
651150    1.0
171329    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 651150, dtype: float64

651198
user
194541    0.435194
678906    0.435194
613864    0.435194
190366    0.435194
827709    0.435194
129947    0.435194
108796    0.435194
323358    0.435194
389377    0.435194
Name: 651198, dtype: float64

651501
user
113970    0.980581
54197     0.554700
8272      0.482805
213694    0.459423
469418    0.442080
89719     0.433148
251474    0.367359
180541    0.344010
385219    0.332687
Name: 651501, dtype: float64

652088
user
43742     0.586939
69329     0.374634
360381    0.305888
198050    0.168068
279615    0.097455
69019     0.093750
72686     0.081536
861280    0.077333
356471    0.059089
Name: 652088, dtype: float64

652365
user
465115    0.348155
906243    0.348155
158717    0.348155
820044    0.348155
703342    0.348155
319105    0.348155
902743    0.348155
627098    0.348155
253041    0.348155
Name: 652365, dtype: float64

652607
user
82581     1.0
487327    1.0
652607    1.0
42615     1.0
7488      1.0
721140    1.0
645667    1.0
664747    1.0
192450    1.0
Name: 652607, dtype: float64

652898
user
321062    0.379663
924153    0.379663
676064    0.379663
57135     0.379663
385886    0.379663
35172     0.335578
108666    0.335578
195653    0.308925
917504    0.296467
Name: 652898, dtype: float64

653894
user
510689    0.577350
135672    0.222566
950331    0.000000
172504    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
Name: 653894, dtype: float64

654512
user
654512    1.0
950331    0.0
172490    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
173126    0.0
Name: 654512, dtype: float64

655295
user
156952    0.194489
950331    0.000000
173415    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 655295, dtype: float64

655832
user
29112     1.0
950331    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 655832, dtype: float64

656088
user
64301     0.205499
950331    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 656088, dtype: float64

656314
user
172490    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
173126    0.0
173038    0.0
Name: 656314, dtype: float64

656737
user
461939    1.000000
656737    1.000000
321090    1.000000
293102    0.948683
830007    0.365148
572720    0.303728
818006    0.183340
391794    0.085057
161129    0.000000
Name: 656737, dtype: float64

656927
user
198050    0.317221
76488     0.270914
70650     0.151186
173038    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173126    0.000000
172504    0.000000
Name: 656927, dtype: float64

657132
user
491634    0.297044
788114    0.160128
172589    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
172490    0.000000
Name: 657132, dtype: float64

657251
user
657251    1.000000
214747    1.000000
180541    0.350823
5666      0.192450
82952     0.186772
138574    0.164957
103304    0.118493
173187    0.000000
173146    0.000000
Name: 657251, dtype: float64

658169
user
62880     1.000000
140023    1.000000
658169    1.000000
819615    1.000000
535452    0.468521
89781     0.464238
361582    0.266667
128271    0.237915
530433    0.198030
Name: 658169, dtype: float64

658421
user
133983    0.70014
445293    0.50000
592038    0.50000
632364    0.50000
289156    0.50000
393149    0.50000
153839    0.50000
170852    0.50000
89133     0.50000
Name: 658421, dtype: float64

659757
user
131381    1.00000
26298     0.32075
173141    0.00000
172770    0.00000
172946    0.00000
172955    0.00000
173038    0.00000
173126    0.00000
950331    0.00000
Name: 659757, dtype: float64

660794
user
950331    0.0
172490    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
173126    0.0
Name: 660794, dtype: float64

661090
user
194889    0.832050
838164    0.554700
48822     0.519778
109622    0.269104
179719    0.256776
623554    0.237729
152406    0.235339
580520    0.216647
694627    0.076274
Name: 661090, dtype: float64

662004
user
950331    0.0
172490    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
173126    0.0
Name: 662004, dtype: float64

662556
user
662556    1.000000
138663    0.577350
21542     0.219382
256163    0.133897
173146    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
Name: 662556, dtype: float64

662901
user
743850    0.707107
789449    0.707107
114625    0.707107
489209    0.707107
127610    0.707107
211085    0.707107
867166    0.552158
116016    0.500000
876665    0.441726
Name: 662901, dtype: float64

662925
user
794785    0.424094
201157    0.424094
23255     0.424094
792019    0.424094
358700    0.424094
219760    0.424094
107751    0.339276
394365    0.339276
45308     0.339276
Name: 662925, dtype: float64

663333
user
93916     1.000000
562119    1.000000
352205    0.707107
328775    0.141510
53368     0.124141
175875    0.000000
172490    0.000000
176544    0.000000
173187    0.000000
Name: 663333, dtype: float64

663999
user
805262    1.000000
108936    0.331891
665569    0.177084
132504    0.162459
745537    0.078206
173146    0.000000
173187    0.000000
173141    0.000000
172589    0.000000
Name: 663999, dtype: float64

664138
user
362085    0.577350
809373    0.577350
325654    0.577350
364818    0.577350
269788    0.495074
194941    0.408248
33179     0.392837
308086    0.384900
280132    0.333333
Name: 664138, dtype: float64

664747
user
82581     1.0
487327    1.0
652607    1.0
42615     1.0
7488      1.0
721140    1.0
645667    1.0
664747    1.0
192450    1.0
Name: 664747, dtype: float64

664880
user
155049    0.577350
391650    0.318788
191100    0.297044
226757    0.295689
361497    0.284268
322019    0.186728
169618    0.182574
360130    0.180775
315118    0.149383
Name: 664880, dtype: float64

665032
user
600241    0.317221
175405    0.302614
504746    0.161281
392082    0.130189
173038    0.000000
172589    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
Name: 665032, dtype: float64

665344
user
280011    0.707107
213776    0.707107
316446    0.707107
100771    0.707107
475240    0.707107
641062    0.707107
111719    0.707107
752281    0.707107
227401    0.707107
Name: 665344, dtype: float64

665456
user
95895     0.624695
31010     0.624695
113728    0.441726
867891    0.346518
137899    0.183487
861280    0.068386
171853    0.000000
172504    0.000000
173236    0.000000
Name: 665456, dtype: float64

665569
user
286962    0.295141
757228    0.295141
8323      0.295141
501746    0.295141
87724     0.295141
709700    0.295141
899377    0.295141
200875    0.295141
268107    0.295141
Name: 665569, dtype: float64

665848
user
546902    0.762493
446157    0.762493
459734    0.762493
367815    0.762493
725655    0.518811
95336     0.518811
153040    0.500142
31058     0.469282
321594    0.457496
Name: 665848, dtype: float64

666409
user
426952    0.707107
28722     0.707107
26352     0.707107
885528    0.707107
193499    0.408248
193549    0.307729
166       0.232119
173141    0.000000
173126    0.000000
Name: 666409, dtype: float64

667101
user
286800    0.468165
370681    0.289430
103304    0.157991
173038    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173126    0.000000
172504    0.000000
Name: 667101, dtype: float64

667169
user
66639     0.780869
65841     0.780869
340512    0.780869
447445    0.780869
417735    0.780869
643010    0.757554
47484     0.552158
65433     0.552158
870790    0.535672
Name: 667169, dtype: float64

667504
user
667504    1.000000
114961    1.000000
684910    0.505076
173126    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
950331    0.000000
Name: 667504, dtype: float64

668508
user
668508    1.000000
224755    0.524142
936595    0.457496
213971    0.421076
135672    0.278207
391153    0.258199
172946    0.000000
172955    0.000000
173038    0.000000
Name: 668508, dtype: float64

669366
user
669366    1.0
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 669366, dtype: float64

669370
user
280573    0.295656
623554    0.056033
173126    0.000000
172589    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173141    0.000000
Name: 669370, dtype: float64

669681
user
950331    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
173126    0.0
Name: 669681, dtype: float64

670377
user
899799    0.707107
805310    0.441726
85626     0.369274
128271    0.317221
21542     0.292509
129333    0.199007
284695    0.180517
64301     0.164399
950331    0.000000
Name: 670377, dtype: float64

670466
user
285213    0.554700
209755    0.422955
273350    0.096561
247421    0.036879
32143     0.027131
391794    0.022241
173146    0.000000
173141    0.000000
172589    0.000000
Name: 670466, dtype: float64

670715
user
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 670715, dtype: float64

670976
user
606979    1.000000
606826    0.894427
135283    0.617213
251581    0.431934
213971    0.421076
279652    0.336861
593182    0.219900
173038    0.000000
172490    0.000000
Name: 670976, dtype: float64

671050
user
945363    0.615457
44555     0.529813
950331    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
172589    0.000000
Name: 671050, dtype: float64

671255
user
169618    0.316228
391794    0.113410
172589    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
Name: 671255, dtype: float64

671505
user
671505    1.0
44140     1.0
950331    0.0
172770    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
Name: 671505, dtype: float64

671890
user
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 671890, dtype: float64

671905
user
671905    1.000000
69546     0.685994
156952    0.199254
173187    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
173146    0.000000
Name: 671905, dtype: float64

672483
user
159773    0.707107
342978    0.707107
106216    0.707107
487400    0.707107
203033    0.707107
267306    0.707107
151203    0.707107
899670    0.707107
177362    0.685994
Name: 672483, dtype: float64

673813
user
631109    0.257248
73273     0.255655
103304    0.209987
385612    0.187680
920668    0.124784
173038    0.000000
172946    0.000000
172955    0.000000
173126    0.000000
Name: 673813, dtype: float64

674425
user
75597     0.400000
332865    0.400000
49500     0.400000
500916    0.300000
387478    0.300000
360002    0.300000
43292     0.221880
150887    0.220863
392887    0.207931
Name: 674425, dtype: float64

674747
user
674747    1.0
173415    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 674747, dtype: float64

674768
user
250560    0.5
85315     0.5
106580    0.5
72150     0.5
389047    0.5
277858    0.5
428771    0.5
67429     0.5
882297    0.5
Name: 674768, dtype: float64

676064
user
321062    1.000000
676064    1.000000
385886    1.000000
328925    0.624695
245897    0.450035
323845    0.441726
314531    0.431934
359001    0.404061
369062    0.404061
Name: 676064, dtype: float64

676118
user
391585    1.000000
676118    1.000000
256539    1.000000
319153    0.478091
196166    0.464238
171853    0.000000
172955    0.000000
173300    0.000000
171636    0.000000
Name: 676118, dtype: float64

676545
user
142761    1.000000
665569    0.236113
950331    0.000000
172770    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 676545, dtype: float64

676901
user
589791    0.154303
76488     0.135457
24319     0.122169
950331    0.000000
173141    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173187    0.000000
Name: 676901, dtype: float64

677551
user
66608     1.000000
677551    1.000000
288873    0.707107
698792    0.624695
192437    0.507093
198312    0.424264
851312    0.277350
82952     0.249029
43793     0.202548
Name: 677551, dtype: float64

677628
user
677628    1.000000
491529    0.624695
398557    0.577350
172504    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
Name: 677628, dtype: float64

677778
user
422401    1.000000
321865    1.000000
677778    1.000000
254215    1.000000
46758     1.000000
539803    1.000000
418830    0.707107
179653    0.600000
305522    0.524142
Name: 677778, dtype: float64

678384
user
584514    0.645497
362748    0.645497
548019    0.645497
391405    0.645497
740367    0.639010
70195     0.516398
441682    0.479463
79213     0.387298
134173    0.387298
Name: 678384, dtype: float64

678481
user
259513    1.0
48575     1.0
200843    1.0
678481    1.0
950331    0.0
173038    0.0
173126    0.0
173141    0.0
173146    0.0
Name: 678481, dtype: float64

678502
user
507859    0.492366
906552    0.485071
90296     0.126239
950331    0.000000
173126    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173146    0.000000
Name: 678502, dtype: float64

678906
user
613864    1.000000
827709    1.000000
108796    1.000000
129947    1.000000
190366    1.000000
389377    1.000000
678906    1.000000
194541    1.000000
721055    0.707107
Name: 678906, dtype: float64

679280
user
45970     1.000000
385514    1.000000
353436    1.000000
679280    1.000000
505806    0.386912
109622    0.323423
623554    0.285714
173187    0.000000
173218    0.000000
Name: 679280, dtype: float64

679886
user

Name: 694190, dtype: float64

694627
user
95336     0.498987
725655    0.498987
154201    0.458349
546902    0.458349
459734    0.458349
446157    0.458349
367815    0.458349
317321    0.458349
49529     0.366679
Name: 694627, dtype: float64

694821
user
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 694821, dtype: float64

695517
user
257776    0.624695
728391    0.325362
69019     0.110540
950331    0.000000
172770    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 695517, dtype: float64

695627
user
46936     0.244796
158711    0.164957
950331    0.000000
173146    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
173187    0.000000
172946    0.000000
Name: 695627, dtype: float64

695760
user
316768    1.0
695760    1.0
27939     1.0
50690     1.0
134761    1.0
50739     1.0
147932    1.0
29070     1.0
256789    1.0
Name: 695760, dtype: float64

695988
user
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 695988, dtype: float64

696492
user
208452    0.624695
950331    0.000000
173421    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 696492, dtype: float64

696718
user
85853     1.000000
129168    1.000000
24614     0.529813
5015      0.487950
114860    0.436436
250495    0.230879
32143     0.138343
173126    0.000000
173141    0.000000
Name: 696718, dtype: float64

696729
user
696729    1.000000
793692    1.000000
242673    0.707107
885332    0.615457
744060    0.447214
269509    0.447214
475084    0.441726
49642     0.243396
257609    0.219382
Name: 696729, dtype: float64

696746
user
198110    0.894427
350912    0.558744
507859    0.550482
845485    0.286299
686300    0.282843
752650    0.134080
391794    0.101437
328775    0.079106
179727    0.039451
Name: 696746, dtype: float64

696769
user
256325    0.229794
179727    0.132324
173415    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 696769, dtype: float64

696992
user
559873    1.0
950331    0.0
173415    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 696992, dtype: float64

697075
user
697075    1.000000
413554    1.000000
724982    0.103325
173141    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173187    0.000000
Name: 697075, dtype: float64

697629
user
109566    1.0
697629    1.0
256643    1.0
354616    1.0
49598     1.0
48740     1.0
352086    1.0
176896    1.0
357454    1.0
Name: 697629, dtype: float64

697795
user
351552    1.000000
501275    0.492366
49642     0.243396
173038    0.000000
173126    0.000000
173141    0.000000
173146    0.000000
173187    0.000000
172946    0.000000
Name: 697795, dtype: float64

697977
user
398874    0.357143
461917    0.285714
524526    0.285714
63622     0.285714
105989    0.285714
218745    0.285714
197958    0.285714
197893    0.285714
252432    0.285714
Name: 697977, dtype: float64

698067
user
841716    1.0
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 698067, dtype: float64

698212
user
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 698212, dtype: float64

698792
user
148356    0.780869
66608     0.624695
213740    0.624695
677551    0.624695
288873    0.441726
192437    0.316778
198312    0.265036
851312    0.173259
82952     0.155567
Name: 698792, dtype: float64

699186
user
789207    0.452267
950331    0.000000
172770    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 699186, dtype: float64

699433
user
88648     1.000000
699433    1.000000
1190      1.000000
148748    0.529813
211039    0.468293
357798    0.312348
781898    0.295487
194979    0.254000
386997    0.216574
Name: 699433, dtype: float64

699447
user
861818    0.577350
212056    0.577350
285710    0.577350
59764     0.577350
91092     0.577350
359203    0.577350
922962    0.577350
425059    0.474579
234398    0.450835
Name: 699447, dtype: float64

699829
user
699829    1.000000
51021     1.000000
382866    0.707107
88042     0.492366
401684    0.281272
425396    0.242536
391631    0.224860
217350    0.194772
53368     0.165521
Name: 699829, dtype: float64

699973
user
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 699973, dtype: float64

700080
user
608132    0.617213
31624     0.447214
172504    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
Name: 700080, dtype: float64

700993
user
700993    1.000000
776502    1.000000
894693    0.780869
26162     0.707107
196412    0.500000
211039    0.374634
788114    0.277350
194979    0.190500
745537    0.156412
Name: 700993, dtype: float64

701051
user
701051    1.000000
419576    1.000000
173428    0.331295
923208    0.284747
173038    0.000000
172589    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
Name: 701051, dtype: float64

701499
user
173141    1.000000
131540    1.000000
701499    1.000000
243313    0.371391
710618    0.291730
923208    0.284747
173146    0.000000
173187    0.000000
173218    0.000000
Name: 701499, dtype: float64

702397
user
86766     0.707107
753989    0.707107
95763     0.707107
562349    0.707107
96613     0.707107
150074    0.707107
14914     0.707107
885308    0.707107
428481    0.565685
Name: 702397, dtype: float64

702417
user
132262    0.386912
2175      0.386912
239439    0.386912
61770     0.386912
244614    0.386912
500916    0.386912
851090    0.386912
340105    0.386912
230190    0.386912
Name: 702417, dtype: float64

703342
user
703342    1.000000
627098    1.000000
253041    1.000000
729240    1.000000
27339     1.000000
360829    0.707107
269477    0.545545
65219     0.421076
172770    0.416025
Name: 703342, dtype: float64

703432
user
82581     1.0
487327    1.0
652607    1.0
42615     1.0
7488      1.0
721140    1.0
645667    1.0
664747    1.0
192450    1.0
Name: 703432, dtype: float64

704888
user
704888    1.000000
248011    0.435194
171582    0.000000
171636    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 704888, dtype: float64

705731
user
343008    0.337869
152151    0.337869
357259    0.337869
354874    0.289720
170923    0.270295
40447     0.270295
642082    0.270295
537947    0.270295
321594    0.270295
Name: 705731, dtype: float64

705834
user
852767    1.000000
902931    0.624695
53368     0.124141
950331    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
Name: 705834, dtype: float64

706055
user
730352    0.215666
950331    0.000000
173126    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173141    0.000000
172504    0.000000
Name: 706055, dtype: float64

706227
user
706227    1.000000
449148    0.707107
85808     0.680414
351590    0.445435
32143     0.103757
950331    0.000000
173146    0.000000
173038    0.000000
173126    0.000000
Name: 706227, dtype: float64

706290
user
914284    0.707107
588404    0.624695
872014    0.485071
351808    0.400000
178898    0.327327
264572    0.305888
148702    0.304114
68632     0.201456
256163    0.178529
Name: 706290, dtype: float64

706307
user
397119    0.292603
950331    0.000000
172504    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
Name: 706307, dtype: float64

706437
user
132480    0.624695
72566     0.624695
151373    0.609756
452187    0.450835
396276    0.384473
239796    0.378777
208228    0.321403
21542     0.228411
243313    0.217506
Name: 706437, dtype: float64

707094
user
707094    1.00000
67607     1.00000
148839    0.57735
153457    0.26389
173146    0.00000
173038    0.00000
173126    0.00000
173141    0.00000
173218    0.00000
Name: 707094, dtype: float64

707460
user
204033    1.000000
48814     1.000000
931768    1.000000
719811    1.000000
75174     1.000000
707460    1.000000
98330     0.780869
62904     0.585206
211914    0.492366
Name: 707460, dtype: float64

707972
user
18966     0.707107
160404    0.707107
229007    0.707107
343630    0.565685
249802    0.452548
852721    0.424264
75773     0.424264
324767    0.424264
315596    0.326599
Name: 707972, dtype: float64

708493
user
318671    0.529813
168976    0.529813
548644    0.397360
73577     0.164486
256325    0.121748
391153    0.109438
641859    0.102385
172770    0.000000
172946    0.000000
Name: 708493, dtype: float64

708518
user
88172     1.0
692426    1.0
529676    1.0
593945    1.0
944033    1.0
473854    1.0
363134    1.0
569529    1.0
182301    1.0
Name: 708518, dtype: float64

709411
user
194482    1.000000
397635    0.230769
70650     0.188982
173236    0.000000
173293    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
Name: 709411, dtype: float64

709700
user
899377    1.000000
42721     1.000000
709700    1.000000
757228    1.000000
87724     1.000000
8323      1.000000
501746    1.000000
470673    0.800000
131375    0.707107
Name: 709700, dtype: float64

710291
user
218745    0.350823
352512    0.350823
645667    0.350823
334992    0.350823
578647    0.350823
652607    0.350823
790296    0.350823
886362    0.350823
42615     0.350823
Name: 710291, dtype: float64

710354
user
361193    0.196116
316768    0.196116
695760    0.196116
27939     0.196116
50690     0.196116
134761    0.196116
50739     0.196116
147932    0.196116
29070     0.196116
Name: 710354, dtype: float64

710581
user
863840    0.894427
227485    0.894427
928303    0.894427
8055      0.894427
756238    0.894427
424498    0.894427
926948    0.632456
420344    0.632456
334520    0.632456
Name: 710581, dtype: float64

710618
user
930847    0.515711
27465     0.496243
816326    0.437595
376096    0.437595
395445    0.437595
316222    0.309426
465110    0.309426
126946    0.309426
256497    0.309426
Name: 710618, dtype: float64

710742
user
96471     1.000000
796502    1.000000
629675    0.529813
48977     0.441726
173187    0.000000
173146    0.000000
173141    0.000000
173126    0.000000
172504    0.000000
Name: 710742, dtype: float64

711410
user
861280    0.145962
950331    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
173126    0.000000
Name: 711410, dtype: float64

711447
user
711447    1.000000
129686    0.265489
173141    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
950331    0.000000
Name: 711447, dtype: float64

712033
user
485567    0.145
950331    0.000
172589    0.000
173300    0.000
173293    0.000
173236    0.000
173218    0.000
173187    0.000
173146    0.000
Name: 712033, dtype: float64

713500
user
154279    0.624695
130558    0.390360
44923     0.297044
46560     0.267860
145101    0.164895
173141    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
Name: 713500, dtype: float64

713695
user
127843    0.400892
175469    0.400000
950331    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
172504    0.000000
Name: 713695, dtype: float64

713818
user
812195    1.0
950331    0.0
172504    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 713818, dtype: float64

714243
user
124281    1.000000
714243    1.000000
132954    0.577350
213564    0.341793
226106    0.294174
218901    0.128271
173038    0.000000
172589    0.000000
172770    0.000000
Name: 714243, dtype: float64

714247
user
714247    1.000000
537372    0.150756
172589    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
950331    0.000000
172504    0.000000
Name: 714247, dtype: float64

714695
user
714695    1.000000
26415     0.524142
641859    0.322078
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
173126    0.000000
Name: 714695, dtype: float64

715137
user
459047    1.000000
568330    0.780869
52776     0.707107
560395    0.707107
170419    0.577350
24614     0.529813
211972    0.468293
192095    0.423999
687969    0.346410
Name: 715137, dtype: float64

716619
user
252541    0.707107
357207    0.707107
283646    0.707107
169063    0.565685
287074    0.441726
271060    0.441726
419560    0.165647
64301     0.145310
173126    0.000000
Name: 716619, dtype: float64

717906
user
393943    1.0
717906    1.0
950331    0.0
173415    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
Name: 717906, dtype: float64

718508
user
950331    0.0
172504    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
173126    0.0
Name: 718508, dtype: float64

719214
user
950331    0.0
172504    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
173126    0.0
Name: 719214, dtype: float64

719811
user
204033    1.000000
48814     1.000000
931768    1.000000
719811    1.000000
75174     1.000000
707460    1.000000
98330     0.780869
62904     0.585206
211914    0.492366
Name: 719811, dtype: float64

720906
user
740988    0.441726
950331    0.000000
172589    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 720906, dtype: float64

721055
user
332593    0.707107
129947    0.707107
678906    0.707107
417312    0.707107
389377    0.707107
323358    0.707107
108796    0.707107
194541    0.707107
613864    0.707107
Name: 721055, dtype: float64

721134
user
524526    0.970143
461917    0.970143
105989    0.970143
63622     0.970143
252432    0.970143
309828    0.970143
250513    0.970143
197893    0.970143
721787    0.685994
Name: 721134, dtype: float64

721140
user
82581     1.0
487327    1.0
652607    1.0
42615     1.0
7488      1.0
721140    1.0
645667    1.0
664747    1.0
192450    1.0
Name: 721140, dtype: float64

721787
user
309828    0.707107
197893    0.707107
461917    0.707107
63622     0.707107
250513    0.707107
524526    0.707107
252432    0.707107
105989    0.707107
721134    0.685994
Name: 721787, dtype: float64

722147
user
214599    1.0
950331    0.0
173415    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 722147, dtype: float64

722243
user
88380     1.000000
369524    0.270501
950331    0.000000
172589    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 722243, dtype: float64

722512
user
728692    0.708659
488981    0.680414
91242     0.680414
887400    0.408248
63622     0.272166
524526    0.272166
252432    0.272166
250513    0.272166
105989    0.272166
Name: 722512, dtype: float64

723330
user
723330    1.000000
914914    1.000000
137630    0.707107
507738    0.615457
851312    0.554700
833379    0.322078
90296     0.315597
166       0.196960
249051    0.187729
Name: 723330, dtype: float64

723530
user
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
173126    0.0
Name: 723530, dtype: float64

724287
user
479054    1.0
950331    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 724287, dtype: float64

724566
user
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
173126    0.0
Name: 724566, dtype: float64

724982
user
495957    0.231043
179191    0.194401
179325    0.172209
303595    0.172209
127163    0.172209
584895    0.172209
155148    0.172209
183443    0.172209
105338    0.164230
Name: 724982, dtype: float64

725030
user
358315    0.196116
950331    0.000000
172770    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 725030, dtype: float64

725466
user
116307    1.000000
725466    1.000000
887586    0.832050
441024    0.624695
191100    0.514496
469418    0.450835
251474    0.374634
884890    0.174574
328775    0.141510
Name: 725466, dtype: float64

725655
user
5121      0.680414
446157    0.680414
618570    0.680414
367815    0.680414
459734    0.680414
546902    0.680414
491529    0.531314
665848    0.518811
694627    0.498987
Name: 725655, dtype: float64

725789
user
387478    0.495074
360002    0.495074
500916    0.495074
857507    0.396059
15289     0.396059
401012    0.396059
190236    0.316847
114257    0.285831
131497    0.285831
Name: 725789, dtype: float64

725849
user
950331    0.0
173415    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 725849, dtype: float64

725984
user
777776    1.000000
315610    1.000000
725984    1.000000
82952     0.311286
315118    0.258738
173141    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
Name: 725984, dtype: float64

726820
user
389047    1.0
558567    1.0
277858    1.0
256861    1.0
159824    1.0
67429     1.0
106580    1.0
72150     1.0
726820    1.0
Name: 726820, dtype: float64

727829
user
31431     0.780869
757292    0.780869
760346    0.780869
421319    0.552158
173187    0.000000
173146    0.000000
173141    0.000000
173126    0.000000
172490    0.000000
Name: 727829, dtype: float64

728009
user
442382    0.201948
226070    0.201948
397051    0.195918
208228    0.166242
218901    0.164059
104713    0.161558
2131      0.161558
492757    0.161558
149905    0.161558
Name: 728009, dtype: float64

728391
user
822723    0.416667
352512    0.416667
82581     0.416667
886362    0.416667
790296    0.416667
652607    0.416667
334992    0.416667
721140    0.416667
664747    0.416667
Name: 728391, dtype: float64

728424
user
156985    1.0
873812    1.0
173126    1.0
950331    0.0
173141    0.0
172946    0.0
172955    0.0
173038    0.0
173146    0.0
Name: 728424, dtype: float64

728464
user
728464    1.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 728464, dtype: float64

728692
user
722512    0.708659
887400    0.650945
91242     0.650945
488981    0.650945
130006    0.431099
194541    0.390567
613864    0.390567
827709    0.390567
190366    0.390567
Name: 728692, dtype: float64

729211
user
171853    1.0
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 729211, dtype: float64

729240
user
703342    1.000000
627098    1.000000
253041    1.000000
729240    1.000000
27339     1.000000
360829    0.707107
269477    0.545545
65219     0.421076
172770    0.416025
Name: 729240, dtype: float64

729456
user
950331    0.0
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 729456, dtype: float64

730158
user
822723    0.609994
647834    0.457496
846528    0.457496
730352    0.328887
728391    0.254164
223400    0.235380
840243    0.225255
638780    0.208546
537372    0.206910
Name: 730158, dtype: float64

730200
user
621501    0.624695
116016    0.552158
308702    0.202041
46154     0.199424
816423    0.196779
256163    0.111526
173293    0.000000
173236    0.000000
173218    0.000000
Name: 730200, dtype: float64

730352
user
159824    0.539164
194342    0.539164
558567    0.539164
428771    0.539164
85315     0.539164
726820    0.539164
389047    0.539164
72150     0.539164
256861    0.539164
Name: 730352, dtype: float64

730664
user
950331    0.0
172504    0.0

user
280855    0.544331
280011    0.544331
534551    0.466760
665344    0.384900
890235    0.335013
126946    0.288675
114162    0.272166
811088    0.268010
502763    0.255031
Name: 745622, dtype: float64

745938
user
209839    1.000000
439699    1.000000
170268    1.000000
745938    1.000000
463997    1.000000
419353    0.780869
59146     0.707107
609485    0.529813
423674    0.514496
Name: 745938, dtype: float64

746330
user
2379      0.615457
177837    0.468165
11951     0.279372
44853     0.272166
173218    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
173146    0.000000
Name: 746330, dtype: float64

747926
user
86857     0.223607
950331    0.000000
173421    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 747926, dtype: float64

748583
user
204033    1.000000
48814     1.000000
931768    1.000000
719811    1.000000
75174     1.000000
707460    1.000000
98330     0.780869
62904     0.585206
211914    0.492366
Name: 748583, dtype: float64

749783
user
648094    0.762493
642214    0.762493
169215    0.762493
38120     0.762493
43207     0.762493
882402    0.762493
230190    0.762493
2175      0.762493
239439    0.762493
Name: 749783, dtype: float64

750203
user
270595    1.000000
116734    1.000000
79511     1.000000
361531    1.000000
882571    0.542326
924558    0.390360
87153     0.350823
173187    0.000000
172770    0.000000
Name: 750203, dtype: float64

750325
user
66431     1.000000
926401    1.000000
33831     0.707107
393293    0.707107
855363    0.624695
314604    0.468165
251266    0.450835
101994    0.377964
90296     0.252478
Name: 750325, dtype: float64

750343
user
386856    1.000000
20363     0.153897
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
173146    0.000000
950331    0.000000
Name: 750343, dtype: float64

751014
user
197359    1.000000
751014    1.000000
63512     0.447214
46322     0.426401
27703     0.303046
5666      0.256600
138574    0.247436
109622    0.194054
173415    0.000000
Name: 751014, dtype: float64

751173
user
334694    0.178885
950331    0.000000
172504    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
Name: 751173, dtype: float64

752281
user
752281    1.000000
475240    1.000000
111719    1.000000
227401    1.000000
641062    1.000000
213776    1.000000
100771    1.000000
805528    0.707107
110095    0.707107
Name: 752281, dtype: float64

752559
user
172955    1.000000
380098    0.800000
190973    0.800000
314366    0.577350
322597    0.401610
224347    0.279372
363254    0.270765
554633    0.242536
315169    0.192450
Name: 752559, dtype: float64

752650
user
446105    0.374766
248636    0.299813
136661    0.299813
158717    0.299813
367017    0.299813
29070     0.299813
361193    0.299813
820044    0.299813
356415    0.299813
Name: 752650, dtype: float64

752963
user
361663    1.000000
752963    1.000000
155666    0.707107
745537    0.195515
950331    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
Name: 752963, dtype: float64

753324
user
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 753324, dtype: float64

753494
user
69019     0.221187
950331    0.000000
171549    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 753494, dtype: float64

753506
user
648839    1.0
783345    1.0
111561    1.0
786717    1.0
753506    1.0
314345    1.0
596425    1.0
257101    1.0
44077     1.0
Name: 753506, dtype: float64

753519
user
199034    1.000000
753519    1.000000
318884    1.000000
476529    1.000000
284559    0.894427
105338    0.662266
212036    0.529813
361582    0.333333
820908    0.246932
Name: 753519, dtype: float64

753900
user
753900    1.000000
191568    1.000000
117432    0.707107
572720    0.303728
68122     0.280976
186286    0.213809
173187    0.000000
173146    0.000000
172589    0.000000
Name: 753900, dtype: float64

753989
user
150074    1.000000
753989    1.000000
885308    1.000000
86766     1.000000
702397    0.707107
39188     0.685994
279785    0.232104
836186    0.191273
249051    0.187729
Name: 753989, dtype: float64

754481
user
926481    0.707107
950331    0.000000
172504    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
Name: 754481, dtype: float64

754864
user
185483    0.445435
323031    0.445435
599605    0.445435
63622     0.356348
49771     0.356348
524526    0.356348
55705     0.356348
197893    0.356348
321692    0.356348
Name: 754864, dtype: float64

755162
user
817844    0.857493
504329    0.707107
197504    0.417029
96320     0.399043
178898    0.327327
72849     0.267860
215042    0.254824
816423    0.236250
68632     0.201456
Name: 755162, dtype: float64

755504
user
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
173126    0.0
Name: 755504, dtype: float64

755817
user
183668    0.617213
386553    0.529813
251311    0.369274
105881    0.218218
257609    0.146254
173126    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
Name: 755817, dtype: float64

756238
user
863840    1.000000
8055      1.000000
928303    1.000000
756238    1.000000
424498    1.000000
710581    0.894427
334520    0.707107
420344    0.707107
926948    0.707107
Name: 756238, dtype: float64

756527
user
316376    0.301511
632095    0.241747
312492    0.140720
172955    0.000000
172504    0.000000
172589    0.000000
172770    0.000000
172946    0.000000
950331    0.000000
Name: 756527, dtype: float64

756913
user
678906    0.624695
613864    0.624695
389377    0.624695
108796    0.624695
129947    0.624695
190366    0.624695
827709    0.624695
323358    0.624695
194541    0.624695
Name: 756913, dtype: float64

757228
user
899377    1.000000
42721     1.000000
709700    1.000000
757228    1.000000
87724     1.000000
8323      1.000000
501746    1.000000
470673    0.800000
131375    0.707107
Name: 757228, dtype: float64

757292
user
31431     1.000000
757292    1.000000
727829    0.780869
421319    0.707107
173187    0.000000
173146    0.000000
173141    0.000000
173126    0.000000
172490    0.000000
Name: 757292, dtype: float64

759526
user
864883    1.000000
893228    1.000000
290662    1.000000
759526    1.000000
918040    0.455842
173428    0.441726
219293    0.431934
73273     0.372678
395948    0.370625
Name: 759526, dtype: float64

760346
user
31431     1.000000
757292    1.000000
727829    0.780869
421319    0.707107
173187    0.000000
173146    0.000000
173141    0.000000
173126    0.000000
172490    0.000000
Name: 760346, dtype: float64

760792
user
950331    0.0
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 760792, dtype: float64

761174
user
950331    0.0
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 761174, dtype: float64

761773
user
132641    1.000000
448633    1.000000
45836     1.000000
92068     0.894427
199410    0.780869
212057    0.707107
4347      0.529813
686300    0.316228
276312    0.226455
Name: 761773, dtype: float64

762073
user
950331    0.0
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 762073, dtype: float64

762568
user
904924    1.0
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 762568, dtype: float64

762747
user
137035    0.780869
621469    0.780869
72686     0.160231
53368     0.129250
950331    0.000000
173141    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
Name: 762747, dtype: float64

762802
user
73803     1.000000
929763    0.196116
156230    0.135147
950331    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 762802, dtype: float64

763520
user
778423    0.832050
896308    0.588348
192095    0.423999
293382    0.323498
391957    0.305995
568971    0.231455
391794    0.085057
172946    0.000000
173325    0.000000
Name: 763520, dtype: float64

763655
user
196651    0.580015
325034    0.487805
529160    0.441726
327420    0.290007
2368      0.279372
95916     0.255031
3816      0.231527
89963     0.215862
130044    0.180217
Name: 763655, dtype: float64

764570
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 764570, dtype: float64

764772
user
320723    0.577350
174105    0.461880
681751    0.356348
212036    0.305888
227120    0.284268
615574    0.270501
155666    0.244949
46987     0.191273
369062    0.174964
Name: 764772, dtype: float64

765136
user
765136    1.000000
924558    0.390360
321572    0.323381
950331    0.000000
173141    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
Name: 765136, dtype: float64

766136
user
90437     1.0
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 766136, dtype: float64

766243
user
514724    1.0
14944     1.0
173146    0.0
172946    0.0
172955    0.0
173038    0.0
173126    0.0
173141    0.0
950331    0.0
Name: 766243, dtype: float64

768586
user
134877    1.000000
318030    0.218218
172504    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
Name: 768586, dtype: float64

768680
user
45410     1.000000
768680    1.000000
836071    0.780869
179727    0.132324
173146    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
Name: 768680, dtype: float64

770086
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 770086, dtype: float64

770493
user
470215    0.780869
798855    0.780869
261998    0.780869
282875    0.725018
114081    0.624695
389608    0.552158
887586    0.433148
247634    0.309635
68203     0.304981
Name: 770493, dtype: float64

770937
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 770937, dtype: float64

772287
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 772287, dtype: float64

772564
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 772564, dtype: float64

773560
user
70650     0.113389
172589    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 773560, dtype: float64

773716
user
99088     0.577350
321062    0.346410
385886    0.346410
924153    0.346410
676064    0.346410
353715    0.316847
328925    0.216401
5311      0.176090
245897    0.155897
Name: 773716, dtype: float64

773775
user
950331    0.0
172770    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 773775, dtype: float64

774737
user
197081    0.745356
202112    0.707107
108457    0.662266
4347      0.662266
65081     0.662266
355767    0.615457
71789     0.615457
251266    0.450835
190348    0.436436
Name: 774737, dtype: float64

775370
user
510614    1.000000
419237    1.000000
155793    1.000000
60263     1.000000
775370    1.000000
821860    0.707107
366858    0.624695
257535    0.483368
54197     0.424264
Name: 775370, dtype: float64

775796
user
219577    0.730297
724982    0.137767
950331    0.000000
172589    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 775796, dtype: float64

775813
user
149576    1.000000
775813    1.000000
333372    0.666667
247348    0.529813
260469    0.386695
705731    0.270295
173218    0.000000
173187    0.000000
173146    0.000000
Name: 775813, dtype: float64

776175
user
96722     0.800000
43065     0.800000
51496     0.800000
195582    0.624695
805528    0.565685
24276     0.461880
743374    0.443760
251311    0.393893
885332    0.393893
Name: 776175, dtype: float64

776228
user
64551     1.000000
828166    0.346410
133400    0.147979
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
173146    0.000000
173187    0.000000
Name: 776228, dtype: float64

776304
user
776304    1.000000
219792    1.000000
217350    0.116863
172589    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 776304, dtype: float64

776502
user
700993    1.000000
776502    1.000000
894693    0.780869
26162     0.707107
196412    0.500000
211039    0.374634
788114    0.277350
194979    0.190500
745537    0.156412
Name: 776502, dtype: float64

776788
user
776788    1.000000
18297     1.000000
182213    0.609994
163884    0.296695
173236    0.000000
173218    0.000000
173187    0.000000
172770    0.000000
173146    0.000000
Name: 776788, dtype: float64

776878
user
371282    0.800000
5010      0.780869
112746    0.615457
5847      0.529813
353401    0.492366
824879    0.408248
632095    0.322329
686300    0.316228
350644    0.300000
Name: 776878, dtype: float64

777776
user
777776    1.000000
315610    1.000000
725984    1.000000
82952     0.311286
315118    0.258738
173141    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
Name: 777776, dtype: float64

777853
user
163709    0.514496
69546     0.514496
156952    0.249068
950331    0.000000
173187    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
173146    0.000000
Name: 777853, dtype: float64

778423
user
763520    0.832050
63998     0.554700
385143    0.554700
563103    0.554700
36587     0.554700
361892    0.554700
896308    0.489535
170172    0.392232
192095    0.352789
Name: 778423, dtype: float64

778970
user
172770    0.0
173415    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 778970, dtype: float64

779654
user
172770    0.0
173415    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 779654, dtype: float64

780237
user
22636     1.0
261654    1.0
222975    1.0
153678    1.0
321692    1.0
37980     1.0
780237    1.0
55705     1.0
194122    1.0
Name: 780237, dtype: float64

780363
user
780363    1.0
173421    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 780363, dtype: float64

780657
user
219299    1.000000
879835    1.000000
780657    1.000000
599892    1.000000
350912    0.780869
132734    0.624695
85808     0.408248
256163    0.133897
580520    0.130189
Name: 780657, dtype: float64

781375
user
535       0.244649
950331    0.000000
172770    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 781375, dtype: float64

781718
user
170364    1.000000
781718    1.000000
91788     0.707107
615574    0.624695
334694    0.357771
173141    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
Name: 781718, dtype: float64

781898
user
175043    0.369358
70299     0.369358
192450    0.295487
596177    0.295487
487327    0.295487
699433    0.295487
645667    0.295487
7488      0.295487
237982    0.295487
Name: 781898, dtype: float64

782157
user
23533     1.0
317949    1.0
158717    1.0
524501    1.0
820044    1.0
739296    1.0
946187    1.0
465115    1.0
835141    1.0
Name: 782157, dtype: float64

783096
user
642339    0.357143
789449    0.357143
489209    0.357143
127610    0.357143
157793    0.357143
114625    0.357143
743850    0.357143
907523    0.357143
178808    0.357143
Name: 783096, dtype: float64

783345
user
648839    1.0
783345    1.0
111561    1.0
786717    1.0
753506    1.0
314345    1.0
596425    1.0
257101    1.0
44077     1.0
Name: 783345, dtype: float64

783730
user
783730    1.000000
27962     1.000000
109581    1.000000
423018    0.514496
220825    0.512148
421743    0.512148
160914    0.500000
130768    0.428571
641859    0.193247
Name: 783730, dtype: float64

783901
user
72150     0.624695
389047    0.624695
558567    0.624695
277858    0.624695
85315     0.624695
67429     0.624695
159824    0.624695
256861    0.624695
194342    0.624695
Name: 783901, dtype: float64

784102
user
950331    0.0
172770    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 784102, dtype: float64

784555
user
922940    0.492366
356593    0.492366
181135    0.492366
282529    0.492366
308373    0.492366
279375    0.492366
288121    0.492366
461242    0.492366
167525    0.492366
Name: 784555, dtype: float64

785864
user
149955    1.000000
785864    1.000000
132734    0.780869
148254    0.771517
158018    0.529999
837135    0.500000
326607    0.441726
534410    0.373002
322019    0.323423
Name: 785864, dtype: float64

786282
user
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 786282, dtype: float64

786333
user
223400    0.857493
51405     0.268028
247859    0.181568
173141    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
Name: 786333, dtype: float64

786402
user
881353    0.577350
224347    0.209529
172770    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 786402, dtype: float64

786717
user
648839    1.0
783345    1.0
111561    1.0
786717    1.0
753506    1.0
314345    1.0
596425    1.0
257101    1.0
44077     1.0
Name: 786717, dtype: float64

787677
user
45978     0.369274
128615    0.320256
550014    0.240192
317295    0.229416
385219    0.195881
674425    0.173205
392887    0.171499
186286    0.092582
535       0.090443
Name: 787677, dtype: float64

787980
user
594913    0.182089
950331    0.000000
172589    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 787980, dtype: float64

788114
user
67902     0.462250
389789    0.453274
27176     0.369800
281732    0.277350
700993    0.277350
776502    0.277350
519716    0.266880
894693    0.216574
131358    0.201319
Name: 788114, dtype: float64

789207
user
317740    0.603023
198873    0.603023
28330     0.482418
321581    0.452267
699186    0.452267
50713     0.452267
50007     0.376705
290566    0.361814
173428    0.266371
Name: 789207, dtype: float64

789449
user
489209    1.000000
789449    1.000000
114625    1.000000
127610    1.000000
867166    0.780869
662901    0.707107
116016    0.707107
876665    0.624695
263524    0.600000
Name: 789449, dtype: float64

789611
user
789611    1.000000
377242    1.000000
24308     1.000000
612464    0.218218
173187    0.000000
173146    0.000000
173141    0.000000
173218    0.000000
173126    0.000000
Name: 789611, dtype: float64

790118
user
109622    0.258738
950331    0.000000
172770    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 790118, dtype: float64

790247
user
790247    1.000000
315174    1.000000
862633    0.980581
182213    0.609994
731285    0.606339
245897    0.562544
87338     0.481125
586606    0.371391
314604    0.351123
Name: 790247, dtype: float64

790296
user
82581     1.0
487327    1.0
652607    1.0
42615     1.0
7488      1.0
721140    1.0
645667    1.0
664747    1.0
192450    1.0
Name: 790296, dtype: float64

790931
user
422401    1.000000

user
366858    0.780869
68246     0.707107
328956    0.707107
127770    0.662266
326195    0.624695
87328     0.624695
172066    0.615457
136933    0.577350
71170     0.514496
Name: 804396, dtype: float64

805262
user
805262    1.000000
108936    0.331891
665569    0.177084
132504    0.162459
745537    0.078206
173146    0.000000
173187    0.000000
173141    0.000000
172589    0.000000
Name: 805262, dtype: float64

805310
user
287905    0.552158
287318    0.552158
85601     0.441726
670377    0.441726
445293    0.441726
148013    0.441726
170852    0.441726
386300    0.441726
52558     0.441726
Name: 805310, dtype: float64

805528
user
885332    0.783349
752281    0.707107
227401    0.707107
641062    0.707107
111719    0.707107
100771    0.707107
51496     0.707107
316446    0.707107
213776    0.707107
Name: 805528, dtype: float64

806035
user
950331    0.0
172770    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 806035, dtype: float64

806497
user
156698    1.000000
806497    1.000000
59146     0.707107
363072    0.577350
286366    0.577350
85669     0.500000
159353    0.266667
356252    0.239426
593182    0.175920
Name: 806497, dtype: float64

806557
user
950331    0.0
172770    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 806557, dtype: float64

806720
user
220866    0.624695
950331    0.000000
172589    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
Name: 806720, dtype: float64

806808
user
806808    1.000000
49680     0.348155
950331    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 806808, dtype: float64

806832
user
950331    0.0
172770    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 806832, dtype: float64

807425
user
500373    0.414781
774737    0.414781
780237    0.311086
246545    0.311086
49771     0.311086
321692    0.311086
37980     0.311086
222975    0.311086
55705     0.311086
Name: 807425, dtype: float64

808328
user
514716    0.387298
923208    0.245072
538853    0.129099
864848    0.100810
391794    0.091507
498923    0.079455
68122     0.048365
361303    0.022473
173038    0.000000
Name: 808328, dtype: float64

808968
user
329400    0.800000
91402     0.334252
160914    0.300000
293161    0.263434
391631    0.179888
256325    0.137876
237668    0.108448
470723    0.099540
43793     0.091147
Name: 808968, dtype: float64

809373
user
362085    1.000000
194941    0.707107
308086    0.666667
664138    0.577350
280132    0.577350
215649    0.552158
247348    0.529813
259023    0.514496
151133    0.461880
Name: 809373, dtype: float64

809423
user
70778     1.0
809423    1.0
950331    0.0
172946    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
Name: 809423, dtype: float64

810011
user
280573    0.301511
950331    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
Name: 810011, dtype: float64

810779
user
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 810779, dtype: float64

811088
user
582183    0.492366
260179    0.492366
302442    0.492366
280855    0.492366
195632    0.492366
394415    0.369274
219615    0.369274
625374    0.369274
67485     0.369274
Name: 811088, dtype: float64

811320
user
811320    1.000000
60473     0.707107
65081     0.529813
180729    0.435194
322627    0.396526
108338    0.368230
192676    0.311400
173038    0.000000
173126    0.000000
Name: 811320, dtype: float64

812195
user
812195    1.0
950331    0.0
172504    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 812195, dtype: float64

812784
user
71245     0.588348
190766    0.168742
363254    0.153168
315462    0.151620
173126    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
Name: 812784, dtype: float64

812978
user
91720     0.207514
950331    0.000000
172589    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 812978, dtype: float64

813653
user
813653    1.000000
388399    0.386695
950331    0.000000
172589    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 813653, dtype: float64

813771
user
813771    1.000000
199410    0.624695
650646    0.340503
950331    0.000000
173126    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173146    0.000000
Name: 813771, dtype: float64

813871
user
813871    1.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 813871, dtype: float64

814144
user
220887    0.962250
173187    0.962250
101994    0.363696
132614    0.355335
17211     0.286888
51405     0.206328
109583    0.192450
597752    0.192450
690482    0.192450
Name: 814144, dtype: float64

814610
user
648839    1.0
783345    1.0
111561    1.0
786717    1.0
753506    1.0
314345    1.0
596425    1.0
257101    1.0
44077     1.0
Name: 814610, dtype: float64

815492
user
27465     0.544331
1582      0.492366
171967    0.409616
150353    0.404061
251266    0.360668
262368    0.350823
171853    0.000000
171871    0.000000
173300    0.000000
Name: 815492, dtype: float64

815556
user
23533     1.0
317949    1.0
158717    1.0
524501    1.0
820044    1.0
739296    1.0
946187    1.0
465115    1.0
835141    1.0
Name: 815556, dtype: float64

816257
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 816257, dtype: float64

816326
user
395445    1.000000
376096    1.000000
465110    0.707107
256497    0.707107
126946    0.707107
397159    0.707107
611078    0.662266
46322     0.639602
464677    0.577350
Name: 816326, dtype: float64

816423
user
360301    0.393750
804396    0.354375
107593    0.324582
224377    0.315000
537282    0.315000
336473    0.315000
621501    0.315000
194941    0.278423
26843     0.277846
Name: 816423, dtype: float64

817367
user
218451    1.000000
190541    1.000000
193020    1.000000
320837    0.800000
137630    0.707107
932113    0.369274
247421    0.188044
724982    0.137767
173146    0.000000
Name: 817367, dtype: float64

817844
user
755162    0.857493
504329    0.606339
642291    0.514496
10762     0.514496
21351     0.514496
901025    0.514496
252964    0.514496
197504    0.357599
96320     0.342177
Name: 817844, dtype: float64

818006
user
46159     0.458349
80911     0.386543
589446    0.366679
196734    0.324102
899670    0.275010
203033    0.275010
151203    0.275010
342978    0.275010
732125    0.275010
Name: 818006, dtype: float64

818300
user
950331    0.0
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 818300, dtype: float64

818821
user
696729    1.000000
793692    1.000000
242673    0.707107
885332    0.615457
744060    0.447214
269509    0.447214
475084    0.441726
49642     0.243396
257609    0.219382
Name: 818821, dtype: float64

819045
user
323463    0.600000
94030     0.600000
3044      0.600000
116445    0.600000
197268    0.582086
308086    0.200000
534410    0.167851
816423    0.141750
710291    0.105247
Name: 819045, dtype: float64

819416
user
950331    0.0
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 819416, dtype: float64

819615
user
62880     1.000000
140023    1.000000
658169    1.000000
819615    1.000000
535452    0.468521
89781     0.464238
361582    0.266667
128271    0.237915
530433    0.198030
Name: 819615, dtype: float64

820044
user
23533     1.0
317949    1.0
158717    1.0
524501    1.0
820044    1.0
739296    1.0
946187    1.0
465115    1.0
835141    1.0
Name: 820044, dtype: float64

820052
user
950331    0.0
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 820052, dtype: float64

820109
user
950331    0.0
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 820109, dtype: float64

820542
user
350771    0.165145
950331    0.000000
172589    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 820542, dtype: float64

820908
user
239796    0.341372
284559    0.309208
158492    0.277663
51766     0.268197
476529    0.246932
940225    0.246932
44204     0.246932
321062    0.246932
318884    0.246932
Name: 820908, dtype: float64

820971
user
820971    1.0
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 820971, dtype: float64

821038
user
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
173126    0.0
Name: 821038, dtype: float64

821433
user
515762    0.707107
71205     0.183726
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
173126    0.000000
Name: 821433, dtype: float64

821502
user
292753    0.707107
950331    0.000000
172589    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 821502, dtype: float64

821511
user
226106    0.392232
107593    0.325396
593182    0.219900
950331    0.000000
173126    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
Name: 821511, dtype: float64

821860
user
60263     0.707107
775370    0.707107
419237    0.707107
4548      0.707107
155793    0.707107
510614    0.707107
532651    0.565685
405980    0.565685
439060    0.565685
Name: 821860, dtype: float64

822237
user
556845    1.000000
440081    1.000000
148723    1.000000
822237    1.000000
135920    0.577350
201349    0.565685
351808    0.500000
251581    0.345547
106083    0.336861
Name: 822237, dtype: float64

822366
user
257241    0.196116
133400    0.038695
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 822366, dtype: float64

822463
user
264572    0.229416
950331    0.000000
172504    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
Name: 822463, dtype: float64

822723
user
730158    0.609994
730352    0.539164
728391    0.416667
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
173126    0.000000
172504    0.000000
Name: 822723, dtype: float64

823508
user
195083    1.000000
823508    1.000000
353976    1.000000
149737    1.000000
222092    1.000000
65345     1.000000
129294    0.707107
570294    0.650945
550554    0.554700
Name: 823508, dtype: float64

823651
user
179325    0.928477
303595    0.928477
127163    0.928477
692299    0.656532
307072    0.656532
534410    0.346324
935084    0.344116
138679    0.315874
288157    0.266698
Name: 823651, dtype: float64

823754
user
469245    0.03434
950331    0.00000
172504    0.00000
173293    0.00000
173236    0.00000
173218    0.00000
173187    0.00000
173146    0.00000
173141    0.00000
Name: 823754, dtype: float64

824879
user
442748    0.816497
13006     0.637577
398891    0.577350
382523    0.540738
834840    0.408248
776878    0.408248
112534    0.408248
163201    0.408248
154501    0.355409
Name: 824879, dtype: float64

826163
user
619179    1.0
950331    0.0
172504    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
173126    0.0
Name: 826163, dtype: float64

827376
user
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 827376, dtype: float64

827709
user
613864    1.000000
827709    1.000000
108796    1.000000
129947    1.000000
190366    1.000000
389377    1.000000
678906    1.000000
194541    1.000000
721055    0.707107
Name: 827709, dtype: float64

828090
user
806808    1.000000
49680     0.348155
950331    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 828090, dtype: float64

828166
user
447445    0.577350
417735    0.577350
340512    0.577350
66639     0.577350
65841     0.577350
643010    0.560112
667169    0.450835
47484     0.408248
65433     0.408248
Name: 828166, dtype: float64

828218
user
828218    1.000000
856133    0.245718
315462    0.214423
224347    0.209529
745537    0.156412
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
Name: 828218, dtype: float64

828554
user
950331    0.0
173421    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 828554, dtype: float64

828625
user
944394    0.894427
853410    0.894427
39314     0.894427
201564    0.894427
622340    0.894427
49805     0.698430
83257     0.516398
4347      0.473879
310557    0.460179
Name: 828625, dtype: float64

830007
user
521321    0.365148
461939    0.365148
656737    0.365148
321090    0.365148
293102    0.346410
149300    0.249610
372209    0.187010
5311      0.167054
391794    0.134587
Name: 830007, dtype: float64

830549
user
950331    0.0
173421    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 830549, dtype: float64

831341
user
420421    0.363803
173415    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
Name: 831341, dtype: float64

831703
user
501746    0.589768
757228    0.589768
216874    0.589768
8323      0.589768
72348     0.589768
200875    0.589768
87724     0.589768
42721     0.589768
899377    0.589768
Name: 831703, dtype: float64

832609
user
714247    1.000000
537372    0.150756
172589    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
950331    0.000000
172504    0.000000
Name: 832609, dtype: float64

832619
user
950331    0.0
173421    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 832619, dtype: float64

833379
user
732125    0.322078
328754    0.322078
439187    0.322078
337835    0.322078
723330    0.322078
188061    0.322078
1028      0.322078
10258     0.322078
851090    0.322078
Name: 833379, dtype: float64

833785
user
219406    1.000000
879926    1.000000
833785    1.000000
480616    1.000000
463007    1.000000
250828    1.000000
551133    0.545545
135672    0.278207
283160    0.201008
Name: 833785, dtype: float64

834097
user
397635    0.230769
950331    0.000000
172589    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 834097, dtype: float64

834745
user
950331    0.0
173421    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 834745, dtype: float64

834840
user
163201    1.000000
834840    1.000000
11328     0.624695
632495    0.505076
196166    0.464238
606826    0.447214
155100    0.447214
824879    0.408248
166       0.262613
Name: 834840, dtype: float64

835141
user
23533     1.0
317949    1.0
158717    1.0
524501    1.0
820044    1.0
739296    1.0
946187    1.0
465115    1.0
835141    1.0
Name: 835141, dtype: float64

836071
user
303258    0.780869
45410     0.780869
768680    0.780869
345311    0.624695
92767     0.265036
179727    0.185990
71205     0.162313
950331    0.000000
173141    0.000000
Name: 836071, dtype: float64

836186
user
899377    0.255031
200875    0.255031
87724     0.255031
501746    0.255031
42721     0.255031
709700    0.255031
8323      0.255031
757228    0.255031
356277    0.255031
Name: 836186, dtype: float64

836215
user
95763     0.600000
96613     0.600000
562349    0.600000
428481    0.480000
702397    0.424264
26705     0.346410
423018    0.308697
292085    0.265036
88418     0.249615
Name: 836215, dtype: float64

836480
user
392159    1.000000
42317     1.000000
836480    1.000000
363944    1.000000
859147    0.390567
284695    0.225647
173141    0.000000
172946    0.000000
172955    0.000000
Name: 836480, dtype: float64

837135
user
191379    0.5
122394    0.5
359293    0.5
745938    0.5
439699    0.5
172946    0.5
922709    0.5
149217    0.5
101449    0.5
Name: 837135, dtype: float64

837685
user
214780    1.000000
44853     0.680414
568404    0.585206
105794    0.565685
155094    0.483368
282032    0.408248
361582    0.333333
51405     0.268028
179727    0.132324
Name: 837685, dtype: float64

838045
user
855588    0.707107
172504    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
Name: 838045, dtype: float64

838116
user
348677    0.707107
503594    0.624695
69676     0.423999
386997    0.173259
218901    0.171028
728009    0.161558
173126    0.000000
172946    0.000000
172955    0.000000
Name: 838116, dtype: float64

838134
user
838134    1.000000
4891      1.000000
6791      1.000000
793871    1.000000
945633    1.000000
288137    1.000000
686161    1.000000
75794     0.648886
906467    0.624695
Name: 838134, dtype: float64

838164
user
661090    0.554700
152406    0.424264
173126    0.000000
172589    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
950331    0.000000
Name: 838164, dtype: float64

838753
user
838753    1.0
950331    0.0
172946    0.0
172955    0.0
173038    0.0
173126    0.0
173141    0.0
173146    0.0
173187    0.0
Name: 838753, dtype: float64

839006
user
219406    1.000000
879926    1.000000
833785    1.000000
480616    1.000000
463007    1.000000
250828    1.000000
551133    0.545545
135672    0.278207
283160    0.201008
Name: 839006, dtype: float64

839512
user
839512    1.000000
425059    0.328798
173038    0.000000
172504    0.000000
172589    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173141    0.000000
Name: 839512, dtype: float64

839683
user
186342    1.0
950331    0.0
173141    0.0
172770    0.0
172946    0.0
172955    0.0
173038    0.0
173126    0.0
173187    0.0
Name: 839683, dtype: float64

839712
user
200652    1.000000
126931    1.000000
839712    1.000000
148206    0.707107
441889    0.707107
2419      0.468165
33061     0.441726
93647     0.424264
531388    0.371391
Name: 839712, dtype: float64

839814
user
923430    0.632456
753506    0.447214
524501    0.447214
786717    0.447214
317949    0.447214
112521    0.447214
393032    0.447214
923681    0.447214
111561    0.447214
Name: 839814, dtype: float64

840243
user
846528    0.492366
36587     0.492366
385143    0.492366
563103    0.492366
361892    0.492366
63998     0.492366
170172    0.348155
364520    0.307579
778423    0.273115
Name: 840243, dtype: float64

840293
user
74537     0.435194
537282    0.435194
906229    0.435194
946771    0.435194
135715    0.435194
199124    0.348155
249802    0.261116
107593    0.236017
112229    0.230571
Name: 840293, dtype: float64

840877
user
129098    1.000000
840877    1.000000
551576    1.000000
444370    0.707107
28304     0.624695
50137     0.624695
92767     0.424264
127843    0.400892
652898    0.284747
Name: 840877, dtype: float64

841181
user
841181    1.000000
519716    0.577350
694627    0.275010
96575     0.217250
315462    0.160817
173126    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
Name: 841181, dtype: float64

841437
user
841437    1.000000
255287    0.707107
476834    0.514496
25840     0.234920
470723    0.165900
249051    0.140797

user
546534    0.737210
248496    0.589768
157659    0.312467
196412    0.294884
347289    0.294884
906552    0.214560
155100    0.211002
370681    0.170696
199202    0.147442
Name: 857499, dtype: float64

857507
user
401012    1.000000
190236    0.800000
186982    0.545545
89719     0.441726
725789    0.396059
173146    0.000000
173141    0.000000
173126    0.000000
173038    0.000000
Name: 857507, dtype: float64

857656
user
950331    0.0
172504    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
173126    0.0
Name: 857656, dtype: float64

857750
user
950331    0.0
172504    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
173126    0.0
Name: 857750, dtype: float64

858004
user
459734    0.577350
240289    0.577350
446157    0.577350
546902    0.577350
367815    0.577350
72531     0.577350
665848    0.440225
95336     0.392837
725655    0.392837
Name: 858004, dtype: float64

859132
user
950331    0.0
172504    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
173126    0.0
Name: 859132, dtype: float64

859147
user
48104     0.650945
522869    0.460287
358474    0.431099
42317     0.390567
68563     0.390567
392159    0.390567
363944    0.390567
836480    0.390567
111904    0.375823
Name: 859147, dtype: float64

859384
user
859384    1.00000
132144    0.26968
950331    0.00000
173141    0.00000
172946    0.00000
172955    0.00000
173038    0.00000
173126    0.00000
173146    0.00000
Name: 859384, dtype: float64

859898
user
208228    0.514496
88316     0.319801
128271    0.317221
145101    0.219860
129333    0.199007
237668    0.180746
728009    0.161558
173141    0.000000
173126    0.000000
Name: 859898, dtype: float64

860255
user
168866    0.577350
256609    0.408248
930847    0.408248
292085    0.318788
241227    0.230940
514754    0.221404
2112      0.214423
149300    0.197334
135672    0.160623
Name: 860255, dtype: float64

860508
user
950331    0.0
172504    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
173126    0.0
Name: 860508, dtype: float64

861280
user
43742     0.184159
431662    0.182453
213776    0.145962
100771    0.145962
641062    0.145962
227401    0.145962
711410    0.145962
358687    0.145962
475240    0.145962
Name: 861280, dtype: float64

861818
user
922962    1.000000
861818    1.000000
359203    1.000000
285710    1.000000
91092     1.000000
234398    0.780869
17211     0.745356
361303    0.696311
151946    0.577350
Name: 861818, dtype: float64

861992
user
370833    0.550482
133586    0.492366
292753    0.435194
111904    0.284268
485831    0.260862
85669     0.246183
816423    0.242336
385272    0.155700
243883    0.142134
Name: 861992, dtype: float64

862265
user
950331    0.0
172490    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
173126    0.0
Name: 862265, dtype: float64

862633
user
790247    0.980581
191023    0.980581
315174    0.980581
182213    0.598149
731285    0.594564
245897    0.551620
87338     0.471782
586606    0.364179
314604    0.344305
Name: 862633, dtype: float64

863730
user
258538    0.707107
143034    0.232495
108936    0.187746
950331    0.000000
172770    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 863730, dtype: float64

863771
user
356277    0.529813
36636     0.491919
498185    0.423850
470036    0.413714
441024    0.413714
887956    0.241511
252295    0.225913
359001    0.214077
836186    0.135119
Name: 863771, dtype: float64

863840
user
863840    1.000000
8055      1.000000
928303    1.000000
756238    1.000000
424498    1.000000
710581    0.894427
334520    0.707107
420344    0.707107
926948    0.707107
Name: 863840, dtype: float64

863919
user
950331    0.0
172490    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
173126    0.0
Name: 863919, dtype: float64

864133
user
380394    0.707107
5282      0.500000
535452    0.441726
180718    0.424264
368907    0.345547
180541    0.186052
219293    0.183254
20363     0.145095
328775    0.125078
Name: 864133, dtype: float64

864848
user
538853    0.780869
498923    0.480592
52663     0.327429
68122     0.292540
361303    0.135932
808328    0.100810
173141    0.000000
172955    0.000000
173038    0.000000
Name: 864848, dtype: float64

864883
user
864883    1.000000
893228    1.000000
290662    1.000000
759526    1.000000
918040    0.455842
173428    0.441726
219293    0.431934
73273     0.372678
395948    0.370625
Name: 864883, dtype: float64

865559
user
62880     1.000000
140023    1.000000
658169    1.000000
819615    1.000000
535452    0.468521
89781     0.464238
361582    0.266667
128271    0.237915
530433    0.198030
Name: 865559, dtype: float64

866248
user
579521    0.426401
395537    0.305424
73273     0.298142
173141    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
950331    0.000000
Name: 866248, dtype: float64

866967
user
866967    1.000000
88316     0.319801
87153     0.263117
636781    0.208514
950331    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
Name: 866967, dtype: float64

867166
user
789449    0.780869
743850    0.780869
489209    0.780869
127610    0.780869
114625    0.780869
173236    0.624695
116016    0.552158
662901    0.552158
876665    0.487805
Name: 867166, dtype: float64

867509
user
140454    0.529813
173421    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 867509, dtype: float64

867891
user
31010     0.554700
95895     0.554700
113728    0.392232
665456    0.346518
861280    0.060724
173218    0.000000
173236    0.000000
173187    0.000000
173146    0.000000
Name: 867891, dtype: float64

868283
user
49529     1.000000
868283    1.000000
694627    0.366679
420805    0.297044
163884    0.237356
900562    0.197814
179727    0.088216
173218    0.000000
173187    0.000000
Name: 868283, dtype: float64

868936
user
16383     1.000000
103304    0.197488
173146    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
173187    0.000000
Name: 868936, dtype: float64

869332
user
869332    1.000000
550031    1.000000
195546    0.845154
903681    0.514496
351825    0.404061
950331    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
Name: 869332, dtype: float64

869698
user
630504    1.000000
5995      1.000000
319753    1.000000
869698    1.000000
849404    1.000000
389704    1.000000
412468    0.980581
7265      0.780869
134131    0.780869
Name: 869698, dtype: float64

870138
user
588237    0.928477
35538     0.689655
172504    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
Name: 870138, dtype: float64

870260
user
326701    1.0
950331    0.0
172504    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 870260, dtype: float64

870449
user
315462    0.268028
950331    0.000000
172504    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
Name: 870449, dtype: float64

870790
user
23255     0.685994
65841     0.685994
447445    0.685994
417735    0.685994
794785    0.685994
340512    0.685994
358700    0.685994
219760    0.685994
66639     0.685994
Name: 870790, dtype: float64

871568
user
950331    0.0
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 871568, dtype: float64

872014
user
588404    0.530288
706290    0.485071
129947    0.485071
190366    0.485071
108796    0.485071
678906    0.485071
389377    0.485071
827709    0.485071
194541    0.485071
Name: 872014, dtype: float64

872642
user
950331    0.0
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 872642, dtype: float64

873812
user
156985    1.0
873812    1.0
173126    1.0
950331    0.0
173141    0.0
172946    0.0
172955    0.0
173038    0.0
173146    0.0
Name: 873812, dtype: float64

874331
user
158018    0.599625
173325    0.500000
255258    0.232495
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
172504    0.000000
173126    0.000000
Name: 874331, dtype: float64

874578
user
158481    0.980581
107432    0.980581
504649    0.980581
85705     0.980581
112616    0.980581
47297     0.980581
855363    0.765705
192236    0.765705
3019      0.747686
Name: 874578, dtype: float64

875164
user
950331    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
173126    0.0
Name: 875164, dtype: float64

875286
user
875286    1.000000
614124    1.000000
609485    0.662266
193185    0.514496
257876    0.514496
314366    0.346410
372398    0.315000
222193    0.303046
90754     0.171219
Name: 875286, dtype: float64

876575
user
325034    0.624695
280573    0.301511
256163    0.178529
173126    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173141    0.000000
Name: 876575, dtype: float64

876665
user
743850    0.624695
489209    0.624695
789449    0.624695
114625    0.624695
127610    0.624695
867166    0.487805
662901    0.441726
116016    0.441726
263524    0.374817
Name: 876665, dtype: float64

877370
user
112180    1.000000
143267    1.000000
632235    1.000000
133152    1.000000
491073    1.000000
606877    1.000000
937146    0.894427
322423    0.800000
71789     0.615457
Name: 877370, dtype: float64

878525
user
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 878525, dtype: float64

879423
user
76488     0.203186
218901    0.171028
950331    0.000000
173141    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173146    0.000000
Name: 879423, dtype: float64

879531
user
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 879531, dtype: float64

879835
user
219299    1.000000
879835    1.000000
780657    1.000000
599892    1.000000
350912    0.780869
132734    0.624695
85808     0.408248
256163    0.133897
580520    0.130189
Name: 879835, dtype: float64

879926
user
219406    1.000000
879926    1.000000
833785    1.000000
480616    1.000000
463007    1.000000
250828    1.000000
551133    0.545545
135672    0.278207
283160    0.201008
Name: 879926, dtype: float64

880233
user
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 880233, dtype: float64

880552
user
24943     1.000000
95664     1.000000
360079    1.000000
880552    1.000000
426302    1.000000
286800    0.585206
158429    0.419314
79647     0.416025
217426    0.346410
Name: 880552, dtype: float64

880907
user
558567    0.615457
57262     0.615457
389047    0.615457
530618    0.615457
106580    0.615457
72150     0.615457
256861    0.615457
428771    0.615457
277858    0.615457
Name: 880907, dtype: float64

880951
user
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 880951, dtype: float64

881353
user
924719    0.577350
451148    0.577350
155636    0.577350
786402    0.577350
630195    0.577350
256395    0.577350
2368      0.516398
282534    0.450835
302395    0.408248
Name: 881353, dtype: float64

881776
user
591073    1.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 881776, dtype: float64

881924
user
418950    1.000000
367276    1.000000
637343    1.000000
881924    1.000000
90754     0.171219
175469    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 881924, dtype: float64

882082
user
46255     0.492366
389037    0.492366
327434    0.492366
293300    0.307579
399266    0.307579
851312    0.273115
115682    0.169972
361582    0.131298
8647      0.122613
Name: 882082, dtype: float64

882247
user
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 882247, dtype: float64

882297
user
882297    1.000000
214796    0.707107
674768    0.500000
173187    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
173146    0.000000
Name: 882297, dtype: float64

882402
user
882402    1.0
465152    1.0
43207     1.0
239439    1.0
648094    1.0
169215    1.0
2175      1.0
642214    1.0
230190    1.0
Name: 882402, dtype: float64

882571
user
750203    0.542326
79511     0.542326
270595    0.542326
116734    0.542326
361531    0.542326
556848    0.325396
68716     0.325396
133493    0.306786
227331    0.239560
Name: 882571, dtype: float64

882927
user
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 882927, dtype: float64

883188
user
316768    1.0
695760    1.0
27939     1.0
50690     1.0
134761    1.0
50739     1.0
147932    1.0
29070     1.0
256789    1.0
Name: 883188, dtype: float64

883362
user
104713    0.357143
943164    0.357143
906136    0.357143
565057    0.357143
571404    0.357143
139802    0.357143
844482    0.285714
127610    0.285714
489209    0.285714
Name: 883362, dtype: float64

884890
user
400694    0.218218
254239    0.218218
73653     0.218218
63030     0.218218
162500    0.218218
328802    0.218218
65017     0.202610
147610    0.187120
745223    0.174574
Name: 884890, dtype: float64

885234
user
256001    1.000000
400150    1.000000
885234    1.000000
180718    0.800000
688990    0.577350
159313    0.520756
308702    0.323423
360130    0.250490
572720    0.242983
Name: 885234, dtype: float64

885308
user
150074    1.000000
753989    1.000000
885308    1.000000
86766     1.000000
702397    0.707107
39188     0.685994
279785    0.232104
836186    0.191273
249051    0.187729
Name: 885308, dtype: float64

885332
user
805528    0.783349
316446    0.615457
641062    0.615457
100771    0.615457
818821    0.615457
752281    0.615457
696729    0.615457
111719    0.615457
475240    0.615457
Name: 885332, dtype: float64

885428
user
216704    0.780869
74618     0.600000
749783    0.457496
229831    0.375000
26843     0.371391
391957    0.305995
215042    0.254824
2109      0.232845
470723    0.165900
Name: 885428, dtype: float64

885528
user
28722     1.000000
26352     1.000000
885528    1.000000
666409    0.707107
193499    0.577350
193549    0.435194
166       0.328266
173141    0.000000
173126    0.000000
Name: 885528, dtype: float64

886362
user
82581     1.0
487327    1.0
652607    1.0
42615     1.0
7488      1.0
721140    1.0
645667    1.0
664747    1.0
192450    1.0
Name: 886362, dtype: float64

886698
user
527607    0.624695
170852    0.600000
289156    0.600000
445293    0.600000
74904     0.424264
215860    0.424264
322844    0.423850
133983    0.420084
93992     0.411597
Name: 886698, dtype: float64

886848
user
886848    1.000000
201349    0.707107
950331    0.000000
172770    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 886848, dtype: float64

887400
user
130006    0.662266
728692    0.650945
534410    0.466252
722512    0.408248
229831    0.125000
173187    0.000000
173146    0.000000
173141    0.000000
173126    0.000000
Name: 887400, dtype: float64

887586
user
75433     0.832050
725466    0.832050
116307    0.832050
470215    0.554700
798855    0.554700
261998    0.554700
441024    0.519778
282875    0.515026
114081    0.443760
Name: 887586, dtype: float64

887956
user
223459    0.569803
356277    0.455842
36636     0.423239
498185    0.364674
470036    0.355953
441024    0.355953
863771    0.241511
252295    0.194372
359001    0.184188
Name: 887956, dtype: float64

889321
user
140454    0.662266
475084    0.552158
356471    0.247841
279615    0.245256
49642     0.194717
173141    0.000000
173146    0.000000
173187    0.000000
173218    0.000000
Name: 889321, dtype: float64

889421
user
246061    0.361787
950331    0.000000
172504    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
Name: 889421, dtype: float64

890235
user
280011    0.615457
534551    0.527750
665344    0.435194
745622    0.335013
85694     0.275241
189901    0.262910
68632     0.123987
356471    0.122028
145101    0.101486
Name: 890235, dtype: float64

890715
user
950331    0.0
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 890715, dtype: float64

890873
user
890873    1.000000
537352    1.000000
251629    1.000000
949019    0.577350
856133    0.307148
194387    0.305888
224347    0.279372
568971    0.231455
745537    0.156412
Name: 890873, dtype: float64

891451
user
63030     0.529813
328802    0.529813
73653     0.529813
400694    0.529813
162500    0.529813
254239    0.529813
65017     0.491919
147610    0.454311
319754    0.272587
Name: 891451, dtype: float64

892043
user
114162    0.707107
745622    0.192450
82952     0.088045
249051    0.066372
173146    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
Name: 892043, dtype: float64

892884
user
151927    1.0
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 892884, dtype: float64

892941
user
918040    0.341882
172589    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
Name: 892941, dtype: float64

893228
user
864883    1.000000
893228    1.000000
290662    1.000000
759526    1.000000
918040    0.455842
173428    0.441726
219293    0.431934
73273     0.372678
395948    0.370625
Name: 893228, dtype: float64

894693
user
281732    0.780869
700993    0.780869
776502    0.780869
250391    0.624695
26162     0.552158
196412    0.390434
211039    0.292540
788114    0.216574
192676    0.194530
Name: 894693, dtype: float64

896308
user
763520    0.588348
778423    0.489535
195147    0.316972
192095    0.249459
209839    0.196116
745938    0.196116
463997    0.196116
191379    0.196116
170268    0.196116
Name: 896308, dtype: float64

896394
user
2849      1.000000
161783    1.000000
400268    0.800000
393981    0.529813
131358    0.518476
367228    0.514496
293382    0.431331
369062    0.404061
390671    0.370625
Name: 896394, dtype: float64

898548
user
69562     0.894427
950331    0.000000
172770    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 898548, dtype: float64

899377
user
899377    1.000000
42721     1.000000
709700    1.000000
757228    1.000000
87724     1.000000
8323      1.000000
501746    1.000000
470673    0.800000
131375    0.707107
Name: 899377, dtype: float64

899381
user
280826    0.577350
334694    0.357771
288157    0.287242
950331    0.000000
173146    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
Name: 899381, dtype: float64

899670
user
487400    1.000000
159773    1.000000
342978    1.000000
106216    1.000000
899670    1.000000
267306    1.000000
203033    1.000000
177362    0.970143
135354    0.707107
Name: 899670, dtype: float64

899799
user
670377    0.707107
578969    0.707107
286962    0.707107
268107    0.707107
85626     0.609272
33179     0.384900
855589    0.312348
805310    0.312348
171967    0.231714
Name: 899799, dtype: float64

899828
user
288190    1.000000
149300    0.341793
385612    0.164153
950331    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000

902556
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 902556, dtype: float64

902743
user
137615    1.000000
902743    1.000000
902931    0.780869
380098    0.600000
652365    0.348155
516840    0.278693
392082    0.260378
308702    0.258738
665569    0.236113
Name: 902743, dtype: float64

902808
user
427412    1.000000
394365    1.000000
476834    0.857493
292194    0.577350
872014    0.363803
662925    0.339276
935084    0.222375
90296     0.189358
217350    0.116863
Name: 902808, dtype: float64

902931
user
137615    0.780869
902743    0.780869
318843    0.780869
705834    0.624695
852767    0.624695
380098    0.468521
652365    0.271864
516840    0.217623
392082    0.203321
Name: 902931, dtype: float64

903681
user
45381     0.514496
869332    0.514496
550031    0.514496
195546    0.434828
351825    0.207888
505806    0.199064
950331    0.000000
172946    0.000000
172955    0.000000
Name: 903681, dtype: float64

904924
user
904924    1.0
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 904924, dtype: float64

905082
user
251283    0.707107
114146    0.707107
22074     0.707107
213301    0.065866
173038    0.000000
173126    0.000000
173141    0.000000
173146    0.000000
950331    0.000000
Name: 905082, dtype: float64

905460
user
392903    0.707107
400110    0.707107
401104    0.707107
26450     0.707107
253153    0.500000
253154    0.500000
130006    0.374634
392887    0.280056
211914    0.261116
Name: 905460, dtype: float64

906136
user
104713    1.000000
943164    1.000000
883362    0.357143
90754     0.285365
115682    0.276172
728009    0.161558
173141    0.000000
173146    0.000000
173187    0.000000
Name: 906136, dtype: float64

906229
user
946771    1.000000
906229    1.000000
135715    1.000000
286800    0.468165
840293    0.435194
171853    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
Name: 906229, dtype: float64

906243
user
23533     1.0
317949    1.0
158717    1.0
524501    1.0
820044    1.0
739296    1.0
946187    1.0
465115    1.0
835141    1.0
Name: 906243, dtype: float64

906467
user
280902    0.624695
945633    0.624695
4891      0.624695
6791      0.624695
793871    0.624695
288137    0.624695
838134    0.624695
686161    0.624695
75794     0.405356
Name: 906467, dtype: float64

906552
user
686640    0.606339
198386    0.606339
612464    0.529256
678502    0.485071
248496    0.363803
692540    0.363803
89999     0.326916
507859    0.238833
390671    0.224724
Name: 906552, dtype: float64

907523
user
642339    1.000000
156173    1.000000
157793    1.000000
97283     0.707107
505806    0.386912
783096    0.357143
321572    0.323381
154501    0.290191
71632     0.248452
Name: 907523, dtype: float64

908860
user
908860    1.000000
209415    1.000000
201162    1.000000
644110    1.000000
152603    1.000000
351982    1.000000
554398    0.707107
848512    0.707107
427422    0.624695
Name: 908860, dtype: float64

908867
user
261984    0.371391
85694     0.132873
950331    0.000000
172770    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 908867, dtype: float64

910316
user
95916     0.408248
90754     0.285365
514754    0.230089
133993    0.213504
171853    0.000000
171678    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
Name: 910316, dtype: float64

911169
user
359553    0.707107
27836     0.441726
632095    0.170941
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
172589    0.000000
173146    0.000000
Name: 911169, dtype: float64

912337
user
950331    0.0
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 912337, dtype: float64

913037
user
262112    0.577350
67890     0.577350
313319    0.577350
173038    0.577350
30202     0.408248
85626     0.284268
28600     0.242091
728391    0.240563
218901    0.222171
Name: 913037, dtype: float64

913374
user
63697     0.441726
279785    0.232104
950331    0.000000
172946    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
Name: 913374, dtype: float64

913946
user
19325     1.000000
290708    1.000000
129333    0.099504
950331    0.000000
172946    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
Name: 913946, dtype: float64

914284
user
706290    0.707107
588404    0.441726
872014    0.342997
282426    0.300000
351808    0.282843
178898    0.231455
264572    0.216295
148702    0.215041
568971    0.174574
Name: 914284, dtype: float64

914914
user
723330    1.000000
914914    1.000000
137630    0.707107
507738    0.615457
851312    0.554700
833379    0.322078
90296     0.315597
166       0.196960
249051    0.187729
Name: 914914, dtype: float64

915067
user
927427    1.000000
2109      0.388075
950331    0.000000
172589    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 915067, dtype: float64

917144
user
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 917144, dtype: float64

917504
user
465152    0.780869
43207     0.780869
230190    0.780869
169215    0.780869
38120     0.780869
648094    0.780869
239439    0.780869
2175      0.780869
642214    0.780869
Name: 917504, dtype: float64

917558
user
264572    0.305888
950331    0.000000
172504    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
Name: 917558, dtype: float64

917934
user
157628    0.268328
322844    0.177705
630210    0.160357
72749     0.130931
249391    0.122474
180541    0.117670
67868     0.101274
5666      0.086066
173038    0.000000
Name: 917934, dtype: float64

918040
user
386792    0.569803
614812    0.569803
786717    0.569803
596425    0.569803
502484    0.569803
923681    0.569803
186572    0.569803
314345    0.569803
257101    0.569803
Name: 918040, dtype: float64

918441
user
152494    0.500000
72686     0.181369
950331    0.000000
172770    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 918441, dtype: float64

918706
user
202044    0.685994
95887     0.514496
89719     0.378777
67211     0.363803
621199    0.272587
159599    0.200839
921028    0.195036
650202    0.164245
89963     0.133337
Name: 918706, dtype: float64

918992
user
918992    1.0
109916    0.6
950331    0.0
173300    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 918992, dtype: float64

919073
user
882402    0.6
43207     0.6
239439    0.6
38120     0.6
169215    0.6
2175      0.6
642214    0.6
230190    0.6
465152    0.6
Name: 919073, dtype: float64

919776
user
89781     0.464238
91720     0.276686
8647      0.249029
820908    0.049386
173218    0.000000
173187    0.000000
173236    0.000000
173146    0.000000
172589    0.000000
Name: 919776, dtype: float64

920109
user
950331    0.0
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 920109, dtype: float64

920668
user
179832    0.970143
178600    0.582086
150785    0.406794
155100    0.347089
370681    0.280788
673813    0.124784
631109    0.121268
103304    0.019159
173038    0.000000
Name: 920668, dtype: float64

920743
user
263360    1.000000
510431    0.470360
459433    0.336861
153457    0.263890
950331    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
Name: 920743, dtype: float64

921028
user
288222    0.305578
287274    0.227449
10287     0.227449
192226    0.227449
192944    0.227449
177065    0.227449
129160    0.227449
930037    0.227449
574781    0.227449
Name: 921028, dtype: float64

921150
user
921150    1.000000
798609    0.404061
600241    0.317221
145101    0.219860
284357    0.214115
391794    0.113410
173187    0.000000
173218    0.000000
173236    0.000000
Name: 921150, dtype: float64

921446
user
288157    0.287242
133993    0.213504
32143     0.138343
173146    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173141    0.000000
173218    0.000000
Name: 921446, dtype: float64

921784
user
227541    0.970143
190236    0.582086
132504    0.262681
283160    0.146254
149300    0.082897
950331    0.000000
173126    0.000000
172589    0.000000
172770    0.000000
Name: 921784, dtype: float64

922173
user
950331    0.0
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 922173, dtype: float64

922439
user
950331    0.0
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 922439, dtype: float64

922709
user
149955    1.000000
785864    1.000000
132734    0.780869
148254    0.771517
158018    0.529999
837135    0.500000
326607    0.441726
534410    0.373002
322019    0.323423
Name: 922709, dtype: float64

922940
user
279375    1.000000
308373    1.000000
288121    1.000000
167525    1.000000
181135    1.000000
261748    0.615457
256985    0.600000
129316    0.597614
85808     0.544331
Name: 922940, dtype: float64

922962
user
922962    1.000000
861818    1.000000
359203    1.000000
285710    1.000000
91092     1.000000
234398    0.780869
17211     0.745356
361303    0.696311
151946    0.577350
Name: 922962, dtype: float64

923208
user
446105    0.379663
85315     0.284747
558567    0.284747
72150     0.284747
173141    0.284747
173838    0.284747
428771    0.284747
194342    0.284747
425198    0.284747
Name: 923208, dtype: float64

923430
user
199178    0.707107
782157    0.707107
319105    0.707107
186572    0.707107
317949    0.707107
648839    0.707107
393032    0.707107
194854    0.707107
524501    0.707107
Name: 923430, dtype: float64

923459
user
151661    0.331133
2847      0.293470
636320    0.264906
461242    0.264906
192836    0.264906
111561    0.264906
395445    0.264906
203033    0.264906
923681    0.264906
Name: 923459, dtype: float64

923681
user
648839    1.0
783345    1.0
111561    1.0
786717    1.0
753506    1.0
314345    1.0
596425    1.0
257101    1.0
44077     1.0
Name: 923681, dtype: float64

923856
user
23682     1.000000
401684    0.225018
950331    0.000000
173126    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173141    0.000000
Name: 923856, dtype: float64

924153
user
321062    1.000000
676064    1.000000
385886    1.000000
328925    0.624695
245897    0.450035
323845    0.441726
314531    0.431934
359001    0.404061
369062    0.404061
Name: 924153, dtype: float64

924557
user
398361    1.000000
924557    1.000000
70861     1.000000
85645     0.707107
5666      0.256600
133400    0.246632
20363     0.205196
256325    0.172345
745537    0.156412
Name: 924557, dtype: float64

924558
user
116734    0.39036
153553    0.39036
270595    0.39036
63763     0.39036
940225    0.39036
750203    0.39036
59764     0.39036
44204     0.39036
765136    0.39036
Name: 924558, dtype: float64

924719
user
256395    1.000000
924719    1.000000
2368      0.894427
282534    0.780869
302395    0.707107
881353    0.577350
284839    0.577350
4629      0.298142
318030    0.290957
Name: 924719, dtype: float64

924772
user
950331    0.0
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 924772, dtype: float64

925400
user
950331    0.0
172504    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 925400, dtype: float64

926401
user
66431     1.000000
926401    1.000000
33831     0.707107
393293    0.707107
855363    0.624695
314604    0.468165
251266    0.450835
101994    0.377964
90296     0.252478
Name: 926401, dtype: float64

926481
user
754481    0.707107
950331    0.000000
172504    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
Name: 926481, dtype: float64

926948
user
227485    0.707107
863840    0.707107
8055      0.707107
928303    0.707107
756238    0.707107
424498    0.707107
710581    0.632456
334520    0.500000
420344    0.500000
Name: 926948, dtype: float64

927427
user
927427    1.000000
2109      0.388075
950331    0.000000
172589    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 927427, dtype: float64

927595
user
854097    0.707107
193213    0.529813
129012    0.468293
147       0.462250
211039    0.374634
372398    0.315000
33179     0.272166
156952    0.199254
364545    0.177778
Name: 927595, dtype: float64

927893
user
839512    1.000000
425059    0.328798
173038    0.000000
172504    0.000000
172589    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173141    0.000000
Name: 927893, dtype: float64

928292
user
928292    1.000000
46592     0.270914
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
172770    0.000000
173146    0.000000
Name: 928292, dtype: float64

928303
user
863840    1.000000
8055      1.000000
928303    1.000000
756238    1.000000
424498    1.000000
710581    0.894427
334520    0.707107
420344    0.707107
926948    0.707107
Name: 928303, dtype: float64

928428
user
287398    0.707107
950331    0.000000
172504    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
173141    0.000000
Name: 928428, dtype: float64

929369
user
442382    0.800000
252295    0.639602
728009    0.161558
950331    0.000000
173038    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173126    0.000000
Name: 929369, dtype: float64

929763
user
186572    0.49029
814610    0.49029
239439    0.49029
2175      0.49029
757228    0.49029
614812    0.49029
43207     0.49029
648839    0.49029
147193    0.49029
Name: 929763, dtype: float64

930037
user
10287     1.000000
930037    1.000000
192226    1.000000
29563     0.780869
288222    0.707107
23433     0.441726
114860    0.436436
138679    0.340207
46560     0.334825
Name: 930037, dtype: float64

930847
user
710618    0.515711
27465     0.481125
860255    0.408248
292085    0.390434
241227    0.282843
514754    0.271163
262368    0.248069
149300    0.241684
43793     0.143223
Name: 930847, dtype: float64

931654
user
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 931654, dtype: float64

931768
user
204033    1.000000
48814     1.000000
931768    1.000000
719811    1.000000
75174     1.000000
707460    1.000000
98330     0.780869
62904     0.585206
211914    0.492366
Name: 931768, dtype: float64

931904
user
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 931904, dtype: float64

932113
user
294354    0.492366
7488      0.492366
790296    0.492366
703432    0.492366
645667    0.492366
886362    0.492366
61776     0.492366
487327    0.492366
42615     0.492366
Name: 932113, dtype: float64

934704
user
950331    0.0
172589    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 934704, dtype: float64

934995
user
934995    1.0
651150    1.0
171329    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 934995, dtype: float64

935034
user
935034    1.000000
136933    0.577350
350644    0.500000
113193    0.441726
174016    0.307794
30196     0.304114
173141    0.000000
173038    0.000000
173126    0.000000
Name: 935034, dtype: float64

935084
user
127163    0.370625
303595    0.370625
101449    0.370625
179325    0.370625
574786    0.370625
156256    0.370625
359293    0.370625
122394    0.370625
172946    0.370625
Name: 935084, dtype: float64

935109
user
172589    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
173141    0.0
Name: 935109, dtype: float64

936541
user
481628    0.776114
138572    0.685994
591369    0.640000
292085    0.441726
68203     0.416605
68977     0.237200
20363     0.123117
173218    0.000000
173146    0.000000
Name: 936541, dtype: float64

936595
user
113732    0.457496
668508    0.457496
150887    0.252610
224755    0.239793
213971    0.192640
108828    0.158086
135672    0.127279
391153    0.118125
217350    0.089108
Name: 936595, dtype: float64

936844
user
279641    0.780869
362703    0.624695
90754     0.178266
71632     0.155207
950331    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
Name: 936844, dtype: float64

937122
user
534984    0.707107
682485    0.539164
389198    0.435194
65219     0.297746
650202    0.225733
133993    0.150970
173293    0.000000
173236    0.000000
173218    0.000000
Name: 937122, dtype: float64

937146
user
133152    0.894427
632235    0.894427
112180    0.894427
606877    0.894427
877370    0.894427
491073    0.894427
143267    0.894427
322423    0.715542
71789     0.550482
Name: 937146, dtype: float64

938515
user
686313    1.0
938515    1.0
950331    0.0
173141    0.0
172770    0.0
172946    0.0
172955    0.0
173038    0.0
173126    0.0
Name: 938515, dtype: float64

938757
user
2419      0.585206
48977     0.552158
172770    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
Name: 938757, dtype: float64

939233
user
98330     0.624695
395948    0.370625
369524    0.270501
20363     0.205196
754864    0.089087
76488     0.067729
950331    0.000000
172955    0.000000
173038    0.000000
Name: 939233, dtype: float64

939724
user
837135    0.500000
243883    0.173205
129333    0.149256
724982    0.137767
391794    0.113410
173126    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
Name: 939724, dtype: float64

940225
user
194777    1.000000
44204     1.000000
76564     1.000000
113896    1.000000
63763     1.000000
940225    1.000000
148777    1.000000
89712     0.928477
87704     0.745356
Name: 940225, dtype: float64

940619
user
753506    0.57735
636320    0.57735
614812    0.57735
186572    0.57735
814610    0.57735
923681    0.57735
648839    0.57735
44077     0.57735
257101    0.57735
Name: 940619, dtype: float64

941678
user
32143     0.103757
172589    0.000000
173325    0.000000
173300    0.000000
173293    0.000000
173236    0.000000
173218    0.000000
173187    0.000000
173146    0.000000
Name: 941678, dtype: float64

942205
user
950331    0.0
173421    0.0
173325    0.0
173300    0.0
173293    0.0
173236    0.0
173218    0.0
173187    0.0
173146    0.0
Name: 942205, dtype: float64

943069
user
556845    1.000000
440081    1.000000
148723    1.000000
822237    1.000000
135920    0.577350
201349    0.565685
351808    0.500000
251581    0.345547
106083    0.336861
Name: 943069, dtype: float64

943164
user
104713    1.000000
943164    1.000000
883362    0.357143
90754     0.285365
115682    0.276172
728009    0.161558
173141    0.000000
173146    0.000000
173187    0.000000
Name: 943164, dtype: float64

944033
user
88172     1.0
692426    1.0
529676    1.0
593945    1.0
944033    1.0
473854    1.0
363134    1.0
569529    1.0
182301    1.0
Name: 944033, dtype: float64

944343
user
177506    1.000000
372209    0.256074
173141    0.000000
172770    0.000000
172946    0.000000
172955    0.000000
173038    0.000000
173126    0.000000
173187    0.000000
Name: 944343, dtype: float64

944394
user
853410    1.000000
39314     1.000000
622340    1.000000
944394    1.000000
828625    0.894427
49805     0.780869
83257     0.577350
4347      0.529813
310557    0.514496
Name: 944394, dtype: float64

944775
user
884890    0.130931
950331    0.000000
172589    0.000000
173300    0.000000

In [4]:
# 특정 지역에 있는 음식점을 뽑아보자!
pick = data['stores'].loc[data['stores']['dong'] == "신사동",:]
pick

,sanga_number,상호명,gu,dong,large_category_id,large_category_name,medium_category_id,medium_category_name,small_category_id,small_category_name,pyojun_category,지번주소,경도,위도,store,store_name,address,latitude,longitude
501905,25776575,탱크떡볶이,강남구,신사동,Q,음식,Q04,분식,Q04A03,떡볶이전문,분식 및 김밥 전문점,서울특별시 강남구 신사동 574-3,127.025323,37.525350,416290,탱크떡볶이,서울특별시 강남구 신사동 574-3,37.525322,127.025307
541779,20467733,이나리,강남구,신사동,Q,음식,Q04,분식,Q04A01,라면김밥분식,분식 및 김밥 전문점,서울특별시 강남구 신사동 583-3,127.027897,37.524047,322997,이나리,서울특별시 강남구 신사동 583-3,37.524063,127.027934
541928,25753008,동대문엽기떡볶이,강남구,신사동,Q,음식,Q04,분식,Q04A03,떡볶이전문,분식 및 김밥 전문점,서울특별시 강남구 신사동 583-3,127.027897,37.524047,102440,동대문엽기떡볶이,서울특별시 강남구 신사동 583-3,37.524029,127.028069
588908,23254410,청담생골뱅이,강남구,신사동,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,한식 음식점업,서울특별시 강남구 신사동 561-17,127.025123,37.518978,378042,청담생골뱅이,서울특별시 강남구 신사동 561-17,37.518943,127.025162
653404,20688140,일치프리아니,강남구,신사동,Q,음식,Q06,양식,Q06A01,정통양식/경양식,서양식 음식점업,서울특별시 강남구 압구정동 429,127.027447,37.527359,333273,일치프리아니,서울특별시 강남구 압구정동 429,37.527320,127.027464
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1229907,16115270,팻보이샌드위치,강남구,신사동,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,한식 음식점업,서울특별시 강남구 신사동 569-23,127.027198,37.523852,430359,팻보이샌드위치,서울특별시 강남구 신사동 569-23,37.523865,127.027223
1231473,16339088,드립,강남구,신사동,Q,음식,Q12,커피점/카페,Q12A01,커피전문점/카페/다방,비알콜 음료점업,서울특별시 강남구 신사동 509-7,127.019834,37.518574,110003,드립,서울특별시 강남구 신사동 509-7,37.518583,127.019859
1231651,16170719,비파티세리,강남구,신사동,Q,음식,Q08,제과제빵떡케익,Q08A01,제과점,제과점업,서울특별시 강남구 신사동 546-17,127.023240,37.521999,198355,비파티세리,서울특별시 강남구 신사동 546-17,37.522000,127.023000
1231785,16150222,아우어베이커리,강남구,신사동,Q,음식,Q08,제과제빵떡케익,Q08A01,제과점,제과점업,서울특별시 강남구 신사동 523-19,127.021455,37.520930,262120,아우어베이커리,서울특별시 강남구 신사동 523-19,37.521000,127.021000
1232013,16325627,랑꼬뉴,강남구,신사동,Q,음식,Q12,커피점/카페,Q12A01,커피전문점/카페/다방,비알콜 음료점업,서울특별시 강남구 신사동 556-27,127.026114,37.521942,120016,랑꼬뉴,서울특별시 강남구 신사동 556-27,37.521955,127.026113

In [5]:
# 해당 지역에 있는 리뷰데이터를 Merge해서 어떤 사용자가 이 지역에서 음식을 먹었는지 보자
pick.rename(columns={'id':'store'}, inplace = True)
merge_picked = pd.merge(pick, data['reviews'], on='store')
reviews_stores = merge_picked.groupby(['store','store_name'])
picked_users = merge_picked.groupby(["user"])["user"]
picked_users.head()

c:\users\multicampus\appdata\local\programs\python\python36\lib\site-packages\pandas\core\frame.py:4238: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(**kwargs)

0      753324
1       64375
2      133993
3      213301
4      255258
        ...
208    314366
209    114160
210    257712
211     32143
212    820908
Name: user, Length: 212, dtype: int64

In [6]:
# 어떤 유저들이 있니?
user_list = list()
for userid, index in picked_users:
    user_list.append(userid)

In [7]:
# 위 유저들과 유사한 유저들은 어떻게 되어있니?
over_sim = list()
for i in user_list:
    top_sim = user_sim_df[i].sort_values(ascending=False)[1:10]
    for j in top_sim.index:
        if(top_sim[j] > 0.7):
            over_sim.append(j)
len(over_sim)

168

In [31]:
# 각 유저별 선호 카테고리를 저장해보자
category_group = ratings_stores.groupby(["user", "medium_category_id", "medium_category_name"]).mean()
category_group = category_group.sort_values(by=["score", "user"], ascending=False)
category_group

                                                     id     store  score  \
user   medium_category_id medium_category_name
950331 Q03                일식/수산물                13493.0  142325.0    5.0
947927 Q06                양식                      872.0  204267.0    5.0
       Q07                패스트푸드                  8994.0  174742.0    5.0
947653 Q03                일식/수산물                 7345.0  168378.0    5.0
946575 Q12                커피점/카페                 3488.0  263931.0    5.0
...                                                 ...       ...    ...
541    Q12                커피점/카페                16083.0  194442.0    1.0
313    Q01                한식                     6394.0  165016.0    1.0
415522 Q04                분식                     4746.0   14136.0    0.0
3739   Q01                한식                     3353.0  213980.0    0.0
       Q10                별식/퓨전요리               15675.0  192190.0    0.0

                                                sanga_number          경도  \
user   medium_category_id medium_category_name
950331 Q03                일식/수산물                  23450190.0  126.972298
947927 Q06                양식                      12643632.0  126.922260
       Q07                패스트푸드                   26178601.0  126.970020
947653 Q03                일식/수산물                  25573468.0  127.001438
946575 Q12                커피점/카페                  12488972.0  127.057927
...                                                      ...         ...
541    Q12                커피점/카페                  11751689.0  129.039164
313    Q01                한식                      12072319.0  126.921360
415522 Q04                분식                      25695000.0  129.090981
3739   Q01                한식                      12511247.0  126.957133
       Q10                별식/퓨전요리                 12670210.0  127.000245

                                                       위도
user   medium_category_id medium_category_name
950331 Q03                일식/수산물                37.550067
947927 Q06                양식                    37.548071
       Q07                패스트푸드                 37.543677
947653 Q03                일식/수산물                37.536558
946575 Q12                커피점/카페                37.598284
...                                                   ...
541    Q12                커피점/카페                35.116351
313    Q01                한식                    37.553965
415522 Q04                분식                    35.267058
3739   Q01                한식                    37.478526
       Q10                별식/퓨전요리               37.536908

[7238 rows x 6 columns]

In [58]:
over_sim["user"] = pd.DataFrame(over_sim)
over_sim_merge = pd.merge(over_sim, ratings_stores, on="user")
over_sim_merge

,0,user,id,store,score,content,reg_time,sanga_number,상호명,gu,...,small_category_id,small_category_name,pyojun_category,지번주소,경도,위도,store_name,address,latitude,longitude
0,134131,134131,15894,193578,4,닭발을 워낙 좋아하는 터라 마침 신림에 일이 있어 갔습니다. 기대안하고 먹었는데 감...,1970-01-01 00:00:00,20670809,불타는꼬꼬발,관악구,...,Q05A08,후라이드/양념치킨,치킨 전문점,서울특별시 관악구 신림동 1464-18,126.925317,37.484035,불타는꼬꼬발,서울특별시 관악구 신림동 1464-18,37.484045,126.925332
1,134131,134131,13207,241462,5,스시광인 저에게 단골이 되게끔 만든 집입니다.\r\n워낙 많은 스시집들이 요즘 즐비...,1970-01-01 00:00:00,11960222,스시도쿠,성동구,...,Q03A02,음식점-일식,일식 음식점업,서울특별시 성동구 행당동 196-18,127.036144,37.561012,스시도쿠,서울특별시 성동구 행당동 196-18,37.561017,127.036170
2,134131,134131,15894,193578,4,닭발을 워낙 좋아하는 터라 마침 신림에 일이 있어 갔습니다. 기대안하고 먹었는데 감...,1970-01-01 00:00:00,20670809,불타는꼬꼬발,관악구,...,Q05A08,후라이드/양념치킨,치킨 전문점,서울특별시 관악구 신림동 1464-18,126.925317,37.484035,불타는꼬꼬발,서울특별시 관악구 신림동 1464-18,37.484045,126.925332
3,134131,134131,13207,241462,5,스시광인 저에게 단골이 되게끔 만든 집입니다.\r\n워낙 많은 스시집들이 요즘 즐비...,1970-01-01 00:00:00,11960222,스시도쿠,성동구,...,Q03A02,음식점-일식,일식 음식점업,서울특별시 성동구 행당동 196-18,127.036144,37.561012,스시도쿠,서울특별시 성동구 행당동 196-18,37.561017,127.036170
4,365420,365420,13211,241462,5,왕십리 최애스시집 jmtgr 연어길이가 엄청 길고 식감운 부드럽다 언제나 바쁜 가게...,2019-02-19 17:16:01,11960222,스시도쿠,성동구,...,Q03A02,음식점-일식,일식 음식점업,서울특별시 성동구 행당동 196-18,127.036144,37.561012,스시도쿠,서울특별시 성동구 행당동 196-18,37.561017,127.036170
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
214,879926,879926,6602,118503,5,칭타오 생맥주가 맛있는 깔끔하고 서비스 좋은 양고기집입니다. 고기는 처음부터 끝까지...,1970-01-01 00:00:00,12522262,라무진,강동구,...,Q06A01,정통양식/경양식,서양식 음식점업,서울특별시 강동구 명일동 47-12,127.154763,37.553226,라무진,서울특별시 강동구 명일동 47-12,37.553394,127.154965
215,833785,833785,6604,118508,5,양갈비 원래 안먹는데 냄세안나고 완전 맛있어요!!,1970-01-01 00:00:00,12543900,라무진,강남구,...,Q01A01,한식/백반/한정식,한식 음식점업,서울특별시 강남구 신사동 550-12,127.024107,37.524061,라무진,서울특별시 강남구 신사동 550-12,37.524060,127.024146
216,480616,480616,6584,118458,4,,1970-01-01 00:00:00,11771793,라무진,수영구,...,Q01A99,기타고기요리,한식 음식점업,부산광역시 수영구 광안동 90-9,129.115814,35.165481,라무진,부산광역시 수영구 광안동 90-9,35.165440,129.115789
217,463007,463007,6580,118450,5,양갈비가 매우 맛있었습니다 \n특히 직원이 직접 맛있게 구워주고 주시는데 너무 편했...,1970-01-01 00:00:00,11981462,라무진,영등포구,...,Q01A01,한식/백반/한정식,한식 음식점업,서울특별시 영등포구 여의도동 45-19,126.929206,37.519733,라무진,서울특별시 영등포구 여의도동 45-19,37.519714,126.929273
218,250828,250828,6583,118450,4,직원 직접 구워주고 잘라줘서 먹기 편하다.마늘밥과 고기가 잘 어울리고 맛이 좋다....,1970-01-01 00:00:00,11981462,라무진,영등포구,...,Q01A01,한식/백반/한정식,한식 음식점업,서울특별시 영등포구 여의도동 45-19,126.929206,37.519733,라무진,서울특별시 영등포구 여의도동 45-19,37.519714,126.929273

In [75]:
# 0.7 이상의 유사도를 가진 모든 유사 유저들의 선호 카테고리 점수 뽑아내기
over_sim_merge = over_sim_merge.groupby(["medium_category_id","medium_category_name"]).mean()
over_sim_merge = over_sim_merge.sort_values(by="score", ascending=False)
over_sim_merge["score"]

medium_category_id  medium_category_name
Q03                 일식/수산물                  4.818182
Q08                 제과제빵떡케익                 4.666667
Q12                 커피점/카페                  4.357143
Q07                 패스트푸드                   4.071429
Q05                 닭/오리요리                  4.000000
Q06                 양식                      4.000000
Q09                 유흥주점                    4.000000
Q01                 한식                      3.892857
Q02                 중식                      2.833333
Name: score, dtype: float64

In [79]:
# 선택한 지역의 카테고리 점수 뽑기 (여기서는 아직 리뷰 개수로 제한 두진 않았다)
picked_medium_category = merge_picked.groupby(["medium_category_id","medium_category_name"]).mean()
picked_medium_category = picked_medium_category.sort_values(by="score", ascending=False)
picked_medium_category["score"]

medium_category_id  medium_category_name
Q10                 별식/퓨전요리                 5.000000
Q08                 제과제빵떡케익                 4.615385
Q07                 패스트푸드                   4.128205
Q03                 일식/수산물                  4.058824
Q12                 커피점/카페                  4.040816
Q05                 닭/오리요리                  4.000000
Q02                 중식                      3.909091
Q01                 한식                      3.750000
Q06                 양식                      3.695652
Q09                 유흥주점                    3.666667
Q04                 분식                      3.181818
Name: score, dtype: float64

In [127]:
# 데이터를 가져오자
from parse import load_dataframes
import pandas as pd

# parse
data = load_dataframes()

In [500]:
#행정동에 따른 유동인구, 매출액, 음식점, 리뷰들을 가져오자 (데이터 수집)
gu = "마포구"
dong = "연남동"
roads = data['area'].loc[(data['area']['gu'] == gu) &(data['area']['dong'] == dong)]['road_name']
foottrafic = data['population'].loc[data['population']['road'].isin(roads),:].sum()
mean_sales = data['mean_sales'].loc[data['mean_sales']['road_name'].isin(roads),:].mean()
stores = data['stores'].loc[(data['stores']['gu'] == gu)&(data['stores']['dong']==dong),:]
stores.rename(columns={'id':'store'}, inplace=True)
store_review_merge = pd.merge(stores, data['reviews'], on="store")
# display(store_review_merge)
users = data['users']
users.rename(columns={'id':'user'}, inplace=True)
store_review_user_merge = pd.merge(users, store_review_merge, on="user").groupby(['user','store_name'])
# display(store_review_user_merge.head())

c:\users\multicampus\appdata\local\programs\python\python36\lib\site-packages\pandas\core\frame.py:4238: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(**kwargs)

In [501]:
# 데이터 정제
# 유동인구 중 남녀/연령의 가장 높은 유동인구가 어디인지 체크하자
men_foottrafic = foottrafic['men_pcnt']
women_foottrafic = foottrafic['women_pcnt']
if men_foottrafic >= women_foottrafic:
    larger_gender='남'
else :
    larger_gender='여'

ages_foottrafic = [foottrafic['teen_pcnt'],foottrafic['twenty_pcnt'],foottrafic['thirty_pcnt'],
                 foottrafic['fourty_pcnt'],foottrafic['fifty_pcnt'],foottrafic['sixty_pcnt']]
ages_column = ['teen','twenty','thirty','fourty','fifty','sixty']
larger_ages = ages_column[0]
max_val = max(ages_foottrafic)
index = 0
for i in ages_foottrafic:
    if i == max_val:
        break
    else:
        index += 1
larger_age = ages_column[index]

display(larger_gender)
display(larger_age)

# 고찰
# 20대가 가장 많고, 여자가 가장 많지만 20대 여자가 가장 많다고 확정은 못지음...
# 그럼 20대가 좋아하는 카테고리, 여성이 좋아하는 카테고리 따로 추린 결과들로 추천한다?

# 고찰2
# 추정매출액이 가장 낮을 때? 유동인구가 가장 많은 사람들을 타겟으로 업종을 추천하는 것은 블루오션일까?

'여'

'twenty'

In [502]:
# 위에서 뽑은 1순위 유동인구
if larger_age == 'teen':
    min_scope=10
    max_scope=20
elif larger_age == 'twenty':
    min_scope=20
    max_scope=30
elif larger_age == 'thirty':
    min_scope=30
    max_scope=40
elif larger_age == 'fourty':
    min_scope=40
    max_scope=50
elif larger_age == 'fifty':
    min_scope=50
    max_scope=60
elif larger_age == 'sixty':
    min_scope=60
    max_scope=100
    
# 타겟 유저들은 누구누구니?
gender_targets = users.loc[ ( users['gender'] == larger_gender ), :]
age_targets = users.loc[( users['age'] >= min_scope ) & ( users['age'] < max_scope ), :] 
display(gender_targets)
display(age_targets)

         user gender  age
1      389728      여   28
2       68716      여   37
3      774353      여   49
5      388883      여   53
7      249051      여   28
...       ...    ...  ...
18977  110919      여   27
18978  316456      여   27
18985  158462      여   25
18988  518267      여   26
18991   17371      여   35

[6693 rows x 3 columns]

         user gender  age
1      389728      여   28
7      249051      여   28
9      946187      여   28
10     319105      여   28
12      31285      여   29
...       ...    ...  ...
18982   66030      남   27
18985  158462      여   25
18986  365349      남   25
18987  171391      남   28
18988  518267      여   26

[5509 rows x 3 columns]

In [585]:
# 전체 음식점 중 타겟 성별이 리뷰를 작성한 음식점들
gender_targets_review_merge = pd.merge(gender_targets, data['reviews'], on="user")
gender_targets_review_store_merge = pd.merge(gender_targets_review_merge, data['stores'], left_on="store", right_on="id")

# 평점 4점 이상인 곳
Gover_four_score_stores = gender_targets_review_store_merge.loc[gender_targets_review_store_merge['score'] >= 4]
# display(over_four_score_stores)

# 리뷰가 3개 이상인 곳
gender_targets_review_store = gender_targets_review_store_merge.groupby(['store']).count().sort_values(by="score", ascending=False)
Gover_three_counts_store = gender_targets_review_store.loc[gender_targets_review_store['score'] >= 3].index
# display(over_three_counts_store)

# 리뷰가 3개 이상이면서 평점이 4점 이상인 곳
Gfiltering_stores = Gover_four_score_stores.loc[Gover_four_score_stores['store'].isin(Gover_three_counts_store)]
# display(filtering_stores)

# 평점 기준 
gender_targets_top_category_by_score = Gfiltering_stores.groupby(['medium_code']).mean().sort_values(by="score", ascending=False)
top_category_by_score = gender_targets_top_category_by_score[0:10].reset_index().loc[:,['medium_code','score']]
top_category_by_score = pd.merge(top_category_by_score,data['medium'], on="medium_code")
display(top_category_by_score)
display("타겟 성별이 선호하는 카테고리(평점 기준)")

# 리뷰 순 기준
gender_targets_top_category_by_cnt = Gfiltering_stores.groupby(['medium_code']).count().sort_values(by="score", ascending=False)
top_category_by_cnt = gender_targets_top_category_by_cnt[0:10].reset_index().loc[:,['medium_code','score']]
top_category_by_cnt = pd.merge(top_category_by_cnt, data['medium'], on="medium_code")
display(top_category_by_cnt)
display("타겟 성별이 선호하는 카테고리(리뷰 수 기준)")

  medium_code     score medium_category
0         Q08  4.546875         제과제빵떡케익
1         Q02  4.450980              중식
2         Q01  4.440288              한식
3         Q06  4.434375              양식
4         Q04  4.426036              분식
5         Q03  4.423423          일식/수산물
6         Q07  4.414894           패스트푸드
7         Q09  4.414634            유흥주점
8         Q12  4.404624          커피점/카페
9         Q10  4.392157         별식/퓨전요리

'타겟 성별이 선호하는 카테고리(평점 기준)'

  medium_code  score medium_category
0         Q01    695              한식
1         Q06    320              양식
2         Q03    222          일식/수산물
3         Q12    173          커피점/카페
4         Q04    169              분식
5         Q07     94           패스트푸드
6         Q09     82            유흥주점
7         Q08     64         제과제빵떡케익
8         Q02     51              중식
9         Q10     51         별식/퓨전요리

'타겟 성별이 선호하는 카테고리(리뷰 수 기준)'

In [586]:
# 전체 음식점 중 타겟 연령이 리뷰를 작성한 음식점들
age_targets_review_merge = pd.merge(age_targets, data['reviews'], on="user")
age_targets_review_store_merge = pd.merge(age_targets_review_merge, data['stores'], left_on="store", right_on="id")

# 평점 4점 이상인 곳
Aover_four_score_stores = age_targets_review_store_merge.loc[age_targets_review_store_merge['score'] >= 4]

# 리뷰가 3개 이상인 곳
age_targets_review_store = age_targets_review_store_merge.groupby(['store']).count().sort_values(by="score", ascending=False)
Aover_three_counts_store = age_targets_review_store.loc[age_targets_review_store['score'] >= 3].index

# 리뷰가 3개 이상이면서 평점이 4점 이상인 곳
Afiltering_stores = Aover_four_score_stores.loc[Aover_four_score_stores['store'].isin(Aover_three_counts_store)]

# 평점 기준 
age_targets_top_category_by_score = Afiltering_stores.groupby(['medium_code']).mean().sort_values(by="score", ascending=False)
Atop_category_by_score = age_targets_top_category_by_score[0:10].reset_index().loc[:,['medium_code','score']]
Atop_category_by_score = pd.merge(Atop_category_by_score,data['medium'], on="medium_code")
display(Atop_category_by_score)
display("타겟 연령이 선호하는 카테고리(평점 기준)")

# 리뷰 순 기준
age_targets_top_category_by_cnt = Afiltering_stores.groupby(['medium_code']).count().sort_values(by="score", ascending=False)
Atop_category_by_cnt = age_targets_top_category_by_cnt[0:10].reset_index().loc[:,['medium_code','score']]
Atop_category_by_cnt = pd.merge(Atop_category_by_cnt, data['medium'], on="medium_code")
display(Atop_category_by_cnt)
display("타겟 연령이 선호하는 카테고리(리뷰 수 기준)")

  medium_code     score medium_category
0         Q08  4.642857         제과제빵떡케익
1         Q05  4.600000          닭/오리요리
2         Q01  4.481959              한식
3         Q12  4.444444          커피점/카페
4         Q04  4.425287              분식
5         Q06  4.421053              양식
6         Q10  4.421053         별식/퓨전요리
7         Q03  4.417219          일식/수산물
8         Q09  4.375000            유흥주점
9         Q07  4.360000           패스트푸드

'타겟 연령이 선호하는 카테고리(평점 기준)'

  medium_code  score medium_category
0         Q01    388              한식
1         Q06    190              양식
2         Q03    151          일식/수산물
3         Q04     87              분식
4         Q07     75           패스트푸드
5         Q12     72          커피점/카페
6         Q09     48            유흥주점
7         Q08     28         제과제빵떡케익
8         Q10     19         별식/퓨전요리
9         Q02     15              중식

'타겟 연령이 선호하는 카테고리(리뷰 수 기준)'

In [587]:
# 실제로 연남동에는 어떤 카테고리의 음식점들이 있을까?

categories_in_dong = store_review_merge.groupby(['medium_code'])
count_categories_in_dong = categories_in_dong.count()['store'].reset_index()
display(count_categories_in_dong)
scores_categories_in_dong = categories_in_dong.mean()['score'].reset_index()
total_info_categories_in_dong = pd.merge(count_categories_in_dong,scores_categories_in_dong, on="medium_code")
display(pd.merge(total_info_categories_in_dong, data['medium'], on="medium_code"))

# 요기까지는 알고리즘 없이 논리로 뽑아낼 수 있는 내용들

  medium_code  store
0         Q01    104
1         Q02      6
2         Q03     48
3         Q04      7
4         Q06     38
5         Q08      8
6         Q09     17
7         Q12      7

  medium_code  store     score medium_category
0         Q01    104  3.826923              한식
1         Q02      6  4.500000              중식
2         Q03     48  4.062500          일식/수산물
3         Q04      7  4.000000              분식
4         Q06     38  3.842105              양식
5         Q08      8  4.250000         제과제빵떡케익
6         Q09     17  3.588235            유흥주점
7         Q12      7  4.285714          커피점/카페

In [2]:
# 1. 전체 구/동을 돌면서 각 구/동에 대한 유동인구 순위를 메기고 구/동이 갖는 정보(점수, 등급, 유동인구 순위)를 저장
# 2. 1번 정보를 토대로 지역에 대한 유사도를 계산하자.
# 3. 선택한 구/동과 유사한 지역의 잘되는 카테고리들과 선택한 지역의 카테고리를 비교
# 4. 그래서 우리는 이런 카테고리들을 추천해 주는 바이다.?

import requests

def pointRegion(code):
    base_url = "http://sg.sbiz.or.kr/areaGreadeDetail.json?admiCd="
    url = base_url + str(code)
    r = requests.get(url)
    to_json = r.json()['areaGrade']
    total_score = 0
    grade = 0
    grothIndex = 0
    stability = 0
    salePwr = 0
    buyingPwr = 0
    gathPwr = 0
    if to_json :
        grothIndex = to_json['grothIndex']
        stability=to_json['stability']
        salePwr=to_json['salePwr']
        buyingPwr=to_json['buyingPwr']
        gathPwr=to_json['gathPwr']
        total_score = round((grothIndex + stability + salePwr + buyingPwr + gathPwr),1)

        if total_score >= 70:
            grade = 1
        elif total_score >= 57.5 and total_score < 70:
            grade = 2
        elif total_score >= 45 and total_score < 57.5:
            grade = 3
        elif total_score >= 32.5 and total_score < 45:
            grade = 4
        elif total_score < 32.5:
            grade = 5
    return {'total_score': total_score,'grade': grade,'grothIndex':grothIndex,
            'stability':stability,'salePwr':salePwr,'buyingPwr':buyingPwr,'gathPwr':gathPwr}


def foottraffic(data, gu, dong):
    areas = data['area'].loc[(data['area']['gu'] == gu) & (data['area']['dong'] == dong),:]['road_name']
    ret = {
        'total' : 0,
        'men' : 0,
        'women' : 0,
        'teen':0,
        'twenty':0,
        'thirty':0,
        'fourty':0,
        'fifty':0,
        'sixty':0,
    }
    roads = data['population'].loc[data['population']['road'].isin(areas)]
    if roads.size == 0:
        return ret
    # 순서를 메기자 1이 더 높은거!
    else:
        roads = roads.groupby(['year','quarter']).sum().reset_index()
        ret['total'] = roads.loc[:,'total_pcnt'].values[0]
        men = roads.loc[:,'men_pcnt'].values[0]
        women = roads.loc[:,'women_pcnt'].values[0]
        if men > women :
            ret['men'] = 1
            ret['women'] = 2
        else:
            ret['men'] = 2
            ret['women'] = 1

        age_value = []
        age_columns = ["teen","twenty","thirty","fourty","fifty","sixty"]
        age_value.append(roads.loc[:,'teen_pcnt'].values[0])
        age_value.append(roads.loc[:,'twenty_pcnt'].values[0])
        age_value.append(roads.loc[:,'thirty_pcnt'].values[0])
        age_value.append(roads.loc[:,'fourty_pcnt'].values[0])
        age_value.append(roads.loc[:,'fifty_pcnt'].values[0])
        age_value.append(roads.loc[:,'sixty_pcnt'].values[0])
        age_sort = list(age_value)
        age_sort.sort(reverse = True)
        
        awards = 1
        for i in range(6):
            for j in range(6):
                if age_sort[i] == age_value[j]:
                    ret[age_columns[j]] = awards
                    awards += 1
    return ret   

def sales(data, gu, dong):
    areas = data['area'].loc[(data['area']['gu'] == gu) & (data['area']['dong'] == dong),:]['road_name']
    ret = {
        'total' : 0,
        'men' : 0,
        'women' : 0,
        'teen':0,
        'twenty':0,
        'thirty':0,
        'fourty':0,
        'fifty':0,
        'sixty':0,
    }
    roads = data['mean_sales'].loc[data['mean_sales']['road_name'].isin(areas)]
    if roads.size == 0:
        return ret
    # 순서를 메기자 1이 더 높은거!
    else:
        roads = roads.mean()
        ret['total'] = roads.month_sales
        men = roads.men_sales
        women = roads.women_sales
        if men > women :
            ret['men'] = 1
            ret['women'] = 2
        else:
            ret['men'] = 2
            ret['women'] = 1
            
        age_value = []
        age_columns = ["teen","twenty","thirty","fourty","fifty","sixty"]
        age_value.append(roads.teen_sales)
        age_value.append(roads.twenty_sales)
        age_value.append(roads.thirty_sales)
        age_value.append(roads.fourty_sales)
        age_value.append(roads.fifty_sales)
        age_value.append(roads.sixty_sales)
        age_sort = list(age_value)
        age_sort.sort(reverse = True)
        
        awards = 1
        for i in range(6):
            for j in range(6):
                if age_sort[i] == age_value[j]:
                    ret[age_columns[j]] = awards
                    awards += 1
    return ret

def repeatAllRegion(data):
    areas = data['area'].loc[:,['gu', 'dong','dong_code']]
    areas = areas.drop_duplicates()
    areas = areas.groupby(['gu','dong']).max().reset_index()
    matrix = []

    for i,v in areas.iterrows():
    #     break
        region = {
            'gu':v.gu,'dong':v.dong
        }
        #지역 점수, 등급 정보
        point = pointRegion(v.dong_code)
        region['total_score'] = point['total_score']
        region['grothIndex'] = point['grothIndex']
        region['stability'] = point['stability']
        region['salePwr'] = point['salePwr']
        region['buyingPwr'] = point['buyingPwr']
        region['gathPwr'] = point['gathPwr']
        region['grade'] = point['grade']

        #지역 유동인구 순위
        foot = foottraffic(data, v.gu, v.dong)
        if foot['total'] == 0:
            region['foot_men'] = 0
            region['foot_women'] = 0
            region['foot_teen'] = 0
            region['foot_twenty'] = 0
            region['foot_thirty'] = 0
            region['foot_fourty'] = 0
            region['foot_fifty'] = 0
            region['foot_sixty'] = 0
        else:
            region['foot_men'] = foot['men']
            region['foot_women'] = foot['women']
            region['foot_teen'] = foot['teen']
            region['foot_twenty'] = foot['twenty']
            region['foot_thirty'] = foot['thirty']
            region['foot_fourty'] = foot['fourty']
            region['foot_fifty'] = foot['fifty']
            region['foot_sixty'] = foot['sixty']

        #지역 매출액 순위
        sale = sales(data, v.gu, v.dong)
        if sale['total'] == 0:
            region['sale_men'] = 0
            region['sale_women'] = 0
            region['sale_teen'] = 0
            region['sale_twenty'] = 0
            region['sale_thirty'] = 0
            region['sale_fourty'] = 0
            region['sale_fifty'] = 0
            region['sale_sixty'] = 0
        else:
            region['sale_men'] = sale['men']
            region['sale_women'] = sale['women']
            region['sale_teen'] = sale['teen']
            region['sale_twenty'] = sale['twenty']
            region['sale_thirty'] = sale['thirty']
            region['sale_fourty'] = sale['fourty']
            region['sale_fifty'] = sale['fifty']
            region['sale_sixty'] = sale['sixty']

        matrix.append(region)

    return matrix

matrix = repeatAllRegion(data)

In [4]:
## 예스! 일단 1번인 잘 나오네~?
df = pd.DataFrame(matrix)
df = df.groupby(['gu','dong']).sum()

In [5]:
# 2. 1번 정보를 토대로 지역에 대한 유사도를 계산하자.

# 맞는지 모르겠다 띵띵...
from sklearn.cluster import KMeans
X = df.values

# wcss =[]
# for i in range (1,101):
#     kmeans = KMeans(n_clusters = i, init = 'k-means++', max_iter =300, n_init = 10, random_state = 0)
#     kmeans.fit(X)
#     wcss.append(kmeans.inertia_)
    
# # display(wcss)

# # inertia를 보고 클러스터의 수를 잡자. 우리 경우는 20으로? 클러스터 수를 100까지 늘려가며 확인해보면 급격한 변화가 줄어드는 시점이 20

# import matplotlib.pyplot as plt
# plt.plot(range(1,101),wcss)
# plt.title('The Elbow Method')
# plt.xlabel('Number of clusters')
# plt.ylabel('WCSS')
# plt.show()

In [6]:
# 전체 지역들의 클러스터를 K-Means로 계산
model = KMeans(n_clusters=20,init = 'k-means++', max_iter = 300, n_init = 10, random_state = 0)
model.fit(X)
predict = pd.DataFrame(model.predict(X))
predict.columns=['predict']
df = df.reset_index()
df['predict'] = predict
display(df.loc[:,['gu','dong','predict']])
data['similarity'] = df.loc[:,['gu','dong','predict']]

       gu  dong  predict
0     강남구  개포1동       17
1     강남구  개포2동        1
2     강남구  개포4동       10
3     강남구  논현1동        7
4     강남구  논현2동        7
..    ...   ...      ...
627  해운대구   좌2동       12
628  해운대구   좌3동       14
629  해운대구   좌4동       12
630  해운대구   중1동       12
631  해운대구   중2동       17

[632 rows x 3 columns]

In [23]:
gu = "강남구"
dong = "개포2동"
# 전체 지역의 클러스터 정보
cluster = df.loc[:,['gu','dong','predict']]
cluster_number = cluster.loc[(cluster['gu'] == gu) & (cluster['dong'] == dong), :]['predict'].values[0]

# 입력받은 행정동 지역과 유사한(같은 클러스터)의 지역 리스트 확인
similar_region = cluster.loc[(cluster['predict'] == cluster_number),['gu','dong']]
similar_region

       gu    dong
1     강남구    개포2동
11    강남구    삼성2동
25    강동구      길동
27    강동구    둔촌2동
30    강동구     상일동
39    강동구    천호3동
59    강서구     공항동
78    강서구    화곡4동
80    강서구    화곡8동
98    관악구     조원동
102   관악구     행운동
103   광진구     광장동
112   광진구    자양4동
113   광진구    중곡1동
119   구로구    개봉1동
120   구로구    개봉2동
128   구로구    구로5동
151   금천구     가산동
198   노원구    중계4동
204   도봉구    방학1동
215   도봉구     창5동
230  동대문구     용신동
235  동대문구    전농1동
240  동대문구    휘경1동
241  동대문구    휘경2동
257   동작구     대방동
263   동작구    상도1동
269   동작구     흑석동
276   마포구     서강동
279   마포구    성산2동
366  서대문구     연희동
371  서대문구    홍제1동
378   서초구    반포4동
381   서초구    방배2동
382   서초구    방배3동
384   서초구    방배본동
390   서초구    양재2동
400   성동구  성수2가3동
414   성북구     보문동
418   성북구     안암동
438   송파구    방이1동
467   양천구     목2동
468   양천구     목3동
469   양천구     목4동
472   양천구    신월2동
514  영등포구    신길1동
521  영등포구    양평2동
526   용산구     보광동
536   용산구     청파동
537   용산구    한강로동
552   은평구    응암1동
564   종로구    숭인2동
599   중랑구    망우본동
604   중랑구    면목7동
606   중랑구     묵1동
610   중랑구    신내1동
611   중랑구    신내2동
613   중랑구    중화2동

In [24]:
stores_reviews_merge = pd.merge(data['stores'], data['reviews'], left_on="id", right_on="store")
stores_reviews_merge = stores_reviews_merge.loc[:,['gu','dong','medium_code','small_code','score','store','store_name','user','content']]

# 유사 지역의 모든 음식점의 리뷰데이터
similar_stores_df = pd.DataFrame(columns=['gu','dong','medium_code','small_code','score','store','store_name','user','content'])
for i, val in similar_region.iterrows():
    gu = val.gu
    dong = val.dong
    similar_region_stores = stores_reviews_merge.loc[(stores_reviews_merge['gu'] == gu) & (stores_reviews_merge['dong'] == dong),:]
    similar_stores_df = pd.concat([similar_stores_df, similar_region_stores], ignore_index=True)
# similar_stores_df
similar_stores_df['score'] = similar_stores_df.score.astype(int)

similar_groupby_small_code = similar_stores_df.groupby(['medium_code'])
similar_scores_small_code = similar_groupby_small_code.mean()
similar_scores_small_code['count'] = similar_groupby_small_code.count()['content']
similar_scores_small_code = similar_scores_small_code.loc[similar_scores_small_code['count']>=3]

# 평점으로 뽑아보기
similar_scores_small_code_sort_by_score = pd.merge(similar_scores_small_code, data['medium'], on="medium_code").sort_values(by="score", ascending=False)[0:10].reset_index()
display(similar_scores_small_code_sort_by_score)
# 리뷰수로 뽑아보기
similar_scores_small_code_sort_by_count =  pd.merge(similar_scores_small_code, data['medium'], on="medium_code").sort_values(by="count", ascending=False)[0:10].reset_index()
display(similar_scores_small_code_sort_by_count)

   index medium_code     score  count medium_category
0     10         Q12  4.075949     79          커피점/카페
1      4         Q05  4.035714     28          닭/오리요리
2      7         Q08  4.000000      8         제과제빵떡케익
3      0         Q01  3.952675    486              한식
4      5         Q06  3.923077    156              양식
5      1         Q02  3.866667     60              중식
6      2         Q03  3.850000    140          일식/수산물
7     11         Q15  3.777778      9              부페
8      3         Q04  3.743243    148              분식
9      9         Q10  3.700000     40         별식/퓨전요리

   index medium_code     score  count medium_category
0      0         Q01  3.952675    486              한식
1      5         Q06  3.923077    156              양식
2      3         Q04  3.743243    148              분식
3      2         Q03  3.850000    140          일식/수산물
4     10         Q12  4.075949     79          커피점/카페
5      8         Q09  3.506494     77            유흥주점
6      1         Q02  3.866667     60              중식
7      6         Q07  3.696429     56           패스트푸드
8      9         Q10  3.700000     40         별식/퓨전요리
9      4         Q05  4.035714     28          닭/오리요리

In [22]:
# 그래서 너가 선택한 지역의 음식점들은?
gu = "강남구"
dong = "개포2동"
region_stores = stores_reviews_merge.loc[(stores_reviews_merge['gu'] == gu) & (stores_reviews_merge['dong'] == dong),['medium_code','score','content']]

region_groupby_small_code =region_stores.groupby(['medium_code'])
region_scores_small_code = region_groupby_small_code.mean()
region_scores_small_code['count'] = region_groupby_small_code.count()['content']
region_scores_small_code = region_scores_small_code.loc[region_scores_small_code['count']>=3]

# 평점으로 뽑아보기
region_scores_small_code_sort_by_score = pd.merge(region_scores_small_code, data['medium'], on="medium_code").sort_values(by="score", ascending=False)[0:10].reset_index()
display(region_scores_small_code_sort_by_score)
# 리뷰수로 뽑아보기
region_scores_small_code_sort_by_count =  pd.merge(region_scores_small_code, data['medium'], on="medium_code").sort_values(by="count", ascending=False)[0:10].reset_index()
display(region_scores_small_code_sort_by_count)

Empty DataFrame
Columns: [index, score, count, medium_category, medium_code]
Index: []

Empty DataFrame
Columns: [index, score, count, medium_category, medium_code]
Index: []

In [608]:
region_scores_small_code_sort_by_count.to_json(orient='index')

'{"0":{"index":8,"medium_code":"Q12","score":4.0408163265,"count":49,"medium_category":"\\ucee4\\ud53c\\uc810\\/\\uce74\\ud398"},"1":{"index":0,"medium_code":"Q01","score":3.75,"count":44,"medium_category":"\\ud55c\\uc2dd"},"2":{"index":5,"medium_code":"Q07","score":4.1282051282,"count":39,"medium_category":"\\ud328\\uc2a4\\ud2b8\\ud478\\ub4dc"},"3":{"index":4,"medium_code":"Q06","score":3.6956521739,"count":23,"medium_category":"\\uc591\\uc2dd"},"4":{"index":2,"medium_code":"Q03","score":4.0588235294,"count":17,"medium_category":"\\uc77c\\uc2dd\\/\\uc218\\uc0b0\\ubb3c"},"5":{"index":6,"medium_code":"Q08","score":4.6153846154,"count":13,"medium_category":"\\uc81c\\uacfc\\uc81c\\ube75\\ub5a1\\ucf00\\uc775"},"6":{"index":1,"medium_code":"Q02","score":3.9090909091,"count":11,"medium_category":"\\uc911\\uc2dd"},"7":{"index":3,"medium_code":"Q04","score":3.2,"count":10,"medium_category":"\\ubd84\\uc2dd"},"8":{"index":7,"medium_code":"Q09","score":3.6666666667,"count":3,"medium_category":"\\uc720\\ud765\\uc8fc\\uc810"}}'

In [6]:
def similarPoint(score, review):
    result ={}
    point = 10
    for i, val in score.iterrows():
        now_key = val.medium_category
        if now_key in result.keys():
            result[now_key] += point
        else:
            result[now_key] = point
        point -= 1
    point = 10
    for i, val in review.iterrows():
        now_key = val.medium_category
        if now_key in result.keys():
            result[now_key] += point
        else:
            result[now_key] = point
        point -= 1
    
    
    return result

def onePlusTen(score, review):
    result ={}
    point = 1
    for i, val in score.iterrows():
        now_key = val.medium_category
        if now_key in result.keys():
            result[now_key] += point
        else:
            result[now_key] = point
        point += 1
    point = 10
    for i, val in review.iterrows():
        now_key = val.medium_category
        if now_key in result.keys():
            result[now_key] += point
        else:
            result[now_key] = point
        point -= 1
    
    return result

def tenPlusTen(score, review):
    result ={}
    point = 10
    for i, val in score.iterrows():
        now_key = val.medium_category
        if now_key in result.keys():
            result[now_key] += point
        else:
            result[now_key] = point
        point -= 1
    point = 10
    for i, val in review.iterrows():
        now_key = val.medium_category
        if now_key in result.keys():
            result[now_key] += point
        else:
            result[now_key] = point
        point -= 1
    
    return result

def onePlusOne(score, review):
    result ={}
    point = 1
    for i, val in score.iterrows():
        now_key = val.medium_category
        if now_key in result.keys():
            result[now_key] += point
        else:
            result[now_key] = point
        point += 1
    point = 1
    for i, val in review.iterrows():
        now_key = val.medium_category
        if now_key in result.keys():
            result[now_key] += point
        else:
            result[now_key] = point
        point += 1
    
    return result

def tenPlusOne(score,review):
    result ={}
    point = 10
    for i, val in score.iterrows():
        now_key = val.medium_category
        if now_key in result.keys():
            result[now_key] += point
        else:
            result[now_key] = point
        point -= 1
    point = 1
    for i, val in review.iterrows():
        now_key = val.medium_category
        if now_key in result.keys():
            result[now_key] += point
        else:
            result[now_key] = point
        point += 1
    
    return result

def recommendResult(similar, ot, tt, oo, to):
    result = {'top':[],'ot':[], 'tt':[],'oo':[],'to':[]}

    # top
    top = 0
    for key, value in similar.items():
        if top == 3:
            break
        if key not in ot.keys():
            result['top'].append(key)
            top += 1
    if len(ot) > 0:
        # 1
        for key, value in ot.items():
            if key in similar.keys():
                ot[key] = value * similar[key]
        sorted_ot = sorted(ot.items(),reverse=True,key=lambda item: item[1])

        # 2
        for key, value in tt.items():
            if key in similar.keys():
                tt[key] = value * similar[key]
        sorted_tt = sorted(tt.items(),reverse=True,key=lambda item: item[1])

        # 3
        for key, value in oo.items():
            if key in similar.keys():
                oo[key] = value * similar[key]
        sorted_oo = sorted(oo.items(),reverse=True,key=lambda item: item[1])

        # 4
        for key, value in to.items():
            if key in similar.keys():
                to[key] = value * similar[key]
        sorted_to = sorted(to.items(),reverse=True,key=lambda item: item[1])

        ot_max = sorted_ot[0][1]
        for i in sorted_ot:
            if i[1] == ot_max:
                result['ot'].append(i[0])
            else :
                break
        tt_max = sorted_tt[0][1]
        for i in sorted_tt:
            if i[1] == tt_max:
                result['tt'].append(i[0])
            else :
                break
        oo_max = sorted_oo[0][1]
        for i in sorted_oo:
            if i[1] == oo_max:
                result['oo'].append(i[0])
            else :
                break
        to_max = sorted_to[0][1]
        for i in sorted_to:
            if i[1] == to_max:
                result['to'].append(i[0])
            else :
                break

    return result

In [641]:
import json
def recommend(data, gu, dong):
    cluster = data['similarity']
    cluster_number = cluster.loc[(cluster['gu'] == gu) & (cluster['dong'] == dong), :]['predict'].values[0]

    # 입력받은 행정동 지역과 유사한(같은 클러스터)의 지역 리스트 확인
    similar_region = cluster.loc[(cluster['predict'] == cluster_number),['gu','dong']]
    
    stores_reviews_merge = pd.merge(data['stores'], data['reviews'], left_on="id", right_on="store")
    stores_reviews_merge = stores_reviews_merge.loc[:,['gu','dong','medium_code','small_code','score','store','store_name','user','content']]

    # 유사 지역의 모든 음식점의 리뷰데이터
    similar_stores_df = pd.DataFrame(columns=['gu','dong','medium_code','small_code','score','store','store_name','user','content'])
    for i, val in similar_region.iterrows():
        now_gu = val.gu
        now_dong = val.dong
        similar_region_stores = stores_reviews_merge.loc[(stores_reviews_merge['gu'] == now_gu) & (stores_reviews_merge['dong'] == now_dong),:]
        similar_stores_df = pd.concat([similar_stores_df, similar_region_stores], ignore_index=True)
    # similar_stores_df
    similar_stores_df['score'] = similar_stores_df.score.astype(int)

    similar_groupby_small_code = similar_stores_df.groupby(['medium_code'])
    similar_scores_small_code = similar_groupby_small_code.mean()
    similar_scores_small_code['count'] = similar_groupby_small_code.count()['content']
    similar_scores_small_code = similar_scores_small_code.loc[similar_scores_small_code['count']>=3]

    # 평점으로 뽑아보기
    similar_scores_small_code_sort_by_score = pd.merge(similar_scores_small_code, data['medium'], on="medium_code").sort_values(by="score", ascending=False)[0:10].reset_index()
#     display(similar_scores_small_code_sort_by_score)
    # 리뷰수로 뽑아보기
    similar_scores_small_code_sort_by_count =  pd.merge(similar_scores_small_code, data['medium'], on="medium_code").sort_values(by="count", ascending=False)[0:10].reset_index()
#     display(similar_scores_small_code_sort_by_count)
    
    
    #선택 지역
    region_stores = stores_reviews_merge.loc[(stores_reviews_merge['gu'] == gu) & (stores_reviews_merge['dong'] == dong),['medium_code','score','content']]

    region_groupby_small_code =region_stores.groupby(['medium_code'])
    region_scores_small_code = region_groupby_small_code.mean()
    region_scores_small_code['count'] = region_groupby_small_code.count()['content']
    region_scores_small_code = region_scores_small_code.loc[region_scores_small_code['count']>=3]

    # 평점으로 뽑아보기
    region_scores_small_code_sort_by_score = pd.merge(region_scores_small_code, data['medium'], on="medium_code").sort_values(by="score", ascending=False)[0:10].reset_index()
#     display(region_scores_small_code_sort_by_score)
    # 리뷰수로 뽑아보기
    region_scores_small_code_sort_by_count =  pd.merge(region_scores_small_code, data['medium'], on="medium_code").sort_values(by="count", ascending=False)[0:10].reset_index()
#     display(region_scores_small_code_sort_by_count)
    
    ret = {}
    
    if similar_scores_small_code.size > 0:
        similar_point = similarPoint(similar_scores_small_code_sort_by_score, similar_scores_small_code_sort_by_count)
        one_plus_ten = onePlusTen(region_scores_small_code_sort_by_score,region_scores_small_code_sort_by_count)
        ten_plus_ten = tenPlusTen(region_scores_small_code_sort_by_score,region_scores_small_code_sort_by_count)
        one_plus_one = onePlusOne(region_scores_small_code_sort_by_score,region_scores_small_code_sort_by_count)
        ten_plus_one = tenPlusOne(region_scores_small_code_sort_by_score,region_scores_small_code_sort_by_count)

        result = recommendResult(similar_point,one_plus_ten,ten_plus_ten,one_plus_one,ten_plus_one)

        ret = {
            'similar_scores_small_code_sort_by_score':json.loads(similar_scores_small_code_sort_by_score.to_json(orient='index',force_ascii=False)),
            'similar_scores_small_code_sort_by_count':json.loads(similar_scores_small_code_sort_by_count.to_json(orient='index',force_ascii=False)),
            'region_scores_small_code_sort_by_score':json.loads(region_scores_small_code_sort_by_score.to_json(orient='index',force_ascii=False)),
            'region_scores_small_code_sort_by_count':json.loads(region_scores_small_code_sort_by_count.to_json(orient='index',force_ascii=False)),
            'recommend' : result
        }
    
    return ret
    
def allRecommend(data):
    similarity = data['similarity']
    result = []
    for i, val in similarity.iterrows():
        res= {}
        res['gu'] = val.gu
        res['dong'] = val.dong
        res['result'] = str(recommend(data, val.gu, val.dong))
        result.append(res)
    
    return result

data = load_dataframes()

data['recommend'] = pd.DataFrame(allRecommend(data))
data['recommend']

       gu  dong                                             result
0     강남구  개포1동                                                 {}
1     강남구  개포2동  {'similar_scores_small_code_sort_by_score': {'...
2     강남구  개포4동  {'similar_scores_small_code_sort_by_score': {'...
3     강남구  논현1동  {'similar_scores_small_code_sort_by_score': {'...
4     강남구  논현2동  {'similar_scores_small_code_sort_by_score': {'...
..    ...   ...                                                ...
627  해운대구   좌2동  {'similar_scores_small_code_sort_by_score': {'...
628  해운대구   좌3동                                                 {}
629  해운대구   좌4동  {'similar_scores_small_code_sort_by_score': {'...
630  해운대구   중1동  {'similar_scores_small_code_sort_by_score': {'...
631  해운대구   중2동                                                 {}

[632 rows x 3 columns]

In [642]:
data['recommend'].values

array([['강남구', '개포1동', '{}'],
       ['강남구', '개포2동',
        "{'similar_scores_small_code_sort_by_score': {'0': {'index': 10, 'medium_code': 'Q12', 'score': 4.0759493671, 'count': 79, 'medium_category': '커피점/카페'}, '1': {'index': 4, 'medium_code': 'Q05', 'score': 4.0357142857, 'count': 28, 'medium_category': '닭/오리요리'}, '2': {'index': 7, 'medium_code': 'Q08', 'score': 4.0, 'count': 8, 'medium_category': '제과제빵떡케익'}, '3': {'index': 0, 'medium_code': 'Q01', 'score': 3.9526748971, 'count': 486, 'medium_category': '한식'}, '4': {'index': 5, 'medium_code': 'Q06', 'score': 3.9230769231, 'count': 156, 'medium_category': '양식'}, '5': {'index': 1, 'medium_code': 'Q02', 'score': 3.8666666667, 'count': 60, 'medium_category': '중식'}, '6': {'index': 2, 'medium_code': 'Q03', 'score': 3.85, 'count': 140, 'medium_category': '일식/수산물'}, '7': {'index': 11, 'medium_code': 'Q15', 'score': 3.7777777778, 'count': 9, 'medium_category': '부페'}, '8': {'index': 3, 'medium_code': 'Q04', 'score': 3.7432432432, 'count': 148, 'medium_category': '분식'}, '9': {'index': 9, 'medium_code': 'Q10', 'score': 3.7, 'count': 40, 'medium_category': '별식/퓨전요리'}}, 'similar_scores_small_code_sort_by_count': {'0': {'index': 0, 'medium_code': 'Q01', 'score': 3.9526748971, 'count': 486, 'medium_category': '한식'}, '1': {'index': 5, 'medium_code': 'Q06', 'score': 3.9230769231, 'count': 156, 'medium_category': '양식'}, '2': {'index': 3, 'medium_code': 'Q04', 'score': 3.7432432432, 'count': 148, 'medium_category': '분식'}, '3': {'index': 2, 'medium_code': 'Q03', 'score': 3.85, 'count': 140, 'medium_category': '일식/수산물'}, '4': {'index': 10, 'medium_code': 'Q12', 'score': 4.0759493671, 'count': 79, 'medium_category': '커피점/카페'}, '5': {'index': 8, 'medium_code': 'Q09', 'score': 3.5064935065, 'count': 77, 'medium_category': '유흥주점'}, '6': {'index': 1, 'medium_code': 'Q02', 'score': 3.8666666667, 'count': 60, 'medium_category': '중식'}, '7': {'index': 6, 'medium_code': 'Q07', 'score': 3.6964285714, 'count': 56, 'medium_category': '패스트푸드'}, '8': {'index': 9, 'medium_code': 'Q10', 'score': 3.7, 'count': 40, 'medium_category': '별식/퓨전요리'}, '9': {'index': 4, 'medium_code': 'Q05', 'score': 4.0357142857, 'count': 28, 'medium_category': '닭/오리요리'}}, 'region_scores_small_code_sort_by_score': {}, 'region_scores_small_code_sort_by_count': {}, 'recommend': {'top': ['커피점/카페', '닭/오리요리', '제과제빵떡케익'], 'ot': [], 'tt': [], 'oo': [], 'to': []}}"],
       ['강남구', '개포4동',
        "{'similar_scores_small_code_sort_by_score': {'0': {'index': 7, 'medium_code': 'Q08', 'score': 4.2, 'count': 15, 'medium_category': '제과제빵떡케익'}, '1': {'index': 9, 'medium_code': 'Q10', 'score': 4.1904761905, 'count': 42, 'medium_category': '별식/퓨전요리'}, '2': {'index': 10, 'medium_code': 'Q12', 'score': 4.1509433962, 'count': 53, 'medium_category': '커피점/카페'}, '3': {'index': 5, 'medium_code': 'Q06', 'score': 4.1325301205, 'count': 166, 'medium_category': '양식'}, '4': {'index': 6, 'medium_code': 'Q07', 'score': 4.0555555556, 'count': 72, 'medium_category': '패스트푸드'}, '5': {'index': 3, 'medium_code': 'Q04', 'score': 4.0185185185, 'count': 54, 'medium_category': '분식'}, '6': {'index': 4, 'medium_code': 'Q05', 'score': 4.0, 'count': 25, 'medium_category': '닭/오리요리'}, '7': {'index': 2, 'medium_code': 'Q03', 'score': 3.8405797101, 'count': 138, 'medium_category': '일식/수산물'}, '8': {'index': 0, 'medium_code': 'Q01', 'score': 3.8359375, 'count': 256, 'medium_category': '한식'}, '9': {'index': 1, 'medium_code': 'Q02', 'score': 3.7857142857, 'count': 14, 'medium_category': '중식'}}, 'similar_scores_small_code_sort_by_count': {'0': {'index': 0, 'medium_code': 'Q01', 'score': 3.8359375, 'count': 256, 'medium_category': '한식'}, '1': {'index': 5, 'medium_code': 'Q06', 'score': 4.1325301205, 'count': 166, 'medium_category': '양식'}, '2': {'index': 2, 'medium_code': 'Q03', 'score': 3.8405797101, 'count': 138, 'medium_category': '일식/수산물'}, '3': {'index': 6, 'medium_code': 'Q07', 'score': 4.0555555556, 'count': 72, 'medium_category': '패스트푸드'}, '4': {'index': 8, 'medium_code': 'Q09', 'score': 3.7258064516, 'count': 62, 'medium_category': '유흥주점'}, '5': {'index': 3, 'medium_code': 'Q04', 'score': 4.0185185185, 'count': 54, 'medium_category': '분식'}, '6': {'index': 10, 'medium_code': 'Q12', 'score': 4.1509433962, 'count': 53, 'medium_category': '커피점/카페'}, '7': {'index': 9, 'medium_code': 'Q10', 'score': 4.1904761905, 'count': 42, 'medium_category': '별식/퓨전요리'}, '8': {'index': 4, 'medium_code': 'Q05', 'score': 4.0, 'count': 25, 'medium_category': '닭/오리요리'}, '9': {'index': 7, 'medium_code': 'Q08', 'score': 4.2, 'count': 15, 'medium_category': '제과제빵떡케익'}}, 'region_scores_small_code_sort_by_score': {}, 'region_scores_small_code_sort_by_count': {}, 'recommend': {'top': ['제과제빵떡케익', '별식/퓨전요리', '커피점/카페'], 'ot': [], 'tt': [], 'oo': [], 'to': []}}"],
       ...,
       ['해운대구', '좌4동',
        "{'similar_scores_small_code_sort_by_score': {'0': {'index': 7, 'medium_code': 'Q08', 'score': 4.3333333333, 'count': 9, 'medium_category': '제과제빵떡케익'}, '1': {'index': 6, 'medium_code': 'Q07', 'score': 4.1666666667, 'count': 42, 'medium_category': '패스트푸드'}, '2': {'index': 0, 'medium_code': 'Q01', 'score': 3.935483871, 'count': 217, 'medium_category': '한식'}, '3': {'index': 5, 'medium_code': 'Q06', 'score': 3.9130434783, 'count': 46, 'medium_category': '양식'}, '4': {'index': 3, 'medium_code': 'Q04', 'score': 3.8219178082, 'count': 73, 'medium_category': '분식'}, '5': {'index': 8, 'medium_code': 'Q09', 'score': 3.76, 'count': 50, 'medium_category': '유흥주점'}, '6': {'index': 11, 'medium_code': 'Q14', 'score': 3.7368421053, 'count': 19, 'medium_category': '기타음식업'}, '7': {'index': 10, 'medium_code': 'Q12', 'score': 3.7083333333, 'count': 24, 'medium_category': '커피점/카페'}, '8': {'index': 2, 'medium_code': 'Q03', 'score': 3.6904761905, 'count': 42, 'medium_category': '일식/수산물'}, '9': {'index': 9, 'medium_code': 'Q10', 'score': 3.5294117647, 'count': 17, 'medium_category': '별식/퓨전요리'}}, 'similar_scores_small_code_sort_by_count': {'0': {'index': 0, 'medium_code': 'Q01', 'score': 3.935483871, 'count': 217, 'medium_category': '한식'}, '1': {'index': 3, 'medium_code': 'Q04', 'score': 3.8219178082, 'count': 73, 'medium_category': '분식'}, '2': {'index': 8, 'medium_code': 'Q09', 'score': 3.76, 'count': 50, 'medium_category': '유흥주점'}, '3': {'index': 5, 'medium_code': 'Q06', 'score': 3.9130434783, 'count': 46, 'medium_category': '양식'}, '4': {'index': 2, 'medium_code': 'Q03', 'score': 3.6904761905, 'count': 42, 'medium_category': '일식/수산물'}, '5': {'index': 6, 'medium_code': 'Q07', 'score': 4.1666666667, 'count': 42, 'medium_category': '패스트푸드'}, '6': {'index': 10, 'medium_code': 'Q12', 'score': 3.7083333333, 'count': 24, 'medium_category': '커피점/카페'}, '7': {'index': 11, 'medium_code': 'Q14', 'score': 3.7368421053, 'count': 19, 'medium_category': '기타음식업'}, '8': {'index': 9, 'medium_code': 'Q10', 'score': 3.5294117647, 'count': 17, 'medium_category': '별식/퓨전요리'}, '9': {'index': 4, 'medium_code': 'Q05', 'score': 3.375, 'count': 16, 'medium_category': '닭/오리요리'}}, 'region_scores_small_code_sort_by_score': {}, 'region_scores_small_code_sort_by_count': {}, 'recommend': {'top': ['제과제빵떡케익', '패스트푸드', '한식'], 'ot': [], 'tt': [], 'oo': [], 'to': []}}"],
       ['해운대구', '중1동',
        "{'similar_scores_small_code_sort_by_score': {'0': {'index': 7, 'medium_code': 'Q08', 'score': 4.3333333333, 'count': 9, 'medium_category': '제과제빵떡케익'}, '1': {'index': 6, 'medium_code': 'Q07', 'score': 4.1666666667, 'count': 42, 'medium_category': '패스트푸드'}, '2': {'index': 0, 'medium_code': 'Q01', 'score': 3.935483871, 'count': 217, 'medium_category': '한식'}, '3': {'index': 5, 'medium_code': 'Q06', 'score': 3.9130434783, 'count': 46, 'medium_category': '양식'}, '4': {'index': 3, 'medium_code': 'Q04', 'score': 3.8219178082, 'count': 73, 'medium_category': '분식'}, '5': {'index': 8, 'medium_code': 'Q09', 'score': 3.76, 'count': 50, 'medium_category': '유흥주점'}, '6': {'index': 11, 'medium_code': 'Q14', 'score': 3.7368421053, 'count': 19, 'medium_category': '기타음식업'}, '7': {'index': 10, 'medium_code': 'Q12', 'score': 3.7083333333, 'count': 24, 'medium_category': '커피점/카페'}, '8': {'index': 2, 'medium_code': 'Q03', 'score': 3.6904761905, 'count': 42, 'medium_category': '일식/수산물'}, '9': {'index': 9, 'medium_code': 'Q10', 'score': 3.5294117647, 'count': 17, 'medium_category': '별식/퓨전요리'}}, 'similar_scores_small_code_sort_by_count': {'0': {'index': 0, 'medium_code': 'Q01', 'score': 3.935483871, 'count': 217, 'medium_category': '한식'}, '1': {'index': 3, 'medium_code': 'Q04', 'score': 3.8219178082, 'count': 73, 'medium_category': '분식'}, '2': {'index': 8, 'medium_code': 'Q09', 'score': 3.76, 'count': 50, 'medium_category': '유흥주점'}, '3': {'index': 5, 'medium_code': 'Q06', 'score': 3.9130434783, 'count': 46, 'medium_category': '양식'}, '4': {'index': 2, 'medium_code': 'Q03', 'score': 3.6904761905, 'count': 42, 'medium_category': '일식/수산물'}, '5': {'index': 6, 'medium_code': 'Q07', 'score': 4.1666666667, 'count': 42, 'medium_category': '패스트푸드'}, '6': {'index': 10, 'medium_code': 'Q12', 'score': 3.7083333333, 'count': 24, 'medium_category': '커피점/카페'}, '7': {'index': 11, 'medium_code': 'Q14', 'score': 3.7368421053, 'count': 19, 'medium_category': '기타음식업'}, '8': {'index': 9, 'medium_code': 'Q10', 'score': 3.5294117647, 'count': 17, 'medium_category': '별식/퓨전요리'}, '9': {'index': 4, 'medium_code': 'Q05', 'score': 3.375, 'count': 16, 'medium_category': '닭/오리요리'}}, 'region_scores_small_code_sort_by_score': {}, 'region_scores_small_code_sort_by_count': {}, 'recommend': {'top': ['제과제빵떡케익', '패스트푸드', '한식'], 'ot': [], 'tt': [], 'oo': [], 'to': []}}"],
       ['해운대구', '중2동', '{}']], dtype=object)

In [20]:
from parse import load_dataframes
import pandas as pd
import json


similar_scores_small_code_sort_by_score = pd.merge(similar_scores_small_code, data['medium'], on="medium_code").sort_values(by="score", ascending=False)[0:10].reset_index()

json.loads(similar_scores_small_code_sort_by_score.to_json(orient='table',force_ascii=False))

{'schema': {'fields': [{'name': 'index', 'type': 'integer'},
   {'name': 'index', 'type': 'integer'},
   {'name': 'medium_code', 'type': 'string'},
   {'name': 'score', 'type': 'number'},
   {'name': 'count', 'type': 'integer'},
   {'name': 'medium_category', 'type': 'string'}],
  'primaryKey': ['index'],
  'pandas_version': '0.20.0'},
 'data': [{'level_0': 0,
   'index': 7,
   'medium_code': 'Q08',
   'score': 4.0,
   'count': 57,
   'medium_category': '제과제빵떡케익'},
  {'level_0': 1,
   'index': 8,
   'medium_code': 'Q09',
   'score': 3.9277108434,
   'count': 166,
   'medium_category': '유흥주점'},
  {'level_0': 2,
   'index': 10,
   'medium_code': 'Q12',
   'score': 3.8944954128,
   'count': 218,
   'medium_category': '커피점/카페'},
  {'level_0': 3,
   'index': 0,
   'medium_code': 'Q01',
   'score': 3.875,
   'count': 1112,
   'medium_category': '한식'},
  {'level_0': 4,
   'index': 2,
   'medium_code': 'Q03',
   'score': 3.8341708543,
   'count': 398,
   'medium_category': '일식/수산물'},
  {'level_0': 5,
   'index': 4,
   'medium_code': 'Q05',
   'score': 3.8311688312,
   'count': 77,
   'medium_category': '닭/오리요리'},
  {'level_0': 6,
   'index': 1,
   'medium_code': 'Q02',
   'score': 3.7796610169,
   'count': 118,
   'medium_category': '중식'},
  {'level_0': 7,
   'index': 3,
   'medium_code': 'Q04',
   'score': 3.76,
   'count': 225,
   'medium_category': '분식'},
  {'level_0': 8,
   'index': 6,
   'medium_code': 'Q07',
   'score': 3.7559055118,
   'count': 127,
   'medium_category': '패스트푸드'},
  {'level_0': 9,
   'index': 9,
   'medium_code': 'Q10',
   'score': 3.7183098592,
   'count': 71,
   'medium_category': '별식/퓨전요리'}]}

In [25]:
from parse import load_dataframes
import pandas as pd

# parse
data = load_dataframes()

def pointRegion(code):
    base_url = "http://sg.sbiz.or.kr/areaGreadeDetail.json?admiCd="
    url = base_url + str(code)
    r = requests.get(url)
    to_json = r.json()['areaGrade']
    total_score = 0
    grade = 0
    grothIndex = 0
    stability = 0
    salePwr = 0
    buyingPwr = 0
    gathPwr = 0
    if to_json :
        grothIndex = to_json['grothIndex']
        stability=to_json['stability']
        salePwr=to_json['salePwr']
        buyingPwr=to_json['buyingPwr']
        gathPwr=to_json['gathPwr']
        total_score = round((grothIndex + stability + salePwr + buyingPwr + gathPwr),1)

        if total_score >= 70:
            grade = 1
        elif total_score >= 57.5 and total_score < 70:
            grade = 2
        elif total_score >= 45 and total_score < 57.5:
            grade = 3
        elif total_score >= 32.5 and total_score < 45:
            grade = 4
        elif total_score < 32.5:
            grade = 5
    return {'total_score': total_score,'grade': grade,'grothIndex':grothIndex,
            'stability':stability,'salePwr':salePwr,'buyingPwr':buyingPwr,'gathPwr':gathPwr}

def similarPoint(score, review):
    result ={}
    point = 10
    for i, val in score.iterrows():
        now_key = val.medium_category
        if now_key in result.keys():
            result[now_key] += point
        else:
            result[now_key] = point
        point -= 1
    point = 10
    for i, val in review.iterrows():
        now_key = val.medium_category
        if now_key in result.keys():
            result[now_key] += point
        else:
            result[now_key] = point
        point -= 1
    
    result = sorted(result.items(),reverse=True,key=lambda item: item[1])
    return result

def onePlusTen(score, review):
    result ={}
    point = 1
    for i, val in score.iterrows():
        now_key = val.medium_category
        if now_key in result.keys():
            result[now_key] += point
        else:
            result[now_key] = point
        point += 1
    point = 10
    for i, val in review.iterrows():
        now_key = val.medium_category
        if now_key in result.keys():
            result[now_key] += point
        else:
            result[now_key] = point
        point -= 1
    
    return result

def tenPlusTen(score, review):
    result ={}
    point = 10
    for i, val in score.iterrows():
        now_key = val.medium_category
        if now_key in result.keys():
            result[now_key] += point
        else:
            result[now_key] = point
        point -= 1
    point = 10
    for i, val in review.iterrows():
        now_key = val.medium_category
        if now_key in result.keys():
            result[now_key] += point
        else:
            result[now_key] = point
        point -= 1
    
    return result

def onePlusOne(score, review):
    result ={}
    point = 1
    for i, val in score.iterrows():
        now_key = val.medium_category
        if now_key in result.keys():
            result[now_key] += point
        else:
            result[now_key] = point
        point += 1
    point = 1
    for i, val in review.iterrows():
        now_key = val.medium_category
        if now_key in result.keys():
            result[now_key] += point
        else:
            result[now_key] = point
        point += 1
    
    return result

def tenPlusOne(score,review):
    result ={}
    point = 10
    for i, val in score.iterrows():
        now_key = val.medium_category
        if now_key in result.keys():
            result[now_key] += point
        else:
            result[now_key] = point
        point -= 1
    point = 1
    for i, val in review.iterrows():
        now_key = val.medium_category
        if now_key in result.keys():
            result[now_key] += point
        else:
            result[now_key] = point
        point += 1
    
    return result

def recommendResult(similar, ot, tt, oo, to):
    result = {'top':[],'ot':[], 'tt':[],'oo':[],'to':[]}

    # top
    top = 0
    for key, value in similar:
        if top == 3:
            break
        if key not in ot.keys():
            result['top'].append(key)
        top += 1
    if len(ot) > 0:
        # 1
        for key, value in ot.items():
            for k, v in similar:
                if key == k:
                    ot[key] = value * v
        sorted_ot = sorted(ot.items(),reverse=True,key=lambda item: item[1])

        # 2
        for key, value in tt.items():
            for k, v in similar:
                if key == k:
                    tt[key] = value * v
        sorted_tt = sorted(tt.items(),reverse=True,key=lambda item: item[1])

        # 3
        for key, value in oo.items():
            for k, v in similar:
                if key == k:
                    oo[key] = value * v
        sorted_oo = sorted(oo.items(),reverse=True,key=lambda item: item[1])

        # 4
        for key, value in to.items():
            for k, v in similar:
                if key == k:
                    to[key] = value * v
        sorted_to = sorted(to.items(),reverse=True,key=lambda item: item[1])

        ot_max = sorted_ot[0][1]
        for i in sorted_ot:
            if i[1] == ot_max:
                result['ot'].append(i[0])
            else :
                break
        tt_max = sorted_tt[0][1]
        for i in sorted_tt:
            if i[1] == tt_max:
                result['tt'].append(i[0])
            else :
                break
        oo_max = sorted_oo[0][1]
        for i in sorted_oo:
            if i[1] == oo_max:
                result['oo'].append(i[0])
            else :
                break
        to_max = sorted_to[0][1]
        for i in sorted_to:
            if i[1] == to_max:
                result['to'].append(i[0])
            else :
                break

    return result

In [26]:
similar_point = similarPoint(similar_scores_small_code_sort_by_score, similar_scores_small_code_sort_by_count)

one_plus_ten = onePlusTen(region_scores_small_code_sort_by_score,region_scores_small_code_sort_by_count)
ten_plus_ten = tenPlusTen(region_scores_small_code_sort_by_score,region_scores_small_code_sort_by_count)
one_plus_one = onePlusOne(region_scores_small_code_sort_by_score,region_scores_small_code_sort_by_count)
ten_plus_one = tenPlusOne(region_scores_small_code_sort_by_score,region_scores_small_code_sort_by_count)

result = recommendResult(similar_point,one_plus_ten,ten_plus_ten,one_plus_one,ten_plus_one)
result

{'top': ['한식', '커피점/카페', '양식'], 'ot': [], 'tt': [], 'oo': [], 'to': []}